"""
Static data constants for the Healthcare Provider.
"""

from .brand_names import BRAND_DRUG_NAMES


__all__ = [
    "ALLERGIES",
    "BLOOD_TYPES",
    "BRAND_DRUG_NAMES",
    "BRAND_FORBIDDEN_ENDINGS",
    "BRAND_INFIXES",
    "BRAND_PREFIXES",
    "BRAND_SUFFIXES",
    "HOSPITAL_DEPARTMENTS",
    "INSURANCE_PLANS",
    "MEDICAL_PROCEDURES",
    "NON_DRUG_INTERVENTIONS",
    "VITAL_SIGNS",
]

HOSPITAL_DEPARTMENTS: tuple[str, ...] = (
    "Emergency Department",
    "Intensive Care Unit (ICU)",
    "Cardiac Care Unit (CCU)",
    "Operating Room",
    "Labor and Delivery",
    "Pediatrics",
    "Maternity Ward",
    "Oncology",
    "Radiology",
    "Laboratory",
    "Pharmacy",
    "Physical Therapy",
    "Occupational Therapy",
    "Respiratory Therapy",
    "Surgery",
    "Inpatient Ward",
    "Outpatient Clinic",
    "Psychiatric Ward",
    "Rehabilitation Unit",
    "Endoscopy Suite",
    "Neonatal Intensive Care Unit (NICU)",
    "Burn Unit",
    "Dialysis Unit",
    "Sleep Lab",
    "Wound Care Center",
    "Infusion Center",
    "Cardiology Unit",
    "Neurology Unit",
    "Medical Observation Unit",
    "Post-Anesthesia Care Unit (PACU)",
)

# Invented morphemes for the fictitious brand names in BRAND_DRUG_NAMES (imported
# above from the generated brand_names.py, and what brand_drug() actually draws from).
#
# These pools are the *input* to scripts/generate_brand_names.py, not a runtime pool.
# brand_drug() used to combine them on the fly, which meant 31,500 possible names, and
# no one can screen 31,500 names against real products: the port of these same pools to
# faker-js found five names shadowing real products in a ~250-name sample. The script
# enumerates the pools, screens what comes out, and ships the reviewed result. Editing a
# morpheme here changes nothing until the script is re-run.
#
# The pools deliberately avoid WHO INN stems (e.g. -mab, -nib, -pril, -sartan, -statin,
# -vir, -prazole, -dipine, -olol, -cillin, -mycin, -gliptin, -floxacin) so a name cannot
# be mistaken for a generic substance; BRAND_FORBIDDEN_ENDINGS below is the screen that
# enforces it. See AGENTS.md.
BRAND_PREFIXES: tuple[str, ...] = (
    "Zol",
    "Vyra",
    "Trova",
    "Cetra",
    "Solva",
    "Quen",
    "Brix",
    "Andel",
    "Reva",
    "Miza",
    "Oxa",
    "Pyra",
    "Zenta",
    "Valo",
    "Nuvi",
    "Klar",
    "Cael",
    "Xely",
    "Ravi",
    "Elix",
    "Ombra",
    "Soli",
    "Venda",
    "Alda",
    "Corva",
    "Neuvo",
    "Ziva",
    "Lume",
    "Adva",
    "Cavi",
    "Rexa",
    "Sona",
    "Tavo",
    "Uvel",
    "Wraxa",
    "Ynova",
    "Zeva",
    "Fenda",
    "Grava",
    "Hylo",
    "Ixen",
    "Juvi",
    "Kesa",
    "Lyra",
    "Morva",
    "Nexa",
    "Orba",
    "Praxa",
    "Quila",
    "Roven",
)

BRAND_INFIXES: tuple[str, ...] = (
    "ra",
    "pra",
    "lo",
    "vi",
    "ze",
    "na",
    "di",
    "co",
    "xa",
    "mi",
    "ta",
    "so",
    "va",
    "ly",
    "no",
    "ri",
    "du",
    "be",
    "go",
    "sy",
)

BRAND_SUFFIXES: tuple[str, ...] = (
    "ex",
    "en",
    "ol",
    "in",
    "yl",
    "zen",
    "via",
    "dyn",
    "mox",
    "pral",
    "vor",
    "nix",
    "quel",
    "dara",
    "vue",
    "tiva",
    "vex",
    "mira",
    "xen",
    "lor",
    "cor",
    "dex",
    "sen",
    "tor",
    "vane",
    "ric",
    "plex",
    "don",
    "fen",
    "gis",
)

# WHO INN class stems a brand name must never end with. Enforced by
# scripts/generate_brand_names.py when it builds BRAND_DRUG_NAMES, and re-asserted over
# every shipped name by tests/test_provider.py.
BRAND_FORBIDDEN_ENDINGS: tuple[str, ...] = (
    "mab",
    "nib",
    "pril",
    "sartan",
    "statin",
    "vir",
    "prazole",
    "dipine",
    "olol",
    "cillin",
    "mycin",
    "gliptin",
    "floxacin",
    "caine",
    "profen",
    "parin",
)

BLOOD_TYPES: tuple[str, ...] = ("A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-")

ALLERGIES: tuple[str, ...] = (
    "Penicillin",
    "Peanuts",
    "Tree Nuts",
    "Shellfish",
    "Fish",
    "Milk",
    "Eggs",
    "Soy",
    "Wheat",
    "Sesame",
    "Latex",
    "Bee Sting",
    "Pollen",
    "Dust Mites",
    "Pet Dander",
    "Sulfa Drugs",
    "Aspirin",
    "Ibuprofen",
    "Codeine",
    "Morphine",
    "Contrast Dye",
    "Anesthesia",
    "Nickel",
    "Adhesive",
    "Fragrance",
    "Insect Bites",
    "Mold",
    "Cockroaches",
    "Grass",
    "Ragweed",
    "Corn",
    "Mustard",
    "Celery",
    "Lupin",
    "Sulfites",
    "Red Dye",
)

MEDICAL_PROCEDURES: tuple[str, ...] = (
    "Blood Test",
    "MRI Scan",
    "CT Scan",
    "X-Ray",
    "Ultrasound",
    "Colonoscopy",
    "Endoscopy",
    "Appendectomy",
    "Cholecystectomy",
    "C-Section",
    "Hysterectomy",
    "Knee Replacement",
    "Hip Replacement",
    "Cataract Surgery",
    "Biopsy",
    "Physical Therapy Session",
    "Electrocardiogram (ECG)",
    "Echocardiogram",
    "Vaccination",
    "Wound Debridement",
    "Angioplasty",
    "Cardiac Catheterization",
    "Coronary Artery Bypass Graft",
    "Pacemaker Insertion",
    "Defibrillator Implantation",
    "Ablation",
    "Tonsillectomy",
    "Adenoidectomy",
    "Mastectomy",
    "Lumpectomy",
    "Prostatectomy",
    "Nephrectomy",
    "Splenectomy",
    "Gastrectomy",
    "Colectomy",
    "Ileostomy",
    "Colostomy",
    "Hernia Repair",
    "Gallbladder Removal",
    "Liver Biopsy",
    "Kidney Biopsy",
    "Bone Marrow Biopsy",
    "Lymph Node Biopsy",
    "Skin Biopsy",
    "Bronchoscopy",
    "Thoracentesis",
    "Paracentesis",
    "Lumbar Puncture",
    "Joint Aspiration",
    "Epidural Injection",
    "Nerve Block",
    "Trigger Point Injection",
    "Joint Injection",
    "Botox Injection",
    "Filler Injection",
    "Laser Hair Removal",
    "Chemical Peel",
    "Microdermabrasion",
    "Dermabrasion",
    "Skin Tag Removal",
    "Mole Removal",
    "Wart Removal",
    "Cryotherapy",
    "Electrocautery",
    "Excision",
    "Incision and Drainage",
    "Suturing",
    "Stapling",
    "Skin Graft",
    "Flap Surgery",
    "LASIK Surgery",
    "Glaucoma Surgery",
    "Retinal Detachment Repair",
    "Corneal Transplant",
    "Vitrectomy",
    "Tympanoplasty",
    "Stapedectomy",
    "Cochlear Implant",
    "Rhinoplasty",
    "Septoplasty",
    "Sinus Surgery",
    "Thyroidectomy",
    "Parathyroidectomy",
    "Adrenalectomy",
    "Pancreatectomy",
    "Whipple Procedure",
    "Liver Resection",
    "Liver Transplant",
    "Kidney Transplant",
    "Heart Transplant",
    "Lung Transplant",
    "Pancreas Transplant",
    "Bone Marrow Transplant",
    "Stem Cell Transplant",
    "Dialysis",
    "Hemodialysis",
    "Peritoneal Dialysis",
    "Plasmapheresis",
    "IVIG Infusion",
    "Chemotherapy",
    "Radiation Therapy",
    "Immunotherapy",
    "Hormone Therapy",
    "Targeted Therapy",
    "CAR T-Cell Therapy",
)

INSURANCE_PLANS: tuple[str, ...] = (
    "PPO",
    "HMO",
    "EPO",
    "POS",
    "Medicare",
    "Medicaid",
    "High-Deductible Health Plan (HDHP)",
    "Private Insurance",
    "Employer-Sponsored",
    "Medicare Advantage",
    "TRICARE",
    "Veterans Affairs (VA)",
    "CHIP",
    "ACA Marketplace",
    "Medigap",
    "Medicare Part A",
    "Medicare Part B",
    "Medicare Part C",
    "Medicare Part D",
    "Dental Insurance",
    "Vision Insurance",
    "Long-Term Care Insurance",
    "Disability Insurance",
    "Critical Illness Insurance",
    "Catastrophic Insurance",
)

VITAL_SIGNS: tuple[str, ...] = (
    "Blood Pressure",
    "Heart Rate",
    "Respiratory Rate",
    "Body Temperature",
    "Oxygen Saturation",
    "Body Mass Index (BMI)",
    "Blood Glucose",
    "Pain Level",
    "Pulse",
    "Peak Flow",
)

# Treatments that a condition's `medications` list may legitimately contain but that
# are not drugs: procedures, devices, and lifestyle measures. They are correct inside
# a condition's treatment list (see AGENTS.md), but wrong in the flat pool a consumer
# draws a medication column from, so `generic_drugs` excludes them and the provider
# exposes them separately via `interventions` / `intervention()`.
# Kept in the same order in every locale, so index i is the same intervention
# everywhere; every entry must also appear in this locale's DISEASE_CORRELATIONS
# (tests/test_locales.py enforces both).
NON_DRUG_INTERVENTIONS: tuple[str, ...] = (
    "Anti-Glare Lenses",
    "Bladder Instillations",
    "Blood Transfusions",
    "CPAP Therapy",
    "Chemotherapy",
    "Chest Tube",
    "Cochlear Implants",
    "Delivery",
    "Dialysis",
    "Diet Control",
    "Electrolyte Management",
    "Exercise",
    "Eyeglasses",
    "Gluten-Free Diet",
    "Hearing Aids",
    "Humidified Air",
    "Hydration",
    "IV Fluids",
    "Iron Infusions",
    "Laser Therapy",
    "Magnifiers",
    "No Medications",
    "Oxygen",
    "Oxygen Therapy",
    "Pelvic Floor Exercises",
    "Photodynamic Therapy",
    "Plasmapheresis",
    "Pleurodesis",
    "Pulmonary Rehab",
    "Radiation",
    "Radioactive Iodine",
    "Saline Irrigation",
    "Splenectomy",
    "Steam Inhalation",
    "Sun Exposure",
    "Supportive Care",
    "Surgery",
    "Thoracentesis",
    "Vitrectomy",
    "Voice Rest",
    "Wrist Splint",
)
