"""
Static data constants for the Healthcare Provider.
"""

HOSPITAL_DEPARTMENTS: tuple[str, ...] = (
    "Emergency Department",
    "Intensive Care Unit (ICU)",
    "Cardiac Care Unit (CCU)",
    "Operating Room",
    "Labor and Delivery",
    "Pediatrics",
    "Maternity Ward",
    "Oncology",
    "Radiology",
    "Laboratory",
    "Pharmacy",
    "Physical Therapy",
    "Occupational Therapy",
    "Respiratory Therapy",
    "Surgery",
    "Inpatient Ward",
    "Outpatient Clinic",
    "Psychiatric Ward",
    "Rehabilitation Unit",
    "Endoscopy Suite",
    "Neonatal Intensive Care Unit (NICU)",
    "Burn Unit",
    "Dialysis Unit",
    "Sleep Lab",
    "Wound Care Center",
    "Infusion Center",
    "Cardiology Unit",
    "Neurology Unit",
    "Medical Observation Unit",
    "Post-Anesthesia Care Unit (PACU)",
)

# Invented morphemes for the fictitious brand-name generator (see brand_drug()).
# These are NOT real drug names. They deliberately avoid WHO INN stems
# (e.g. -mab, -nib, -pril, -sartan, -statin, -vir, -prazole, -dipine, -olol,
# -cillin, -mycin, -gliptin, -floxacin) so a generated brand can never be
# mistaken for a generic substance name. Any resemblance to a real brand is
# coincidental. See AGENTS.md.
BRAND_PREFIXES: tuple[str, ...] = (
    "Zol", "Vyra", "Trova", "Cetra", "Solva", "Quen", "Brix", "Andel",
    "Reva", "Miza", "Oxa", "Pyra", "Zenta", "Valo", "Nuvi", "Klar",
    "Cael", "Xely", "Ravi", "Elix", "Ombra", "Soli", "Venda", "Alda",
    "Corva", "Neuvo", "Ziva", "Lume", "Adva", "Cavi", "Rexa", "Sona",
    "Tavo", "Uvel", "Wraxa", "Ynova", "Zeva", "Fenda", "Grava", "Hylo",
    "Ixen", "Juvi", "Kesa", "Lyra", "Morva", "Nexa", "Orba", "Praxa",
    "Quila", "Roven",
)

BRAND_INFIXES: tuple[str, ...] = (
    "ra", "pra", "lo", "vi", "ze", "na", "di", "co", "xa", "mi",
    "ta", "se", "va", "ly", "no", "ri", "du", "be", "ga", "sy",
)

BRAND_SUFFIXES: tuple[str, ...] = (
    "ex", "en", "ol", "in", "yl", "zen", "via", "dyn", "mox", "pral",
    "vor", "nix", "quel", "dara", "vue", "tiva", "zia", "mira", "xen",
    "lor", "cor", "dex", "sen", "tor", "vane", "ric", "pex", "don",
    "fen", "gis",
)

# WHO INN class stems a generated brand must never end with (enforced in brand_drug()).
BRAND_FORBIDDEN_ENDINGS: tuple[str, ...] = (
    "mab", "nib", "pril", "sartan", "statin", "vir", "prazole", "dipine",
    "olol", "cillin", "mycin", "gliptin", "floxacin", "caine", "profen", "parin",
)

BLOOD_TYPES: tuple[str, ...] = ("A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-")

ALLERGIES: tuple[str, ...] = (
    "Penicillin",
    "Peanuts",
    "Tree Nuts",
    "Shellfish",
    "Fish",
    "Milk",
    "Eggs",
    "Soy",
    "Wheat",
    "Sesame",
    "Latex",
    "Bee Sting",
    "Pollen",
    "Dust Mites",
    "Pet Dander",
    "Sulfa Drugs",
    "Aspirin",
    "Ibuprofen",
    "Codeine",
    "Morphine",
    "Contrast Dye",
    "Anesthesia",
    "Nickel",
    "Adhesive",
    "Fragrance",
    "Insect Bites",
    "Mold",
    "Cockroaches",
    "Grass",
    "Ragweed",
    "Corn",
    "Mustard",
    "Celery",
    "Lupin",
    "Sulfites",
    "MSG",
    "Red Dye",
    "Gluten",
    "Lactose",
    "Fructose",
)

MEDICAL_PROCEDURES: tuple[str, ...] = (
    "Blood Test",
    "MRI Scan",
    "CT Scan",
    "X-Ray",
    "Ultrasound",
    "Colonoscopy",
    "Endoscopy",
    "Appendectomy",
    "Cholecystectomy",
    "C-Section",
    "Hysterectomy",
    "Knee Replacement",
    "Hip Replacement",
    "Cataract Surgery",
    "Biopsy",
    "Physical Therapy Session",
    "Electrocardiogram (ECG)",
    "Echocardiogram",
    "Vaccination",
    "Wound Debridement",
    "Angioplasty",
    "Cardiac Catheterization",
    "Coronary Artery Bypass Graft",
    "Pacemaker Insertion",
    "Defibrillator Implantation",
    "Ablation",
    "Tonsillectomy",
    "Adenoidectomy",
    "Mastectomy",
    "Lumpectomy",
    "Prostatectomy",
    "Nephrectomy",
    "Splenectomy",
    "Gastrectomy",
    "Colectomy",
    "Ileostomy",
    "Colostomy",
    "Hernia Repair",
    "Gallbladder Removal",
    "Liver Biopsy",
    "Kidney Biopsy",
    "Bone Marrow Biopsy",
    "Lymph Node Biopsy",
    "Skin Biopsy",
    "Bronchoscopy",
    "Thoracentesis",
    "Paracentesis",
    "Lumbar Puncture",
    "Joint Aspiration",
    "Epidural Injection",
    "Nerve Block",
    "Trigger Point Injection",
    "Joint Injection",
    "Botox Injection",
    "Filler Injection",
    "Laser Hair Removal",
    "Chemical Peel",
    "Microdermabrasion",
    "Dermabrasion",
    "Skin Tag Removal",
    "Mole Removal",
    "Wart Removal",
    "Cryotherapy",
    "Electrocautery",
    "Excision",
    "Incision and Drainage",
    "Suturing",
    "Stapling",
    "Skin Graft",
    "Flap Surgery",
    "LASIK Surgery",
    "Glaucoma Surgery",
    "Retinal Detachment Repair",
    "Corneal Transplant",
    "Vitrectomy",
    "Tympanoplasty",
    "Stapedectomy",
    "Cochlear Implant",
    "Rhinoplasty",
    "Septoplasty",
    "Sinus Surgery",
    "Thyroidectomy",
    "Parathyroidectomy",
    "Adrenalectomy",
    "Pancreatectomy",
    "Whipple Procedure",
    "Liver Resection",
    "Liver Transplant",
    "Kidney Transplant",
    "Heart Transplant",
    "Lung Transplant",
    "Pancreas Transplant",
    "Bone Marrow Transplant",
    "Stem Cell Transplant",
    "Dialysis",
    "Hemodialysis",
    "Peritoneal Dialysis",
    "Plasmapheresis",
    "IVIG Infusion",
    "Chemotherapy",
    "Radiation Therapy",
    "Immunotherapy",
    "Hormone Therapy",
    "Targeted Therapy",
    "CAR T-Cell Therapy",
)

INSURANCE_PLANS: tuple[str, ...] = (
    "PPO",
    "HMO",
    "EPO",
    "POS",
    "Medicare",
    "Medicaid",
    "High-Deductible Health Plan (HDHP)",
    "Private Insurance",
    "Employer-Sponsored",
    "Medicare Advantage",
    "TRICARE",
    "Veterans Affairs (VA)",
    "CHIP",
    "ACA Marketplace",
    "Medigap",
    "Medicare Part A",
    "Medicare Part B",
    "Medicare Part C",
    "Medicare Part D",
    "Dental Insurance",
    "Vision Insurance",
    "Long-Term Care Insurance",
    "Disability Insurance",
    "Critical Illness Insurance",
    "Catastrophic Insurance",
)

VITAL_SIGNS: tuple[str, ...] = (
    "Blood Pressure",
    "Heart Rate",
    "Respiratory Rate",
    "Body Temperature",
    "Oxygen Saturation",
    "Body Mass Index (BMI)",
    "Blood Glucose",
    "Pain Level",
    "Pulse",
    "Peak Flow",
)
