"""
Disease Correlations Data

This module contains the DISEASE_CORRELATIONS dictionary mapping all 150 diseases
to their symptoms, ICD-10 codes, medications, and primary specialties.

Data sourced from WHO ICD-10 classification.

MEDICAL DISCLAIMER: This data is for TESTING AND DEVELOPMENT PURPOSES ONLY.
It should NOT be used for actual medical diagnosis, treatment, or healthcare decisions.
"""

from .types import DiseaseData


DISEASE_CORRELATIONS: dict[str, DiseaseData] = {
    "Type 2 Diabetes": {
        "icd10": "E11.9",
        "symptoms": ["Frequent Urination", "Increased Appetite", "Fatigue", "Blurred Vision", "Weight Loss"],
        "medications": ["Metformin", "Insulin Glargine", "Empagliflozin", "Sitagliptin", "Glimepiride"],
        "specialty": "Endocrinology",
    },
    "Essential Hypertension": {
        "icd10": "I10",
        "symptoms": ["Headache", "Dizziness", "Chest Pain", "Blurred Vision", "Palpitations"],
        "medications": ["Lisinopril", "Amlodipine", "Losartan", "Hydrochlorothiazide", "Metoprolol"],
        "specialty": "Cardiology",
    },
    "Hyperlipidemia": {
        "icd10": "E78.5",
        "symptoms": ["Chest Pain", "Fatigue", "Numbness", "Weakness"],
        "medications": ["Atorvastatin", "Simvastatin", "Rosuvastatin", "Fenofibrate", "Ezetimibe"],
        "specialty": "Cardiology",
    },
    "Coronary Artery Disease": {
        "icd10": "I25.10",
        "symptoms": ["Chest Pain", "Shortness of Breath", "Fatigue", "Palpitations", "Dizziness"],
        "medications": ["Aspirin", "Clopidogrel", "Atorvastatin", "Metoprolol", "Nitroglycerin"],
        "specialty": "Cardiology",
    },
    "Chronic Obstructive Pulmonary Disease": {
        "icd10": "J44.9",
        "symptoms": ["Shortness of Breath", "Cough", "Wheezing", "Chest Pain", "Fatigue"],
        "medications": ["Albuterol", "Tiotropium", "Fluticasone", "Prednisone", "Azithromycin"],
        "specialty": "Pulmonology",
    },
    "Asthma": {
        "icd10": "J45.909",
        "symptoms": ["Wheezing", "Shortness of Breath", "Cough", "Chest Pain", "Difficulty Breathing"],
        "medications": ["Albuterol", "Fluticasone", "Montelukast", "Prednisone", "Budesonide"],
        "specialty": "Pulmonology",
    },
    "Chronic Kidney Disease": {
        "icd10": "N18.9",
        "symptoms": ["Fatigue", "Swelling", "Nausea", "Loss of Appetite", "Frequent Urination"],
        "medications": ["Lisinopril", "Furosemide", "Erythropoietin", "Calcium Carbonate", "Sevelamer"],
        "specialty": "Nephrology",
    },
    "Osteoarthritis": {
        "icd10": "M17.9",
        "symptoms": ["Joint Pain", "Swelling", "Weakness", "Back Pain"],
        "medications": ["Ibuprofen", "Acetaminophen", "Naproxen", "Celecoxib", "Tramadol"],
        "specialty": "Orthopedics",
    },
    "Rheumatoid Arthritis": {
        "icd10": "M79.1",
        "symptoms": ["Joint Pain", "Swelling", "Fatigue", "Weakness", "Muscle Aches"],
        "medications": ["Methotrexate", "Prednisone", "Adalimumab", "Hydroxychloroquine", "Sulfasalazine"],
        "specialty": "Rheumatology",
    },
    "Depression": {
        "icd10": "F32.9",
        "symptoms": ["Depression", "Fatigue", "Insomnia", "Loss of Appetite", "Anxiety"],
        "medications": ["Sertraline", "Fluoxetine", "Escitalopram", "Bupropion", "Duloxetine"],
        "specialty": "Psychiatry",
    },
    "Anxiety Disorder": {
        "icd10": "F41.9",
        "symptoms": ["Anxiety", "Palpitations", "Sweating", "Tremor", "Insomnia"],
        "medications": ["Sertraline", "Escitalopram", "Alprazolam", "Lorazepam", "Buspirone"],
        "specialty": "Psychiatry",
    },
    "Gastroesophageal Reflux Disease": {
        "icd10": "K21.9",
        "symptoms": ["Heartburn", "Chest Pain", "Difficulty Swallowing", "Sore Throat", "Nausea"],
        "medications": ["Omeprazole", "Pantoprazole", "Esomeprazole", "Ranitidine", "Famotidine"],
        "specialty": "Gastroenterology",
    },
    "Obesity": {
        "icd10": "E66.9",
        "symptoms": ["Fatigue", "Joint Pain", "Shortness of Breath", "Sweating"],
        "medications": ["Orlistat", "Phentermine", "Liraglutide", "Semaglutide", "Naltrexone"],
        "specialty": "Endocrinology",
    },
    "Hypothyroidism": {
        "icd10": "E03.9",
        "symptoms": ["Fatigue", "Weight Loss", "Hair Loss", "Dry Skin", "Constipation"],
        "medications": ["Levothyroxine", "Liothyronine", "Thyroid"],
        "specialty": "Endocrinology",
    },
    "Atrial Fibrillation": {
        "icd10": "I48.91",
        "symptoms": ["Palpitations", "Dizziness", "Fatigue", "Shortness of Breath", "Chest Pain"],
        "medications": ["Warfarin", "Apixaban", "Rivaroxaban", "Metoprolol", "Diltiazem"],
        "specialty": "Cardiology",
    },
    "Congestive Heart Failure": {
        "icd10": "I50.9",
        "symptoms": ["Shortness of Breath", "Fatigue", "Swelling", "Cough", "Rapid Heartbeat"],
        "medications": ["Furosemide", "Lisinopril", "Metoprolol", "Spironolactone", "Digoxin"],
        "specialty": "Cardiology",
    },
    "Pneumonia": {
        "icd10": "J18.9",
        "symptoms": ["Fever", "Cough", "Shortness of Breath", "Chest Pain", "Fatigue"],
        "medications": ["Amoxicillin", "Azithromycin", "Ceftriaxone", "Levofloxacin", "Doxycycline"],
        "specialty": "Pulmonology",
    },
    "Urinary Tract Infection": {
        "icd10": "N39.0",
        "symptoms": ["Painful Urination", "Frequent Urination", "Fever", "Abdominal Pain", "Cloudy Urine"],
        "medications": ["Nitrofurantoin", "Ciprofloxacin", "Trimethoprim", "Amoxicillin", "Cephalexin"],
        "specialty": "Internal Medicine",
    },
    "Acute Bronchitis": {
        "icd10": "J20.9",
        "symptoms": ["Cough", "Fever", "Fatigue", "Shortness of Breath", "Chest Pain"],
        "medications": ["Albuterol", "Guaifenesin", "Dextromethorphan", "Ibuprofen", "Azithromycin"],
        "specialty": "Pulmonology",
    },
    "Anemia": {
        "icd10": "D64.9",
        "symptoms": ["Fatigue", "Weakness", "Dizziness", "Headache", "Shortness of Breath"],
        "medications": ["Ferrous Sulfate", "Vitamin B12", "Folic Acid", "Erythropoietin"],
        "specialty": "Hematology",
    },
    "Migraine": {
        "icd10": "G43.909",
        "symptoms": ["Headache", "Nausea", "Light Sensitivity", "Blurred Vision", "Dizziness"],
        "medications": ["Sumatriptan", "Ibuprofen", "Topiramate", "Propranolol", "Amitriptyline"],
        "specialty": "Neurology",
    },
    "Stroke": {
        "icd10": "I63.9",
        "symptoms": ["Numbness", "Confusion", "Difficulty Swallowing", "Blurred Vision", "Weakness"],
        "medications": ["Aspirin", "Clopidogrel", "Alteplase", "Warfarin", "Atorvastatin"],
        "specialty": "Neurology",
    },
    "Alzheimer's Disease": {
        "icd10": "G30.9",
        "symptoms": ["Memory Loss", "Confusion", "Anxiety", "Depression", "Difficulty Swallowing"],
        "medications": ["Donepezil", "Memantine", "Rivastigmine", "Galantamine"],
        "specialty": "Neurology",
    },
    "Breast Cancer": {
        "icd10": "C50.919",
        "symptoms": ["Breast Lump", "Nipple Discharge", "Swelling", "Weight Loss", "Fatigue"],
        "medications": ["Tamoxifen", "Anastrozole", "Trastuzumab", "Chemotherapy", "Radiation"],
        "specialty": "Oncology",
    },
    "Prostate Cancer": {
        "icd10": "C61",
        "symptoms": ["Painful Urination", "Frequent Urination", "Weakness", "Weight Loss"],
        "medications": ["Leuprolide", "Bicalutamide", "Docetaxel", "Abiraterone", "Enzalutamide"],
        "specialty": "Oncology",
    },
    "Lung Cancer": {
        "icd10": "C34.90",
        "symptoms": ["Cough", "Coughing Blood", "Shortness of Breath", "Chest Pain", "Weight Loss"],
        "medications": ["Carboplatin", "Paclitaxel", "Pembrolizumab", "Erlotinib", "Chemotherapy"],
        "specialty": "Oncology",
    },
    "COVID-19": {
        "icd10": "U07.1",
        "symptoms": ["Fever", "Cough", "Fatigue", "Loss of Smell", "Loss of Taste", "Shortness of Breath"],
        "medications": ["Remdesivir", "Dexamethasone", "Paxlovid", "Molnupiravir"],
        "specialty": "Infectious Disease",
    },
    "Influenza": {
        "icd10": "J11.1",
        "symptoms": ["Fever", "Cough", "Sore Throat", "Muscle Aches", "Fatigue", "Headache"],
        "medications": ["Oseltamivir", "Zanamivir", "Baloxavir", "Ibuprofen", "Acetaminophen"],
        "specialty": "Internal Medicine",
    },
    "Osteoporosis": {
        "icd10": "M81.0",
        "symptoms": ["Back Pain", "Bone Loss", "Weakness"],
        "medications": ["Alendronate", "Risedronate", "Denosumab", "Calcium Carbonate", "Vitamin D"],
        "specialty": "Endocrinology",
    },
    "Peripheral Artery Disease": {
        "icd10": "I73.9",
        "symptoms": ["Leg Pain", "Numbness", "Weakness", "Cold Extremities"],
        "medications": ["Cilostazol", "Aspirin", "Clopidogrel", "Atorvastatin", "Pentoxifylline"],
        "specialty": "Vascular Surgery",
    },
    "Angina Pectoris": {
        "icd10": "I20.9",
        "symptoms": ["Chest Pain", "Shortness of Breath", "Fatigue", "Nausea", "Sweating"],
        "medications": ["Nitroglycerin", "Aspirin", "Metoprolol", "Amlodipine", "Atorvastatin"],
        "specialty": "Cardiology",
    },
    "Hyperthyroidism": {
        "icd10": "E05.90",
        "symptoms": ["Weight Loss", "Palpitations", "Anxiety", "Tremor", "Heat Intolerance"],
        "medications": ["Methimazole", "Propylthiouracil", "Propranolol", "Radioactive Iodine", "Levothyroxine"],
        "specialty": "Endocrinology",
    },
    "Gout": {
        "icd10": "M10.9",
        "symptoms": ["Joint Pain", "Swelling", "Redness", "Tophi", "Limited Mobility"],
        "medications": ["Allopurinol", "Colchicine", "Indomethacin", "Febuxostat", "Probenecid"],
        "specialty": "Rheumatology",
    },
    "Multiple Sclerosis": {
        "icd10": "G35",
        "symptoms": ["Fatigue", "Numbness", "Vision Problems", "Balance Issues", "Muscle Weakness"],
        "medications": ["Interferon Beta", "Glatiramer Acetate", "Fingolimod", "Natalizumab", "Ocrelizumab"],
        "specialty": "Neurology",
    },
    "Parkinson's Disease": {
        "icd10": "G20",
        "symptoms": ["Tremor", "Bradykinesia", "Rigidity", "Postural Instability", "Speech Changes"],
        "medications": ["Levodopa", "Carbidopa", "Pramipexole", "Selegiline", "Amantadine"],
        "specialty": "Neurology",
    },
    "Epilepsy": {
        "icd10": "G40.909",
        "symptoms": ["Seizures", "Loss of Consciousness", "Confusion", "Staring Spells", "Convulsions"],
        "medications": ["Carbamazepine", "Valproate", "Lamotrigine", "Levetiracetam", "Phenytoin"],
        "specialty": "Neurology",
    },
    "Bipolar Disorder": {
        "icd10": "F31.9",
        "symptoms": ["Mood Swings", "Mania", "Depression", "Irritability", "Insomnia"],
        "medications": ["Lithium", "Valproate", "Olanzapine", "Quetiapine", "Lamotrigine"],
        "specialty": "Psychiatry",
    },
    "Schizophrenia": {
        "icd10": "F20.9",
        "symptoms": ["Hallucinations", "Delusions", "Disorganized Thinking", "Negative Symptoms", "Cognitive Impairment"],
        "medications": ["Risperidone", "Olanzapine", "Quetiapine", "Aripiprazole", "Haloperidol"],
        "specialty": "Psychiatry",
    },
    "Attention Deficit Hyperactivity Disorder": {
        "icd10": "F90.9",
        "symptoms": ["Inattention", "Hyperactivity", "Impulsivity", "Disorganization", "Forgetfulness"],
        "medications": ["Methylphenidate", "Amphetamine", "Atomoxetine", "Guanfacine", "Clonidine"],
        "specialty": "Psychiatry",
    },
    "Autism Spectrum Disorder": {
        "icd10": "F84.0",
        "symptoms": ["Social Impairment", "Communication Difficulties", "Repetitive Behaviors", "Sensory Sensitivities", "Restricted Interests"],
        "medications": ["Risperidone", "Aripiprazole", "SSRIs", "Stimulants", "Anticonvulsants"],
        "specialty": "Psychiatry",
    },
    "Crohn's Disease": {
        "icd10": "K50.90",
        "symptoms": ["Abdominal Pain", "Diarrhea", "Weight Loss", "Fatigue", "Blood in Stool"],
        "medications": ["Mesalamine", "Prednisone", "Azathioprine", "Infliximab", "Adalimumab"],
        "specialty": "Gastroenterology",
    },
    "Ulcerative Colitis": {
        "icd10": "K51.90",
        "symptoms": ["Bloody Diarrhea", "Abdominal Pain", "Urgency", "Weight Loss", "Fatigue"],
        "medications": ["Mesalamine", "Prednisone", "Azathioprine", "Infliximab", "Vedolizumab"],
        "specialty": "Gastroenterology",
    },
    "Irritable Bowel Syndrome": {
        "icd10": "K58.9",
        "symptoms": ["Abdominal Pain", "Bloating", "Diarrhea", "Constipation", "Gas"],
        "medications": ["Loperamide", "Lubiprostone", "Linaclotide", "Dicyclomine", "Rifaximin"],
        "specialty": "Gastroenterology",
    },
    "Celiac Disease": {
        "icd10": "K90.0",
        "symptoms": ["Abdominal Pain", "Diarrhea", "Bloating", "Fatigue", "Weight Loss"],
        "medications": ["No Medications", "Gluten-Free Diet", "Vitamin Supplements", "Iron Supplements", "Probiotics"],
        "specialty": "Gastroenterology",
    },
    "Cirrhosis": {
        "icd10": "K74.60",
        "symptoms": ["Fatigue", "Jaundice", "Abdominal Swelling", "Confusion", "Easy Bruising"],
        "medications": ["Lactulose", "Propranolol", "Diuretics", "Vitamin Supplements", "Antibiotics"],
        "specialty": "Gastroenterology",
    },
    "Hepatitis C": {
        "icd10": "B18.2",
        "symptoms": ["Fatigue", "Jaundice", "Abdominal Pain", "Loss of Appetite", "Nausea"],
        "medications": ["Sofosbuvir", "Ledipasvir", "Glecaprevir", "Pibrentasvir", "Ribavirin"],
        "specialty": "Gastroenterology",
    },
    "HIV/AIDS": {
        "icd10": "B20",
        "symptoms": ["Fever", "Fatigue", "Weight Loss", "Swollen Lymph Nodes", "Recurrent Infections"],
        "medications": ["Tenofovir", "Emtricitabine", "Dolutegravir", "Efavirenz", "Ritonavir"],
        "specialty": "Infectious Disease",
    },
    "Tuberculosis": {
        "icd10": "A15.0",
        "symptoms": ["Cough", "Fever", "Night Sweats", "Weight Loss", "Chest Pain"],
        "medications": ["Isoniazid", "Rifampin", "Pyrazinamide", "Ethambutol", "Streptomycin"],
        "specialty": "Pulmonology",
    },
    "Sepsis": {
        "icd10": "A41.9",
        "symptoms": ["Fever", "Rapid Heart Rate", "Confusion", "Shortness of Breath", "Low Blood Pressure"],
        "medications": ["Broad-Spectrum Antibiotics", "IV Fluids", "Vasopressors", "Corticosteroids", "Insulin"],
        "specialty": "Critical Care",
    },
    "Deep Vein Thrombosis": {
        "icd10": "I82.409",
        "symptoms": ["Leg Pain", "Swelling", "Redness", "Warmth", "Cramping"],
        "medications": ["Heparin", "Warfarin", "Rivaroxaban", "Apixaban", "Enoxaparin"],
        "specialty": "Vascular Medicine",
    },
    "Pulmonary Embolism": {
        "icd10": "I26.99",
        "symptoms": ["Shortness of Breath", "Chest Pain", "Cough", "Hemoptysis", "Rapid Heart Rate"],
        "medications": ["Heparin", "Warfarin", "Rivaroxaban", "Apixaban", "Thrombolytics"],
        "specialty": "Pulmonology",
    },
    "Aortic Aneurysm": {
        "icd10": "I71.9",
        "symptoms": ["Abdominal Pain", "Back Pain", "Pulsatile Mass", "Hypotension", "Syncope"],
        "medications": ["Beta-Blockers", "Statins", "ACE Inhibitors", "Antihypertensives", "Pain Relievers"],
        "specialty": "Vascular Surgery",
    },
    "Valvular Heart Disease": {
        "icd10": "I38",
        "symptoms": ["Shortness of Breath", "Fatigue", "Chest Pain", "Palpitations", "Edema"],
        "medications": ["Diuretics", "ACE Inhibitors", "Beta-Blockers", "Anticoagulants", "Vasodilators"],
        "specialty": "Cardiology",
    },
    "Cardiomyopathy": {
        "icd10": "I42.9",
        "symptoms": ["Fatigue", "Shortness of Breath", "Swelling", "Irregular Heartbeat", "Chest Pain"],
        "medications": ["ACE Inhibitors", "Beta-Blockers", "Diuretics", "Aldosterone Antagonists", "Digoxin"],
        "specialty": "Cardiology",
    },
    "Endocarditis": {
        "icd10": "I33.0",
        "symptoms": ["Fever", "Fatigue", "Shortness of Breath", "Night Sweats", "Joint Pain"],
        "medications": ["Penicillin", "Vancomycin", "Gentamicin", "Ampicillin", "Ceftriaxone"],
        "specialty": "Cardiology",
    },
    "Pericarditis": {
        "icd10": "I30.9",
        "symptoms": ["Chest Pain", "Fever", "Fatigue", "Shortness of Breath", "Cough"],
        "medications": ["Ibuprofen", "Colchicine", "Prednisone", "Aspirin", "Antibiotics"],
        "specialty": "Cardiology",
    },
    "Myocardial Infarction": {
        "icd10": "I21.9",
        "symptoms": ["Chest Pain", "Shortness of Breath", "Nausea", "Sweating", "Lightheadedness"],
        "medications": ["Aspirin", "Clopidogrel", "Heparin", "Beta-Blockers", "ACE Inhibitors"],
        "specialty": "Cardiology",
    },
    "Congenital Heart Disease": {
        "icd10": "Q24.9",
        "symptoms": ["Cyanosis", "Shortness of Breath", "Fatigue", "Poor Growth", "Heart Murmurs"],
        "medications": ["Diuretics", "ACE Inhibitors", "Beta-Blockers", "Prostaglandin E1", "Antibiotics"],
        "specialty": "Cardiology",
    },
    "Peripheral Neuropathy": {
        "icd10": "G62.9",
        "symptoms": ["Numbness", "Tingling", "Pain", "Weakness", "Burning Sensation"],
        "medications": ["Gabapentin", "Pregabalin", "Duloxetine", "Amitriptyline", "Capsaicin"],
        "specialty": "Neurology",
    },
    "Sleep Apnea": {
        "icd10": "G47.30",
        "symptoms": ["Snoring", "Daytime Sleepiness", "Fatigue", "Morning Headaches", "Irritability"],
        "medications": ["CPAP Therapy", "Modafinil", "Armodafinil", "Acetazolamide", "Theophylline"],
        "specialty": "Pulmonology",
    },
    "Narcolepsy": {
        "icd10": "G47.419",
        "symptoms": ["Excessive Daytime Sleepiness", "Cataplexy", "Sleep Paralysis", "Hallucinations", "Fragmented Sleep"],
        "medications": ["Modafinil", "Sodium Oxybate", "Pitolisant", "Methylphenidate", "Amphetamine"],
        "specialty": "Neurology",
    },
    "Restless Leg Syndrome": {
        "icd10": "G25.81",
        "symptoms": ["Urge to Move Legs", "Uncomfortable Sensations", "Worsening at Night", "Sleep Disturbance", "Relief with Movement"],
        "medications": ["Pramipexole", "Ropinirole", "Gabapentin", "Iron Supplements", "Clonazepam"],
        "specialty": "Neurology",
    },
    "Fibromyalgia": {
        "icd10": "M79.7",
        "symptoms": ["Widespread Pain", "Fatigue", "Sleep Disturbances", "Cognitive Difficulties", "Headaches"],
        "medications": ["Duloxetine", "Pregabalin", "Milnacipran", "Amitriptyline", "Cyclobenzaprine"],
        "specialty": "Rheumatology",
    },
    "Lupus": {
        "icd10": "M32.9",
        "symptoms": ["Fatigue", "Joint Pain", "Rash", "Fever", "Photosensitivity"],
        "medications": ["Hydroxychloroquine", "Prednisone", "Methotrexate", "Mycophenolate", "Belimumab"],
        "specialty": "Rheumatology",
    },
    "Scleroderma": {
        "icd10": "M34.9",
        "symptoms": ["Skin Thickening", "Raynaud's Phenomenon", "Joint Pain", "Shortness of Breath", "Gastrointestinal Issues"],
        "medications": ["Methotrexate", "Mycophenolate", "Cyclophosphamide", "Nifedipine", "Proton Pump Inhibitors"],
        "specialty": "Rheumatology",
    },
    "Sjögren's Syndrome": {
        "icd10": "M35.00",
        "symptoms": ["Dry Mouth", "Dry Eyes", "Fatigue", "Joint Pain", "Swollen Salivary Glands"],
        "medications": ["Pilocarpine", "Cevimeline", "Hydroxychloroquine", "Cyclosporine", "Artificial Tears"],
        "specialty": "Rheumatology",
    },
    "Psoriasis": {
        "icd10": "L40.9",
        "symptoms": ["Red Patches", "Itching", "Scaling", "Thickened Skin", "Joint Pain"],
        "medications": ["Methotrexate", "Cyclosporine", "Adalimumab", "Topical Corticosteroids", "Vitamin D Analogues"],
        "specialty": "Dermatology",
    },
    "Eczema": {
        "icd10": "L30.9",
        "symptoms": ["Itching", "Redness", "Dry Skin", "Rash", "Swelling"],
        "medications": ["Hydrocortisone", "Tacrolimus", "Pimecrolimus", "Dupilumab", "Moisturizers"],
        "specialty": "Dermatology",
    },
    "Rosacea": {
        "icd10": "L71.9",
        "symptoms": ["Facial Redness", "Pimples", "Visible Blood Vessels", "Eye Irritation", "Swelling"],
        "medications": ["Metronidazole", "Azelaic Acid", "Ivermectin", "Doxycycline", "Brimonidine"],
        "specialty": "Dermatology",
    },
    "Acne Vulgaris": {
        "icd10": "L70.0",
        "symptoms": ["Pimples", "Blackheads", "Whiteheads", "Cysts", "Scarring"],
        "medications": ["Benzoyl Peroxide", "Salicylic Acid", "Retinoids", "Antibiotics", "Isotretinoin"],
        "specialty": "Dermatology",
    },
    "Melanoma": {
        "icd10": "C43.9",
        "symptoms": ["Changing Mole", "Asymmetrical Shape", "Irregular Borders", "Color Variation", "Diameter Increase"],
        "medications": ["Pembrolizumab", "Nivolumab", "Ipilimumab", "Dacarbazine", "Trametinib"],
        "specialty": "Oncology",
    },
    "Basal Cell Carcinoma": {
        "icd10": "C44.91",
        "symptoms": ["Pearly Bump", "Sore That Doesn't Heal", "Scar-Like Area", "Red Patch", "Bleeding"],
        "medications": ["Imiquimod", "Fluorouracil", "Vismodegib", "Sonidegib", "Photodynamic Therapy"],
        "specialty": "Dermatology",
    },
    "Squamous Cell Carcinoma": {
        "icd10": "C44.92",
        "symptoms": ["Rough Red Patch", "Open Sore", "Crusted Surface", "Growth with Central Depression", "Itching"],
        "medications": ["Fluorouracil", "Imiquimod", "Pembrolizumab", "Cemiplimab", "Chemotherapy"],
        "specialty": "Dermatology",
    },
    "Leukemia": {
        "icd10": "C95.90",
        "symptoms": ["Fatigue", "Fever", "Weight Loss", "Easy Bruising", "Recurrent Infections"],
        "medications": ["Imatinib", "Cytarabine", "Daunorubicin", "Vincristine", "Hydroxyurea"],
        "specialty": "Hematology",
    },
    "Lymphoma": {
        "icd10": "C85.90",
        "symptoms": ["Swollen Lymph Nodes", "Fever", "Night Sweats", "Weight Loss", "Fatigue"],
        "medications": ["Rituximab", "Cyclophosphamide", "Doxorubicin", "Vincristine", "Prednisone"],
        "specialty": "Oncology",
    },
    "Myeloma": {
        "icd10": "C90.00",
        "symptoms": ["Bone Pain", "Fatigue", "Anemia", "Recurrent Infections", "Kidney Problems"],
        "medications": ["Bortezomib", "Lenalidomide", "Dexamethasone", "Daratumumab", "Melphalan"],
        "specialty": "Hematology",
    },
    "Colon Cancer": {
        "icd10": "C18.9",
        "symptoms": ["Abdominal Pain", "Blood in Stool", "Change in Bowel Habits", "Weight Loss", "Fatigue"],
        "medications": ["Fluorouracil", "Oxaliplatin", "Capecitabine", "Bevacizumab", "Cetuximab"],
        "specialty": "Oncology",
    },
    "Pancreatic Cancer": {
        "icd10": "C25.9",
        "symptoms": ["Abdominal Pain", "Jaundice", "Weight Loss", "Loss of Appetite", "Nausea"],
        "medications": ["Gemcitabine", "Paclitaxel", "Erlotinib", "FOLFIRINOX", "Capecitabine"],
        "specialty": "Oncology",
    },
    "Kidney Cancer": {
        "icd10": "C64.9",
        "symptoms": ["Blood in Urine", "Back Pain", "Weight Loss", "Fatigue", "Fever"],
        "medications": ["Sunitinib", "Pazopanib", "Axitinib", "Nivolumab", "Cabozantinib"],
        "specialty": "Oncology",
    },
    "Bladder Cancer": {
        "icd10": "C67.9",
        "symptoms": ["Blood in Urine", "Frequent Urination", "Painful Urination", "Back Pain", "Pelvic Pain"],
        "medications": ["BCG", "Mitomycin", "Gemcitabine", "Cisplatin", "Pembrolizumab"],
        "specialty": "Urology",
    },
    "Ovarian Cancer": {
        "icd10": "C56.9",
        "symptoms": ["Abdominal Bloating", "Pelvic Pain", "Loss of Appetite", "Frequent Urination", "Fatigue"],
        "medications": ["Carboplatin", "Paclitaxel", "Bevacizumab", "Olaparib", "Doxorubicin"],
        "specialty": "Oncology",
    },
    "Endometrial Cancer": {
        "icd10": "C54.1",
        "symptoms": ["Abnormal Vaginal Bleeding", "Pelvic Pain", "Weight Loss", "Fatigue", "Bloating"],
        "medications": ["Progesterone", "Tamoxifen", "Carboplatin", "Paclitaxel", "Doxorubicin"],
        "specialty": "Oncology",
    },
    "Thyroid Cancer": {
        "icd10": "C73",
        "symptoms": ["Neck Lump", "Hoarseness", "Difficulty Swallowing", "Neck Pain", "Swollen Lymph Nodes"],
        "medications": ["Levothyroxine", "Radioactive Iodine", "Sorafenib", "Lenvatinib", "Cabozantinib"],
        "specialty": "Endocrinology",
    },
    "Brain Tumor": {
        "icd10": "C71.9",
        "symptoms": ["Headaches", "Seizures", "Nausea", "Vision Changes", "Cognitive Impairment"],
        "medications": ["Temozolomide", "Bevacizumab", "Carmustine", "Lomustine", "Dexamethasone"],
        "specialty": "Neurology",
    },
    "Glaucoma": {
        "icd10": "H40.9",
        "symptoms": ["Vision Loss", "Eye Pain", "Halos Around Lights", "Red Eyes", "Nausea"],
        "medications": ["Timolol", "Latanoprost", "Brimonidine", "Acetazolamide", "Pilocarpine"],
        "specialty": "Ophthalmology",
    },
    "Macular Degeneration": {
        "icd10": "H35.30",
        "symptoms": ["Blurred Vision", "Central Vision Loss", "Distorted Vision", "Dark Spots", "Color Fading"],
        "medications": ["Ranibizumab", "Aflibercept", "Bevacizumab", "Verteporfin", "Vitamin Supplements"],
        "specialty": "Ophthalmology",
    },
    "Cataracts": {
        "icd10": "H26.9",
        "symptoms": ["Blurred Vision", "Glare Sensitivity", "Poor Night Vision", "Fading Colors", "Double Vision"],
        "medications": ["No Medications", "Surgery", "Eyeglasses", "Anti-Glare Lenses", "Magnifiers"],
        "specialty": "Ophthalmology",
    },
    "Diabetic Retinopathy": {
        "icd10": "E11.319",
        "symptoms": ["Blurred Vision", "Floaters", "Vision Loss", "Color Changes", "Dark Areas"],
        "medications": ["Ranibizumab", "Aflibercept", "Bevacizumab", "Laser Therapy", "Vitrectomy"],
        "specialty": "Ophthalmology",
    },
    "Hearing Loss": {
        "icd10": "H91.90",
        "symptoms": ["Difficulty Hearing", "Muffled Sounds", "Tinnitus", "Ear Pain", "Balance Issues"],
        "medications": ["No Medications", "Hearing Aids", "Cochlear Implants", "Steroids", "Antibiotics"],
        "specialty": "Otolaryngology",
    },
    "Meniere's Disease": {
        "icd10": "H81.09",
        "symptoms": ["Vertigo", "Hearing Loss", "Tinnitus", "Ear Fullness", "Nausea"],
        "medications": ["Meclizine", "Diuretics", "Betahistine", "Steroids", "Gentamicin"],
        "specialty": "Otolaryngology",
    },
    "Benign Prostatic Hyperplasia": {
        "icd10": "N40.0",
        "symptoms": ["Frequent Urination", "Weak Stream", "Urgency", "Nocturia", "Incomplete Emptying"],
        "medications": ["Tamsulosin", "Finasteride", "Dutasteride", "Terazosin", "Sildenafil"],
        "specialty": "Urology",
    },
    "Erectile Dysfunction": {
        "icd10": "N52.9",
        "symptoms": ["Inability to Maintain Erection", "Reduced Libido", "Premature Ejaculation", "Stress", "Fatigue"],
        "medications": ["Sildenafil", "Tadalafil", "Vardenafil", "Alprostadil", "Testosterone"],
        "specialty": "Urology",
    },
    "Polycystic Ovary Syndrome": {
        "icd10": "E28.2",
        "symptoms": ["Irregular Periods", "Excess Hair Growth", "Acne", "Weight Gain", "Infertility"],
        "medications": ["Combined Oral Contraceptives", "Metformin", "Spironolactone", "Clomiphene", "Letrozole"],
        "specialty": "Endocrinology",
    },
    "Endometriosis": {
        "icd10": "N80.9",
        "symptoms": ["Pelvic Pain", "Dysmenorrhea", "Infertility", "Painful Intercourse", "Heavy Periods"],
        "medications": ["Ibuprofen", "Combined Oral Contraceptives", "Progestins", "GnRH Agonists", "Danazol"],
        "specialty": "Gynecology",
    },
    "Uterine Fibroids": {
        "icd10": "D25.9",
        "symptoms": ["Heavy Menstrual Bleeding", "Pelvic Pain", "Frequent Urination", "Constipation", "Back Pain"],
        "medications": ["GnRH Agonists", "Progestins", "Tranexamic Acid", "Ibuprofen", "Ulipristal Acetate"],
        "specialty": "Gynecology",
    },
    "Preeclampsia": {
        "icd10": "O14.90",
        "symptoms": ["High Blood Pressure", "Proteinuria", "Swelling", "Headache", "Vision Changes"],
        "medications": ["Magnesium Sulfate", "Labetalol", "Hydralazine", "Nifedipine", "Delivery"],
        "specialty": "Obstetrics",
    },
    "Gestational Diabetes": {
        "icd10": "O24.419",
        "symptoms": ["Increased Thirst", "Frequent Urination", "Fatigue", "Blurred Vision", "Nausea"],
        "medications": ["Insulin", "Metformin", "Glyburide", "Diet Control", "Exercise"],
        "specialty": "Obstetrics",
    },
    "Vitamin D Deficiency": {
        "icd10": "E55.9",
        "symptoms": ["Fatigue", "Bone Pain", "Muscle Weakness", "Depression", "Hair Loss"],
        "medications": ["Vitamin D Supplements", "Cholecalciferol", "Ergocalciferol", "Calcium Supplements", "Sun Exposure"],
        "specialty": "Endocrinology",
    },
    "Iron Deficiency Anemia": {
        "icd10": "D50.9",
        "symptoms": ["Fatigue", "Pale Skin", "Shortness of Breath", "Dizziness", "Cold Hands"],
        "medications": ["Ferrous Sulfate", "Ferrous Gluconate", "Iron Infusions", "Vitamin C", "Folic Acid"],
        "specialty": "Hematology",
    },
    "Pernicious Anemia": {
        "icd10": "D51.0",
        "symptoms": ["Fatigue", "Weakness", "Pale Skin", "Numbness", "Cognitive Changes"],
        "medications": ["Vitamin B12 Injections", "Oral B12 Supplements", "Folic Acid", "Iron Supplements", "Erythropoietin"],
        "specialty": "Hematology",
    },
    "Sickle Cell Disease": {
        "icd10": "D57.1",
        "symptoms": ["Pain Crises", "Anemia", "Fatigue", "Jaundice", "Swelling"],
        "medications": ["Hydroxyurea", "Pain Relievers", "Antibiotics", "Blood Transfusions", "Voxelotor"],
        "specialty": "Hematology",
    },
    "Hemophilia": {
        "icd10": "D68.311",
        "symptoms": ["Prolonged Bleeding", "Joint Pain", "Bruising", "Hemarthrosis", "Nosebleeds"],
        "medications": ["Factor VIII", "Factor IX", "Desmopressin", "Antifibrinolytics", "Emicizumab"],
        "specialty": "Hematology",
    },
    "Thrombocytopenia": {
        "icd10": "D69.6",
        "symptoms": ["Bruising", "Bleeding Gums", "Nosebleeds", "Petechiae", "Heavy Periods"],
        "medications": ["Corticosteroids", "IVIG", "Romiplostim", "Eltrombopag", "Splenectomy"],
        "specialty": "Hematology",
    },
    "Leukopenia": {
        "icd10": "D72.819",
        "symptoms": ["Frequent Infections", "Fever", "Fatigue", "Mouth Ulcers", "Sore Throat"],
        "medications": ["G-CSF", "GM-CSF", "Antibiotics", "Antivirals", "Vitamin Supplements"],
        "specialty": "Hematology",
    },
    "Diverticulitis": {
        "icd10": "K57.92",
        "symptoms": ["Abdominal Pain", "Fever", "Nausea", "Constipation", "Diarrhea"],
        "medications": ["Ciprofloxacin", "Metronidazole", "Augmentin", "Ibuprofen", "Acetaminophen"],
        "specialty": "Gastroenterology",
    },
    "Appendicitis": {
        "icd10": "K35.80",
        "symptoms": ["Abdominal Pain", "Nausea", "Vomiting", "Fever", "Loss of Appetite"],
        "medications": ["Antibiotics", "Pain Relievers", "IV Fluids", "Surgery", "Anti-Nausea"],
        "specialty": "General Surgery",
    },
    "Cholecystitis": {
        "icd10": "K81.0",
        "symptoms": ["Abdominal Pain", "Nausea", "Vomiting", "Fever", "Jaundice"],
        "medications": ["Antibiotics", "Pain Relievers", "Ursodiol", "IV Fluids", "Surgery"],
        "specialty": "General Surgery",
    },
    "Pancreatitis": {
        "icd10": "K85.90",
        "symptoms": ["Abdominal Pain", "Nausea", "Vomiting", "Fever", "Rapid Pulse"],
        "medications": ["IV Fluids", "Pain Relievers", "Antibiotics", "Enzyme Supplements", "Insulin"],
        "specialty": "Gastroenterology",
    },
    "Peptic Ulcer Disease": {
        "icd10": "K27.9",
        "symptoms": ["Abdominal Pain", "Bloating", "Nausea", "Vomiting", "Heartburn"],
        "medications": ["Omeprazole", "Ranitidine", "Amoxicillin", "Clarithromycin", "Sucralfate"],
        "specialty": "Gastroenterology",
    },
    "Gastritis": {
        "icd10": "K29.70",
        "symptoms": ["Abdominal Pain", "Nausea", "Vomiting", "Bloating", "Loss of Appetite"],
        "medications": ["Omeprazole", "Ranitidine", "Antacids", "Sucralfate", "Antibiotics"],
        "specialty": "Gastroenterology",
    },
    "Esophagitis": {
        "icd10": "K20.90",
        "symptoms": ["Heartburn", "Difficulty Swallowing", "Chest Pain", "Regurgitation", "Nausea"],
        "medications": ["Omeprazole", "Ranitidine", "Sucralfate", "Antacids", "Prokinetics"],
        "specialty": "Gastroenterology",
    },
    "Barrett's Esophagus": {
        "icd10": "K22.70",
        "symptoms": ["Heartburn", "Regurgitation", "Difficulty Swallowing", "Chest Pain", "Nausea"],
        "medications": ["Omeprazole", "Esomeprazole", "Antacids", "H2 Blockers", "Proton Pump Inhibitors"],
        "specialty": "Gastroenterology",
    },
    "Hiatal Hernia": {
        "icd10": "K44.9",
        "symptoms": ["Heartburn", "Chest Pain", "Difficulty Swallowing", "Regurgitation", "Bloating"],
        "medications": ["Antacids", "H2 Blockers", "Proton Pump Inhibitors", "Prokinetics", "Surgery"],
        "specialty": "Gastroenterology",
    },
    "Hemorrhoids": {
        "icd10": "K64.9",
        "symptoms": ["Rectal Bleeding", "Itching", "Pain", "Swelling", "Discomfort"],
        "medications": ["Hydrocortisone", "Witch Hazel", "Lidocaine", "Stool Softeners", "Fiber Supplements"],
        "specialty": "Gastroenterology",
    },
    "Anal Fissure": {
        "icd10": "K60.2",
        "symptoms": ["Pain During Bowel Movements", "Bleeding", "Itching", "Spasms", "Constipation"],
        "medications": ["Nitroglycerin Ointment", "Diltiazem", "Botulinum Toxin", "Stool Softeners", "Pain Relievers"],
        "specialty": "Gastroenterology",
    },
    "Fecal Incontinence": {
        "icd10": "R15.9",
        "symptoms": ["Involuntary Bowel Movements", "Urgency", "Leakage", "Diarrhea", "Constipation"],
        "medications": ["Loperamide", "Bismuth Subsalicylate", "Fiber Supplements", "Antidiarrheals", "Cholestyramine"],
        "specialty": "Gastroenterology",
    },
    "Acute Kidney Injury": {
        "icd10": "N17.9",
        "symptoms": ["Decreased Urine Output", "Swelling", "Fatigue", "Nausea", "Confusion"],
        "medications": ["Diuretics", "IV Fluids", "Dialysis", "Electrolyte Management", "Vasopressors"],
        "specialty": "Nephrology",
    },
    "Nephrotic Syndrome": {
        "icd10": "N04.9",
        "symptoms": ["Edema", "Proteinuria", "Hypoalbuminemia", "Hyperlipidemia", "Fatigue"],
        "medications": ["ACE Inhibitors", "Diuretics", "Statins", "Corticosteroids", "Immunosuppressants"],
        "specialty": "Nephrology",
    },
    "Polycystic Kidney Disease": {
        "icd10": "Q61.3",
        "symptoms": ["Abdominal Pain", "Hypertension", "Hematuria", "Back Pain", "Frequent Infections"],
        "medications": ["ACE Inhibitors", "Diuretics", "Pain Relievers", "Antibiotics", "Tolvaptan"],
        "specialty": "Nephrology",
    },
    "Kidney Stones": {
        "icd10": "N20.0",
        "symptoms": ["Severe Pain", "Hematuria", "Nausea", "Vomiting", "Frequent Urination"],
        "medications": ["Pain Relievers", "Alpha Blockers", "Allopurinol", "Potassium Citrate", "Thiazides"],
        "specialty": "Urology",
    },
    "Interstitial Cystitis": {
        "icd10": "N30.10",
        "symptoms": ["Bladder Pain", "Urgency", "Frequency", "Pelvic Pain", "Nocturia"],
        "medications": ["Pentosan Polysulfate", "Amitriptyline", "Hydroxyzine", "Antihistamines", "Bladder Instillations"],
        "specialty": "Urology",
    },
    "Overactive Bladder": {
        "icd10": "N32.81",
        "symptoms": ["Urgency", "Frequency", "Nocturia", "Incontinence", "Bladder Spasms"],
        "medications": ["Oxybutynin", "Tolterodine", "Mirabegron", "Solifenacin", "Darifenacin"],
        "specialty": "Urology",
    },
    "Stress Incontinence": {
        "icd10": "N39.3",
        "symptoms": ["Urine Leakage with Coughing", "Sneezing", "Exercise", "Lifting", "Laughing"],
        "medications": ["Duloxetine", "Estrogen Cream", "No Medications", "Pelvic Floor Exercises", "Surgery"],
        "specialty": "Urology",
    },
    "Urge Incontinence": {
        "icd10": "N39.41",
        "symptoms": ["Sudden Urge to Urinate", "Involuntary Leakage", "Frequency", "Nocturia", "Bladder Spasms"],
        "medications": ["Oxybutynin", "Tolterodine", "Mirabegron", "Solifenacin", "Botulinum Toxin"],
        "specialty": "Urology",
    },
    "Pyelonephritis": {
        "icd10": "N10",
        "symptoms": ["Fever", "Flank Pain", "Nausea", "Vomiting", "Frequent Urination"],
        "medications": ["Ciprofloxacin", "Ceftriaxone", "Amoxicillin", "Trimethoprim", "Nitrofurantoin"],
        "specialty": "Nephrology",
    },
    "Glomerulonephritis": {
        "icd10": "N05.9",
        "symptoms": ["Hematuria", "Proteinuria", "Edema", "Hypertension", "Fatigue"],
        "medications": ["Corticosteroids", "Immunosuppressants", "ACE Inhibitors", "Diuretics", "Plasmapheresis"],
        "specialty": "Nephrology",
    },
    "Acute Sinusitis": {
        "icd10": "J01.90",
        "symptoms": ["Facial Pain", "Nasal Congestion", "Headache", "Fever", "Cough"],
        "medications": ["Amoxicillin", "Augmentin", "Decongestants", "Nasal Steroids", "Pain Relievers"],
        "specialty": "Otolaryngology",
    },
    "Chronic Sinusitis": {
        "icd10": "J32.9",
        "symptoms": ["Nasal Congestion", "Facial Pressure", "Postnasal Drip", "Headache", "Fatigue"],
        "medications": ["Nasal Steroids", "Antibiotics", "Saline Irrigation", "Decongestants", "Surgery"],
        "specialty": "Otolaryngology",
    },
    "Allergic Rhinitis": {
        "icd10": "J30.9",
        "symptoms": ["Sneezing", "Runny Nose", "Itchy Eyes", "Congestion", "Postnasal Drip"],
        "medications": ["Loratadine", "Cetirizine", "Fluticasone", "Montelukast", "Azithromycin"],
        "specialty": "Allergy",
    },
    "Otitis Media": {
        "icd10": "H66.90",
        "symptoms": ["Ear Pain", "Fever", "Hearing Loss", "Fluid Drainage", "Irritability"],
        "medications": ["Amoxicillin", "Azithromycin", "Ibuprofen", "Acetaminophen", "Decongestants"],
        "specialty": "Otolaryngology",
    },
    "Otitis Externa": {
        "icd10": "H60.90",
        "symptoms": ["Ear Pain", "Itching", "Redness", "Swelling", "Discharge"],
        "medications": ["Ciprofloxacin", "Hydrocortisone", "Neomycin", "Acetic Acid", "Pain Relievers"],
        "specialty": "Otolaryngology",
    },
    "Pharyngitis": {
        "icd10": "J02.9",
        "symptoms": ["Sore Throat", "Fever", "Swollen Lymph Nodes", "Headache", "Cough"],
        "medications": ["Penicillin", "Amoxicillin", "Azithromycin", "Ibuprofen", "Acetaminophen"],
        "specialty": "Otolaryngology",
    },
    "Tonsillitis": {
        "icd10": "J03.90",
        "symptoms": ["Sore Throat", "Fever", "Swollen Tonsils", "Difficulty Swallowing", "Headache"],
        "medications": ["Penicillin", "Amoxicillin", "Azithromycin", "Ibuprofen", "Acetaminophen"],
        "specialty": "Otolaryngology",
    },
    "Laryngitis": {
        "icd10": "J04.0",
        "symptoms": ["Hoarseness", "Sore Throat", "Cough", "Difficulty Speaking", "Fever"],
        "medications": ["Ibuprofen", "Acetaminophen", "Steam Inhalation", "Voice Rest", "Antibiotics"],
        "specialty": "Otolaryngology",
    },
    "Croup": {
        "icd10": "J05.0",
        "symptoms": ["Barking Cough", "Stridor", "Hoarseness", "Fever", "Respiratory Distress"],
        "medications": ["Dexamethasone", "Epinephrine", "Humidified Air", "Ibuprofen", "Acetaminophen"],
        "specialty": "Pediatrics",
    },
    "Bronchiolitis": {
        "icd10": "J21.9",
        "symptoms": ["Cough", "Wheezing", "Shortness of Breath", "Fever", "Runny Nose"],
        "medications": ["Supportive Care", "Oxygen", "Hydration", "Albuterol", "Corticosteroids"],
        "specialty": "Pediatrics",
    },
    "Emphysema": {
        "icd10": "J43.9",
        "symptoms": ["Shortness of Breath", "Chronic Cough", "Wheezing", "Fatigue", "Weight Loss"],
        "medications": ["Bronchodilators", "Inhaled Steroids", "Oxygen Therapy", "Antibiotics", "Pulmonary Rehab"],
        "specialty": "Pulmonology",
    },
    "Cystic Fibrosis": {
        "icd10": "E84.9",
        "symptoms": ["Persistent Cough", "Wheezing", "Recurrent Infections", "Poor Growth", "Salty Skin"],
        "medications": ["Ivacaftor", "Lumacaftor", "Dornase Alfa", "Pancreatic Enzymes", "Antibiotics"],
        "specialty": "Pulmonology",
    },
    "Interstitial Lung Disease": {
        "icd10": "J84.9",
        "symptoms": ["Shortness of Breath", "Dry Cough", "Fatigue", "Weight Loss", "Chest Discomfort"],
        "medications": ["Prednisone", "Azathioprine", "Nintedanib", "Pirfenidone", "Oxygen Therapy"],
        "specialty": "Pulmonology",
    },
    "Sarcoidosis": {
        "icd10": "D86.9",
        "symptoms": ["Fatigue", "Cough", "Shortness of Breath", "Skin Rash", "Joint Pain"],
        "medications": ["Prednisone", "Methotrexate", "Hydroxychloroquine", "Infliximab", "Azathioprine"],
        "specialty": "Pulmonology",
    },
    "Pleural Effusion": {
        "icd10": "J90",
        "symptoms": ["Shortness of Breath", "Chest Pain", "Cough", "Fever", "Weight Loss"],
        "medications": ["Diuretics", "Antibiotics", "Corticosteroids", "Chemotherapy", "Thoracentesis"],
        "specialty": "Pulmonology",
    },
    "Pneumothorax": {
        "icd10": "J93.9",
        "symptoms": ["Chest Pain", "Shortness of Breath", "Rapid Heart Rate", "Cyanosis", "Decreased Breath Sounds"],
        "medications": ["Oxygen", "Pain Relievers", "Chest Tube", "Surgery", "Pleurodesis"],
        "specialty": "Pulmonology",
    },
    "Pulmonary Hypertension": {
        "icd10": "I27.20",
        "symptoms": ["Shortness of Breath", "Fatigue", "Chest Pain", "Dizziness", "Swelling"],
        "medications": ["Sildenafil", "Bosentan", "Epoprostenol", "Treprostinil", "Riociguat"],
        "specialty": "Pulmonology",
    },
    "Type 1 Diabetes": {
        "icd10": "E10.9",
        "symptoms": ["Increased Thirst", "Frequent Urination", "Extreme Hunger", "Unexplained Weight Loss", "Fatigue"],
        "medications": ["Insulin", "Pramlintide", "Metformin", "Empagliflozin", "Liraglutide"],
        "specialty": "Endocrinology",
    },
    "Chronic Liver Disease": {
        "icd10": "K76.9",
        "symptoms": ["Fatigue", "Jaundice", "Abdominal Pain", "Swelling in Legs", "Itching"],
        "medications": ["Diuretics", "Beta Blockers", "Ursodiol", "Antivirals", "Immunosuppressants"],
        "specialty": "Gastroenterology",
    },
    "Hypertensive Heart Disease": {
        "icd10": "I11.9",
        "symptoms": ["Shortness of Breath", "Fatigue", "Chest Pain", "Palpitations", "Dizziness"],
        "medications": ["Lisinopril", "Metoprolol", "Hydrochlorothiazide", "Amlodipine", "Losartan"],
        "specialty": "Cardiology",
    },
    "Post-Traumatic Stress Disorder": {
        "icd10": "F43.1",
        "symptoms": ["Flashbacks", "Nightmares", "Severe Anxiety", "Avoidance Behaviors", "Hypervigilance"],
        "medications": ["Sertraline", "Paroxetine", "Venlafaxine", "Prazosin", "Clonidine"],
        "specialty": "Psychiatry",
    },
    "Substance Use Disorder": {
        "icd10": "F19.9",
        "symptoms": ["Cravings", "Loss of Control", "Tolerance", "Withdrawal Symptoms", "Neglect of Responsibilities"],
        "medications": ["Naltrexone", "Acamprosate", "Disulfiram", "Methadone", "Buprenorphine"],
        "specialty": "Psychiatry",
    },
    "Chronic Pain Syndrome": {
        "icd10": "G89.4",
        "symptoms": ["Persistent Pain", "Fatigue", "Sleep Disturbance", "Depression", "Reduced Mobility"],
        "medications": ["Gabapentin", "Duloxetine", "Tramadol", "Amitriptyline", "Ibuprofen"],
        "specialty": "Pain Medicine",
    },
    "Seizure Disorder": {
        "icd10": "G40.909",
        "symptoms": ["Seizures", "Loss of Consciousness", "Convulsions", "Confusion", "Uncontrolled Movements"],
        "medications": ["Levetiracetam", "Valproic Acid", "Carbamazepine", "Lamotrigine", "Topiramate"],
        "specialty": "Neurology",
    },
}
