"""The committed Chinese equivalent of every English medication and symptom.

This file exists because of a defect class the parity tests could not see. zh_CN once
shipped `地西泮` (diazepam) where the base catalogue has Disulfiram, `可乐定` (clonidine)
where the base has Clonazepam, `铝碳酸镁` (hydrotalcite) where the base has Sucralfate,
and `布林佐胺` (brinzolamide) where the base has Brimonidine. Every one of them is a real
drug, plausible for the condition, and wrong — the worst shape a defect can take in a
package whose whole claim is that a record's parts belong together. Counting symptoms and
medications per ICD-10 code, which is what `TestLocaleParity` does, cannot detect it: the
counts were right.

So the mapping is pinned. `tests/test_locales.py::TestZhTranslationEquivalence` walks the
base catalogue and the zh_CN catalogue together, condition by condition and slot by slot,
and requires the Chinese string in each slot to be exactly the one recorded here for the
English string in the same slot. A substitution, an index shift, or a second spelling of a
drug that already has one all fail, by name.

Keys are the base catalogue's exact English spelling, which is the identity the package
already uses for an undosed medication; `faker_healthcare/clinical_labels.py`'s
`MEDICATION_NAMES` maps a substance ID to that same spelling for the subset with a dose
ladder, and a test asserts the two tables agree, so this one extends that mapping rather
than competing with it.

The values were extracted from the catalogues on 2026-08-16, at the end of a term-by-term
Simplified-Chinese review of `faker_healthcare/zh_CN/disease_correlations.py`: 24
medication names corrected (the four above among them), 24 symptom terms, and four
condition names that named a different disease. Extraction is the last step, not
the guarantee: what makes an entry right is the review, and what this file guarantees is
that changing one is a deliberate, visible act. Correcting a translation means correcting
it here in the same commit.
"""

ZH_MEDICATIONS: dict[str, str] = {
    "ACE Inhibitors": "血管紧张素转换酶抑制剂",
    "Abiraterone": "醋酸阿比特龙",
    "Acamprosate": "阿坎普罗斯",
    "Acetaminophen": "对乙酰氨基酚",
    "Acetazolamide": "乙酰唑胺",
    "Acetic Acid": "醋酸",
    "Acyclovir": "阿昔洛韦",
    "Adalimumab": "阿达木单抗",
    "Aflibercept": "阿柏西普",
    "Albuterol": "沙丁胺醇",
    "Aldosterone Antagonists": "醛固酮拮抗剂",
    "Alendronate": "阿仑膦酸盐",
    "Allopurinol": "别嘌呤醇",
    "Alpha Blockers": "α阻滞剂",
    "Alprazolam": "阿普唑仑",
    "Alprostadil": "前列地尔",
    "Alteplase": "阿替普酶",
    "Amantadine": "金刚烷胺",
    "Amitriptyline": "阿米替林",
    "Amlodipine": "氨氯地平",
    "Amoxicillin": "阿莫西林",
    "Amoxicillin-Clavulanate": "阿莫西林/克拉维酸",
    "Amphetamine": "苯丙胺",
    "Ampicillin": "氨苄青霉素",
    "Anastrozole": "阿那曲唑",
    "Antacids": "抗酸剂",
    "Anti-Glare Lenses": "防眩光镜片",
    "Anti-Nausea": "止恶心药",
    "Antibiotics": "抗生素",
    "Anticoagulants": "抗凝剂",
    "Antidiarrheals": "止泻药",
    "Antifibrinolytics": "抗纤溶药",
    "Antihistamines": "抗组胺药",
    "Antihypertensives": "抗高血压药",
    "Antivirals": "抗病毒药",
    "Apixaban": "阿哌沙班",
    "Aripiprazole": "阿立哌唑",
    "Armodafinil": "阿莫达非尼",
    "Artificial Tears": "人工泪液",
    "Aspirin": "阿司匹林",
    "Atomoxetine": "阿托莫西汀",
    "Atorvastatin": "阿托伐他汀",
    "Axitinib": "阿昔替尼",
    "Azathioprine": "硫唑嘌呤",
    "Azelaic Acid": "壬二酸",
    "Azithromycin": "阿奇霉素",
    "BCG": "卡介苗",
    "Baloxavir": "巴洛沙韦",
    "Belimumab": "贝利木单抗",
    "Benzoyl Peroxide": "过氧化苯甲酰",
    "Beta Blockers": "β阻滞剂",
    "Beta-Blockers": "β受体阻滞剂",
    "Betahistine": "贝他司汀",
    "Bevacizumab": "贝伐珠单抗",
    "Bicalutamide": "比卡鲁胺",
    "Bismuth Subsalicylate": "次水杨酸铋",
    "Bladder Instillations": "膀胱灌注",
    "Blood Transfusions": "输血",
    "Bortezomib": "硼替佐米",
    "Bosentan": "波生坦",
    "Botulinum Toxin": "肉毒毒素",
    "Brimonidine": "溴莫尼定",
    "Broad-Spectrum Antibiotics": "广谱抗生素",
    "Bronchodilators": "支气管扩张剂",
    "Budesonide": "布地奈德",
    "Buprenorphine": "丁丙诺啡",
    "Bupropion": "安非他酮",
    "Buspirone": "丁螺环酮",
    "CPAP Therapy": "CPAP治疗",
    "Cabozantinib": "卡博替尼",
    "Calcium Carbonate": "碳酸钙",
    "Calcium Supplements": "钙补充剂",
    "Capecitabine": "卡培他滨",
    "Capsaicin": "辣椒素",
    "Carbamazepine": "卡马西平",
    "Carbidopa": "卡比多巴",
    "Carboplatin": "卡铂",
    "Carmustine": "卡莫司汀",
    "Cefazolin": "头孢唑林",
    "Ceftriaxone": "头孢曲松",
    "Cefuroxime": "头孢呋辛",
    "Celecoxib": "塞来昔布",
    "Cemiplimab": "塞米普利单抗",
    "Cephalexin": "头孢氨苄",
    "Cetirizine": "西替利嗪",
    "Cetuximab": "西妥昔单抗",
    "Cevimeline": "西维美林",
    "Chemotherapy": "化疗",
    "Chest Tube": "胸管",
    "Cholecalciferol": "胆钙化醇",
    "Cholestyramine": "考来烯胺",
    "Cilostazol": "西洛他唑",
    "Ciprofloxacin": "环丙沙星",
    "Cisplatin": "顺铂",
    "Clarithromycin": "克拉霉素",
    "Clindamycin": "克林霉素",
    "Clomiphene": "克罗米芬",
    "Clonazepam": "氯硝西泮",
    "Clonidine": "可乐定",
    "Clopidogrel": "氯吡格雷",
    "Cochlear Implants": "人工耳蜗",
    "Colchicine": "秋水仙碱",
    "Combined Oral Contraceptives": "复方口服避孕药",
    "Corticosteroid Injection": "皮质类固醇注射",
    "Corticosteroids": "皮质类固醇",
    "Cyclobenzaprine": "环苯扎林",
    "Cyclophosphamide": "环磷酰胺",
    "Cyclosporine": "环孢素",
    "Cytarabine": "阿糖胞苷",
    "Dacarbazine": "达卡巴嗪",
    "Danazol": "达那唑",
    "Daratumumab": "达雷妥尤单抗",
    "Darifenacin": "达非那辛",
    "Daunorubicin": "柔红霉素",
    "Decongestants": "减充血剂",
    "Delivery": "分娩",
    "Denosumab": "地诺单抗",
    "Desmopressin": "去氨加压素",
    "Dexamethasone": "地塞米松",
    "Dextromethorphan": "右美沙芬",
    "Dialysis": "透析",
    "Dicloxacillin": "双氯西林",
    "Dicyclomine": "双环维林",
    "Diet Control": "饮食控制",
    "Digoxin": "地高辛",
    "Diltiazem": "地尔硫卓",
    "Disulfiram": "双硫仑",
    "Diuretics": "利尿剂",
    "Docetaxel": "多西紫杉醇",
    "Dolutegravir": "度鲁特韦",
    "Donepezil": "多奈哌齐",
    "Dornase Alfa": "多纳酶α",
    "Doxorubicin": "多柔比星",
    "Doxycycline": "多西环素",
    "Duloxetine": "度洛西汀",
    "Dupilumab": "度普利尤单抗",
    "Dutasteride": "度他雄胺",
    "Efavirenz": "依法韦仑",
    "Electrolyte Management": "电解质管理",
    "Eltrombopag": "艾曲波帕",
    "Emicizumab": "艾美赛珠单抗",
    "Empagliflozin": "恩格列净",
    "Emtricitabine": "恩曲他滨",
    "Enoxaparin": "依诺肝素",
    "Enzalutamide": "恩杂鲁胺",
    "Enzyme Supplements": "酶补充剂",
    "Epinephrine": "肾上腺素",
    "Epoprostenol": "依前列醇",
    "Ergocalciferol": "麦角钙化醇",
    "Erlotinib": "厄洛替尼",
    "Erythropoietin": "促红细胞生成素",
    "Escitalopram": "艾司西酞普兰",
    "Esomeprazole": "埃索美拉唑",
    "Estrogen Cream": "雌激素霜",
    "Ethambutol": "乙胺丁醇",
    "Exercise": "运动",
    "Eyeglasses": "眼镜",
    "Ezetimibe": "依折麦布",
    "FOLFIRINOX": "FOLFIRINOX",
    "Factor IX": "因子IX",
    "Factor VIII": "因子VIII",
    "Famciclovir": "泛昔洛韦",
    "Famotidine": "法莫替丁",
    "Febuxostat": "非布司他",
    "Fenofibrate": "非诺贝特",
    "Ferrous Gluconate": "葡萄糖酸亚铁",
    "Ferrous Sulfate": "硫酸亚铁",
    "Fiber Supplements": "纤维补充剂",
    "Finasteride": "非那雄胺",
    "Fingolimod": "芬戈莫德",
    "Fluorouracil": "氟尿嘧啶",
    "Fluoxetine": "氟西汀",
    "Fluticasone": "氟替卡松",
    "Folic Acid": "叶酸",
    "Furosemide": "呋塞米",
    "G-CSF": "G-CSF",
    "GM-CSF": "GM-CSF",
    "Gabapentin": "加巴喷丁",
    "Galantamine": "加兰他敏",
    "Gemcitabine": "吉西他滨",
    "Gentamicin": "庆大霉素",
    "Glatiramer Acetate": "格拉替雷",
    "Glecaprevir": "格卡瑞韦",
    "Glimepiride": "格列美脲",
    "Gluten-Free Diet": "无麸质饮食",
    "Glyburide": "格列本脲",
    "GnRH Agonists": "GnRH激动剂",
    "Guaifenesin": "愈创木酚甘油醚",
    "Guanfacine": "胍法辛",
    "H2 Blockers": "H2阻滞剂",
    "Haloperidol": "氟哌啶醇",
    "Hearing Aids": "助听器",
    "Heparin": "肝素",
    "Humidified Air": "湿化空气",
    "Hydralazine": "肼屈嗪",
    "Hydration": "水化",
    "Hydrochlorothiazide": "氢氯噻嗪",
    "Hydrocortisone": "氢化可的松",
    "Hydroxychloroquine": "羟氯喹",
    "Hydroxyurea": "羟基脲",
    "Hydroxyzine": "羟嗪",
    "IV Fluids": "静脉输液",
    "IVIG": "IVIG",
    "Ibuprofen": "布洛芬",
    "Imatinib": "伊马替尼",
    "Imiquimod": "咪喹莫特",
    "Immunosuppressants": "免疫抑制剂",
    "Indomethacin": "吲哚美辛",
    "Infliximab": "英夫利昔单抗",
    "Inhaled Steroids": "吸入类固醇",
    "Insulin": "胰岛素",
    "Insulin Glargine": "甘精胰岛素",
    "Interferon Beta": "干扰素β",
    "Ipilimumab": "伊匹单抗",
    "Iron Infusions": "铁输注",
    "Iron Supplements": "铁补充剂",
    "Isoniazid": "异烟肼",
    "Isotretinoin": "异维A酸",
    "Ivacaftor": "依伐卡托",
    "Ivermectin": "伊维菌素",
    "Labetalol": "拉贝洛尔",
    "Lactulose": "乳果糖",
    "Lamotrigine": "拉莫三嗪",
    "Laser Therapy": "激光疗法",
    "Latanoprost": "拉坦前列素",
    "Ledipasvir": "雷迪帕韦",
    "Lenalidomide": "来那度胺",
    "Lenvatinib": "仑伐替尼",
    "Letrozole": "来曲唑",
    "Leuprolide": "亮丙瑞林",
    "Levetiracetam": "左乙拉西坦",
    "Levodopa": "左旋多巴",
    "Levofloxacin": "左氧氟沙星",
    "Levothyroxine": "左甲状腺素",
    "Lidocaine": "利多卡因",
    "Linaclotide": "利那洛肽",
    "Liothyronine": "碘塞罗宁",
    "Liraglutide": "利拉鲁肽",
    "Lisinopril": "赖诺普利",
    "Lithium": "锂盐",
    "Lomustine": "洛莫司汀",
    "Loperamide": "洛哌丁胺",
    "Loratadine": "氯雷他定",
    "Lorazepam": "劳拉西泮",
    "Losartan": "氯沙坦",
    "Lubiprostone": "鲁比前列酮",
    "Lumacaftor": "鲁玛卡托",
    "Magnesium Sulfate": "硫酸镁",
    "Magnifiers": "放大镜",
    "Meclizine": "美克洛嗪",
    "Melatonin": "褪黑素",
    "Melphalan": "美法仑",
    "Memantine": "美金刚",
    "Mesalamine": "美沙拉嗪",
    "Metformin": "二甲双胍",
    "Methadone": "美沙酮",
    "Methimazole": "甲巯咪唑",
    "Methotrexate": "甲氨蝶呤",
    "Methylphenidate": "哌甲酯",
    "Metoprolol": "美托洛尔",
    "Metronidazole": "甲硝唑",
    "Milnacipran": "米那普仑",
    "Mirabegron": "米拉贝隆",
    "Mitomycin": "丝裂霉素",
    "Modafinil": "莫达非尼",
    "Moisturizers": "保湿剂",
    "Molnupiravir": "莫努匹韦",
    "Montelukast": "孟鲁司特",
    "Mycophenolate": "霉酚酸酯",
    "Naltrexone": "纳曲酮",
    "Naproxen": "萘普生",
    "Nasal Steroids": "鼻腔类固醇",
    "Natalizumab": "那他珠单抗",
    "Neomycin": "新霉素",
    "Nifedipine": "硝苯地平",
    "Nintedanib": "尼达尼布",
    "Nitrofurantoin": "呋喃妥因",
    "Nitroglycerin": "硝酸甘油",
    "Nitroglycerin Ointment": "硝酸甘油软膏",
    "Nivolumab": "纳武利尤单抗",
    "No Medications": "无药物",
    "Ocrelizumab": "奥瑞珠单抗",
    "Olanzapine": "奥氮平",
    "Olaparib": "奥拉帕利",
    "Omeprazole": "奥美拉唑",
    "Oral B12 Supplements": "口服B12补充剂",
    "Orlistat": "奥利司他",
    "Oseltamivir": "奥司他韦",
    "Oxaliplatin": "奥沙利铂",
    "Oxybutynin": "奥昔布宁",
    "Oxygen": "氧气",
    "Oxygen Therapy": "氧疗",
    "Paclitaxel": "紫杉醇",
    "Pain Relievers": "止痛药",
    "Pancreatic Enzymes": "胰酶",
    "Pantoprazole": "泮托拉唑",
    "Paroxetine": "帕罗西汀",
    "Paxlovid": "帕克洛维",
    "Pazopanib": "帕唑帕尼",
    "Pelvic Floor Exercises": "盆底运动",
    "Pembrolizumab": "派姆单抗",
    "Penicillin": "青霉素",
    "Pentosan Polysulfate": "戊聚糖多硫酸钠",
    "Pentoxifylline": "己酮可可碱",
    "Phentermine": "芬特明",
    "Phenytoin": "苯妥英",
    "Photodynamic Therapy": "光动力疗法",
    "Pibrentasvir": "匹布他韦",
    "Pilocarpine": "匹罗卡品",
    "Pimecrolimus": "匹美莫司",
    "Pioglitazone": "吡格列酮",
    "Pirfenidone": "吡非尼酮",
    "Pitolisant": "匹托利桑",
    "Plasmapheresis": "血浆置换",
    "Pleurodesis": "胸膜固定术",
    "Potassium Citrate": "柠檬酸钾",
    "Pramipexole": "普拉克索",
    "Pramlintide": "普兰林肽",
    "Prazosin": "哌唑嗪",
    "Prednisone": "泼尼松",
    "Pregabalin": "普瑞巴林",
    "Probenecid": "丙磺舒",
    "Probiotics": "益生菌",
    "Progesterone": "黄体酮",
    "Progestins": "孕激素",
    "Prokinetics": "促动力药",
    "Propranolol": "普萘洛尔",
    "Propylthiouracil": "丙硫氧嘧啶",
    "Prostaglandin E1": "前列腺素E1",
    "Proton Pump Inhibitors": "质子泵抑制剂",
    "Pulmonary Rehab": "肺康复",
    "Pyrazinamide": "吡嗪酰胺",
    "Quetiapine": "喹硫平",
    "Radiation": "放疗",
    "Radioactive Iodine": "放射性碘",
    "Ranibizumab": "雷珠单抗",
    "Ranitidine": "雷尼替丁",
    "Remdesivir": "瑞德西韦",
    "Resmetirom": "瑞美替罗",
    "Retinoids": "维甲酸类",
    "Ribavirin": "利巴韦林",
    "Rifampin": "利福平",
    "Rifaximin": "利福昔明",
    "Riociguat": "利奥西呱",
    "Risedronate": "利塞膦酸盐",
    "Risperidone": "利培酮",
    "Ritonavir": "利托那韦",
    "Rituximab": "利妥昔单抗",
    "Rivaroxaban": "利伐沙班",
    "Rivastigmine": "利斯的明",
    "Romiplostim": "罗米司亭",
    "Ropinirole": "罗匹尼罗",
    "Rosuvastatin": "瑞舒伐他汀",
    "Salicylic Acid": "水杨酸",
    "Saline Irrigation": "生理盐水冲洗",
    "Selegiline": "司来吉兰",
    "Semaglutide": "司美格鲁肽",
    "Sertraline": "舍曲林",
    "Sevelamer": "司维拉姆",
    "Sildenafil": "西地那非",
    "Simvastatin": "辛伐他汀",
    "Sitagliptin": "西格列汀",
    "Sodium Oxybate": "羟丁酸钠",
    "Sofosbuvir": "索非布韦",
    "Solifenacin": "索利那新",
    "Sonidegib": "索尼德吉",
    "Sorafenib": "索拉非尼",
    "Spironolactone": "螺内酯",
    "Splenectomy": "脾切除术",
    "Statins": "他汀类",
    "Steam Inhalation": "蒸汽吸入",
    "Steroids": "类固醇",
    "Stool Softeners": "粪便软化剂",
    "Streptomycin": "链霉素",
    "Sucralfate": "硫糖铝",
    "Sulfasalazine": "柳氮磺胺吡啶",
    "Sumatriptan": "舒马普坦",
    "Sun Exposure": "日光暴露",
    "Sunitinib": "舒尼替尼",
    "Supportive Care": "支持性护理",
    "Surgery": "手术",
    "Tacrolimus": "他克莫司",
    "Tadalafil": "他达拉非",
    "Tamoxifen": "他莫昔芬",
    "Tamsulosin": "坦索罗辛",
    "Temozolomide": "替莫唑胺",
    "Tenofovir": "替诺福韦",
    "Terazosin": "特拉唑嗪",
    "Testosterone": "睾酮",
    "Theophylline": "茶碱",
    "Thiazides": "噻嗪类",
    "Thoracentesis": "胸腔穿刺",
    "Thrombolytics": "溶栓药",
    "Thyroid": "甲状腺片",
    "Timolol": "噻吗洛尔",
    "Tiotropium": "噻托溴铵",
    "Tolterodine": "托特罗定",
    "Tolvaptan": "托伐普坦",
    "Topical Corticosteroids": "局部皮质类固醇",
    "Topiramate": "托吡酯",
    "Tramadol": "曲马多",
    "Trametinib": "曲美替尼",
    "Tranexamic Acid": "氨甲环酸",
    "Trastuzumab": "曲妥珠单抗",
    "Treprostinil": "曲前列尼尔",
    "Trimethoprim": "甲氧苄啶",
    "Ulipristal Acetate": "醋酸乌利司他",
    "Ursodiol": "熊去氧胆酸",
    "Valacyclovir": "伐昔洛韦",
    "Valproate": "丙戊酸盐",
    "Valproic Acid": "丙戊酸",
    "Vancomycin": "万古霉素",
    "Vardenafil": "伐地那非",
    "Vasodilators": "血管扩张剂",
    "Vasopressors": "升压药",
    "Vedolizumab": "维多珠单抗",
    "Venlafaxine": "文拉法辛",
    "Verteporfin": "维替泊芬",
    "Vincristine": "长春新碱",
    "Vismodegib": "维莫德吉",
    "Vitamin B12": "维生素B12",
    "Vitamin B12 Injections": "维生素B12注射",
    "Vitamin C": "维生素C",
    "Vitamin D": "维生素D",
    "Vitamin D Analogues": "维生素D类似物",
    "Vitamin D Supplements": "维生素D补充剂",
    "Vitamin E": "维生素E",
    "Vitamin Supplements": "维生素补充剂",
    "Vitrectomy": "玻璃体切除术",
    "Voice Rest": "声音休息",
    "Voxelotor": "Voxelotor",
    "Warfarin": "华法林",
    "Witch Hazel": "金缕梅",
    "Wrist Splint": "腕部夹板",
    "Zanamivir": "扎那米韦",
}

ZH_SYMPTOMS: dict[str, str] = {
    "Abdominal Bloating": "腹胀",
    "Abdominal Pain": "腹痛",
    "Abdominal Swelling": "腹部肿胀",
    "Abnormal Vaginal Bleeding": "异常阴道出血",
    "Acne": "痤疮",
    "Anemia": "贫血",
    "Anxiety": "焦虑",
    "Asymmetrical Shape": "不对称形状",
    "Avoidance Behaviors": "回避行为",
    "Back Pain": "背痛",
    "Balance Issues": "平衡问题",
    "Barking Cough": "犬吠样咳嗽",
    "Blackheads": "黑头",
    "Bladder Pain": "膀胱痛",
    "Bladder Spasms": "膀胱痉挛",
    "Bleeding": "出血",
    "Bleeding Gums": "牙龈出血",
    "Bloating": "胀气",
    "Blood in Stool": "便血",
    "Blood in Urine": "尿血",
    "Bloody Diarrhea": "血性腹泻",
    "Blurred Vision": "视力模糊",
    "Bone Loss": "骨丢失",
    "Bone Pain": "骨痛",
    "Bradykinesia": "运动迟缓",
    "Breast Lump": "乳房肿块",
    "Bruising": "瘀伤",
    "Burning Sensation": "烧灼感",
    "Cataplexy": "猝倒",
    "Central Vision Loss": "中心视力丧失",
    "Change in Bowel Habits": "排便习惯改变",
    "Changing Mole": "痣变化",
    "Chest Discomfort": "胸部不适",
    "Chest Pain": "胸痛",
    "Chronic Cough": "慢性咳嗽",
    "Cloudy Urine": "尿混浊",
    "Cognitive Changes": "认知变化",
    "Cognitive Difficulties": "认知困难",
    "Cognitive Impairment": "认知损害",
    "Cold Extremities": "四肢冰冷",
    "Cold Hands": "手冷",
    "Color Changes": "颜色变化",
    "Color Fading": "颜色褪色",
    "Color Variation": "颜色变化",
    "Communication Difficulties": "沟通困难",
    "Confusion": "意识模糊",
    "Congestion": "鼻塞",
    "Constipation": "便秘",
    "Convulsions": "抽搐",
    "Cough": "咳嗽",
    "Coughing Blood": "咳血",
    "Cramping": "痉挛",
    "Cravings": "渴求",
    "Crusted Surface": "结痂表面",
    "Cyanosis": "发绀",
    "Cysts": "囊肿",
    "Dark Areas": "暗区",
    "Dark Spots": "暗点",
    "Daytime Sleepiness": "白天嗜睡",
    "Decreased Breath Sounds": "呼吸音减弱",
    "Decreased Urine Output": "尿量减少",
    "Delusions": "妄想",
    "Depression": "抑郁",
    "Diameter Increase": "直径增加",
    "Diarrhea": "腹泻",
    "Difficulty Breathing": "呼吸困难",
    "Difficulty Hearing": "听力困难",
    "Difficulty Speaking": "言语困难",
    "Difficulty Swallowing": "吞咽困难",
    "Discharge": "耳道分泌物",
    "Discomfort": "不适",
    "Disorganization": "缺乏条理",
    "Disorganized Thinking": "思维紊乱",
    "Distorted Vision": "视力扭曲",
    "Dizziness": "头晕",
    "Double Vision": "复视",
    "Dry Cough": "干咳",
    "Dry Eyes": "眼干",
    "Dry Mouth": "口干",
    "Dry Skin": "皮肤干燥",
    "Dysmenorrhea": "痛经",
    "Ear Fullness": "耳胀",
    "Ear Pain": "耳痛",
    "Easy Bruising": "易瘀伤",
    "Edema": "水肿",
    "Excess Hair Growth": "多毛",
    "Excessive Daytime Sleepiness": "过度白天嗜睡",
    "Extreme Hunger": "极度饥饿",
    "Eye Irritation": "眼刺激",
    "Eye Pain": "眼痛",
    "Facial Pain": "面痛",
    "Facial Pressure": "面部压迫感",
    "Facial Redness": "面部发红",
    "Fading Colors": "颜色褪色",
    "Fatigue": "疲劳",
    "Fever": "发热",
    "Flank Pain": "腰痛",
    "Flashbacks": "闪回",
    "Floaters": "飞蚊症",
    "Fluid Drainage": "耳道流液",
    "Forgetfulness": "健忘",
    "Fragmented Sleep": "睡眠碎片化",
    "Frequency": "尿频",
    "Frequent Infections": "频繁感染",
    "Frequent Urination": "尿频",
    "Gas": "排气增多",
    "Gastrointestinal Issues": "胃肠问题",
    "Glare Sensitivity": "眩光敏感",
    "Growth with Central Depression": "中央凹陷的肿物",
    "Hair Loss": "脱发",
    "Hallucinations": "幻觉",
    "Halos Around Lights": "光晕",
    "Headache": "头痛",
    "Headaches": "头痛",
    "Hearing Loss": "听力丧失",
    "Heart Murmurs": "心脏杂音",
    "Heartburn": "烧心",
    "Heat Intolerance": "怕热",
    "Heavy Menstrual Bleeding": "月经过多",
    "Heavy Periods": "月经过多",
    "Hemarthrosis": "关节积血",
    "Hematuria": "血尿",
    "Hemoptysis": "咯血",
    "High Blood Pressure": "高血压",
    "Hoarseness": "声音嘶哑",
    "Hyperactivity": "多动",
    "Hyperlipidemia": "高脂血症",
    "Hypertension": "高血压",
    "Hypervigilance": "过度警觉",
    "Hypoalbuminemia": "低白蛋白血症",
    "Hypotension": "低血压",
    "Impulsivity": "冲动",
    "Inability to Maintain Erection": "无法维持勃起",
    "Inattention": "注意缺陷",
    "Incomplete Emptying": "排空不完全",
    "Incontinence": "失禁",
    "Increased Appetite": "食欲增加",
    "Increased Thirst": "口渴增加",
    "Infertility": "不孕",
    "Insomnia": "失眠",
    "Involuntary Bowel Movements": "不由自主排便",
    "Involuntary Leakage": "不由自主漏尿",
    "Irregular Borders": "不规则边界",
    "Irregular Heartbeat": "心律不齐",
    "Irregular Periods": "月经不规则",
    "Irritability": "易怒",
    "Itching": "瘙痒",
    "Itchy Eyes": "眼痒",
    "Jaundice": "黄疸",
    "Joint Pain": "关节痛",
    "Kidney Problems": "肾问题",
    "Leakage": "渗漏",
    "Leg Pain": "腿痛",
    "Light Sensitivity": "光敏感",
    "Lightheadedness": "头昏眼花",
    "Limited Mobility": "活动受限",
    "Loss of Appetite": "食欲不振",
    "Loss of Consciousness": "意识丧失",
    "Loss of Control": "失控",
    "Loss of Smell": "嗅觉丧失",
    "Loss of Taste": "味觉丧失",
    "Low Blood Pressure": "低血压",
    "Mania": "躁狂",
    "Memory Loss": "记忆丧失",
    "Mood Swings": "情绪波动",
    "Morning Headaches": "晨间头痛",
    "Mouth Ulcers": "口腔溃疡",
    "Muffled Sounds": "声音模糊",
    "Muscle Aches": "肌肉痛",
    "Muscle Weakness": "肌肉虚弱",
    "Nasal Congestion": "鼻塞",
    "Nausea": "恶心",
    "Neck Lump": "颈部肿块",
    "Neck Pain": "颈痛",
    "Negative Symptoms": "阴性症状",
    "Neglect of Responsibilities": "忽视责任",
    "Night Sweats": "盗汗",
    "Nightmares": "噩梦",
    "Nipple Discharge": "乳头溢液",
    "Nocturia": "夜尿",
    "Nosebleeds": "鼻出血",
    "Numbness": "麻木",
    "Open Sore": "开放性溃疡",
    "Pain": "疼痛",
    "Pain Crises": "疼痛发作",
    "Pain During Bowel Movements": "排便痛",
    "Painful Intercourse": "性交痛",
    "Painful Urination": "尿痛",
    "Pale Skin": "皮肤苍白",
    "Palpitations": "心悸",
    "Pearly Bump": "珍珠样丘疹",
    "Pelvic Pain": "盆腔痛",
    "Persistent Cough": "持续咳嗽",
    "Persistent Pain": "持续疼痛",
    "Petechiae": "瘀点",
    "Photosensitivity": "光敏感",
    "Pimples": "丘疹",
    "Poor Growth": "生长不良",
    "Poor Night Vision": "夜视不良",
    "Postnasal Drip": "鼻后滴流",
    "Postural Instability": "姿势不稳",
    "Premature Ejaculation": "早泄",
    "Prolonged Bleeding": "出血时间延长",
    "Proteinuria": "蛋白尿",
    "Pulsatile Mass": "搏动性肿块",
    "Rapid Heart Rate": "心率加快",
    "Rapid Heartbeat": "心跳加速",
    "Rapid Pulse": "脉搏加快",
    "Rash": "皮疹",
    "Raynaud's Phenomenon": "雷诺现象",
    "Rectal Bleeding": "直肠出血",
    "Recurrent Infections": "反复感染",
    "Red Eyes": "红眼",
    "Red Patch": "红斑",
    "Red Patches": "红斑",
    "Redness": "发红",
    "Reduced Libido": "性欲降低",
    "Reduced Mobility": "活动减少",
    "Regurgitation": "反流",
    "Relief with Movement": "运动缓解",
    "Repetitive Behaviors": "重复行为",
    "Respiratory Distress": "呼吸窘迫",
    "Restricted Interests": "兴趣受限",
    "Rigidity": "僵硬",
    "Rough Red Patch": "粗糙红斑",
    "Runny Nose": "流鼻涕",
    "Salty Skin": "皮肤有咸味",
    "Scaling": "鳞屑",
    "Scar-Like Area": "瘢痕样区域",
    "Scarring": "疤痕",
    "Seizures": "癫痫发作",
    "Sensory Sensitivities": "感觉敏感",
    "Severe Anxiety": "严重焦虑",
    "Severe Pain": "剧痛",
    "Shortness of Breath": "呼吸短促",
    "Skin Rash": "皮疹",
    "Skin Thickening": "皮肤增厚",
    "Sleep Disturbance": "睡眠障碍",
    "Sleep Disturbances": "睡眠障碍",
    "Sleep Paralysis": "睡眠麻痹",
    "Sneezing": "打喷嚏",
    "Snoring": "打鼾",
    "Social Impairment": "社会损害",
    "Sore That Doesn't Heal": "经久不愈的溃疡",
    "Sore Throat": "咽痛",
    "Spasms": "痉挛",
    "Speech Changes": "言语变化",
    "Staring Spells": "凝视发作",
    "Stress": "压力",
    "Stridor": "喘鸣",
    "Sudden Urge to Urinate": "突然尿意",
    "Sweating": "出汗",
    "Swelling": "肿胀",
    "Swelling in Legs": "腿肿",
    "Swollen Lymph Nodes": "淋巴结肿大",
    "Swollen Salivary Glands": "唾液腺肿胀",
    "Swollen Tonsils": "扁桃体肿大",
    "Syncope": "晕厥",
    "Thickened Skin": "皮肤增厚",
    "Tingling": "刺痛",
    "Tinnitus": "耳鸣",
    "Tolerance": "耐受",
    "Tophi": "痛风石",
    "Tremor": "震颤",
    "Uncomfortable Sensations": "不适感",
    "Uncontrolled Movements": "不自主运动",
    "Unexplained Weight Loss": "不明体重减轻",
    "Urge to Move Legs": "活动双腿的冲动",
    "Urgency": "急迫感",
    "Urine Leakage During Exercise": "运动时漏尿",
    "Urine Leakage When Lifting": "提重物时漏尿",
    "Urine Leakage with Coughing": "咳嗽时漏尿",
    "Urine Leakage with Laughing": "大笑时漏尿",
    "Urine Leakage with Sneezing": "打喷嚏时漏尿",
    "Vertigo": "眩晕",
    "Visible Blood Vessels": "可见血管",
    "Vision Changes": "视力变化",
    "Vision Loss": "视力丧失",
    "Vision Problems": "视力问题",
    "Vomiting": "呕吐",
    "Warmth": "皮温升高",
    "Weak Stream": "尿流弱",
    "Weakness": "虚弱",
    "Weight Gain": "体重增加",
    "Weight Loss": "体重减轻",
    "Wheezing": "喘息",
    "Whiteheads": "白头",
    "Widespread Pain": "广泛疼痛",
    "Withdrawal Symptoms": "戒断症状",
    "Worsening at Night": "夜间加重",
}
