from .. import HealthcareProvider as BaseHealthcareProvider


class Provider(BaseHealthcareProvider):
    """Faker provider for generating healthcare/medical fake data."""

    diseases= (
        "Diabetes Tipo 2",
        "Hipertensão Essencial",
        "Hiperlipidemia",
        "Doença Arterial Coronariana",
        "Doença Pulmonar Obstrutiva Crônica",
        "Asma",
        "Doença Renal Crônica",
        "Osteoartrite",
        "Artrite Reumatoide",
        "Depressão",
        "Transtorno de Ansiedade",
        "Doença do Refluxo Gastroesofágico",
        "Obesidade",
        "Hipotireoidismo",
        "Fibrilação Atrial",
        "Insuficiência Cardíaca Congestiva",
        "Pneumonia",
        "Infecção do Trato Urinário",
        "Bronquite Aguda",
        "Anemia",
        "Enxaqueca",
        "Acidente Vascular Cerebral",
        "Doença de Alzheimer",
        "Câncer de Mama",
        "Câncer de Próstata",
        "Câncer de Pulmão",
        "COVID-19",
        "Influenza",
        "Osteoporose",
        "Doença Arterial Periférica",
        "Angina Pectoris",
        "Hipertireoidismo",
        "Gota",
        "Esclerose Múltipla",
        "Doença de Parkinson",
        "Epilepsia",
        "Transtorno Bipolar",
        "Esquizofrenia",
        "Transtorno de Déficit de Atenção e Hiperatividade",
        "Transtorno do Espectro Autista",
        "Doença de Crohn",
        "Colite Ulcerativa",
        "Síndrome do Intestino Irritável",
        "Doença Celíaca",
        "Cirrose",
        "Hepatite C",
        "HIV/AIDS",
        "Tuberculose",
        "Sepse",
        "Trombose Venosa Profunda",
        "Embolia Pulmonar",
        "Aneurisma Aórtico",
        "Doença Valvular Cardíaca",
        "Cardiomiopatia",
        "Endocardite",
        "Pericardite",
        "Infarto do Miocárdio",
        "Doença Cardíaca Congênita",
        "Neuropatia Periférica",
        "Apneia do Sono",
        "Narcolepsia",
        "Síndrome das Pernas Inquietas",
        "Fibromialgia",
        "Lúpus",
        "Esclerodermia",
        "Síndrome de Sjögren",
        "Psoríase",
        "Eczema",
        "Rosácea",
        "Acne Vulgar",
        "Melanoma",
        "Carcinoma Basocelular",
        "Carcinoma Espinocelular",
        "Leucemia",
        "Linfoma",
        "Mieloma",
        "Câncer de Cólon",
        "Câncer Pancreático",
        "Câncer Renal",
        "Câncer de Bexiga",
        "Câncer Ovariano",
        "Câncer Endometrial",
        "Câncer de Tireoide",
        "Tumor Cerebral",
        "Glaucoma",
        "Degeneração Macular",
        "Catarata",
        "Retinopatia Diabética",
        "Perda Auditiva",
        "Doença de Ménière",
        "Hiperplasia Prostática Benigna",
        "Disfunção Erétil",
        "Síndrome do Ovário Policístico",
        "Endometriose",
        "Miomas Uterinos",
        "Pré-eclâmpsia",
        "Diabetes Gestacional",
        "Deficiência de Vitamina D",
        "Anemia por Deficiência de Ferro",
        "Anemia Perniciosa",
        "Doença Falciforme",
        "Hemofilia",
        "Trombocitopenia",
        "Leucopenia",
        "Diverticulite",
        "Apendicite",
        "Colecistite",
        "Pancreatite",
        "Doença Ulcerosa Péptica",
        "Gastrite",
        "Esofagite",
        "Esôfago de Barrett",
        "Hérnia Hiatal",
        "Hemorróidas",
        "Fissura Anal",
        "Incontinência Fecal",
        "Lesão Renal Aguda",
        "Síndrome Nefrótica",
        "Doença Renal Policística",
        "Cálculos Renais",
        "Cistite Intersticial",
        "Bexiga Hiperativa",
        "Incontinência de Esforço",
        "Incontinência de Urgência",
        "Pielonefrite",
        "Glomerulonefrite",
        "Sinusite Aguda",
        "Sinusite Crônica",
        "Rinite Alérgica",
        "Otite Média",
        "Otite Externa",
        "Faringite",
        "Tonsilite",
        "Laringite",
        "Crupe",
        "Bronquiolite",
        "Enfisema",
        "Fibrose Cística",
        "Doença Pulmonar Intersticial",
        "Sarcoidose",
        "Derrame Pleural",
        "Pneumotórax",
        "Hipertensão Pulmonar",
    )

    icd10_codes= (
        "E11.9", "I10", "E78.5", "I25.10", "J44.9",
        "J45.909", "N18.9", "M17.9", "M79.1", "F32.9",
        "F41.9", "K21.9", "E66.9", "E03.9", "I48.91",
        "I50.9", "J18.9", "N39.0", "J20.9", "D64.9",
        "G43.909", "I63.9", "G30.9", "R10.9", "R50.9",
        "R06.00", "R53.81", "Z00.00", "Z79.899", "Z68.1",
        "C50.919", "C61", "C34.90", "U07.1", "J11.1",
        "M81.0", "I73.9", "K70.30", "G20", "E10.9",
        "I20.9", "E05.90", "M10.9", "G35", "G21.9",
        "G40.909", "F31.9", "F20.9", "F90.9", "F84.0",
        "K50.90", "K51.90", "K58.9", "K90.0", "K74.60",
        "B18.2", "B20", "A15.9", "A41.9", "I82.409",
        "I26.99", "I71.9", "I35.9", "I42.9", "I33.9",
        "I30.9", "I21.9", "Q24.9", "G62.9", "G47.33",
        "G47.419", "G25.81", "M79.7", "M32.9", "M34.9",
        "M35.00", "L40.9", "L20.9", "L71.9", "L70.0",
        "C43.9", "C44.91", "C44.92", "C95.90", "C85.90",
        "C90.00", "C18.9", "C25.9", "C64.9", "C67.9",
        "C56.9", "C54.1", "C73", "C71.9", "H40.9",
        "H35.30", "H25.9", "H36", "H90.3", "H81.0",
        "N40.0", "N52.9", "E28.2", "N80.9", "D25.9",
        "O14.9", "O24.919", "E55.9", "D50.9", "D51.0",
        "D57.1", "D66", "D69.6", "D70.9", "K57.90",
        "K35.80", "K81.9", "K85.90", "K27.9", "K29.70",
        "K20.9", "K22.70", "K44.9", "I84.9", "K60.2",
        "R15.9", "N17.9", "N04.9", "Q61.9", "N20.0",
        "N30.10", "N32.81", "N39.3", "N39.41", "N10",
        "N05.9", "J01.90", "J32.9", "J30.9", "H66.90",
        "H60.90", "J02.9", "J03.90", "J04.0", "J05.0",
        "J21.9", "J43.9", "E84.9", "J84.9", "D86.9",
        "J90", "J93.9", "I27.20", "Z00.01", "Z00.121",
        "Z00.129", "Z13.6", "Z13.89", "Z23", "J06.9",
        "R07.9", "M54.5", "M25.50", "M19.90", "R51.9",
        "R53.83", "E78.0", "I11.9", "I25.5", "I63.50",
        "I67.9", "I70.0", "I21.3", "I21.4", "I48.0",
        "I48.2", "I49.9", "I50.1", "I50.20", "I50.30",
        "I50.40", "I61.9", "I63.40", "I64", "I69.30",
        "I80.10", "I80.20", "I80.3", "I82.40", "I82.90",
        "I83.90", "I87.2", "I95.9", "J00", "J02.0",
        "J03.00", "J04.10", "J05.10", "J12.89", "J15.9",
        "J18.0", "J18.1", "J20.0", "J20.8", "J21.0",
        "J40", "J41.0", "J42", "J44.0", "J44.1",
        "J45.20", "J45.30", "J45.40", "J45.50", "J45.901",
        "J47.0", "J47.9", "J60", "J61", "J70.9",
        "J80", "J81.0", "J82", "J84.10", "J84.112",
        "J84.117", "J84.170", "J84.89", "J91.8", "J92.0",
        "J93.0", "J93.11", "J93.12", "J93.81", "J94.0",
        "J94.2", "J94.8", "J95.1", "J95.2", "J96.00",
        "J96.01", "J96.02", "J96.10", "J96.11", "J96.12",
        "J96.20", "J96.21", "J96.22", "J96.90", "J96.91",
        "J96.92", "J98.4", "J98.9", "K02.9", "K03.9",
        "K04.7", "K04.90", "K05.6", "K08.9", "K12.0",
        "K21.0", "K22.0", "K22.10", "K22.2", "K22.6",
        "K25.9", "K26.9", "K28.9", "K29.00", "K29.50",
        "K29.60", "K30", "K31.84", "K31.9", "K35.2",
        "K35.3", "K36", "K38.9", "K40.90", "K42.9",
        "K43.9", "K46.9", "K50.00", "K50.10", "K50.80",
        "K51.00", "K51.20", "K51.30", "K51.50", "K51.80",
        "K52.9", "K55.0", "K56.0", "K56.60", "K57.30",
        "K57.32", "K57.50", "K57.92", "K58.0", "K59.00",
        "K59.01", "K59.02", "K59.09", "K59.1", "K59.2",
        "K59.3", "K59.4", "K60.0", "K60.1", "K60.3",
        "K60.4", "K61.0", "K62.5", "K63.5", "K64.9",
        "K70.0", "K70.10", "K70.9", "K71.9", "K72.00",
        "K72.10", "K72.90", "K73.9", "K74.0", "K74.3",
        "K75.9", "K76.0", "K76.9", "K80.20", "K80.50",
        "K82.9", "K83.0", "K85.00", "K85.10", "K85.20",
        "K85.30", "K85.80", "K86.0", "K86.1", "K86.9",
        "K91.2", "K92.0", "K92.1", "K92.2", "K92.9",
    )

    medical_specialties= (
        "Cardiologia",
        "Dermatologia",
        "Endocrinologia",
        "Gastroenterologia",
        "Hematologia",
        "Infectologia",
        "Nefrologia",
        "Neurologia",
        "Oncologia",
        "Pneumologia",
        "Reumatologia",
        "Alergia e Imunologia",
        "Medicina de Família",
        "Clínica Médica",
        "Pediatria",
        "Psiquiatria",
        "Obstetrícia e Ginecologia",
        "Ortopedia",
        "Urologia",
        "Oftalmologia",
        "Otorrinolaringologia",
        "Anestesiologia",
        "Radiologia",
        "Patologia",
        "Medicina de Emergência",
        "Cirurgia Geral",
        "Cirurgia Plástica",
        "Neurocirurgia",
        "Medicina Física e Reabilitação",
        "Cirurgia Vascular",
        "Cirurgia Torácica",
        "Cirurgia Cardíaca",
        "Cirurgia Colorretal",
        "Cirurgia de Transplante",
        "Cirurgia Pediátrica",
        "Neonatologia",
        "Geriatria",
        "Medicina da Dor",
        "Cuidados Paliativos",
        "Medicina Esportiva",
        "Medicina Ocupacional",
        "Medicina Preventiva",
        "Genética Médica",
        "Medicina Nuclear",
        "Radiologia Intervencionista",
    )

    hospital_departments= (
        "Pronto-Socorro",
        "Unidade de Terapia Intensiva (UTI)",
        "Unidade de Cuidados Cardíacos (UCC)",
        "Sala de Cirurgia",
        "Trabalho de Parto e Nascimento",
        "Pediatria",
        "Ala de Maternidade",
        "Oncologia",
        "Radiologia",
        "Laboratório",
        "Farmácia",
        "Fisioterapia",
        "Terapia Ocupacional",
        "Terapia Respiratória",
        "Cirurgia",
        "Ala de Internação",
        "Clínica Ambulatorial",
        "Ala Psiquiátrica",
        "Unidade de Reabilitação",
        "Sala de Endoscopia",
        "Unidade de Terapia Intensiva Neonatal (UTIN)",
        "Unidade de Queimados",
        "Unidade de Diálise",
        "Laboratório do Sono",
        "Centro de Cuidados com Feridas",
        "Centro de Infusão",
        "Unidade de Cardiologia",
        "Unidade de Neurologia",
        "Unidade de Observação Médica",
        "Unidade de Cuidados Pós-Anestesia (SRPA)",
    )

    generic_drugs= (
        "Atorvastatina", "Levotiroxina", "Lisinopril", "Metformina", "Anlodipino",
        "Metoprolol", "Omeprazol", "Sinvastatina", "Losartana", "Gabapentina",
        "Hidroclorotiazida", "Sertralina", "Amoxicilina", "Albuterol", "Citalopram",
        "Pantoprazol", "Trazodona", "Fluoxetina", "Tramadol", "Clopidogrel",
        "Rosuvastatina", "Escitalopram", "Montelucaste", "Furosemida", "Bupropiona",
        "Prednisona", "Meloxicam", "Dextroanfetamina", "Duloxetina", "Carvedilol",
        "Ibuprofeno", "Paracetamol", "Ácido Acetilsalicílico", "Naproxeno", "Varfarina",
        "Apixabana", "Rivaroxabana", "Dabigatrana", "Insulina Glargina", "Insulina Asparte",
        "Insulina Lispro", "Insulina Detemir", "Empagliflozina", "Dapagliflozina", "Sitagliptina",
        "Glimepirida", "Pioglitazona", "Acarbosida", "Repaglinida", "Nateglinida",
        "Enalapril", "Quinapril", "Ramipril", "Benazepril", "Fosinopril",
        "Candesartana", "Valsartana", "Irbesartana", "Olmesartana", "Telmisartana",
        "Diltiazem", "Verapamil", "Nifedipino", "Felodipino", "Isradipino",
        "Bisoprolol", "Atenolol", "Propranolol", "Nadolol", "Labetalol",
        "Clonidina", "Hidralazina", "Prazosina", "Doxazosina", "Terazosina",
        "Espironolactona", "Triamtereno", "Amilorida", "Clortalidona", "Indapamida",
        "Amiodarona", "Digoxina", "Flecainida", "Propafenona", "Sotalol",
        "Nitrofurantoína", "Ciprofloxacino", "Levofloxacino", "Azitromicina", "Claritromicina",
        "Doxiciclina", "Cefalexina", "Cefuroxima", "Ceftriaxona", "Clindamicina",
        "Metronidazol", "Vancomicina", "Linezolida", "Aciclovir", "Valaciclovir",
        "Oseltamivir", "Fluconazol", "Voriconazol", "Anfotericina", "Terbinafina",
        "Venlafaxina", "Desvenlafaxina", "Mirtazapina", "Nortriptilina", "Amitriptilina",
        "Paroxetina", "Fluvoxamina", "Clomipramina", "Lítio", "Valproato",
        "Lamotrigina", "Carbamazepina", "Oxcarbazepina", "Topiramato", "Levetiracetam",
        "Fenitoína", "Fenobarbital", "Primidona", "Lacosamida", "Zonisamida",
        "Donepezil", "Rivastigmina", "Galantamina", "Memantina", "Levodopa",
        "Carbidopa", "Pramipexol", "Ropinirol", "Rasagilina", "Selegilina",
        "Baclofeno", "Tizanidina", "Ciclobenzaprina", "Carisoprodol", "Metocarbamol",
        "Alprazolam", "Lorazepam", "Diazepam", "Clonazepam", "Temazepam",
        "Zolpidem", "Eszopiclona", "Zaleplona", "Ramelteona", "Suvorexanto",
        "Metilfenidato", "Dexmetilfenidato", "Lisdexanfetamina", "Atomoxetina", "Guanfacina",
        "Aripiprazol", "Quetiapina", "Olanzapina", "Risperidona", "Ziprasidona",
        "Paliperidona", "Lurasidona", "Haloperidol", "Clorpromazina", "Perfenazina",
        "Tamsulosina", "Finasterida", "Dutasterida", "Sildenafila", "Tadalafila",
        "Vardenafila", "Oxibutinina", "Tolterodina", "Solifenacina", "Darifenacina",
        "Sulfato Ferroso", "Ácido Fólico", "Vitamina B12", "Vitamina D", "Carbonato de Cálcio",
        "Ranitidina", "Famotidina", "Esomeprazol", "Lansoprazol", "Rabeprazol",
        "Alopurinol", "Colchicina", "Probenecida", "Febuxostate", "Pegloticase",
        "Celecoxibe", "Diclofenaco", "Indometacina", "Cetorolaco", "Piroxicam",
        "Oxicodona", "Hidrocodona", "Morfina", "Fentanila", "Codeína",
        "Hidromorfona", "Oximorfona", "Metadona", "Buprenorfina", "Naloxona",
    )

    brand_drugs= (
        "Lipitor", "Synthroid", "Prinivil", "Glucophage", "Norvasc",
        "Lopressor", "Prilosec", "Zocor", "Cozaar", "Neurontin",
        "Zoloft", "Prozac", "Effexor", "Lexapro", "Cymbalta",
        "Plavix", "Eliquis", "Ozempic", "Jardiance", "Farxiga",
        "Crestor", "Januvia", "Victoza", "Trulicity", "Mounjaro",
        "Zepbound", "Lantus", "Humalog", "NovoLog", "Toujeo",
        "Basaglar", "Levemir", "Tresiba", "Zestril", "Altace",
        "Vasotec", "Accupril", "Diovan", "Avapro", "Benicar",
        "Micardis", "Coreg", "Tenormin", "Inderal", "Lopressor",
        "Toprol XL", "Catapres", "Cardizem", "Procardia", "Norvasc",
        "Plendil", "DynaCirc", "Aldactone", "Lasix", "Bumex",
        "Demadex", "Zaroxolyn", "Cordarone", "Lanoxin", "Tambocor",
        "Rythmol", "Betapace", "Xarelto", "Pradaxa", "Savaysa",
        "Macrobid", "Cipro", "Levaquin", "Zithromax", "Biaxin",
        "Vibramycin", "Keflex", "Ceftin", "Rocephin", "Cleocin",
        "Flagyl", "Vancocin", "Zyvox", "Zovirax", "Valtrex",
        "Tamiflu", "Diflucan", "Vfend", "AmBisome", "Lamisil",
        "Wellbutrin", "Pristiq", "Remeron", "Pamelor", "Elavil",
        "Paxil", "Luvox", "Anafranil", "Eskalith", "Depakote",
        "Lamictal", "Tegretol", "Trileptal", "Topamax", "Keppra",
        "Dilantin", "Luminal", "Mysoline", "Vimpat", "Zonegran",
        "Aricept", "Exelon", "Razadyne", "Namenda", "Sinemet",
        "Mirapex", "Requip", "Azilect", "Eldepryl", "Lioresal",
        "Zanaflex", "Flexeril", "Soma", "Robaxin", "Xanax",
        "Ativan", "Valium", "Klonopin", "Restoril", "Ambien",
        "Lunesta", "Sonata", "Rozerem", "Belsomra", "Ritalin",
        "Concerta", "Focalin", "Vyvanse", "Strattera", "Intuniv",
        "Abilify", "Seroquel", "Zyprexa", "Risperdal", "Geodon",
        "Invega", "Latuda", "Haldol", "Thorazine", "Trilafon",
        "Flomax", "Proscar", "Avodart", "Viagra", "Cialis",
        "Levitra", "Ditropan", "Detrol", "Vesicare", "Enablex",
        "Slow-Fe", "Folvite", "Nascobal", "Rocaltrol", "Caltrate",
        "Zantac", "Pepcid", "Nexium", "Prevacid", "Aciphex",
        "Zyloprim", "Colcrys", "Benemid", "Uloric", "Krystexxa",
        "Celebrex", "Voltaren", "Indocin", "Toradol", "Feldene",
        "OxyContin", "Vicodin", "MS Contin", "Duragesic", "Tylenol #3",
        "Dilaudid", "Opana", "Dolophine", "Suboxone", "Narcan",
        "Advair", "Symbicort", "Spiriva", "Singulair", "Dulera",
        "ProAir", "Ventolin", "Xopenex", "Flovent", "Pulmicort",
        "Keytruda", "Opdivo", "Yervoy", "Tecentriq", "Imfinzi",
        "Humira", "Enbrel", "Remicade", "Stelara", "Cosentyx",
        "Dupixent", "Xolair", "Skyrizi", "Taltz", "Entyvio",
    )

    symptoms= (
        "Febre", "Tosse", "Falta de Ar", "Dor de Cabeça", "Fadiga",
        "Dor Abdominal", "Náusea", "Vômito", "Diarreia", "Dor no Peito",
        "Tontura", "Erupção Cutânea", "Dor de Garganta", "Dor nas Articulações", "Dor nas Costas",
        "Tosse com Sangue", "Perda de Peso", "Inchaço", "Visão Embaçada", "Palpitações",
        "Calafrios", "Sudorese", "Dores Musculares", "Fraqueza", "Dormência",
        "Formigamento", "Confusão", "Perda de Memória", "Ansiedade", "Depressão",
        "Insônia", "Tremor", "Convulsões", "Perda de Consciência", "Desmaio",
        "Batimento Cardíaco Rápido", "Batimento Cardíaco Irregular", "Batimento Cardíaco Lento", "Pressão Alta", "Pressão Baixa",
        "Dificuldade para Engolir", "Azia", "Fezes com Sangue", "Fezes Pretas", "Constipação",
        "Inchaço Abdominal", "Gases", "Eructação", "Perda de Apetite", "Aumento de Apetite",
        "Micção Frequente", "Dor ao Urinar", "Sangue na Urina", "Urina Turva", "Urina Escura",
        "Incontinência", "Impotência", "Dor na Relação Sexual", "Menstruação Irregular", "Menstruação Pesada",
        "Corrimento Vaginal", "Sangramento Vaginal", "Ondas de Calor", "Suores Noturnos", "Sensibilidade Mamária",
        "Nódulo Mamário", "Secreção Mamilar", "Dor Testicular", "Inchaço Testicular", "Massa Escrotal",
        "Coceira", "Urticária", "Eczema", "Pele Seca", "Pele Oleosa",
        "Perda de Cabelo", "Unhas Frágeis", "Unhas Amarelas", "Fungos nas Unhas", "Caspa",
        "Olhos Vermelhos", "Olhos Lacrimejantes", "Visão Dupla", "Sensibilidade à Luz", "Dor nos Olhos",
        "Dor de Ouvido", "Secreção no Ouvido", "Zumbido nos Ouvidos", "Perda Auditiva", "Problemas de Equilíbrio",
        "Coriza", "Nariz Entupido", "Sangramento Nasal", "Espirros", "Gotejamento Pós-Nasal",
        "Perda de Olfato", "Perda de Paladar", "Mau Hálito", "Boca Seca", "Aftas",
        "Sangramento Gengival", "Dor de Dente", "Dor na Mandíbula", "Dificuldade para Mastigar", "Dificuldade para Respirar",
        "Sibilo", "Respiração Rápida", "Respiração Superficial", "Ronco", "Apneia do Sono",
    )

    blood_types= (
        "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-",
    )

    allergies= (
        "Penicilina", "Amendoim", "Nozes", "Mariscos", "Peixe",
        "Leite", "Ovos", "Soja", "Trigo", "Gergelim",
        "Látex", "Picada de Abelha", "Pólen", "Ácaros", "Pelos de Animais",
        "Sulfa", "Ácido Acetilsalicílico", "Ibuprofeno", "Codeína", "Morfina",
        "Meio de Contraste", "Anestesia", "Níquel", "Adesivo", "Fragrância",
        "Picadas de Insetos", "Mofo", "Baratas", "Gramíneas", "Ambrosia",
        "Milho", "Mostarda", "Aipo", "Lupino", "Sulfitos",
        "Glutamato Monossódico", "Corante Vermelho", "Glúten", "Lactose", "Frutose",
    )

    medical_procedures= (
        "Exame de Sangue", "Ressonância Magnética", "Tomografia Computadorizada", "Raio-X", "Ultrassonografia",
        "Colonoscopia", "Endoscopia", "Apendicectomia", "Colecistectomia", "Cesariana",
        "Histerectomia", "Artroplastia de Joelho", "Artroplastia de Quadril", "Cirurgia de Catarata", "Biópsia",
        "Sessão de Fisioterapia", "Eletrocardiograma (ECG)", "Ecocardiograma", "Vacinação", "Debridamento de Ferida",
        "Angioplastia", "Cateterismo Cardíaco", "Revascularização do Miocárdio", "Implante de Marcapasso", "Implante de Desfibrilador",
        "Ablação", "Tonsilectomia", "Adenoidectomia", "Mastectomia", "Lumpectomia",
        "Prostatectomia", "Nefrectomia", "Esplenectomia", "Gastrectomia", "Colectomia",
        "Ileostomia", "Colostomia", "Correção de Hérnia", "Remoção de Vesícula Biliar", "Biópsia de Fígado",
        "Biópsia Renal", "Biópsia de Medula Óssea", "Biópsia de Linfonodo", "Biópsia de Pele", "Broncoscopia",
        "Toracocentese", "Paracentese", "Punção Lombar", "Aspiração Articular", "Injeção Epidural",
        "Bloqueio Nervoso", "Injeção em Ponto-Gatilho", "Injeção Articular", "Injeção de Botox", "Injeção de Preenchimento",
        "Remoção a Laser de Pelos", "Peeling Químico", "Microdermoabrasão", "Dermoabrasão", "Remoção de Pápula Cutânea",
        "Remoção de Nevo", "Remoção de Verruga", "Crioterapia", "Eletrocauterização", "Excisição",
        "Incisão e Drenagem", "Sutura", "Grampeamento", "Enxerto de Pele", "Cirurgia de Retalho",
        "Cirurgia LASIK", "Cirurgia de Glaucoma", "Reparo de Descolamento de Retina", "Transplante de Córnea", "Vitrectomia",
        "Timpanoplastia", "Estapedectomia", "Implante Coclear", "Rinoplastia", "Septoplastia",
        "Cirurgia de Seios Paranasais", "Tireoidectomia", "Paratireoidectomia", "Adrenalectomia", "Pancreatectomia",
        "Procedimento de Whipple", "Ressecção Hepática", "Transplante de Fígado", "Transplante Renal", "Transplante Cardíaco",
        "Transplante Pulmonar", "Transplante de Pâncreas", "Transplante de Medula Óssea", "Transplante de Células-Tronco", "Diálise",
        "Hemodiálise", "Diálise Peritoneal", "Plasmaférese", "Infusão de IVIG", "Quimioterapia",
        "Radioterapia", "Imunoterapia", "Hormonioterapia", "Terapia Alvo", "Terapia CAR-T",
    )

    insurance_plans= (
        "Plano Individual", "Plano Familiar", "Plano Empresarial", "Plano por Adesão", "Plano Odontológico",
        "Plano Ambulatorial", "Plano Hospitalar", "Plano Referência", "Plano com Coparticipação", "Plano sem Coparticipação",
        "Plano Coletivo", "Plano de Saúde Suplementar", "Plano para Servidores Públicos", "Plano para Idosos", "Plano para Crianças",
        "Plano de Saúde Internacional", "Plano de Saúde Regional", "Plano de Saúde Nacional", "Plano de Saúde com Reembolso", "Plano de Saúde sem Reembolso",
    )

    vital_signs= (
        "Pressão Arterial", "Frequência Cardíaca", "Frequência Respiratória", "Temperatura Corporal", "Saturação de Oxigênio",
        "Índice de Massa Corporal (IMC)", "Glicemia", "Nível de Dor", "Pulso", "Fluxo de Pico",
    )
