"""Display labels for the locale-neutral clinical values (pt_BR).

Words only: the numbers, units and reference intervals live once in
`faker_healthcare/clinical_values.py` and are never translated. The key set must match
the base catalogue exactly (`faker_healthcare/clinical_labels.py`); see
`tests/test_locales.py::TestClinicalLabelParity`.

Duas estruturas: `CLINICAL_LABELS` (nomes dos analitos e sinais vitais, sinalizações,
categorias de álcool, vias, frequências, situação da prescrição e faixas das escalas) e
`MEDICATION_NAMES`, que liga o identificador neutro de uma substância à grafia exata
usada por este catálogo — é o que permite a uma única tabela de doses valer para os seis
idiomas.
"""

CLINICAL_LABELS: dict[str, str] = {
    # Sinais vitais
    "systolic_bp": "Pressão arterial sistólica",
    "diastolic_bp": "Pressão arterial diastólica",
    "heart_rate": "Frequência cardíaca",
    "respiratory_rate": "Frequência respiratória",
    "temperature_c": "Temperatura corporal",
    "oxygen_saturation": "Saturação de oxigênio",
    # Hematologia
    "haemoglobin": "Hemoglobina",
    "wbc": "Contagem de leucócitos",
    "platelets": "Contagem de plaquetas",
    "ferritin": "Ferritina",
    "inr": "INR (RNI)",
    # Função renal
    "sodium": "Sódio",
    "potassium": "Potássio",
    "urea": "Ureia",
    "creatinine": "Creatinina",
    "egfr": "Taxa de filtração glomerular estimada (TFGe)",
    # Função hepática
    "alt": "Alanina aminotransferase (ALT/TGP)",
    "ast": "Aspartato aminotransferase (AST/TGO)",
    "alkaline_phosphatase": "Fosfatase alcalina",
    "bilirubin_total": "Bilirrubina total",
    "albumin": "Albumina",
    # Metabolismo
    "fasting_glucose": "Glicemia de jejum",
    "hba1c": "Hemoglobina glicada (HbA1c)",
    # Tireoide
    "tsh": "Hormônio tireoestimulante (TSH)",
    "free_t4": "Tiroxina livre (T4 livre)",
    # Lipídios
    "total_cholesterol": "Colesterol total",
    "ldl": "Colesterol LDL",
    "hdl": "Colesterol HDL",
    "triglycerides": "Triglicerídeos",
    # Marcadores inflamatórios
    "crp": "Proteína C reativa (PCR)",
    # Sinalização do resultado
    "flag_low": "Baixo",
    "flag_normal": "Normal",
    "flag_high": "Alto",
    # Consumo semanal de álcool
    "alcohol_none": "Não bebedor",
    "alcohol_low_risk": "Baixo risco",
    "alcohol_increasing_risk": "Risco crescente",
    "alcohol_higher_risk": "Risco alto",
    # Vias de administração
    "route_oral": "Via oral",
    "route_intravenous": "Via intravenosa",
    "route_subcutaneous": "Via subcutânea",
    "route_inhaled": "Via inalatória",
    "route_sublingual": "Via sublingual",
    "route_ophthalmic": "Via oftálmica",
    # Frequências posológicas
    "frequency_once_daily": "Uma vez ao dia",
    "frequency_twice_daily": "Duas vezes ao dia",
    "frequency_three_times_daily": "Três vezes ao dia",
    "frequency_four_times_daily": "Quatro vezes ao dia",
    "frequency_at_night": "À noite",
    "frequency_as_required": "Se necessário",
    "frequency_once_weekly": "Uma vez por semana",
    "frequency_every_three_weeks": "A cada três semanas",
    # Situação da prescrição
    "medication_status_past": "Uso anterior",
    "medication_status_current": "Uso atual",
    "medication_status_future": "Uso planejado",
    # Faixas de gravidade das escalas
    "assessment_minimal": "Mínimo",
    "assessment_mild": "Leve",
    "assessment_moderate": "Moderado",
    "assessment_moderately_severe": "Moderadamente grave",
    "assessment_severe": "Grave",
    "assessment_symptoms_absent": "Sintomas ausentes",
    "assessment_normal_cognition": "Cognição normal",
    "assessment_screen_negative": "Rastreio negativo",
    "assessment_screen_positive": "Rastreio positivo",
    "alcohol_possible_dependence": "Possível dependência",
}

# As substâncias que `medication_order()` sabe dosear, com o nome deste catálogo.
MEDICATION_NAMES: dict[str, str] = {
    "acamprosate": "Acamprosato",
    "acetaminophen": "Paracetamol",
    "acyclovir": "Aciclovir",
    "albuterol": "Salbutamol",
    "alendronate": "Alendronato",
    "allopurinol": "Alopurinol",
    "alprazolam": "Alprazolam",
    "amitriptyline": "Amitriptilina",
    "amlodipine": "Anlodipina",
    "amoxicillin": "Amoxicilina",
    "anastrozole": "Anastrozol",
    "apixaban": "Apixabana",
    "aripiprazole": "Aripiprazol",
    "aspirin": "Aspirina",
    "atomoxetine": "Atomoxetina",
    "atorvastatin": "Atorvastatina",
    "azathioprine": "Azatioprina",
    "azithromycin": "Azitromicina",
    "bicalutamide": "Bicalutamida",
    "budesonide": "Budesonida",
    "buprenorphine": "Buprenorfina",
    "bupropion": "Bupropiona",
    "buspirone": "Buspirona",
    "calcium_carbonate": "Carbonato de cálcio",
    "carbamazepine": "Carbamazepina",
    "ceftriaxone": "Ceftriaxona",
    "cefuroxime": "Cefuroxima",
    "cephalexin": "Cefalexina",
    "cetirizine": "Cetirizina",
    "cholecalciferol": "Colecalciferol",
    "cilostazol": "Cilostazol",
    "ciprofloxacin": "Ciprofloxacino",
    "clarithromycin": "Claritromicina",
    "clindamycin": "Clindamicina",
    "clopidogrel": "Clopidogrel",
    "colchicine": "Colchicina",
    "dexamethasone": "Dexametasona",
    "digoxin": "Digoxina",
    "diltiazem": "Diltiazem",
    "donepezil": "Donepezila",
    "doxycycline": "Doxiciclina",
    "duloxetine": "Duloxetina",
    "dutasteride": "Dutasterida",
    "empagliflozin": "Empagliflozina",
    "enoxaparin": "Enoxaparina",
    "escitalopram": "Escitalopram",
    "esomeprazole": "Esomeprazol",
    "famotidine": "Famotidina",
    "febuxostat": "Febuxostate",
    "ferrous_sulfate": "Sulfato ferroso",
    "finasteride": "Finasterida",
    "fluoxetine": "Fluoxetina",
    "fluticasone": "Fluticasona",
    "folic_acid": "Ácido fólico",
    "furosemide": "Furosemida",
    "gabapentin": "Gabapentina",
    "galantamine": "Galantamina",
    "glimepiride": "Glimepirida",
    "glyburide": "Gliburida",
    "haloperidol": "Haloperidol",
    "hydrochlorothiazide": "Hidroclorotiazida",
    "hydrocortisone": "Hidrocortisona",
    "hydroxychloroquine": "Hidroxicloroquina",
    "ibuprofen": "Ibuprofeno",
    "insulin": "Insulina",
    "insulin_glargine": "Insulina glargina",
    "lactulose": "Lactulose",
    "lamotrigine": "Lamotrigina",
    "latanoprost": "Latanoprosta",
    "letrozole": "Letrozol",
    "levetiracetam": "Levetiracetam",
    "levofloxacin": "Levofloxacino",
    "levothyroxine": "Levotiroxina",
    "liraglutide": "Liraglutida",
    "lisinopril": "Lisinopril",
    "lithium": "Lítio",
    "loperamide": "Loperamida",
    "loratadine": "Loratadina",
    "lorazepam": "Lorazepam",
    "losartan": "Losartana",
    "melatonin": "Melatonina",
    "memantine": "Memantina",
    "mesalamine": "Mesalazina",
    "metformin": "Metformina",
    "methadone": "Metadona",
    "methimazole": "Metimazol",
    "methotrexate": "Metotrexato",
    "methylphenidate": "Metilfenidato",
    "metoprolol": "Metoprolol",
    "metronidazole": "Metronidazol",
    "montelukast": "Montelucaste",
    "naltrexone": "Naltrexona",
    "naproxen": "Naproxeno",
    "nitrofurantoin": "Nitrofurantoína",
    "nitroglycerin": "Nitroglicerina",
    "olanzapine": "Olanzapina",
    "omeprazole": "Omeprazol",
    "oseltamivir": "Oseltamivir",
    "oxybutynin": "Oxibutinina",
    "pantoprazole": "Pantoprazol",
    "paroxetine": "Paroxetina",
    "pembrolizumab": "Pembrolizumabe",
    "phenytoin": "Fenitoína",
    "pioglitazone": "Pioglitazona",
    "prednisone": "Prednisona",
    "pregabalin": "Pregabalina",
    "propranolol": "Propranolol",
    "quetiapine": "Quetiapina",
    "risperidone": "Risperidona",
    "rivaroxaban": "Rivaroxabana",
    "rosuvastatin": "Rosuvastatina",
    "sertraline": "Sertralina",
    "sildenafil": "Sildenafila",
    "simvastatin": "Sinvastatina",
    "sitagliptin": "Sitagliptina",
    "solifenacin": "Solifenacina",
    "spironolactone": "Espironolactona",
    "sulfasalazine": "Sulfassalazina",
    "sumatriptan": "Sumatriptano",
    "tadalafil": "Tadalafila",
    "tamoxifen": "Tamoxifeno",
    "tamsulosin": "Tansulosina",
    "theophylline": "Teofilina",
    "timolol": "Timolol",
    "tiotropium": "Tiotrópio",
    "tolterodine": "Tolterodina",
    "topiramate": "Topiramato",
    "tramadol": "Tramadol",
    "trimethoprim": "Trimetoprim",
    "ursodiol": "Ursodiol",
    "valacyclovir": "Valaciclovir",
    "valproate": "Valproato",
    "valproic_acid": "Ácido valproico",
    "venlafaxine": "Venlafaxina",
    "warfarin": "Varfarina",
}
