"""
Constantes de dados estáticos para o provedor de assistência médica (pt_BR).
"""

HOSPITAL_DEPARTMENTS: tuple[str, ...] = (
    "Pronto-Socorro",
    "Unidade de Terapia Intensiva (UTI)",
    "Unidade de Cuidados Cardíacos (UCC)",
    "Sala de Cirurgia",
    "Trabalho de Parto e Nascimento",
    "Pediatria",
    "Ala de Maternidade",
    "Oncologia",
    "Radiologia",
    "Laboratório",
    "Farmácia",
    "Fisioterapia",
    "Terapia Ocupacional",
    "Terapia Respiratória",
    "Cirurgia",
    "Ala de Internação",
    "Clínica Ambulatorial",
    "Ala Psiquiátrica",
    "Unidade de Reabilitação",
    "Sala de Endoscopia",
    "Unidade de Terapia Intensiva Neonatal (UTIN)",
    "Unidade de Queimados",
    "Unidade de Diálise",
    "Laboratório do Sono",
    "Centro de Cuidados com Feridas",
    "Centro de Infusão",
    "Unidade de Cardiologia",
    "Unidade de Neurologia",
    "Unidade de Observação Médica",
    "Unidade de Cuidados Pós-Anestesia (SRPA)",
)

BRAND_DRUGS: tuple[str, ...] = (
    "Lipitor",
    "Synthroid",
    "Prinivil",
    "Glucophage",
    "Norvasc",
    "Lopressor",
    "Prilosec",
    "Zocor",
    "Cozaar",
    "Neurontin",
    "Zoloft",
    "Prozac",
    "Effexor",
    "Lexapro",
    "Cymbalta",
    "Plavix",
    "Eliquis",
    "Ozempic",
    "Jardiance",
    "Farxiga",
    "Crestor",
    "Januvia",
    "Victoza",
    "Trulicity",
    "Mounjaro",
    "Zepbound",
    "Lantus",
    "Humalog",
    "NovoLog",
    "Toujeo",
    "Basaglar",
    "Levemir",
    "Tresiba",
    "Zestril",
    "Altace",
    "Vasotec",
    "Accupril",
    "Diovan",
    "Avapro",
    "Benicar",
    "Micardis",
    "Coreg",
    "Tenormin",
    "Inderal",
    "Lopressor",
    "Toprol XL",
    "Catapres",
    "Cardizem",
    "Procardia",
    "Norvasc",
    "Plendil",
    "DynaCirc",
    "Aldactone",
    "Lasix",
    "Bumex",
    "Demadex",
    "Zaroxolyn",
    "Cordarone",
    "Lanoxin",
    "Tambocor",
    "Rythmol",
    "Betapace",
    "Xarelto",
    "Pradaxa",
    "Savaysa",
    "Macrobid",
    "Cipro",
    "Levaquin",
    "Zithromax",
    "Biaxin",
    "Vibramycin",
    "Keflex",
    "Ceftin",
    "Rocephin",
    "Cleocin",
    "Flagyl",
    "Vancocin",
    "Zyvox",
    "Zovirax",
    "Valtrex",
    "Tamiflu",
    "Diflucan",
    "Vfend",
    "AmBisome",
    "Lamisil",
    "Wellbutrin",
    "Pristiq",
    "Remeron",
    "Pamelor",
    "Elavil",
    "Paxil",
    "Luvox",
    "Anafranil",
    "Eskalith",
    "Depakote",
    "Lamictal",
    "Tegretol",
    "Trileptal",
    "Topamax",
    "Keppra",
    "Dilantin",
    "Luminal",
    "Mysoline",
    "Vimpat",
    "Zonegran",
    "Aricept",
    "Exelon",
    "Razadyne",
    "Namenda",
    "Sinemet",
    "Mirapex",
    "Requip",
    "Azilect",
    "Eldepryl",
    "Lioresal",
    "Zanaflex",
    "Flexeril",
    "Soma",
    "Robaxin",
    "Xanax",
    "Ativan",
    "Valium",
    "Klonopin",
    "Restoril",
    "Ambien",
    "Lunesta",
    "Sonata",
    "Rozerem",
    "Belsomra",
    "Ritalin",
    "Concerta",
    "Focalin",
    "Vyvanse",
    "Strattera",
    "Intuniv",
    "Abilify",
    "Seroquel",
    "Zyprexa",
    "Risperdal",
    "Geodon",
    "Invega",
    "Latuda",
    "Haldol",
    "Thorazine",
    "Trilafon",
    "Flomax",
    "Proscar",
    "Avodart",
    "Viagra",
    "Cialis",
    "Levitra",
    "Ditropan",
    "Detrol",
    "Vesicare",
    "Enablex",
    "Slow-Fe",
    "Folvite",
    "Nascobal",
    "Rocaltrol",
    "Caltrate",
    "Zantac",
    "Pepcid",
    "Nexium",
    "Prevacid",
    "Aciphex",
    "Zyloprim",
    "Colcrys",
    "Benemid",
    "Uloric",
    "Krystexxa",
    "Celebrex",
    "Voltaren",
    "Indocin",
    "Toradol",
    "Feldene",
    "OxyContin",
    "Vicodin",
    "MS Contin",
    "Duragesic",
    "Tylenol #3",
    "Dilaudid",
    "Opana",
    "Dolophine",
    "Suboxone",
    "Narcan",
    "Advair",
    "Symbicort",
    "Spiriva",
    "Singulair",
    "Dulera",
    "ProAir",
    "Ventolin",
    "Xopenex",
    "Flovent",
    "Pulmicort",
    "Keytruda",
    "Opdivo",
    "Yervoy",
    "Tecentriq",
    "Imfinzi",
    "Humira",
    "Enbrel",
    "Remicade",
    "Stelara",
    "Cosentyx",
    "Dupixent",
    "Xolair",
    "Skyrizi",
    "Taltz",
    "Entyvio",
)

BLOOD_TYPES: tuple[str, ...] = ("A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-")

ALLERGIES: tuple[str, ...] = (
    "Penicilina",
    "Amendoim",
    "Nozes",
    "Mariscos",
    "Peixe",
    "Leite",
    "Ovos",
    "Soja",
    "Trigo",
    "Gergelim",
    "Látex",
    "Picada de Abelha",
    "Pólen",
    "Ácaros",
    "Pelos de Animais",
    "Sulfa",
    "Ácido Acetilsalicílico",
    "Ibuprofeno",
    "Codeína",
    "Morfina",
    "Meio de Contraste",
    "Anestesia",
    "Níquel",
    "Adesivo",
    "Fragrância",
    "Picadas de Insetos",
    "Mofo",
    "Baratas",
    "Gramíneas",
    "Ambrosia",
    "Milho",
    "Mostarda",
    "Aipo",
    "Lupino",
    "Sulfitos",
    "Glutamato Monossódico",
    "Corante Vermelho",
    "Glúten",
    "Lactose",
    "Frutose",
)

MEDICAL_PROCEDURES: tuple[str, ...] = (
    "Exame de Sangue",
    "Ressonância Magnética",
    "Tomografia Computadorizada",
    "Raio-X",
    "Ultrassonografia",
    "Colonoscopia",
    "Endoscopia",
    "Apendicectomia",
    "Colecistectomia",
    "Cesariana",
    "Histerectomia",
    "Artroplastia de Joelho",
    "Artroplastia de Quadril",
    "Cirurgia de Catarata",
    "Biópsia",
    "Sessão de Fisioterapia",
    "Eletrocardiograma (ECG)",
    "Ecocardiograma",
    "Vacinação",
    "Debridamento de Ferida",
    "Angioplastia",
    "Cateterismo Cardíaco",
    "Revascularização do Miocárdio",
    "Implante de Marcapasso",
    "Implante de Desfibrilador",
    "Ablação",
    "Tonsilectomia",
    "Adenoidectomia",
    "Mastectomia",
    "Lumpectomia",
    "Prostatectomia",
    "Nefrectomia",
    "Esplenectomia",
    "Gastrectomia",
    "Colectomia",
    "Ileostomia",
    "Colostomia",
    "Correção de Hérnia",
    "Remoção de Vesícula Biliar",
    "Biópsia de Fígado",
    "Biópsia Renal",
    "Biópsia de Medula Óssea",
    "Biópsia de Linfonodo",
    "Biópsia de Pele",
    "Broncoscopia",
    "Toracocentese",
    "Paracentese",
    "Punção Lombar",
    "Aspiração Articular",
    "Injeção Epidural",
    "Bloqueio Nervoso",
    "Injeção em Ponto-Gatilho",
    "Injeção Articular",
    "Injeção de Botox",
    "Injeção de Preenchimento",
    "Remoção a Laser de Pelos",
    "Peeling Químico",
    "Microdermoabrasão",
    "Dermoabrasão",
    "Remoção de Pápula Cutânea",
    "Remoção de Nevo",
    "Remoção de Verruga",
    "Crioterapia",
    "Eletrocauterização",
    "Excisição",
    "Incisão e Drenagem",
    "Sutura",
    "Grampeamento",
    "Enxerto de Pele",
    "Cirurgia de Retalho",
    "Cirurgia LASIK",
    "Cirurgia de Glaucoma",
    "Reparo de Descolamento de Retina",
    "Transplante de Córnea",
    "Vitrectomia",
    "Timpanoplastia",
    "Estapedectomia",
    "Implante Coclear",
    "Rinoplastia",
    "Septoplastia",
    "Cirurgia de Seios Paranasais",
    "Tireoidectomia",
    "Paratireoidectomia",
    "Adrenalectomia",
    "Pancreatectomia",
    "Procedimento de Whipple",
    "Ressecção Hepática",
    "Transplante de Fígado",
    "Transplante Renal",
    "Transplante Cardíaco",
    "Transplante Pulmonar",
    "Transplante de Pâncreas",
    "Transplante de Medula Óssea",
    "Transplante de Células-Tronco",
    "Diálise",
    "Hemodiálise",
    "Diálise Peritoneal",
    "Plasmaférese",
    "Infusão de IVIG",
    "Quimioterapia",
    "Radioterapia",
    "Imunoterapia",
    "Hormonioterapia",
    "Terapia Alvo",
    "Terapia CAR-T",
)

INSURANCE_PLANS: tuple[str, ...] = (
    "Plano Individual",
    "Plano Familiar",
    "Plano Empresarial",
    "Plano por Adesão",
    "Plano Odontológico",
    "Plano Ambulatorial",
    "Plano Hospitalar",
    "Plano Referência",
    "Plano com Coparticipação",
    "Plano sem Coparticipação",
    "Plano Coletivo",
    "Plano de Saúde Suplementar",
    "Plano para Servidores Públicos",
    "Plano para Idosos",
    "Plano para Crianças",
    "Plano de Saúde Internacional",
    "Plano de Saúde Regional",
    "Plano de Saúde Nacional",
    "Plano de Saúde com Reembolso",
    "Plano de Saúde sem Reembolso",
)

VITAL_SIGNS: tuple[str, ...] = (
    "Pressão Arterial",
    "Frequência Cardíaca",
    "Frequência Respiratória",
    "Temperatura Corporal",
    "Saturação de Oxigênio",
    "Índice de Massa Corporal (IMC)",
    "Glicemia",
    "Nível de Dor",
    "Pulso",
    "Fluxo de Pico",
)
