"""
Dados de Correlações de Doenças
Este módulo contém o dicionário DISEASE_CORRELATIONS mapeando todas as 150 doenças
para seus sintomas, códigos CID-10, medicamentos e especialidades primárias.
Dados obtidos da classificação CID-10 da OMS.
AVISO MÉDICO: Esses dados são APENAS PARA FINS DE TESTE E DESENVOLVIMENTO.
NÃO devem ser usados para diagnóstico médico real, tratamento ou decisões de saúde.
"""

from ..types import DiseaseData


DISEASE_CORRELATIONS: dict[str, DiseaseData] = {
    "Diabetes mellitus tipo 2": {
        "icd10": "E11.9",
        "symptoms": ["Micção frequente", "Aumento do apetite", "Fadiga", "Visão turva", "Perda de peso"],
        "medications": ["Metformina", "Insulina glargina", "Empagliflozina", "Sitagliptina", "Glimepirida"],
        "medical_specialty": "Endocrinologia",
    },
    "Hipertensão essencial (primária)": {
        "icd10": "I10",
        "symptoms": ["Dor de cabeça", "Tontura", "Dor no peito", "Visão turva", "Palpitações"],
        "medications": ["Lisinopril", "Anlodipina", "Losartana", "Hidroclorotiazida", "Metoprolol"],
        "medical_specialty": "Cardiologia",
    },
    "Hiperlipidemia não especificada": {
        "icd10": "E78.5",
        "symptoms": ["Dor no peito", "Fadiga", "Dormência", "Fraqueza"],
        "medications": ["Atorvastatina", "Sinvastatina", "Rosuvastatina", "Fenofibrato", "Ezetimiba"],
        "medical_specialty": "Cardiologia",
    },
    "Doença arterial coronariana": {
        "icd10": "I25.10",
        "symptoms": ["Dor no peito", "Falta de ar", "Fadiga", "Palpitações", "Tontura"],
        "medications": ["Aspirina", "Clopidogrel", "Atorvastatina", "Metoprolol", "Nitroglicerina"],
        "medical_specialty": "Cardiologia",
    },
    "Doença pulmonar obstrutiva crônica": {
        "icd10": "J44.9",
        "symptoms": ["Falta de ar", "Tosse", "Sibilo", "Dor no peito", "Fadiga"],
        "medications": ["Salbutamol", "Tiotrópio", "Fluticasona", "Prednisona", "Azitromicina"],
        "medical_specialty": "Pneumologia",
    },
    "Asma": {
        "icd10": "J45.909",
        "symptoms": ["Sibilo", "Falta de ar", "Tosse", "Dor no peito", "Dificuldade para respirar"],
        "medications": ["Salbutamol", "Fluticasona", "Montelucaste", "Prednisona", "Budesonida"],
        "medical_specialty": "Pneumologia",
    },
    "Doença renal crônica": {
        "icd10": "N18.9",
        "symptoms": ["Fadiga", "Inchaço", "Náusea", "Perda de apetite", "Micção frequente"],
        "medications": ["Lisinopril", "Furosemida", "Eritropoietina", "Carbonato de cálcio", "Sevelamer"],
        "medical_specialty": "Nefrologia",
    },
    "Osteoartrite": {
        "icd10": "M17.9",
        "symptoms": ["Dor articular", "Inchaço", "Fraqueza", "Dor nas costas"],
        "medications": ["Ibuprofeno", "Paracetamol", "Naproxeno", "Celecoxibe", "Tramadol"],
        "medical_specialty": "Ortopedia",
    },
    "Artrite reumatoide": {
        "icd10": "M79.1",
        "symptoms": ["Dor articular", "Inchaço", "Fadiga", "Fraqueza", "Dores musculares"],
        "medications": ["Metotrexato", "Prednisona", "Adalimumabe", "Hidroxicloroquina", "Sulfassalazina"],
        "medical_specialty": "Reumatologia",
    },
    "Depressão": {
        "icd10": "F32.9",
        "symptoms": ["Depressão", "Fadiga", "Insônia", "Perda de apetite", "Ansiedade"],
        "medications": ["Sertralina", "Fluoxetina", "Escitalopram", "Bupropiona", "Duloxetina"],
        "medical_specialty": "Psiquiatria",
    },
    "Transtorno de ansiedade": {
        "icd10": "F41.9",
        "symptoms": ["Ansiedade", "Palpitações", "Sudorese", "Tremor", "Insônia"],
        "medications": ["Sertralina", "Escitalopram", "Alprazolam", "Lorazepam", "Buspirona"],
        "medical_specialty": "Psiquiatria",
    },
    "Doença do refluxo gastroesofágico": {
        "icd10": "K21.9",
        "symptoms": ["Azia", "Dor no peito", "Dificuldade para engolir", "Dor de garganta", "Náusea"],
        "medications": ["Omeprazol", "Pantoprazol", "Esomeprazol", "Ranitidina", "Famotidina"],
        "medical_specialty": "Gastroenterologia",
    },
    "Obesidade": {
        "icd10": "E66.9",
        "symptoms": ["Fadiga", "Dor articular", "Falta de ar", "Sudorese"],
        "medications": ["Orlistate", "Fentermina", "Liraglutida", "Semaglutida", "Naltrexona"],
        "medical_specialty": "Endocrinologia",
    },
    "Hipotireoidismo": {
        "icd10": "E03.9",
        "symptoms": ["Fadiga", "Ganho de peso", "Queda de cabelo", "Pele seca", "Constipação"],
        "medications": ["Levotiroxina", "Liotironina", "Tireoide"],
        "medical_specialty": "Endocrinologia",
    },
    "Fibrilação atrial": {
        "icd10": "I48.91",
        "symptoms": ["Palpitações", "Tontura", "Fadiga", "Falta de ar", "Dor no peito"],
        "medications": ["Varfarina", "Apixabana", "Rivaroxabana", "Metoprolol", "Diltiazem"],
        "medical_specialty": "Cardiologia",
    },
    "Insuficiência cardíaca congestiva": {
        "icd10": "I50.9",
        "symptoms": ["Falta de ar", "Fadiga", "Inchaço", "Tosse", "Batimento cardíaco rápido"],
        "medications": ["Furosemida", "Lisinopril", "Metoprolol", "Espironolactona", "Digoxina"],
        "medical_specialty": "Cardiologia",
    },
    "Pneumonia": {
        "icd10": "J18.9",
        "symptoms": ["Febre", "Tosse", "Falta de ar", "Dor no peito", "Fadiga"],
        "medications": ["Amoxicilina", "Azitromicina", "Ceftriaxona", "Levofloxacino", "Doxiciclina"],
        "medical_specialty": "Pneumologia",
    },
    "Infecção do trato urinário": {
        "icd10": "N39.0",
        "symptoms": ["Dor ao urinar", "Micção frequente", "Febre", "Dor abdominal", "Urina turva"],
        "medications": ["Nitrofurantoína", "Ciprofloxacino", "Trimetoprim", "Amoxicilina", "Cefalexina"],
        "medical_specialty": "Medicina Interna",
    },
    "Bronquite aguda": {
        "icd10": "J20.9",
        "symptoms": ["Tosse", "Febre", "Fadiga", "Falta de ar", "Dor no peito"],
        "medications": ["Salbutamol", "Guaifenesina", "Dextrometorfano", "Ibuprofeno", "Azitromicina"],
        "medical_specialty": "Pneumologia",
    },
    "Anemia": {
        "icd10": "D64.9",
        "symptoms": ["Fadiga", "Fraqueza", "Tontura", "Dor de cabeça", "Falta de ar"],
        "medications": ["Sulfato ferroso", "Vitamina B12", "Ácido fólico", "Eritropoietina"],
        "medical_specialty": "Hematologia",
    },
    "Enxaqueca": {
        "icd10": "G43.909",
        "symptoms": ["Dor de cabeça", "Náusea", "Sensibilidade à luz", "Visão turva", "Tontura"],
        "medications": ["Sumatriptano", "Ibuprofeno", "Topiramato", "Propranolol", "Amitriptilina"],
        "medical_specialty": "Neurologia",
    },
    "Acidente vascular cerebral": {
        "icd10": "I63.9",
        "symptoms": ["Dormência", "Confusão", "Dificuldade para engolir", "Visão turva", "Fraqueza"],
        "medications": ["Aspirina", "Clopidogrel", "Alteplase", "Varfarina", "Atorvastatina"],
        "medical_specialty": "Neurologia",
    },
    "Doença de Alzheimer": {
        "icd10": "G30.9",
        "symptoms": ["Perda de memória", "Confusão", "Ansiedade", "Depressão", "Dificuldade para engolir"],
        "medications": ["Donepezila", "Memantina", "Rivastigmina", "Galantamina"],
        "medical_specialty": "Neurologia",
    },
    "Câncer de mama": {
        "icd10": "C50.919",
        "symptoms": ["Nódulo na mama", "Secreção no mamilo", "Inchaço", "Perda de peso", "Fadiga"],
        "medications": ["Tamoxifeno", "Anastrozol", "Trastuzumabe", "Quimioterapia", "Radioterapia"],
        "medical_specialty": "Oncologia",
    },
    "Câncer de próstata": {
        "icd10": "C61",
        "symptoms": ["Dor ao urinar", "Micção frequente", "Fraqueza", "Perda de peso"],
        "medications": ["Leuprolida", "Bicalutamida", "Docetaxel", "Abiraterona", "Enzalutamida"],
        "medical_specialty": "Oncologia",
    },
    "Câncer de pulmão": {
        "icd10": "C34.90",
        "symptoms": ["Tosse", "Tosse com sangue", "Falta de ar", "Dor no peito", "Perda de peso"],
        "medications": ["Carboplatina", "Paclitaxel", "Pembrolizumabe", "Erlotinibe", "Quimioterapia"],
        "medical_specialty": "Oncologia",
    },
    "COVID-19": {
        "icd10": "U07.1",
        "symptoms": ["Febre", "Tosse", "Fadiga", "Perda de olfato", "Perda de paladar", "Falta de ar"],
        "medications": ["Remdesivir", "Dexametasona", "Paxlovid", "Molnupiravir"],
        "medical_specialty": "Doenças Infecciosas",
    },
    "Influenza": {
        "icd10": "J11.1",
        "symptoms": ["Febre", "Tosse", "Dor de garganta", "Dores musculares", "Fadiga", "Dor de cabeça"],
        "medications": ["Oseltamivir", "Zanamivir", "Baloxavir", "Ibuprofeno", "Paracetamol"],
        "medical_specialty": "Medicina Interna",
    },
    "Osteoporose": {
        "icd10": "M81.0",
        "symptoms": ["Dor nas costas", "Perda óssea", "Fraqueza"],
        "medications": ["Alendronato", "Risedronato", "Denosumabe", "Carbonato de cálcio", "Vitamina D"],
        "medical_specialty": "Endocrinologia",
    },
    "Doença arterial periférica": {
        "icd10": "I73.9",
        "symptoms": ["Dor na perna", "Dormência", "Fraqueza", "Extremidades frias"],
        "medications": ["Cilostazol", "Aspirina", "Clopidogrel", "Atorvastatina", "Pentoxifilina"],
        "medical_specialty": "Cirurgia Vascular",
    },
    "Angina pectoris": {
        "icd10": "I20.9",
        "symptoms": ["Dor no peito", "Falta de ar", "Fadiga", "Náusea", "Sudorese"],
        "medications": ["Nitroglicerina", "Aspirina", "Metoprolol", "Anlodipina", "Atorvastatina"],
        "medical_specialty": "Cardiologia",
    },
    "Hipertireoidismo": {
        "icd10": "E05.90",
        "symptoms": ["Perda de peso", "Palpitações", "Ansiedade", "Tremor", "Intolerância ao calor"],
        "medications": ["Metimazol", "Propiltiouracila", "Propranolol", "Iodo radioativo", "Levotiroxina"],
        "medical_specialty": "Endocrinologia",
    },
    "Gota": {
        "icd10": "M10.9",
        "symptoms": ["Dor articular", "Inchaço", "Vermelhidão", "Tofos", "Mobilidade limitada"],
        "medications": ["Alopurinol", "Colchicina", "Indometacina", "Febuxostate", "Probenecida"],
        "medical_specialty": "Reumatologia",
    },
    "Esclerose múltipla": {
        "icd10": "G35",
        "symptoms": ["Fadiga", "Dormência", "Problemas de visão", "Problemas de equilíbrio", "Fraqueza muscular"],
        "medications": ["Interferon beta", "Acetato de glatirâmer", "Fingolimode", "Natalizumabe", "Ocrelizumabe"],
        "medical_specialty": "Neurologia",
    },
    "Doença de Parkinson": {
        "icd10": "G20",
        "symptoms": ["Tremor", "Bradicinesia", "Rigidez", "Instabilidade postural", "Alterações na fala"],
        "medications": ["Levodopa", "Carbidopa", "Pramipexol", "Selegilina", "Amantadina"],
        "medical_specialty": "Neurologia",
    },
    "Epilepsia": {
        "icd10": "G40.909",
        "symptoms": ["Convulsões", "Perda de consciência", "Confusão", "Episódios de olhar fixo", "Convulsões"],
        "medications": ["Carbamazepina", "Valproato", "Lamotrigina", "Levetiracetam", "Fenitoína"],
        "medical_specialty": "Neurologia",
    },
    "Transtorno bipolar": {
        "icd10": "F31.9",
        "symptoms": ["Oscilações de humor", "Mania", "Depressão", "Irritabilidade", "Insônia"],
        "medications": ["Lítio", "Valproato", "Olanzapina", "Quetiapina", "Lamotrigina"],
        "medical_specialty": "Psiquiatria",
    },
    "Esquizofrenia": {
        "icd10": "F20.9",
        "symptoms": ["Alucinações", "Delírios", "Pensamento desorganizado", "Sintomas negativos", "Comprometimento cognitivo"],
        "medications": ["Risperidona", "Olanzapina", "Quetiapina", "Aripiprazol", "Haloperidol"],
        "medical_specialty": "Psiquiatria",
    },
    "Transtorno do déficit de atenção com hiperatividade": {
        "icd10": "F90.9",
        "symptoms": ["Desatenção", "Hiperatividade", "Impulsividade", "Desorganização", "Esquecimento"],
        "medications": ["Metilfenidato", "Anfetamina", "Atomoxetina", "Guanfacina", "Clonidina"],
        "medical_specialty": "Psiquiatria",
    },
    "Transtorno do espectro autista": {
        "icd10": "F84.0",
        "symptoms": ["Comprometimento social", "Dificuldades de comunicação", "Comportamentos repetitivos", "Sensibilidades sensoriais", "Interesses restritos"],
        "medications": ["Risperidona", "Aripiprazol", "ISRSs", "Estimulantes", "Anticonvulsivantes"],
        "medical_specialty": "Psiquiatria",
    },
    "Doença de Crohn": {
        "icd10": "K50.90",
        "symptoms": ["Dor abdominal", "Diarréia", "Perda de peso", "Fadiga", "Sangue nas fezes"],
        "medications": ["Mesalazina", "Prednisona", "Azatioprina", "Infliximabe", "Adalimumabe"],
        "medical_specialty": "Gastroenterologia",
    },
    "Colite ulcerativa": {
        "icd10": "K51.90",
        "symptoms": ["Diarréia sanguinolenta", "Dor abdominal", "Urgência", "Perda de peso", "Fadiga"],
        "medications": ["Mesalazina", "Prednisona", "Azatioprina", "Infliximabe", "Vedolizumabe"],
        "medical_specialty": "Gastroenterologia",
    },
    "Síndrome do intestino irritável": {
        "icd10": "K58.9",
        "symptoms": ["Dor abdominal", "Inchaço", "Diarréia", "Constipação", "Gases"],
        "medications": ["Loperamida", "Lubiprostona", "Linaclotida", "Diclominas", "Rifaximina"],
        "medical_specialty": "Gastroenterologia",
    },
    "Doença celíaca": {
        "icd10": "K90.0",
        "symptoms": ["Dor abdominal", "Diarréia", "Inchaço", "Fadiga", "Perda de peso"],
        "medications": ["Sem medicamentos", "Dieta sem glúten", "Suplementos vitamínicos", "Suplementos de ferro", "Probióticos"],
        "medical_specialty": "Gastroenterologia",
    },
    "Cirrose": {
        "icd10": "K74.60",
        "symptoms": ["Fadiga", "Icterícia", "Inchaço abdominal", "Confusão", "Equimoses fáceis"],
        "medications": ["Lactulose", "Propranolol", "Diuréticos", "Suplementos vitamínicos", "Antibióticos"],
        "medical_specialty": "Gastroenterologia",
    },
    "Hepatite C": {
        "icd10": "B18.2",
        "symptoms": ["Fadiga", "Icterícia", "Dor abdominal", "Perda de apetite", "Náusea"],
        "medications": ["Sofosbuvir", "Ledipasvir", "Glecaprevir", "Pibrentasvir", "Ribavirina"],
        "medical_specialty": "Gastroenterologia",
    },
    "HIV/AIDS": {
        "icd10": "B20",
        "symptoms": ["Febre", "Fadiga", "Perda de peso", "Linfonodos inchados", "Infecções recorrentes"],
        "medications": ["Tenofovir", "Emtricitabina", "Dolutegravir", "Efavirenz", "Ritonavir"],
        "medical_specialty": "Doenças Infecciosas",
    },
    "Tuberculose": {
        "icd10": "A15.0",
        "symptoms": ["Tosse", "Febre", "Suores noturnos", "Perda de peso", "Dor no peito"],
        "medications": ["Isoniazida", "Rifampicina", "Pirazinamida", "Etambutol", "Estreptomicina"],
        "medical_specialty": "Pneumologia",
    },
    "Sepse": {
        "icd10": "A41.9",
        "symptoms": ["Febre", "Frequência cardíaca rápida", "Confusão", "Falta de ar", "Pressão arterial baixa"],
        "medications": ["Antibióticos de amplo espectro", "Líquidos intravenosos", "Vasopressores", "Corticosteroides", "Insulina"],
        "medical_specialty": "Cuidados Intensivos",
    },
    "Trombose venosa profunda": {
        "icd10": "I82.409",
        "symptoms": ["Dor na perna", "Inchaço", "Vermelhidão", "Calor", "Câimbras"],
        "medications": ["Heparina", "Varfarina", "Rivaroxabana", "Apixabana", "Enoxaparina"],
        "medical_specialty": "Medicina Vascular",
    },
    "Embolia pulmonar": {
        "icd10": "I26.99",
        "symptoms": ["Falta de ar", "Dor no peito", "Tosse", "Hemoptise", "Frequência cardíaca rápida"],
        "medications": ["Heparina", "Varfarina", "Rivaroxabana", "Apixabana", "Trombolíticos"],
        "medical_specialty": "Pneumologia",
    },
    "Aneurisma aórtico": {
        "icd10": "I71.9",
        "symptoms": ["Dor abdominal", "Dor nas costas", "Massa pulsátil", "Hipotensão", "Síncope"],
        "medications": ["Beta-bloqueadores", "Estatina", "Inibidores da ECA", "Antihipertensivos", "Analgésicos"],
        "medical_specialty": "Cirurgia Vascular",
    },
    "Doença valvular cardíaca": {
        "icd10": "I38",
        "symptoms": ["Falta de ar", "Fadiga", "Dor no peito", "Palpitações", "Edema"],
        "medications": ["Diuréticos", "Inibidores da ECA", "Beta-bloqueadores", "Anticoagulantes", "Vasodilatadores"],
        "medical_specialty": "Cardiologia",
    },
    "Cardiomiopatia": {
        "icd10": "I42.9",
        "symptoms": ["Fadiga", "Falta de ar", "Inchaço", "Batimento cardíaco irregular", "Dor no peito"],
        "medications": ["Inibidores da ECA", "Beta-bloqueadores", "Diuréticos", "Antagonistas da aldosterona", "Digoxina"],
        "medical_specialty": "Cardiologia",
    },
    "Endocardite": {
        "icd10": "I33.0",
        "symptoms": ["Febre", "Fadiga", "Falta de ar", "Suores noturnos", "Dor articular"],
        "medications": ["Penicilina", "Vancomicina", "Gentamicina", "Ampicilina", "Ceftriaxona"],
        "medical_specialty": "Cardiologia",
    },
    "Pericardite": {
        "icd10": "I30.9",
        "symptoms": ["Dor no peito", "Febre", "Fadiga", "Falta de ar", "Tosse"],
        "medications": ["Ibuprofeno", "Colchicina", "Prednisona", "Aspirina", "Antibióticos"],
        "medical_specialty": "Cardiologia",
    },
    "Infarto do miocárdio": {
        "icd10": "I21.9",
        "symptoms": ["Dor no peito", "Falta de ar", "Náusea", "Sudorese", "Tontura"],
        "medications": ["Aspirina", "Clopidogrel", "Heparina", "Beta-bloqueadores", "Inibidores da ECA"],
        "medical_specialty": "Cardiologia",
    },
    "Doença cardíaca congênita": {
        "icd10": "Q24.9",
        "symptoms": ["Cianose", "Falta de ar", "Fadiga", "Crescimento ruim", "Sopros cardíacos"],
        "medications": ["Diuréticos", "Inibidores da ECA", "Beta-bloqueadores", "Prostaglandina E1", "Antibióticos"],
        "medical_specialty": "Cardiologia",
    },
    "Neuropatia periférica": {
        "icd10": "G62.9",
        "symptoms": ["Dormência", "Formigamento", "Dor", "Fraqueza", "Sensação de queimação"],
        "medications": ["Gabapentina", "Pregabalina", "Duloxetina", "Amitriptilina", "Capsaicina"],
        "medical_specialty": "Neurologia",
    },
    "Apneia do sono": {
        "icd10": "G47.30",
        "symptoms": ["Ronco", "Sonolência diurna", "Fadiga", "Dores de cabeça matinais", "Irritabilidade"],
        "medications": ["Terapia CPAP", "Modafinil", "Armodafinil", "Acetazolamida", "Teofilina"],
        "medical_specialty": "Pneumologia",
    },
    "Narcolepsia": {
        "icd10": "G47.419",
        "symptoms": ["Sonolência diurna excessiva", "Cataplexia", "Paralisia do sono", "Alucinações", "Sono fragmentado"],
        "medications": ["Modafinil", "Oxibato de sódio", "Pitolisante", "Metilfenidato", "Anfetamina"],
        "medical_specialty": "Neurologia",
    },
    "Síndrome das pernas inquietas": {
        "icd10": "G25.81",
        "symptoms": ["Urgência para mover as pernas", "Sensações desconfortáveis", "Piora à noite", "Distúrbio do sono", "Alívio com movimento"],
        "medications": ["Pramipexol", "Ropinirol", "Gabapentina", "Suplementos de ferro", "Clonazepam"],
        "medical_specialty": "Neurologia",
    },
    "Fibromialgia": {
        "icd10": "M79.7",
        "symptoms": ["Dor generalizada", "Fadiga", "Distúrbios do sono", "Dificuldades cognitivas", "Dores de cabeça"],
        "medications": ["Duloxetina", "Pregabalina", "Milnaciprano", "Amitriptilina", "Cic lobenzaprina"],
        "medical_specialty": "Reumatologia",
    },
    "Lúpus": {
        "icd10": "M32.9",
        "symptoms": ["Fadiga", "Dor articular", "Erupção cutânea", "Febre", "Fotossensibilidade"],
        "medications": ["Hidroxicloroquina", "Prednisona", "Metotrexato", "Micofenolato", "Belimumabe"],
        "medical_specialty": "Reumatologia",
    },
    "Esclerodermia": {
        "icd10": "M34.9",
        "symptoms": ["Espessamento da pele", "Fenômeno de Raynaud", "Dor articular", "Falta de ar", "Problemas gastrointestinais"],
        "medications": ["Metotrexato", "Micofenolato", "Ciclofosfamida", "Nifedipina", "Inibidores da bomba de prótons"],
        "medical_specialty": "Reumatologia",
    },
    "Síndrome de Sjögren": {
        "icd10": "M35.00",
        "symptoms": ["Boca seca", "Olhos secos", "Fadiga", "Dor articular", "Glândulas salivares inchadas"],
        "medications": ["Pilocarpina", "Cevimelina", "Hidroxicloroquina", "Ciclosporina", "Lágrimas artificiais"],
        "medical_specialty": "Reumatologia",
    },
    "Psoríase": {
        "icd10": "L40.9",
        "symptoms": ["Placas vermelhas", "Coceira", "Escamação", "Pele espessada", "Dor articular"],
        "medications": ["Metotrexato", "Ciclosporina", "Adalimumabe", "Corticosteroides tópicos", "Análogos da vitamina D"],
        "medical_specialty": "Dermatologia",
    },
    "Eczema": {
        "icd10": "L30.9",
        "symptoms": ["Coceira", "Vermelhidão", "Pele seca", "Erupção cutânea", "Inchaço"],
        "medications": ["Hidrocortisona", "Tacrolimo", "Pimecrolimo", "Dupilumabe", "Hidratantes"],
        "medical_specialty": "Dermatologia",
    },
    "Rosácea": {
        "icd10": "L71.9",
        "symptoms": ["Vermelhidão facial", "Pústulas", "Vasos sanguíneos visíveis", "Irritação ocular", "Inchaço"],
        "medications": ["Metronidazol", "Ácido azelaico", "Ivermectina", "Doxiciclina", "Brimonidina"],
        "medical_specialty": "Dermatologia",
    },
    "Acne vulgar": {
        "icd10": "L70.0",
        "symptoms": ["Espinhas", "Cravos", "Espinhas brancas", "Cistos", "Cicatrizes"],
        "medications": ["Peróxido de benzoíla", "Ácido salicílico", "Retinoides", "Antibióticos", "Isotretinoína"],
        "medical_specialty": "Dermatologia",
    },
    "Melanoma": {
        "icd10": "C43.9",
        "symptoms": ["Pinta que muda", "Forma assimétrica", "Bordas irregulares", "Variação de cor", "Aumento de diâmetro"],
        "medications": ["Pembrolizumabe", "Nivolumabe", "Ipilimumabe", "Dacarbazina", "Trametinibe"],
        "medical_specialty": "Oncologia",
    },
    "Carcinoma basocelular": {
        "icd10": "C44.91",
        "symptoms": ["Protuberância perolada", "Ferida que não cicatriza", "Área semelhante a cicatriz", "Placa vermelha", "Sangramento"],
        "medications": ["Imiquimode", "Fluorouracila", "Vismodegibe", "Sonidegibe", "Terapia fotodinâmica"],
        "medical_specialty": "Dermatologia",
    },
    "Carcinoma de células escamosas": {
        "icd10": "C44.92",
        "symptoms": ["Placa vermelha áspera", "Ferida aberta", "Superfície crostosa", "Crescimento com depressão central", "Coceira"],
        "medications": ["Fluorouracila", "Imiquimode", "Pembrolizumabe", "Cemiplimabe", "Quimioterapia"],
        "medical_specialty": "Dermatologia",
    },
    "Leucemia": {
        "icd10": "C95.90",
        "symptoms": ["Fadiga", "Febre", "Perda de peso", "Equimoses fáceis", "Infecções recorrentes"],
        "medications": ["Imatinibe", "Citarabina", "Daunorrubicina", "Vincristina", "Hidroxiureia"],
        "medical_specialty": "Hematologia",
    },
    "Linfoma": {
        "icd10": "C85.90",
        "symptoms": ["Linfonodos inchados", "Febre", "Suores noturnos", "Perda de peso", "Fadiga"],
        "medications": ["Rituximabe", "Ciclofosfamida", "Doxorrubicina", "Vincristina", "Prednisona"],
        "medical_specialty": "Oncologia",
    },
    "Mieloma": {
        "icd10": "C90.00",
        "symptoms": ["Dor óssea", "Fadiga", "Anemia", "Infecções recorrentes", "Problemas renais"],
        "medications": ["Bortezomibe", "Lenalidomida", "Dexametasona", "Daratumumabe", "Melfalano"],
        "medical_specialty": "Hematologia",
    },
    "Câncer de cólon": {
        "icd10": "C18.9",
        "symptoms": ["Dor abdominal", "Sangue nas fezes", "Alteração nos hábitos intestinais", "Perda de peso", "Fadiga"],
        "medications": ["Fluorouracila", "Oxaliplatina", "Capecitabina", "Bevacizumabe", "Cetuximabe"],
        "medical_specialty": "Oncologia",
    },
    "Câncer pancreático": {
        "icd10": "C25.9",
        "symptoms": ["Dor abdominal", "Icterícia", "Perda de peso", "Perda de apetite", "Náusea"],
        "medications": ["Gemcitabina", "Paclitaxel", "Erlotinibe", "FOLFIRINOX", "Capecitabina"],
        "medical_specialty": "Oncologia",
    },
    "Câncer renal": {
        "icd10": "C64.9",
        "symptoms": ["Sangue na urina", "Dor nas costas", "Perda de peso", "Fadiga", "Febre"],
        "medications": ["Sunitinibe", "Pazopanibe", "Axitinibe", "Nivolumabe", "Cabozantinibe"],
        "medical_specialty": "Oncologia",
    },
    "Câncer de bexiga": {
        "icd10": "C67.9",
        "symptoms": ["Sangue na urina", "Micção frequente", "Dor ao urinar", "Dor nas costas", "Dor pélvica"],
        "medications": ["BCG", "Mitomicina", "Gemcitabina", "Cisplatina", "Pembrolizumabe"],
        "medical_specialty": "Urologia",
    },
    "Câncer ovariano": {
        "icd10": "C56.9",
        "symptoms": ["Inchaço abdominal", "Dor pélvica", "Perda de apetite", "Micção frequente", "Fadiga"],
        "medications": ["Carboplatina", "Paclitaxel", "Bevacizumabe", "Olaparibe", "Doxorrubicina"],
        "medical_specialty": "Oncologia",
    },
    "Câncer endometrial": {
        "icd10": "C54.1",
        "symptoms": ["Sangramento vaginal anormal", "Dor pélvica", "Perda de peso", "Fadiga", "Inchaço"],
        "medications": ["Progesterona", "Tamoxifeno", "Carboplatina", "Paclitaxel", "Doxorrubicina"],
        "medical_specialty": "Oncologia",
    },
    "Câncer de tireoide": {
        "icd10": "C73",
        "symptoms": ["Nódulo no pescoço", "Rouquidão", "Dificuldade para engolir", "Dor no pescoço", "Linfonodos inchados"],
        "medications": ["Levotiroxina", "Iodo radioativo", "Sorafenibe", "Lenvatinibe", "Cabozantinibe"],
        "medical_specialty": "Endocrinologia",
    },
    "Tumor cerebral": {
        "icd10": "C71.9",
        "symptoms": ["Dores de cabeça", "Convulsões", "Náusea", "Alterações na visão", "Comprometimento cognitivo"],
        "medications": ["Temozolomida", "Bevacizumabe", "Carmustina", "Lomustina", "Dexametasona"],
        "medical_specialty": "Neurologia",
    },
    "Glaucoma": {
        "icd10": "H40.9",
        "symptoms": ["Perda de visão", "Dor ocular", "Halos ao redor das luzes", "Olhos vermelhos", "Náusea"],
        "medications": ["Timolol", "Latanoprosta", "Brimonidina", "Acetazolamida", "Pilocarpina"],
        "medical_specialty": "Oftalmologia",
    },
    "Degeneração macular": {
        "icd10": "H35.30",
        "symptoms": ["Visão turva", "Perda da visão central", "Visão distorcida", "Manchas escuras", "Desbotamento de cores"],
        "medications": ["Ranibizumabe", "Aflibercepte", "Bevacizumabe", "Verteporfina", "Suplementos vitamínicos"],
        "medical_specialty": "Oftalmologia",
    },
    "Catarata": {
        "icd10": "H26.9",
        "symptoms": ["Visão turva", "Sensibilidade ao brilho", "Visão noturna ruim", "Cores desbotadas", "Visão dupla"],
        "medications": ["Sem medicamentos", "Cirurgia", "Óculos", "Lentes anti-reflexo", "Ampliadores"],
        "medical_specialty": "Oftalmologia",
    },
    "Retinopatia diabética": {
        "icd10": "E11.319",
        "symptoms": ["Visão turva", "Moscas volantes", "Perda de visão", "Alterações de cor", "Áreas escuras"],
        "medications": ["Ranibizumabe", "Aflibercepte", "Bevacizumabe", "Terapia a laser", "Vitrectomia"],
        "medical_specialty": "Oftalmologia",
    },
    "Perda auditiva": {
        "icd10": "H91.90",
        "symptoms": ["Dificuldade para ouvir", "Sons abafados", "Zumbido", "Dor de ouvido", "Problemas de equilíbrio"],
        "medications": ["Sem medicamentos", "Aparelhos auditivos", "Implantes cocleares", "Esteroides", "Antibióticos"],
        "medical_specialty": "Otorrinolaringologia",
    },
    "Doença de Ménière": {
        "icd10": "H81.09",
        "symptoms": ["Vertigem", "Perda auditiva", "Zumbido", "Sensação de plenitude no ouvido", "Náusea"],
        "medications": ["Meclizina", "Diuréticos", "Beta-histina", "Esteroides", "Gentamicina"],
        "medical_specialty": "Otorrinolaringologia",
    },
    "Hiperplasia prostática benigna": {
        "icd10": "N40.0",
        "symptoms": ["Micção frequente", "Jato fraco", "Urgência", "Noctúria", "Esvaziamento incompleto"],
        "medications": ["Tansulosina", "Finasterida", "Dutasterida", "Terazosina", "Sildenafila"],
        "medical_specialty": "Urologia",
    },
    "Disfunção erétil": {
        "icd10": "N52.9",
        "symptoms": ["Incapacidade de manter ereção", "Libido reduzida", "Ejaculação precoce", "Estresse", "Fadiga"],
        "medications": ["Sildenafila", "Tadalafila", "Vardenafila", "Alprostadil", "Testosterona"],
        "medical_specialty": "Urologia",
    },
    "Síndrome do ovário policístico": {
        "icd10": "E28.2",
        "symptoms": ["Períodos irregulares", "Crescimento excessivo de pelos", "Acne", "Ganho de peso", "Infertilidade"],
        "medications": ["Anticoncepcionais orais combinados", "Metformina", "Espironolactona", "Clomifeno", "Letrozol"],
        "medical_specialty": "Endocrinologia",
    },
    "Endometriose": {
        "icd10": "N80.9",
        "symptoms": ["Dor pélvica", "Dismenorreia", "Infertilidade", "Dor durante relação sexual", "Períodos pesados"],
        "medications": ["Ibuprofeno", "Anticoncepcionais orais combinados", "Progestagênios", "Agonistas GnRH", "Danazol"],
        "medical_specialty": "Ginecologia",
    },
    "Fibroides uterinos": {
        "icd10": "D25.9",
        "symptoms": ["Sangramento menstrual pesado", "Dor pélvica", "Micção frequente", "Constipação", "Dor nas costas"],
        "medications": ["Agonistas GnRH", "Progestagênios", "Ácido tranexâmico", "Ibuprofeno", "Acetato de ulipristal"],
        "medical_specialty": "Ginecologia",
    },
    "Pré-eclâmpsia": {
        "icd10": "O14.90",
        "symptoms": ["Pressão arterial alta", "Proteinúria", "Inchaço", "Dor de cabeça", "Alterações na visão"],
        "medications": ["Sulfato de magnésio", "Labetalol", "Hidralazina", "Nifedipina", "Parto"],
        "medical_specialty": "Obstetrícia",
    },
    "Diabetes gestacional": {
        "icd10": "O24.419",
        "symptoms": ["Sede aumentada", "Micção frequente", "Fadiga", "Visão turva", "Náusea"],
        "medications": ["Insulina", "Metformina", "Gliburida", "Controle dietético", "Exercício"],
        "medical_specialty": "Obstetrícia",
    },
    "Deficiência de vitamina D": {
        "icd10": "E55.9",
        "symptoms": ["Fadiga", "Dor óssea", "Fraqueza muscular", "Depressão", "Queda de cabelo"],
        "medications": ["Suplementos de vitamina D", "Colecalciferol", "Ergocalciferol", "Suplementos de cálcio", "Exposição solar"],
        "medical_specialty": "Endocrinologia",
    },
    "Anemia por deficiência de ferro": {
        "icd10": "D50.9",
        "symptoms": ["Fadiga", "Pele pálida", "Falta de ar", "Tontura", "Mãos frias"],
        "medications": ["Sulfato ferroso", "Gliconato ferroso", "Infusões de ferro", "Vitamina C", "Ácido fólico"],
        "medical_specialty": "Hematologia",
    },
    "Anemia perniciosa": {
        "icd10": "D51.0",
        "symptoms": ["Fadiga", "Fraqueza", "Pele pálida", "Dormência", "Alterações cognitivas"],
        "medications": ["Injeções de vitamina B12", "Suplementos orais de B12", "Ácido fólico", "Suplementos de ferro", "Eritropoietina"],
        "medical_specialty": "Hematologia",
    },
    "Doença falciforme": {
        "icd10": "D57.1",
        "symptoms": ["Crises de dor", "Anemia", "Fadiga", "Icterícia", "Inchaço"],
        "medications": ["Hidroxiureia", "Analgésicos", "Antibióticos", "Transfusões de sangue", "Voxelotor"],
        "medical_specialty": "Hematologia",
    },
    "Hemofilia": {
        "icd10": "D68.311",
        "symptoms": ["Sangramento prolongado", "Dor articular", "Equimoses", "Hemartrose", "Sangramento nasal"],
        "medications": ["Fator VIII", "Fator IX", "Desmopressina", "Antifibrinolíticos", "Emicizumabe"],
        "medical_specialty": "Hematologia",
    },
    "Trombocitopenia": {
        "icd10": "D69.6",
        "symptoms": ["Equimoses", "Sangramento gengival", "Sangramento nasal", "Petéquias", "Períodos pesados"],
        "medications": ["Corticosteroides", "IVIG", "Romiplostim", "Eltrombopag", "Esplenectomia"],
        "medical_specialty": "Hematologia",
    },
    "Leucopenia": {
        "icd10": "D72.819",
        "symptoms": ["Infecções frequentes", "Febre", "Fadiga", "Úlceras bucais", "Dor de garganta"],
        "medications": ["G-CSF", "GM-CSF", "Antibióticos", "Antivirals", "Suplementos vitamínicos"],
        "medical_specialty": "Hematologia",
    },
    "Diverticulite": {
        "icd10": "K57.92",
        "symptoms": ["Dor abdominal", "Febre", "Náusea", "Constipação", "Diarréia"],
        "medications": ["Ciprofloxacino", "Metronidazol", "Amoxicilina-clavulanato", "Ibuprofeno", "Paracetamol"],
        "medical_specialty": "Gastroenterologia",
    },
    "Apendicite": {
        "icd10": "K35.80",
        "symptoms": ["Dor abdominal", "Náusea", "Vômito", "Febre", "Perda de apetite"],
        "medications": ["Antibióticos", "Analgésicos", "Líquidos intravenosos", "Cirurgia", "Anti-náusea"],
        "medical_specialty": "Cirurgia Geral",
    },
    "Colecistite": {
        "icd10": "K81.0",
        "symptoms": ["Dor abdominal", "Náusea", "Vômito", "Febre", "Icterícia"],
        "medications": ["Antibióticos", "Analgésicos", "Ursodiol", "Líquidos intravenosos", "Cirurgia"],
        "medical_specialty": "Cirurgia Geral",
    },
    "Pancreatite": {
        "icd10": "K85.90",
        "symptoms": ["Dor abdominal", "Náusea", "Vômito", "Febre", "Pulso rápido"],
        "medications": ["Líquidos intravenosos", "Analgésicos", "Antibióticos", "Suplementos enzimáticos", "Insulina"],
        "medical_specialty": "Gastroenterologia",
    },
    "Doença ulcerosa péptica": {
        "icd10": "K27.9",
        "symptoms": ["Dor abdominal", "Inchaço", "Náusea", "Vômito", "Azia"],
        "medications": ["Omeprazol", "Ranitidina", "Amoxicilina", "Claritromicina", "Sucralfato"],
        "medical_specialty": "Gastroenterologia",
    },
    "Gastrite": {
        "icd10": "K29.70",
        "symptoms": ["Dor abdominal", "Náusea", "Vômito", "Inchaço", "Perda de apetite"],
        "medications": ["Omeprazol", "Ranitidina", "Antiácidos", "Sucralfato", "Antibióticos"],
        "medical_specialty": "Gastroenterologia",
    },
    "Esofagite": {
        "icd10": "K20.90",
        "symptoms": ["Azia", "Dificuldade para engolir", "Dor no peito", "Regurgitação", "Náusea"],
        "medications": ["Omeprazol", "Ranitidina", "Sucralfato", "Antiácidos", "Procinéticos"],
        "medical_specialty": "Gastroenterologia",
    },
    "Esôfago de Barrett": {
        "icd10": "K22.70",
        "symptoms": ["Azia", "Regurgitação", "Dificuldade para engolir", "Dor no peito", "Náusea"],
        "medications": ["Omeprazol", "Esomeprazol", "Antiácidos", "Bloqueadores H2", "Inibidores da bomba de prótons"],
        "medical_specialty": "Gastroenterologia",
    },
    "Hérnia hiatal": {
        "icd10": "K44.9",
        "symptoms": ["Azia", "Dor no peito", "Dificuldade para engolir", "Regurgitação", "Inchaço"],
        "medications": ["Antiácidos", "Bloqueadores H2", "Inibidores da bomba de prótons", "Procinéticos", "Cirurgia"],
        "medical_specialty": "Gastroenterologia",
    },
    "Hemorroidas": {
        "icd10": "K64.9",
        "symptoms": ["Sangramento retal", "Coceira", "Dor", "Inchaço", "Desconforto"],
        "medications": ["Hidrocortisona", "Hamamélis", "Lidocaína", "Abrandadores de fezes", "Suplementos de fibra"],
        "medical_specialty": "Gastroenterologia",
    },
    "Fissura anal": {
        "icd10": "K60.2",
        "symptoms": ["Dor durante evacuações", "Sangramento", "Coceira", "Espasmos", "Constipação"],
        "medications": ["Pomada de nitroglicerina", "Diltiazem", "Toxina botulínica", "Abrandadores de fezes", "Analgésicos"],
        "medical_specialty": "Gastroenterologia",
    },
    "Incontinência fecal": {
        "icd10": "R15.9",
        "symptoms": ["Evacuações involuntárias", "Urgência", "Vazamento", "Diarréia", "Constipação"],
        "medications": ["Loperamida", "Subsalicilato de bismuto", "Suplementos de fibra", "Antidiarréicos", "Colestiramina"],
        "medical_specialty": "Gastroenterologia",
    },
    "Lesão renal aguda": {
        "icd10": "N17.9",
        "symptoms": ["Diminuição da produção de urina", "Inchaço", "Fadiga", "Náusea", "Confusão"],
        "medications": ["Diuréticos", "Líquidos intravenosos", "Diálise", "Gerenciamento de eletrólitos", "Vasopressores"],
        "medical_specialty": "Nefrologia",
    },
    "Síndrome nefrótica": {
        "icd10": "N04.9",
        "symptoms": ["Edema", "Proteinúria", "Hipoalbuminemia", "Hiperlipidemia", "Fadiga"],
        "medications": ["Inibidores da ECA", "Diuréticos", "Estatina", "Corticosteroides", "Imunossupressores"],
        "medical_specialty": "Nefrologia",
    },
    "Doença renal policística": {
        "icd10": "Q61.3",
        "symptoms": ["Dor abdominal", "Hipertensão", "Hematúria", "Dor nas costas", "Infecções frequentes"],
        "medications": ["Inibidores da ECA", "Diuréticos", "Analgésicos", "Antibióticos", "Tolvaptana"],
        "medical_specialty": "Nefrologia",
    },
    "Cálculos renais": {
        "icd10": "N20.0",
        "symptoms": ["Dor severa", "Hematúria", "Náusea", "Vômito", "Micção frequente"],
        "medications": ["Analgésicos", "Bloqueadores alfa", "Alopurinol", "Citrato de potássio", "Tiazidas"],
        "medical_specialty": "Urologia",
    },
    "Cistite intersticial": {
        "icd10": "N30.10",
        "symptoms": ["Dor na bexiga", "Urgência", "Frequência", "Dor pélvica", "Noctúria"],
        "medications": ["Polissulfato de pentosano", "Amitriptilina", "Hidroxizina", "Antihistamínicos", "Instilações na bexiga"],
        "medical_specialty": "Urologia",
    },
    "Bexiga hiperativa": {
        "icd10": "N32.81",
        "symptoms": ["Urgência", "Frequência", "Noctúria", "Incontinência", "Espasmos na bexiga"],
        "medications": ["Oxibutinina", "Tolterodina", "Mirabegrona", "Solifenacina", "Darifenacina"],
        "medical_specialty": "Urologia",
    },
    "Incontinência de esforço": {
        "icd10": "N39.3",
        "symptoms": ["Vazamento de urina ao tossir", "Espirrar", "Exercício", "Levantar", "Rir"],
        "medications": ["Duloxetina", "Creme de estrogênio", "Sem medicamentos", "Exercícios do assoalho pélvico", "Cirurgia"],
        "medical_specialty": "Urologia",
    },
    "Incontinência de urgência": {
        "icd10": "N39.41",
        "symptoms": ["Urgência súbita para urinar", "Vazamento involuntário", "Frequência", "Noctúria", "Espasmos na bexiga"],
        "medications": ["Oxibutinina", "Tolterodina", "Mirabegrona", "Solifenacina", "Toxina botulínica"],
        "medical_specialty": "Urologia",
    },
    "Pielonefrite": {
        "icd10": "N10",
        "symptoms": ["Febre", "Dor no flanco", "Náusea", "Vômito", "Micção frequente"],
        "medications": ["Ciprofloxacino", "Ceftriaxona", "Amoxicilina", "Trimetoprim", "Nitrofurantoína"],
        "medical_specialty": "Nefrologia",
    },
    "Glomerulonefrite": {
        "icd10": "N05.9",
        "symptoms": ["Hematúria", "Proteinúria", "Edema", "Hipertensão", "Fadiga"],
        "medications": ["Corticosteroides", "Imunossupressores", "Inibidores da ECA", "Diuréticos", "Plasmaférese"],
        "medical_specialty": "Nefrologia",
    },
    "Sinusite aguda": {
        "icd10": "J01.90",
        "symptoms": ["Dor facial", "Congestão nasal", "Dor de cabeça", "Febre", "Tosse"],
        "medications": ["Amoxicilina", "Amoxicilina-clavulanato", "Descongestionantes", "Esteroides nasais", "Analgésicos"],
        "medical_specialty": "Otorrinolaringologia",
    },
    "Sinusite crônica": {
        "icd10": "J32.9",
        "symptoms": ["Congestão nasal", "Pressão facial", "Gotejamento pós-nasal", "Dor de cabeça", "Fadiga"],
        "medications": ["Esteroides nasais", "Antibióticos", "Irrigação salina", "Descongestionantes", "Cirurgia"],
        "medical_specialty": "Otorrinolaringologia",
    },
    "Rinite alérgica": {
        "icd10": "J30.9",
        "symptoms": ["Espirros", "Nariz escorrendo", "Olhos coçando", "Congestão", "Gotejamento pós-nasal"],
        "medications": ["Loratadina", "Cetirizina", "Fluticasona", "Montelucaste", "Azitromicina"],
        "medical_specialty": "Alergologia",
    },
    "Otite média": {
        "icd10": "H66.90",
        "symptoms": ["Dor de ouvido", "Febre", "Perda auditiva", "Drenagem de fluido", "Irritabilidade"],
        "medications": ["Amoxicilina", "Azitromicina", "Ibuprofeno", "Paracetamol", "Descongestionantes"],
        "medical_specialty": "Otorrinolaringologia",
    },
    "Otite externa": {
        "icd10": "H60.90",
        "symptoms": ["Dor de ouvido", "Coceira", "Vermelhidão", "Inchaço", "Descarga"],
        "medications": ["Ciprofloxacino", "Hidrocortisona", "Neomicina", "Ácido acético", "Analgésicos"],
        "medical_specialty": "Otorrinolaringologia",
    },
    "Faringite": {
        "icd10": "J02.9",
        "symptoms": ["Dor de garganta", "Febre", "Linfonodos inchados", "Dor de cabeça", "Tosse"],
        "medications": ["Penicilina", "Amoxicilina", "Azitromicina", "Ibuprofeno", "Paracetamol"],
        "medical_specialty": "Otorrinolaringologia",
    },
    "Amigdalite": {
        "icd10": "J03.90",
        "symptoms": ["Dor de garganta", "Febre", "Amígdalas inchadas", "Dificuldade para engolir", "Dor de cabeça"],
        "medications": ["Penicilina", "Amoxicilina", "Azitromicina", "Ibuprofeno", "Paracetamol"],
        "medical_specialty": "Otorrinolaringologia",
    },
    "Laringite": {
        "icd10": "J04.0",
        "symptoms": ["Rouquidão", "Dor de garganta", "Tosse", "Dificuldade para falar", "Febre"],
        "medications": ["Ibuprofeno", "Paracetamol", "Inalação de vapor", "Repouso vocal", "Antibióticos"],
        "medical_specialty": "Otorrinolaringologia",
    },
    "Crupe": {
        "icd10": "J05.0",
        "symptoms": ["Tosse latindo", "Estridor", "Rouquidão", "Febre", "Distúrbio respiratório"],
        "medications": ["Dexametasona", "Epinefrina", "Ar umidificado", "Ibuprofeno", "Paracetamol"],
        "medical_specialty": "Pediatria",
    },
    "Bronquiolite": {
        "icd10": "J21.9",
        "symptoms": ["Tosse", "Sibilo", "Falta de ar", "Febre", "Nariz escorrendo"],
        "medications": ["Cuidados de suporte", "Oxigênio", "Hidratação", "Salbutamol", "Corticosteroides"],
        "medical_specialty": "Pediatria",
    },
    "Enfisema": {
        "icd10": "J43.9",
        "symptoms": ["Falta de ar", "Tosse crônica", "Sibilo", "Fadiga", "Perda de peso"],
        "medications": ["Broncodilatadores", "Esteroides inalados", "Terapia de oxigênio", "Antibióticos", "Reabilitação pulmonar"],
        "medical_specialty": "Pneumologia",
    },
    "Fibrose cística": {
        "icd10": "E84.9",
        "symptoms": ["Tosse persistente", "Sibilo", "Infecções recorrentes", "Crescimento ruim", "Pele salgada"],
        "medications": ["Ivacaftor", "Lumacaftor", "Dornase alfa", "Enzimas pancreáticas", "Antibióticos"],
        "medical_specialty": "Pneumologia",
    },
    "Doença pulmonar intersticial": {
        "icd10": "J84.9",
        "symptoms": ["Falta de ar", "Tosse seca", "Fadiga", "Perda de peso", "Desconforto no peito"],
        "medications": ["Prednisona", "Azatioprina", "Nintedanibe", "Pirfenidona", "Terapia de oxigênio"],
        "medical_specialty": "Pneumologia",
    },
    "Sarcoidose": {
        "icd10": "D86.9",
        "symptoms": ["Fadiga", "Tosse", "Falta de ar", "Erupção cutânea", "Dor articular"],
        "medications": ["Prednisona", "Metotrexato", "Hidroxicloroquina", "Infliximabe", "Azatioprina"],
        "medical_specialty": "Pneumologia",
    },
    "Derrame pleural": {
        "icd10": "J90",
        "symptoms": ["Falta de ar", "Dor no peito", "Tosse", "Febre", "Perda de peso"],
        "medications": ["Diuréticos", "Antibióticos", "Corticosteroides", "Quimioterapia", "Toracocentese"],
        "medical_specialty": "Pneumologia",
    },
    "Pneumotórax": {
        "icd10": "J93.9",
        "symptoms": ["Dor no peito", "Falta de ar", "Frequência cardíaca rápida", "Cianose", "Sons respiratórios diminuídos"],
        "medications": ["Oxigênio", "Analgésicos", "Tubo torácico", "Cirurgia", "Pleurodese"],
        "medical_specialty": "Pneumologia",
    },
    "Hipertensão pulmonar": {
        "icd10": "I27.20",
        "symptoms": ["Falta de ar", "Fadiga", "Dor no peito", "Tontura", "Inchaço"],
        "medications": ["Sildenafila", "Bosentana", "Epoprostenol", "Treprostinil", "Riociguat"],
        "medical_specialty": "Pneumologia",
    },
    "Diabetes mellitus tipo 1": {
        "icd10": "E10.9",
        "symptoms": ["Sede aumentada", "Micção frequente", "Fome extrema", "Perda de peso inexplicada", "Fadiga"],
        "medications": ["Insulina", "Pramlintida", "Metformina", "Empagliflozina", "Liraglutida"],
        "medical_specialty": "Endocrinologia",
    },
    "Doença hepática crônica": {
        "icd10": "K76.9",
        "symptoms": ["Fadiga", "Icterícia", "Dor abdominal", "Inchaço nas pernas", "Coceira"],
        "medications": ["Diuréticos", "Beta-bloqueadores", "Ursodiol", "Antivirals", "Imunossupressores"],
        "medical_specialty": "Gastroenterologia",
    },
    "Doença cardíaca hipertensiva": {
        "icd10": "I11.9",
        "symptoms": ["Falta de ar", "Fadiga", "Dor no peito", "Palpitações", "Tontura"],
        "medications": ["Lisinopril", "Metoprolol", "Hidroclorotiazida", "Anlodipina", "Losartana"],
        "medical_specialty": "Cardiologia",
    },
    "Transtorno de estresse pós-traumático": {
        "icd10": "F43.1",
        "symptoms": ["Flashbacks", "Pesadelos", "Ansiedade severa", "Comportamentos de evitação", "Hipervigilância"],
        "medications": ["Sertralina", "Paroxetina", "Venlafaxina", "Prazosina", "Clonidina"],
        "medical_specialty": "Psiquiatria",
    },
    "Transtorno por uso de substâncias": {
        "icd10": "F19.9",
        "symptoms": ["Desejos", "Perda de controle", "Tolerância", "Sintomas de abstinência", "Negligência de responsabilidades"],
        "medications": ["Naltrexona", "Acamprosato", "Dissulfiram", "Metadona", "Buprenorfina"],
        "medical_specialty": "Psiquiatria",
    },
    "Síndrome da dor crônica": {
        "icd10": "G89.4",
        "symptoms": ["Dor persistente", "Fadiga", "Distúrbio do sono", "Depressão", "Mobilidade reduzida"],
        "medications": ["Gabapentina", "Duloxetina", "Tramadol", "Amitriptilina", "Ibuprofeno"],
        "medical_specialty": "Medicina da Dor",
    },
    "Transtorno convulsivo": {
        "icd10": "G40.909",
        "symptoms": ["Convulsões", "Perda de consciência", "Convulsões", "Confusão", "Movimentos incontrolados"],
        "medications": ["Levetiracetam", "Ácido valproico", "Carbamazepina", "Lamotrigina", "Topiramato"],
        "medical_specialty": "Neurologia",
    },
}
