"""Display labels for the locale-neutral clinical values (zh_CN).

Words only: the numbers, units and reference intervals live once in
`faker_healthcare/clinical_values.py` and are never translated. The key set must match
the base catalogue exactly (`faker_healthcare/clinical_labels.py`); see
`tests/test_locales.py::TestClinicalLabelParity`, which also re-runs the Japanese-kana
check over these labels — a katakana drug name once reached the Simplified Chinese
catalogue that way.

本模块有两个字典：`CLINICAL_LABELS`（检验项目与生命体征名称、结果标记、饮酒分级、给药途径、
用药频次、用药状态、量表严重程度分级）与 `MEDICATION_NAMES`——把中性的药物标识映射到本目录
所用的确切写法，使同一份剂量表可以服务于六种语言。
"""

CLINICAL_LABELS: dict[str, str] = {
    # 生命体征
    "systolic_bp": "收缩压",
    "diastolic_bp": "舒张压",
    "heart_rate": "心率",
    "respiratory_rate": "呼吸频率",
    "temperature_c": "体温",
    "oxygen_saturation": "血氧饱和度",
    # 血液学
    "haemoglobin": "血红蛋白",
    "wbc": "白细胞计数",
    "platelets": "血小板计数",
    "ferritin": "铁蛋白",
    "inr": "国际标准化比值 (INR)",
    # 肾功能
    "sodium": "血钠",
    "potassium": "血钾",
    "urea": "尿素",
    "creatinine": "肌酐",
    "egfr": "估算肾小球滤过率 (eGFR)",
    # 肝功能
    "alt": "丙氨酸氨基转移酶 (ALT)",
    "ast": "天门冬氨酸氨基转移酶 (AST)",
    "alkaline_phosphatase": "碱性磷酸酶",
    "bilirubin_total": "总胆红素",
    "albumin": "白蛋白",
    # 代谢
    "fasting_glucose": "空腹血糖",
    "hba1c": "糖化血红蛋白 (HbA1c)",
    # 甲状腺
    "tsh": "促甲状腺激素 (TSH)",
    "free_t4": "游离甲状腺素 (FT4)",
    # 血脂
    "total_cholesterol": "总胆固醇",
    "ldl": "低密度脂蛋白胆固醇 (LDL-C)",
    "hdl": "高密度脂蛋白胆固醇 (HDL-C)",
    "triglycerides": "甘油三酯",
    # 炎症标志物
    "crp": "C反应蛋白 (CRP)",
    # 结果标记
    "flag_low": "偏低",
    "flag_normal": "正常",
    "flag_high": "偏高",
    # 每周饮酒量
    "alcohol_none": "不饮酒",
    "alcohol_low_risk": "低风险",
    "alcohol_increasing_risk": "风险增加",
    "alcohol_higher_risk": "高风险",
    # 给药途径
    "route_oral": "口服",
    "route_intravenous": "静脉注射",
    "route_subcutaneous": "皮下注射",
    "route_inhaled": "吸入",
    "route_sublingual": "舌下含服",
    "route_ophthalmic": "滴眼",
    # 用药频次
    "frequency_once_daily": "每日一次",
    "frequency_twice_daily": "每日两次",
    "frequency_three_times_daily": "每日三次",
    "frequency_four_times_daily": "每日四次",
    "frequency_at_night": "睡前",
    "frequency_as_required": "必要时",
    "frequency_once_weekly": "每周一次",
    "frequency_every_three_weeks": "每三周一次",
    # 用药状态
    "medication_status_past": "既往用药",
    "medication_status_current": "当前用药",
    "medication_status_future": "计划用药",
    # 评估量表严重程度分级
    "assessment_minimal": "极轻微",
    "assessment_mild": "轻度",
    "assessment_moderate": "中度",
    "assessment_moderately_severe": "中重度",
    "assessment_severe": "重度",
    "assessment_symptoms_absent": "无症状",
    "assessment_normal_cognition": "认知正常",
    "assessment_screen_negative": "筛查阴性",
    "assessment_screen_positive": "筛查阳性",
    "alcohol_possible_dependence": "可能存在依赖",
}

# `medication_order()` 能给出剂量的药物，名称与本目录一致。
MEDICATION_NAMES: dict[str, str] = {
    "acamprosate": "阿坎普罗斯",
    "acetaminophen": "对乙酰氨基酚",
    "acyclovir": "阿昔洛韦",
    "albuterol": "沙丁胺醇",
    "alendronate": "阿仑膦酸盐",
    "allopurinol": "别嘌呤醇",
    "alprazolam": "阿普唑仑",
    "amitriptyline": "阿米替林",
    "amlodipine": "氨氯地平",
    "amoxicillin": "阿莫西林",
    "anastrozole": "阿那曲唑",
    "apixaban": "阿哌沙班",
    "aripiprazole": "阿立哌唑",
    "aspirin": "阿司匹林",
    "atomoxetine": "阿托莫西汀",
    "atorvastatin": "阿托伐他汀",
    "azathioprine": "硫唑嘌呤",
    "azithromycin": "阿奇霉素",
    "bicalutamide": "比卡鲁胺",
    "budesonide": "布地奈德",
    "buprenorphine": "丁丙诺啡",
    "bupropion": "安非他酮",
    "buspirone": "丁螺环酮",
    "calcium_carbonate": "碳酸钙",
    "carbamazepine": "卡马西平",
    "ceftriaxone": "头孢曲松",
    "cefuroxime": "头孢呋辛",
    "cephalexin": "头孢氨苄",
    "cetirizine": "西替利嗪",
    "cholecalciferol": "胆钙化醇",
    "cilostazol": "西洛他唑",
    "ciprofloxacin": "环丙沙星",
    "clarithromycin": "克拉霉素",
    "clindamycin": "克林霉素",
    "clopidogrel": "氯吡格雷",
    "colchicine": "秋水仙碱",
    "dexamethasone": "地塞米松",
    "digoxin": "地高辛",
    "diltiazem": "地尔硫卓",
    "donepezil": "多奈哌齐",
    "doxycycline": "多西环素",
    "duloxetine": "度洛西汀",
    "dutasteride": "度他雄胺",
    "empagliflozin": "恩格列净",
    "enoxaparin": "依诺肝素",
    "escitalopram": "艾司西酞普兰",
    "esomeprazole": "埃索美拉唑",
    "famotidine": "法莫替丁",
    "febuxostat": "非布司他",
    "ferrous_sulfate": "硫酸亚铁",
    "finasteride": "非那雄胺",
    "fluoxetine": "氟西汀",
    "fluticasone": "氟替卡松",
    "folic_acid": "叶酸",
    "furosemide": "呋塞米",
    "gabapentin": "加巴喷丁",
    "galantamine": "加兰他敏",
    "glimepiride": "格列美脲",
    "glyburide": "格列本脲",
    "haloperidol": "氟哌啶醇",
    "hydrochlorothiazide": "氢氯噻嗪",
    "hydrocortisone": "氢化可的松",
    "hydroxychloroquine": "羟氯喹",
    "ibuprofen": "布洛芬",
    "insulin": "胰岛素",
    "insulin_glargine": "甘精胰岛素",
    "lactulose": "乳果糖",
    "lamotrigine": "拉莫三嗪",
    "latanoprost": "拉坦前列素",
    "letrozole": "来曲唑",
    "levetiracetam": "左乙拉西坦",
    "levofloxacin": "左氧氟沙星",
    "levothyroxine": "左甲状腺素",
    "liraglutide": "利拉鲁肽",
    "lisinopril": "赖诺普利",
    "lithium": "锂盐",
    "loperamide": "洛哌丁胺",
    "loratadine": "氯雷他定",
    "lorazepam": "劳拉西泮",
    "losartan": "氯沙坦",
    "melatonin": "褪黑素",
    "memantine": "美金刚",
    "mesalamine": "美沙拉嗪",
    "metformin": "二甲双胍",
    "methadone": "美沙酮",
    "methimazole": "甲巯咪唑",
    "methotrexate": "甲氨蝶呤",
    "methylphenidate": "哌甲酯",
    "metoprolol": "美托洛尔",
    "metronidazole": "甲硝唑",
    "montelukast": "孟鲁司特",
    "naltrexone": "纳曲酮",
    "naproxen": "萘普生",
    "nitrofurantoin": "呋喃妥因",
    "nitroglycerin": "硝酸甘油",
    "olanzapine": "奥氮平",
    "omeprazole": "奥美拉唑",
    "oseltamivir": "奥司他韦",
    "oxybutynin": "奥昔布宁",
    "pantoprazole": "泮托拉唑",
    "paroxetine": "帕罗西汀",
    "pembrolizumab": "派姆单抗",
    "phenytoin": "苯妥英",
    "pioglitazone": "吡格列酮",
    "prednisone": "泼尼松",
    "pregabalin": "普瑞巴林",
    "propranolol": "普萘洛尔",
    "quetiapine": "喹硫平",
    "risperidone": "利培酮",
    "rivaroxaban": "利伐沙班",
    "rosuvastatin": "瑞舒伐他汀",
    "sertraline": "舍曲林",
    "sildenafil": "西地那非",
    "simvastatin": "辛伐他汀",
    "sitagliptin": "西格列汀",
    "solifenacin": "索利那新",
    "spironolactone": "螺内酯",
    "sulfasalazine": "柳氮磺胺吡啶",
    "sumatriptan": "舒马普坦",
    "tadalafil": "他达拉非",
    "tamoxifen": "他莫昔芬",
    "tamsulosin": "坦索罗辛",
    "theophylline": "茶碱",
    "timolol": "噻吗洛尔",
    "tiotropium": "噻托溴铵",
    "tolterodine": "托特罗定",
    "topiramate": "托吡酯",
    "tramadol": "曲马多",
    "trimethoprim": "甲氧苄啶",
    "ursodiol": "熊去氧胆酸",
    "valacyclovir": "伐昔洛韦",
    "valproate": "丙戊酸盐",
    "valproic_acid": "丙戊酸",
    "venlafaxine": "文拉法辛",
    "warfarin": "华法林",
}
