"""
静态数据常量用于 Healthcare Provider (zh_CN).
"""

HOSPITAL_DEPARTMENTS: tuple[str, ...] = (
    "急诊科",
    "重症监护室 (ICU)",
    "心脏重症监护室 (CCU)",
    "手术室",
    "分娩室",
    "儿科病房",
    "产科病房",
    "肿瘤科病房",
    "放射科",
    "检验科",
    "药剂科 (药房)",
    "物理治疗室",
    "作业治疗室",
    "呼吸治疗室",
    "外科病房",
    "住院部",
    "门诊部",
    "精神科病房",
    "康复中心",
    "内镜中心",
    "新生儿重症监护室 (NICU)",
    "烧伤科病房",
    "血液净化中心 (透析室)",
    "睡眠监测中心",
    "伤口造口门诊",
    "输液中心",
    "心内科病房",
    "神经内科病房",
    "留观室",
    "麻醉复苏室 (PACU)",
)

BRAND_DRUGS: tuple[str, ...] = (
    "立普妥 (Lipitor)",
    "优甲乐 (Synthroid)",
    "捷赐瑞 (Prinivil)",
    "格华止 (Glucophage)",
    "络活喜 (Norvasc)",
    "倍他乐克 (Lopressor)",
    "洛赛克 (Prilosec)",
    "舒降之 (Zocor)",
    "科素亚 (Cozaar)",
    "加巴喷丁 (Neurontin)",
    "左洛复 (Zoloft)",
    "百忧解 (Prozac)",
    "怡诺思 (Effexor)",
    "来士普 (Lexapro)",
    "欣百达 (Cymbalta)",
    "波立维 (Plavix)",
    "艾乐妥 (Eliquis)",
    "诺和泰 (Ozempic)",
    "恩格列净 (Jardiance)",
    "达格列净 (Farxiga)",
    "可定 (Crestor)",
    "捷诺维 (Januvia)",
    "诺和力 (Victoza)",
    "度易达 (Trulicity)",
    "替尔泊肽 (Mounjaro)",
    "Zepbound (替尔泊肽减肥版)",
    "来得时 (Lantus)",
    "优泌乐 (Humalog)",
    "诺和锐 (NovoLog)",
    "多杰 (Toujeo)",
    "Basaglar",
    "诺和平 (Levemir)",
    "德谷胰岛素 (Tresiba)",
    "捷赐瑞 (Zestril)",
    "瑞泰 (Altace)",
    "Vasotec",
    "Accupril",
    "代文 (Diovan)",
    "安博维 (Avapro)",
    "傲坦 (Benicar)",
    "美卡素 (Micardis)",
    "达利全 (Coreg)",
    "氨酰心安 (Tenormin)",
    "心得安 (Inderal)",
    "倍他乐克 (Lopressor)",
    "倍他乐克缓释片 (Toprol XL)",
    "Catapres",
    "合心爽 (Cardizem)",
    "硝苯地平 (Procardia)",
    "络活喜 (Norvasc)",
    "波依定 (Plendil)",
    "DynaCirc",
    "安体舒通 (Aldactone)",
    "速尿 (Lasix)",
    "丁脲胺 (Bumex)",
    "托拉塞米 (Demadex)",
    "Zaroxolyn",
    "可达龙 (Cordarone)",
    "地高辛 (Lanoxin)",
    "Tambocor",
    "悦复隆 (Rythmol)",
    "索他洛尔 (Betapace)",
    "拜瑞妥 (Xarelto)",
    "泰毕全 (Pradaxa)",
    "Savaysa",
    "Macrobid",
    "西普乐 (Cipro)",
    "左氧氟沙星 (Levaquin)",
    "希舒美 (Zithromax)",
    "克拉仙 (Biaxin)",
    "Vibramycin",
    "先锋霉素 (Keflex)",
    "西力欣 (Ceftin)",
    "罗氏芬 (Rocephin)",
    "Cleocin",
    "甲硝唑 (Flagyl)",
    "稳可信 (Vancocin)",
    "斯沃 (Zyvox)",
    "Zovirax",
    "维德思 (Valtrex)",
    "达菲 (Tamiflu)",
    "大扶康 (Diflucan)",
    "威凡 (Vfend)",
    "安必素 (AmBisome)",
    "兰美抒 (Lamisil)",
    "悦亭 (Wellbutrin)",
    "Pristiq",
    "米氮平 (Remeron)",
    "Pamelor",
    "Elavil",
    "赛乐特 (Paxil)",
    "兰释 (Luvox)",
    "氯米帕明 (Anafranil)",
    "Eskalith",
    "丙戊酸钠 (Depakote)",
    "利必通 (Lamictal)",
    "卡马西平 (Tegretol)",
    "奥卡西平 (Trileptal)",
    "妥泰 (Topamax)",
    "开浦兰 (Keppra)",
    "苯妥英钠 (Dilantin)",
    "鲁米那 (Luminal)",
    "扑米酮 (Mysoline)",
    "维派特 (Vimpat)",
    "Zonegran",
    "安理申 (Aricept)",
    "艾斯能 (Exelon)",
    "Razadyne",
    "易倍申 (Namenda)",
    "息宁 (Sinemet)",
    "森福罗 (Mirapex)",
    "力克平 (Requip)",
    "雷沙吉兰 (Azilect)",
    "司来吉兰 (Eldepryl)",
    "力奥来素 (Lioresal)",
    "Zanaflex",
    "Flexeril",
    "Soma",
    "Robaxin",
    "赞安诺 (Xanax)",
    "劳拉西泮 (Ativan)",
    "安定 (Valium)",
    "氯硝西泮 (Klonopin)",
    "Restoril",
    "思诺思 (Ambien)",
    "右佐匹克隆 (Lunesta)",
    "扎来普隆 (Sonata)",
    "雷美替胺 (Rozerem)",
    "Belsomra",
    "利他林 (Ritalin)",
    "专注达 (Concerta)",
    "右哌甲酯 (Focalin)",
    "阿得拉 (Vyvanse)",
    "择思达 (Strattera)",
    "Intuniv",
    "安律凡 (Abilify)",
    "思瑞康 (Seroquel)",
    "再普乐 (Zyprexa)",
    "维思通 (Risperdal)",
    "齐拉西酮 (Geodon)",
    "Invega",
    "鲁拉西酮 (Latuda)",
    "氟哌啶醇 (Haldol)",
    "氯丙嗪 (Thorazine)",
    "奋乃静 (Trilafon)",
    "哈乐 (Flomax)",
    "保列治 (Proscar)",
    "适尿通 (Avodart)",
    "万艾可 (Viagra)",
    "希爱力 (Cialis)",
    "艾力达 (Levitra)",
    "Ditropan",
    "得妥 (Detrol)",
    "卫喜康 (Vesicare)",
    "Enablex",
    "Slow-Fe",
    "Folvite",
    "Nascobal",
    "罗盖全 (Rocaltrol)",
    "钙尔奇 (Caltrate)",
    "善胃得 (Zantac)",
    "法莫替丁 (Pepcid)",
    "耐信 (Nexium)",
    "兰索拉唑 (Prevacid)",
    "雷贝拉唑 (Aciphex)",
    "别嘌醇 (Zyloprim)",
    "秋水仙碱 (Colcrys)",
    "丙磺舒 (Benemid)",
    "非布司他 (Uloric)",
    "Krystexxa",
    "西乐葆 (Celebrex)",
    "扶他林 (Voltaren)",
    "消炎痛 (Indocin)",
    "Toradol",
    "Feldene",
    "奥施康定 (OxyContin)",
    "Vicodin",
    "美施康定 (MS Contin)",
    "多瑞吉 (Duragesic)",
    "泰诺 (Tylenol #3)",
    "Dilaudid",
    "Opana",
    "美沙酮 (Dolophine)",
    "赛博松 (Suboxone)",
    "纳洛酮 (Narcan)",
    "舒利迭 (Advair)",
    "信必可 (Symbicort)",
    "思力华 (Spiriva)",
    "顺尔宁 (Singulair)",
    "Dulera",
    "万托林 (ProAir/Ventolin)",
    "Xopenex",
    "辅舒酮 (Flovent)",
    "普米克 (Pulmicort)",
    "K药 (Keytruda)",
    "O药 (Opdivo)",
    "Y药 (Yervoy)",
    "T药 (Tecentriq)",
    "I药 (Imfinzi)",
    "修美乐 (Humira)",
    "恩利 (Enbrel)",
    "类克 (Remicade)",
    "喜达诺 (Stelara)",
    "可善挺 (Cosentyx)",
    "达必妥 (Dupixent)",
    "茁乐 (Xolair)",
    "Skyrizi",
    "Tapezentis",
    "安吉优 (Entyvio)",
)

BLOOD_TYPES: tuple[str, ...] = ("A型Rh阳性", "A型Rh阴性", "B型Rh阳性", "B型Rh阴性", "AB型Rh阳性", "AB型Rh阴性", "O型Rh阳性", "O型Rh阴性")

ALLERGIES: tuple[str, ...] = (
    "青霉素",
    "花生",
    "树坚果",
    "贝类",
    "鱼类",
    "牛奶",
    "鸡蛋",
    "大豆",
    "小麦",
    "芝麻",
    "乳胶",
    "蜂蛰伤",
    "花粉",
    "尘螨",
    "宠物皮屑",
    "磺胺类药物",
    "阿司匹林",
    "布洛芬",
    "可待因",
    "吗啡",
    "造影剂",
    "麻醉剂",
    "镍",
    "医用胶带",
    "香精",
    "昆虫叮咬",
    "霉菌",
    "蟑螂",
    "草",
    "豚草",
    "玉米",
    "芥末",
    "芹菜",
    "羽扇豆",
    "亚硫酸盐",
    "味精 (MSG)",
    "红色染料",
    "麸质",
    "乳糖",
    "果糖",
)

MEDICAL_PROCEDURES: tuple[str, ...] = (
    "血液检查",
    "磁共振成像 (MRI)",
    "CT扫描",
    "X光检查",
    "超声检查",
    "结肠镜检查",
    "内窥镜检查 (胃镜)",
    "阑尾切除术",
    "胆囊切除术",
    "剖宫产术",
    "子宫切除术",
    "膝关节置换术",
    "髋关节置换术",
    "白内障手术",
    "活检",
    "物理治疗",
    "心电图 (ECG)",
    "超声心动图",
    "疫苗接种",
    "清创术",
    "血管成形术 (支架)",
    "心脏导管检查",
    "冠状动脉旁路移植术 (搭桥)",
    "起搏器植入术",
    "除颤器植入术",
    "消融术",
    "扁桃体切除术",
    "腺样体切除术",
    "乳房切除术",
    "乳房肿块切除术",
    "前列腺切除术",
    "肾切除术",
    "脾切除术",
    "胃切除术",
    "结肠切除术",
    "回肠造口术",
    "结肠造口术",
    "疝修补术",
    "胆囊摘除术",
    "肝活检",
    "肾活检",
    "骨髓活检",
    "淋巴结活检",
    "皮肤活检",
    "支气管镜检查",
    "胸腔穿刺术",
    "腹腔穿刺术",
    "腰椎穿刺",
    "关节穿刺术",
    "硬膜外注射",
    "神经阻滞",
    "激痛点注射",
    "关节腔注射",
    "肉毒杆菌注射",
    "填充剂注射",
    "激光脱毛",
    "化学换肤",
    "微晶磨皮",
    "磨皮术",
    "皮赘去除术",
    "痣切除术",
    "疣去除术",
    "冷冻疗法",
    "电灼术",
    "切除术",
    "切开引流术",
    "缝合术",
    "吻合器缝合",
    "植皮术",
    "皮瓣手术",
    "激光近视手术 (LASIK)",
    "青光眼手术",
    "视网膜脱离修复术",
    "角膜移植术",
    "玻璃体切除术",
    "鼓室成形术",
    "镫骨切除术",
    "人工耳蜗植入术",
    "鼻整形术",
    "鼻中隔成形术",
    "鼻窦手术",
    "甲状腺切除术",
    "甲状旁腺切除术",
    "肾上腺切除术",
    "胰腺切除术",
    "惠普尔手术 (胰十二指肠切除术)",
    "肝切除术",
    "肝移植",
    "肾移植",
    "心脏移植",
    "肺移植",
    "胰腺移植",
    "骨髓移植",
    "干细胞移植",
    "透析",
    "血液透析",
    "腹膜透析",
    "血浆置换",
    "静脉注射免疫球蛋白 (IVIG)",
    "化疗",
    "放疗",
    "免疫疗法",
    "激素疗法",
    "靶向治疗",
    "CAR-T细胞疗法",
)

INSURANCE_PLANS: tuple[str, ...] = (
    "优选医疗机构组织 (PPO)",
    "健康维护组织 (HMO)",
    "独家医疗服务提供者组织 (EPO)",
    "定点服务计划 (POS)",
    "美国联邦医疗保险 (Medicare)",
    "美国医疗补助计划 (Medicaid)",
    "高免赔额健康计划 (HDHP)",
    "商业保险",
    "雇主赞助保险",
    "联邦医疗保险优势计划 (Medicare Advantage)",
    "军人医疗保险 (TRICARE)",
    "退伍军人事务部医疗 (VA)",
    "儿童健康保险计划 (CHIP)",
    "平价医疗法案市场计划 (ACA)",
    "补充医疗保险 (Medigap)",
    "联邦医疗保险 A 部分 (住院)",
    "联邦医疗保险 B 部分 (门诊)",
    "联邦医疗保险 C 部分",
    "联邦医疗保险 D 部分 (处方药)",
    "牙科保险",
    "眼科保险",
    "长期护理保险",
    "残疾保险",
    "重大疾病保险",
    "巨灾医疗保险",
    "城镇职工基本医疗保险",
    "城乡居民基本医疗保险",
    "新型农村合作医疗 (新农合)",
    "公费医疗",
    "大病互助",
)

VITAL_SIGNS: tuple[str, ...] = (
    "血压",
    "心率",
    "呼吸频率",
    "体温",
    "血氧饱和度",
    "体重指数 (BMI)",
    "血糖",
    "疼痛等级",
    "脉搏",
    "峰流速",
)
