from .. import HealthcareProvider as BaseHealthcareProvider


class Provider(BaseHealthcareProvider):
    """Faker provider for generating healthcare/medical fake data."""

    diseases= (
        "Diabète de type 2",
        "Hypertension essentielle",
        "Hyperlipidémie",
        "Maladie coronarienne",
        "Bronchopneumopathie chronique obstructive",
        "Asthme",
        "Maladie rénale chronique",
        "Arthrose",
        "Arthrite rhumatoïde",
        "Dépression",
        "Trouble anxieux",
        "Reflux gastro-œsophagien",
        "Obésité",
        "Hypothyroïdie",
        "Fibrillation auriculaire",
        "Insuffisance cardiaque congestive",
        "Pneumonie",
        "Infection urinaire",
        "Bronchite aiguë",
        "Anémie",
        "Migraine",
        "Accident vasculaire cérébral",
        "Maladie d'Alzheimer",
        "Cancer du sein",
        "Cancer de la prostate",
        "Cancer du poumon",
        "COVID-19",
        "Grippe",
        "Ostéoporose",
        "Artériopathie oblitérante des membres inférieurs",
        "Angine de poitrine",
        "Hyperthyroïdie",
        "Goutte",
        "Sclérose en plaques",
        "Maladie de Parkinson",
        "Épilepsie",
        "Trouble bipolaire",
        "Schizophrénie",
        "Trouble déficitaire de l'attention avec hyperactivité",
        "Troubles du spectre autistique",
        "Maladie de Crohn",
        "Colite ulcéreuse",
        "Syndrome du côlon irritable",
        "Maladie cœliaque",
        "Cirrhose",
        "Hépatite C",
        "VIH/SIDA",
        "Tuberculose",
        "Septicémie",
        "Thrombose veineuse profonde",
        "Embolie pulmonaire",
        "Anévrisme aortique",
        "Valvulopathie cardiaque",
        "Cardiomyopathie",
        "Endocardite",
        "Péricardite",
        "Infarctus du myocarde",
        "Cardiopathie congénitale",
        "Neuropathie périphérique",
        "Apnée du sommeil",
        "Narcolepsie",
        "Syndrome des jambes sans repos",
        "Fibromyalgie",
        "Lupus",
        "Sclérodermie",
        "Syndrome de Sjögren",
        "Psoriasis",
        "Eczéma",
        "Rosacée",
        "Acné vulgaire",
        "Mélanome",
        "Carcinome basocellulaire",
        "Carcinome spinocellulaire",
        "Leucémie",
        "Lymphome",
        "Myélome",
        "Cancer du côlon",
        "Cancer du pancréas",
        "Cancer du rein",
        "Cancer de la vessie",
        "Cancer de l'ovaire",
        "Cancer de l'endomètre",
        "Cancer de la thyroïde",
        "Tumeur cérébrale",
        "Glaucome",
        "Dégénérescence maculaire",
        "Cataracte",
        "Rétinopathie diabétique",
        "Perte auditive",
        "Maladie de Ménière",
        "Hyperplasie bénigne de la prostate",
        "Dysfonction érectile",
        "Syndrome des ovaires polykystiques",
        "Endométriose",
        "Fibromes utérins",
        "Pré-éclampsie",
        "Diabète gestationnel",
        "Carence en vitamine D",
        "Anémie ferriprive",
        "Anémie pernicieuse",
        "Drépanocytose",
        "Hémophilie",
        "Thrombocytopénie",
        "Leucopénie",
        "Diverticulite",
        "Appendicite",
        "Cholécystite",
        "Pancréatite",
        "Ulcère gastroduodénal",
        "Gastrite",
        "Œsophagite",
        "Œsophage de Barrett",
        "Hernie hiatale",
        "Hémorroïdes",
        "Fissure anale",
        "Incontinence fécale",
        "Insuffisance rénale aiguë",
        "Syndrome néphrotique",
        "Maladie polykystique des reins",
        "Calculs rénaux",
        "Cystite interstitielle",
        "Vessie hyperactive",
        "Incontinence urinaire d'effort",
        "Incontinence urinaire par impériosité",
        "Pyélonéphrite",
        "Glomérulonéphrite",
        "Sinusite aiguë",
        "Sinusite chronique",
        "Rhinite allergique",
        "Otite moyenne",
        "Otite externe",
        "Pharyngite",
        "Amygdalite",
        "Laryngite",
        "Croup",
        "Bronchiolite",
        "Emphysème",
        "Mucoviscidose",
        "Maladie pulmonaire interstitielle",
        "Sarcoïdose",
        "Épanchement pleural",
        "Pneumothorax",
        "Hypertension pulmonaire",
    )

    icd10_codes= (
        "E11.9", "I10", "E78.5", "I25.10", "J44.9",
        "J45.909", "N18.9", "M17.9", "M79.1", "F32.9",
        "F41.9", "K21.9", "E66.9", "E03.9", "I48.91",
        "I50.9", "J18.9", "N39.0", "J20.9", "D64.9",
        "G43.909", "I63.9", "G30.9", "R10.9", "R50.9",
        "R06.00", "R53.81", "Z00.00", "Z79.899", "Z68.1",
        "C50.919", "C61", "C34.90", "U07.1", "J11.1",
        "M81.0", "I73.9", "K70.30", "G20", "E10.9",
        "I20.9", "E05.90", "M10.9", "G35", "G21.9",
        "G40.909", "F31.9", "F20.9", "F90.9", "F84.0",
        "K50.90", "K51.90", "K58.9", "K90.0", "K74.60",
        "B18.2", "B20", "A15.9", "A41.9", "I82.409",
        "I26.99", "I71.9", "I35.9", "I42.9", "I33.9",
        "I30.9", "I21.9", "Q24.9", "G62.9", "G47.33",
        "G47.419", "G25.81", "M79.7", "M32.9", "M34.9",
        "M35.00", "L40.9", "L20.9", "L71.9", "L70.0",
        "C43.9", "C44.91", "C44.92", "C95.90", "C85.90",
        "C90.00", "C18.9", "C25.9", "C64.9", "C67.9",
        "C56.9", "C54.1", "C73", "C71.9", "H40.9",
        "H35.30", "H25.9", "H36", "H90.3", "H81.0",
        "N40.0", "N52.9", "E28.2", "N80.9", "D25.9",
        "O14.9", "O24.919", "E55.9", "D50.9", "D51.0",
        "D57.1", "D66", "D69.6", "D70.9", "K57.90",
        "K35.80", "K81.9", "K85.90", "K27.9", "K29.70",
        "K20.9", "K22.70", "K44.9", "I84.9", "K60.2",
        "R15.9", "N17.9", "N04.9", "Q61.9", "N20.0",
        "N30.10", "N32.81", "N39.3", "N39.41", "N10",
        "N05.9", "J01.90", "J32.9", "J30.9", "H66.90",
        "H60.90", "J02.9", "J03.90", "J04.0", "J05.0",
        "J21.9", "J43.9", "E84.9", "J84.9", "D86.9",
        "J90", "J93.9", "I27.20", "Z00.01", "Z00.121",
        "Z00.129", "Z13.6", "Z13.89", "Z23", "J06.9",
        "R07.9", "M54.5", "M25.50", "M19.90", "R51.9",
        "R53.83", "E78.0", "I11.9", "I25.5", "I63.50",
        "I67.9", "I70.0", "I21.3", "I21.4", "I48.0",
        "I48.2", "I49.9", "I50.1", "I50.20", "I50.30",
        "I50.40", "I61.9", "I63.40", "I64", "I69.30",
        "I80.10", "I80.20", "I80.3", "I82.40", "I82.90",
        "I83.90", "I87.2", "I95.9", "J00", "J02.0",
        "J03.00", "J04.10", "J05.10", "J12.89", "J15.9",
        "J18.0", "J18.1", "J20.0", "J20.8", "J21.0",
        "J40", "J41.0", "J42", "J44.0", "J44.1",
        "J45.20", "J45.30", "J45.40", "J45.50", "J45.901",
        "J47.0", "J47.9", "J60", "J61", "J70.9",
        "J80", "J81.0", "J82", "J84.10", "J84.112",
        "J84.117", "J84.170", "J84.89", "J91.8", "J92.0",
        "J93.0", "J93.11", "J93.12", "J93.81", "J94.0",
        "J94.2", "J94.8", "J95.1", "J95.2", "J96.00",
        "J96.01", "J96.02", "J96.10", "J96.11", "J96.12",
        "J96.20", "J96.21", "J96.22", "J96.90", "J96.91",
        "J96.92", "J98.4", "J98.9", "K02.9", "K03.9",
        "K04.7", "K04.90", "K05.6", "K08.9", "K12.0",
        "K21.0", "K22.0", "K22.10", "K22.2", "K22.6",
        "K25.9", "K26.9", "K28.9", "K29.00", "K29.50",
        "K29.60", "K30", "K31.84", "K31.9", "K35.2",
        "K35.3", "K36", "K38.9", "K40.90", "K42.9",
        "K43.9", "K46.9", "K50.00", "K50.10", "K50.80",
        "K51.00", "K51.20", "K51.30", "K51.50", "K51.80",
        "K52.9", "K55.0", "K56.0", "K56.60", "K57.30",
        "K57.32", "K57.50", "K57.92", "K58.0", "K59.00",
        "K59.01", "K59.02", "K59.09", "K59.1", "K59.2",
        "K59.3", "K59.4", "K60.0", "K60.1", "K60.3",
        "K60.4", "K61.0", "K62.5", "K63.5", "K64.9",
        "K70.0", "K70.10", "K70.9", "K71.9", "K72.00",
        "K72.10", "K72.90", "K73.9", "K74.0", "K74.3",
        "K75.9", "K76.0", "K76.9", "K80.20", "K80.50",
        "K82.9", "K83.0", "K85.00", "K85.10", "K85.20",
        "K85.30", "K85.80", "K86.0", "K86.1", "K86.9",
        "K91.2", "K92.0", "K92.1", "K92.2", "K92.9",
    )

    medical_specialties= (
        "Cardiologie",
        "Dermatologie",
        "Endocrinologie",
        "Gastroentérologie",
        "Hématologie",
        "Maladies infectieuses",
        "Néphrologie",
        "Neurologie",
        "Oncologie",
        "Pneumologie",
        "Rhumatologie",
        "Allergologie et immunologie",
        "Médecine de famille",
        "Médecine interne",
        "Pédiatrie",
        "Psychiatrie",
        "Obstétrique et gynécologie",
        "Orthopédie",
        "Urologie",
        "Ophtalmologie",
        "Oto-rhino-laryngologie",
        "Anesthésiologie",
        "Radiologie",
        "Anatomie pathologique",
        "Médecine d'urgence",
        "Chirurgie générale",
        "Chirurgie plastique",
        "Neurochirurgie",
        "Médecine physique et de réadaptation",
        "Chirurgie vasculaire",
        "Chirurgie thoracique",
        "Chirurgie cardiaque",
        "Chirurgie colorectale",
        "Chirurgie de transplantation",
        "Chirurgie pédiatrique",
        "Néonatologie",
        "Gériatrie",
        "Médecine de la douleur",
        "Soins palliatifs",
        "Médecine du sport",
        "Médecine du travail",
        "Médecine préventive",
        "Génétique médicale",
        "Médecine nucléaire",
        "Radiologie interventionnelle",
    )

    hospital_departments= (
        "Urgences",
        "Unité de soins intensifs",
        "Unité de soins cardiaques",
        "Salle d'opération",
        "Salle de travail et d'accouchement",
        "Pédiatrie",
        "Maternité",
        "Oncologie",
        "Radiologie",
        "Laboratoire",
        "Pharmacie",
        "Physiothérapie",
        "Ergothérapie",
        "Thérapie respiratoire",
        "Chirurgie",
        "Service d'hospitalisation",
        "Consultations externes",
        "Service de psychiatrie",
        "Unité de rééducation",
        "Salle d'endoscopie",
        "Unité de soins intensifs néonatals",
        "Unité des brûlés",
        "Unité de dialyse",
        "Laboratoire du sommeil",
        "Centre de soins des plaies",
        "Centre d'infusion",
        "Unité de cardiologie",
        "Unité de neurologie",
        "Unité d'observation médicale",
        "Salle de réveil",
    )

    generic_drugs= (
        "Atorvastatine", "Lévothyroxine", "Lisinopril", "Metformine", "Amlodipine",
        "Métoprolol", "Oméprazole", "Simvastatine", "Losartan", "Gabapentine",
        "Hydrochlorothiazide", "Sertraline", "Amoxicilline", "Albutérol", "Citalopram",
        "Pantoprazole", "Trazodone", "Fluoxétine", "Tramadol", "Clopidogrel",
        "Rosuvastatine", "Escitalopram", "Montélukast", "Furosémide", "Bupropion",
        "Prednisone", "Méloxicam", "Dextroamphétamine", "Duloxétine", "Carvédilol",
        "Ibuprofène", "Paracétamol", "Aspirine", "Naproxène", "Warfarine",
        "Apixaban", "Rivaroxaban", "Dabigatran", "Insuline glargine", "Insuline aspart",
        "Insuline lispro", "Insuline détémir", "Empagliflozine", "Dapagliflozine", "Sitagliptine",
        "Glimépiride", "Pioglitazone", "Acarbose", "Répaglinide", "Natéglinide",
        "Énalapril", "Quinapril", "Ramipril", "Bénazépril", "Fosinopril",
        "Candésartan", "Valsartan", "Irbésartan", "Olmésartan", "Telmisartan",
        "Diltiazem", "Vérapamil", "Nifédipine", "Félodipine", "Isradipine",
        "Bisoprolol", "Aténolol", "Propranolol", "Nadolol", "Labetalol",
        "Clonidine", "Hydralazine", "Prazosine", "Doxazosine", "Térazosine",
        "Spironolactone", "Triamtérène", "Amiloride", "Chlortalidone", "Indapamide",
        "Amiodarone", "Digoxine", "Flécaïnide", "Propafénone", "Sotalol",
        "Nitrofurantoïne", "Ciprofloxacine", "Lévofloxacine", "Azithromycine", "Clarithromycine",
        "Doxycycline", "Céfalexine", "Céfuroxime", "Ceftriaxone", "Clindamycine",
        "Métronidazole", "Vancomycine", "Linézolide", "Aciclovir", "Valaciclovir",
        "Oseltamivir", "Fluconazole", "Voriconazole", "Amphotéricine", "Terbinafine",
        "Venlafaxine", "Desvenlafaxine", "Mirtazapine", "Nortriptyline", "Amitriptyline",
        "Paroxétine", "Fluvoxamine", "Clomipramine", "Lithium", "Valproate",
        "Lamotrigine", "Carbamazépine", "Oxcarbazépine", "Topiramate", "Lévétiracétam",
        "Phénytoïne", "Phénobarbital", "Primidone", "Lacosamide", "Zonisamide",
        "Donépézil", "Rivastigmine", "Galantamine", "Mémantine", "Lévodopa",
        "Carbidopa", "Pramipexole", "Ropinirole", "Rasagiline", "Sélégiline",
        "Baclofène", "Tizanidine", "Cyclobenzaprine", "Carisoprodol", "Méthocarbamol",
        "Alprazolam", "Lorazépam", "Diazépam", "Clonazépam", "Témazépam",
        "Zolpidem", "Eszopiclone", "Zaleplon", "Rameltéon", "Suvorexant",
        "Méthylphénidate", "Dexméthylphénidate", "Lisdexamfétamine", "Atomoxétine", "Guanfacine",
        "Aripiprazole", "Quétiapine", "Olanzapine", "Rispéridone", "Ziprasidone",
        "Palipéridone", "Lurasidone", "Halopéridol", "Chlorpromazine", "Perphénazine",
        "Tamsulosine", "Finastéride", "Dutastéride", "Sildénafil", "Tadalafil",
        "Vardénafil", "Oxybutynine", "Toltérodine", "Solifénacine", "Darifénacine",
        "Sulfate ferreux", "Acide folique", "Vitamine B12", "Vitamine D", "Carbonate de calcium",
        "Ranitidine", "Famotidine", "Ésoméprazole", "Lansoprazole", "Rabéprazole",
        "Allopurinol", "Colchicine", "Probénécid", "Féburxostat", "Pegloticase",
        "Célécoxib", "Diclofénac", "Indométacine", "Kétorolac", "Piroxicam",
        "Oxycodone", "Hydrocodone", "Morphine", "Fentanyl", "Codéine",
        "Hydromorphone", "Oxymorphone", "Méthadone", "Buprénorphine", "Naloxone",
    )

    brand_drugs= (
        "Lipitor", "Synthroid", "Prinivil", "Glucophage", "Norvasc",
        "Lopressor", "Prilosec", "Zocor", "Cozaar", "Neurontin",
        "Zoloft", "Prozac", "Effexor", "Lexapro", "Cymbalta",
        "Plavix", "Eliquis", "Ozempic", "Jardiance", "Farxiga",
        "Crestor", "Januvia", "Victoza", "Trulicity", "Mounjaro",
        "Zepbound", "Lantus", "Humalog", "NovoLog", "Toujeo",
        "Basaglar", "Levemir", "Tresiba", "Zestril", "Altace",
        "Vasotec", "Accupril", "Diovan", "Avapro", "Benicar",
        "Micardis", "Coreg", "Tenormin", "Inderal", "Lopressor",
        "Toprol XL", "Catapres", "Cardizem", "Procardia", "Norvasc",
        "Plendil", "DynaCirc", "Aldactone", "Lasix", "Bumex",
        "Demadex", "Zaroxolyn", "Cordarone", "Lanoxin", "Tambocor",
        "Rythmol", "Betapace", "Xarelto", "Pradaxa", "Savaysa",
        "Macrobid", "Cipro", "Levaquin", "Zithromax", "Biaxin",
        "Vibramycin", "Keflex", "Ceftin", "Rocephin", "Cleocin",
        "Flagyl", "Vancocin", "Zyvox", "Zovirax", "Valtrex",
        "Tamiflu", "Diflucan", "Vfend", "AmBisome", "Lamisil",
        "Wellbutrin", "Pristiq", "Remeron", "Pamelor", "Elavil",
        "Paxil", "Luvox", "Anafranil", "Eskalith", "Depakote",
        "Lamictal", "Tegretol", "Trileptal", "Topamax", "Keppra",
        "Dilantin", "Luminal", "Mysoline", "Vimpat", "Zonegran",
        "Aricept", "Exelon", "Razadyne", "Namenda", "Sinemet",
        "Mirapex", "Requip", "Azilect", "Eldepryl", "Lioresal",
        "Zanaflex", "Flexeril", "Soma", "Robaxin", "Xanax",
        "Ativan", "Valium", "Klonopin", "Restoril", "Ambien",
        "Lunesta", "Sonata", "Rozerem", "Belsomra", "Ritalin",
        "Concerta", "Focalin", "Vyvanse", "Strattera", "Intuniv",
        "Abilify", "Seroquel", "Zyprexa", "Risperdal", "Geodon",
        "Invega", "Latuda", "Haldol", "Thorazine", "Trilafon",
        "Flomax", "Proscar", "Avodart", "Viagra", "Cialis",
        "Levitra", "Ditropan", "Detrol", "Vesicare", "Enablex",
        "Slow-Fe", "Folvite", "Nascobal", "Rocaltrol", "Caltrate",
        "Zantac", "Pepcid", "Nexium", "Prevacid", "Aciphex",
        "Zyloprim", "Colcrys", "Benemid", "Uloric", "Krystexxa",
        "Celebrex", "Voltaren", "Indocin", "Toradol", "Feldene",
        "OxyContin", "Vicodin", "MS Contin", "Duragesic", "Tylenol #3",
        "Dilaudid", "Opana", "Dolophine", "Suboxone", "Narcan",
        "Advair", "Symbicort", "Spiriva", "Singulair", "Dulera",
        "ProAir", "Ventolin", "Xopenex", "Flovent", "Pulmicort",
        "Keytruda", "Opdivo", "Yervoy", "Tecentriq", "Imfinzi",
        "Humira", "Enbrel", "Remicade", "Stelara", "Cosentyx",
        "Dupixent", "Xolair", "Skyrizi", "Taltz", "Entyvio",
    )

    symptoms= (
        "Fièvre", "Toux", "Dyspnée", "Céphalée", "Fatigue",
        "Douleur abdominale", "Nausée", "Vomissement", "Diarrhée", "Douleur thoracique",
        "Vertige", "Éruption cutanée", "Mal de gorge", "Arthralgie", "Lombalgie",
        "Hémoptysie", "Perte de poids", "Œdème", "Vision floue", "Palpitations",
        "Frissons", "Sudation", "Myalgie", "Asthénie", "Engourdissement",
        "Paresthésie", "Confusion", "Perte de mémoire", "Anxiété", "Dépression",
        "Insomnie", "Tremblement", "Convulsion", "Perte de conscience", "Syncope",
        "Tachycardie", "Arythmie cardiaque", "Bradycardie", "Hypertension artérielle", "Hypotension artérielle",
        "Dysphagie", "Pyrosis", "Méléna", "Rectorragie", "Constipation",
        "Ballonnement", "Gaz", "Éructation", "Anorexie", "Polyphagie",
        "Pollakiurie", "Dysurie", "Hématurie", "Urine trouble", "Urine foncée",
        "Incontinence", "Impuissance", "Dyspareunie", "Ménorragie", "Dysménorrhée",
        "Leucorrhée", "Métrorragie", "Bouffées de chaleur", "Sueurs nocturnes", "Sensibilité mammaire",
        "Tumeur mammaire", "Écoulement mamelonnaire", "Douleur testiculaire", "Gonflement testiculaire", "Masse scrotale",
        "Prurit", "Urticaire", "Eczéma", "Xérose", "Peau grasse",
        "Alopécie", "Ongle cassant", "Ongle jaune", "Onychomycose", "Pellicules",
        "Yeux rouges", "Larmoiement", "Diplopie", "Photophobie", "Douleur oculaire",
        "Otalgie", "Otorrhée", "Acouphènes", "Hypoacousie", "Trouble de l'équilibre",
        "Rhinorrhée", "Congestion nasale", "Épistaxis", "Éternuement", "Écoulement post-nasal",
        "Anosmie", "Agueusie", "Halitose", "Xérostomie", "Aphtes",
        "Saignement gingival", "Odontalgie", "Douleur mandibulaire", "Difficulté de mastication", "Difficulté respiratoire",
        "Sibilants", "Tachypnée", "Polypnée", "Ronflement", "Apnée du sommeil",
    )

    blood_types= (
        "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-",
    )

    allergies= (
        "Pénicilline", "Arachides", "Noix", "Crustacés", "Poisson",
        "Lait", "Œufs", "Soja", "Blé", "Sésame",
        "Latex", "Piqûre d'abeille", "Pollen", "Acariens", "Poils d'animaux",
        "Sulfamides", "Aspirine", "Ibuprofène", "Codéine", "Morphine",
        "Produit de contraste", "Anesthésie", "Nickel", "Adhésif", "Parfum",
        "Piqûres d'insectes", "Moisissure", "Cafards", "Graminées", "Ambroisie",
        "Maïs", "Moutarde", "Céleri", "Lupin", "Sulfites",
        "Glutamate monosodique", "Colorant rouge", "Gluten", "Lactose", "Fructose",
    )

    medical_procedures= (
        "Analyse de sang", "IRM", "Tomodensitométrie", "Radiographie", "Échographie",
        "Coloscopie", "Endoscopie", "Appendicectomie", "Cholécystectomie", "Césarienne",
        "Hystérectomie", "Arthroplastie du genou", "Arthroplastie de la hanche", "Chirurgie de la cataracte", "Biopsie",
        "Séance de physiothérapie", "Électrocardiogramme (ECG)", "Échocardiogramme", "Vaccination", "Débridement de plaie",
        "Angioplastie", "Cathétérisme cardiaque", "Pontage aorto-coronarien", "Implantation de pacemaker", "Implantation de défibrillateur",
        "Ablation", "Amygdalectomie", "Adénoïdectomie", "Mastectomie", "Tumorectomie",
        "Prostatectomie", "Néphrectomie", "Splénectomie", "Gastrectomie", "Colectomie",
        "Iléostomie", "Colostomie", "Réparation de hernie", "Ablation de la vésicule biliaire", "Biopsie hépatique",
        "Biopsie rénale", "Biopsie de moelle osseuse", "Biopsie ganglionnaire", "Biopsie cutanée", "Bronchoscopie",
        "Thoracocentèse", "Paracentèse", "Ponction lombaire", "Ponction articulaire", "Injection épidurale",
        "Bloc nerveux", "Injection en point trigger", "Injection intra-articulaire", "Injection de Botox", "Injection de filler",
        "Épilation laser", "Peeling chimique", "Microdermabrasion", "Dermabrasion", "Exérèse de lésion cutanée",
        "Exérèse de grain de beauté", "Exérèse de verrue", "Cryothérapie", "Électrocoagulation", "Excision",
        "Incision et drainage", "Suture", "Agrafage", "Greffe de peau", "Lambeau cutané",
        "Chirurgie LASIK", "Chirurgie du glaucome", "Réparation de décollement de rétine", "Greffe de cornée", "Vitrectomie",
        "Tympanoplastie", "Stapedectomie", "Implant cochléaire", "Rhinoplastie", "Septoplastie",
        "Chirurgie des sinus", "Thyroïdectomie", "Parathyroïdectomie", "Surrénalectomie", "Pancréatectomie",
        "Procédure de Whipple", "Résection hépatique", "Transplantation hépatique", "Transplantation rénale", "Transplantation cardiaque",
        "Transplantation pulmonaire", "Transplantation pancréatique", "Greffe de moelle osseuse", "Greffe de cellules souches", "Dialyse",
        "Hémodialyse", "Dialyse péritonéale", "Plasmaphérèse", "Infusion d'IVIG", "Chimiothérapie",
        "Radiothérapie", "Immunothérapie", "Hormonothérapie", "Thérapie ciblée", "Thérapie CAR-T",
    )

    insurance_plans= (
        "Assurance Maladie", "Mutuelle", "Complémentaire santé", "Régime général", "Régime agricole",
        "Régime des indépendants", "Complémentaire santé solidaire", "Assurance privée", "Assurance expatriés", "100% Santé",
        "Carte européenne d'assurance maladie", "Aide médicale de l'État", "Couverture maladie universelle", "Assurance santé collective", "Assurance santé individuelle",
    )

    vital_signs= (
        "Tension artérielle", "Fréquence cardiaque", "Fréquence respiratoire", "Température corporelle", "Saturation en oxygène",
        "Indice de masse corporelle (IMC)", "Glycémie", "Niveau de douleur", "Pouls", "Débit expiratoire de pointe",
    )
