"""Display labels for the locale-neutral clinical values (fr_FR).

Words only: the numbers, units and reference intervals live once in
`faker_healthcare/clinical_values.py` and are never translated. The key set must match
the base catalogue exactly (`faker_healthcare/clinical_labels.py`); see
`tests/test_locales.py::TestClinicalLabelParity`.

Note that fr_FR keeps *medication* names in English by convention (see AGENTS.md); that
convention is about drug names only. Analyte and vital-sign names are translated here,
with the French enzyme abbreviations (ALAT, ASAT) rather than the English ones.

Deux dictionnaires : `CLINICAL_LABELS` (noms des analytes et des constantes, indicateurs,
catégories d'alcool, voies, fréquences, statut de la prescription, bandes de sévérité) et
`MEDICATION_NAMES`, qui associe l'identifiant neutre d'une substance à l'orthographe
exacte de ce catalogue. Comme les médicaments sont volontairement laissés en anglais en
fr_FR (voir AGENTS.md), ses valeurs sont les noms anglais du catalogue : c'est bien la
convention, pas un oubli de traduction.
"""

CLINICAL_LABELS: dict[str, str] = {
    # Signes vitaux
    "systolic_bp": "Pression artérielle systolique",
    "diastolic_bp": "Pression artérielle diastolique",
    "heart_rate": "Fréquence cardiaque",
    "respiratory_rate": "Fréquence respiratoire",
    "temperature_c": "Température corporelle",
    "oxygen_saturation": "Saturation en oxygène",
    # Hématologie
    "haemoglobin": "Hémoglobine",
    "wbc": "Numération leucocytaire",
    "platelets": "Numération plaquettaire",
    "ferritin": "Ferritine",
    "inr": "INR (rapport international normalisé)",
    # Fonction rénale
    "sodium": "Sodium",
    "potassium": "Potassium",
    "urea": "Urée",
    "creatinine": "Créatinine",
    "egfr": "Débit de filtration glomérulaire estimé (DFGe)",
    # Fonction hépatique
    "alt": "Alanine aminotransférase (ALAT)",
    "ast": "Aspartate aminotransférase (ASAT)",
    "alkaline_phosphatase": "Phosphatases alcalines",
    "bilirubin_total": "Bilirubine totale",
    "albumin": "Albumine",
    # Métabolisme
    "fasting_glucose": "Glycémie à jeun",
    "hba1c": "Hémoglobine glyquée (HbA1c)",
    # Thyroïde
    "tsh": "Thyréostimuline (TSH)",
    "free_t4": "Thyroxine libre (T4 libre)",
    # Lipides
    "total_cholesterol": "Cholestérol total",
    "ldl": "Cholestérol LDL",
    "hdl": "Cholestérol HDL",
    "triglycerides": "Triglycérides",
    # Marqueurs inflammatoires
    "crp": "Protéine C réactive (CRP)",
    # Interprétation du résultat
    "flag_low": "Bas",
    "flag_normal": "Normal",
    "flag_high": "Élevé",
    # Consommation hebdomadaire d'alcool
    "alcohol_none": "Non-buveur",
    "alcohol_low_risk": "Risque faible",
    "alcohol_increasing_risk": "Risque croissant",
    "alcohol_higher_risk": "Risque élevé",
    # Voies d'administration
    "route_oral": "Voie orale",
    "route_intravenous": "Voie intraveineuse",
    "route_subcutaneous": "Voie sous-cutanée",
    "route_inhaled": "Voie inhalée",
    "route_sublingual": "Voie sublinguale",
    "route_ophthalmic": "Voie ophtalmique",
    # Fréquences d'administration
    "frequency_once_daily": "Une fois par jour",
    "frequency_twice_daily": "Deux fois par jour",
    "frequency_three_times_daily": "Trois fois par jour",
    "frequency_four_times_daily": "Quatre fois par jour",
    "frequency_at_night": "Le soir",
    "frequency_as_required": "Si besoin",
    "frequency_once_weekly": "Une fois par semaine",
    "frequency_every_three_weeks": "Toutes les trois semaines",
    # Statut de la prescription
    "medication_status_past": "Traitement passé",
    "medication_status_current": "Traitement en cours",
    "medication_status_future": "Traitement à venir",
    # Bandes de sévérité des échelles
    "assessment_minimal": "Minime",
    "assessment_mild": "Léger",
    "assessment_moderate": "Modéré",
    "assessment_moderately_severe": "Modérément sévère",
    "assessment_severe": "Sévère",
    "assessment_symptoms_absent": "Symptômes absents",
    "assessment_normal_cognition": "Cognition normale",
    "assessment_screen_negative": "Dépistage négatif",
    "assessment_screen_positive": "Dépistage positif",
    "alcohol_possible_dependence": "Dépendance possible",
}

# Les substances que `medication_order()` sait poser, nommées comme ce catalogue les nomme.
MEDICATION_NAMES: dict[str, str] = {
    "acamprosate": "Acamprosate",
    "acetaminophen": "Acetaminophen",
    "acyclovir": "Acyclovir",
    "albuterol": "Albuterol",
    "alendronate": "Alendronate",
    "allopurinol": "Allopurinol",
    "alprazolam": "Alprazolam",
    "amitriptyline": "Amitriptyline",
    "amlodipine": "Amlodipine",
    "amoxicillin": "Amoxicillin",
    "anastrozole": "Anastrozole",
    "apixaban": "Apixaban",
    "aripiprazole": "Aripiprazole",
    "aspirin": "Aspirin",
    "atomoxetine": "Atomoxetine",
    "atorvastatin": "Atorvastatin",
    "azathioprine": "Azathioprine",
    "azithromycin": "Azithromycin",
    "bicalutamide": "Bicalutamide",
    "budesonide": "Budesonide",
    "buprenorphine": "Buprenorphine",
    "bupropion": "Bupropion",
    "buspirone": "Buspirone",
    "calcium_carbonate": "Calcium Carbonate",
    "carbamazepine": "Carbamazepine",
    "ceftriaxone": "Ceftriaxone",
    "cefuroxime": "Cefuroxime",
    "cephalexin": "Cephalexin",
    "cetirizine": "Cetirizine",
    "cholecalciferol": "Cholecalciferol",
    "cilostazol": "Cilostazol",
    "ciprofloxacin": "Ciprofloxacin",
    "clarithromycin": "Clarithromycin",
    "clindamycin": "Clindamycin",
    "clopidogrel": "Clopidogrel",
    "colchicine": "Colchicine",
    "dexamethasone": "Dexamethasone",
    "digoxin": "Digoxin",
    "diltiazem": "Diltiazem",
    "donepezil": "Donepezil",
    "doxycycline": "Doxycycline",
    "duloxetine": "Duloxetine",
    "dutasteride": "Dutasteride",
    "empagliflozin": "Empagliflozin",
    "enoxaparin": "Enoxaparin",
    "escitalopram": "Escitalopram",
    "esomeprazole": "Esomeprazole",
    "famotidine": "Famotidine",
    "febuxostat": "Febuxostat",
    "ferrous_sulfate": "Ferrous Sulfate",
    "finasteride": "Finasteride",
    "fluoxetine": "Fluoxetine",
    "fluticasone": "Fluticasone",
    "folic_acid": "Folic Acid",
    "furosemide": "Furosemide",
    "gabapentin": "Gabapentin",
    "galantamine": "Galantamine",
    "glimepiride": "Glimepiride",
    "glyburide": "Glyburide",
    "haloperidol": "Haloperidol",
    "hydrochlorothiazide": "Hydrochlorothiazide",
    "hydrocortisone": "Hydrocortisone",
    "hydroxychloroquine": "Hydroxychloroquine",
    "ibuprofen": "Ibuprofen",
    "insulin": "Insulin",
    "insulin_glargine": "Insulin Glargine",
    "lactulose": "Lactulose",
    "lamotrigine": "Lamotrigine",
    "latanoprost": "Latanoprost",
    "letrozole": "Letrozole",
    "levetiracetam": "Levetiracetam",
    "levofloxacin": "Levofloxacin",
    "levothyroxine": "Levothyroxine",
    "liraglutide": "Liraglutide",
    "lisinopril": "Lisinopril",
    "lithium": "Lithium",
    "loperamide": "Loperamide",
    "loratadine": "Loratadine",
    "lorazepam": "Lorazepam",
    "losartan": "Losartan",
    "melatonin": "Melatonin",
    "memantine": "Memantine",
    "mesalamine": "Mesalamine",
    "metformin": "Metformin",
    "methadone": "Methadone",
    "methimazole": "Methimazole",
    "methotrexate": "Methotrexate",
    "methylphenidate": "Methylphenidate",
    "metoprolol": "Metoprolol",
    "metronidazole": "Metronidazole",
    "montelukast": "Montelukast",
    "naltrexone": "Naltrexone",
    "naproxen": "Naproxen",
    "nitrofurantoin": "Nitrofurantoin",
    "nitroglycerin": "Nitroglycerin",
    "olanzapine": "Olanzapine",
    "omeprazole": "Omeprazole",
    "oseltamivir": "Oseltamivir",
    "oxybutynin": "Oxybutynin",
    "pantoprazole": "Pantoprazole",
    "paroxetine": "Paroxetine",
    "pembrolizumab": "Pembrolizumab",
    "phenytoin": "Phenytoin",
    "pioglitazone": "Pioglitazone",
    "prednisone": "Prednisone",
    "pregabalin": "Pregabalin",
    "propranolol": "Propranolol",
    "quetiapine": "Quetiapine",
    "risperidone": "Risperidone",
    "rivaroxaban": "Rivaroxaban",
    "rosuvastatin": "Rosuvastatin",
    "sertraline": "Sertraline",
    "sildenafil": "Sildenafil",
    "simvastatin": "Simvastatin",
    "sitagliptin": "Sitagliptin",
    "solifenacin": "Solifenacin",
    "spironolactone": "Spironolactone",
    "sulfasalazine": "Sulfasalazine",
    "sumatriptan": "Sumatriptan",
    "tadalafil": "Tadalafil",
    "tamoxifen": "Tamoxifen",
    "tamsulosin": "Tamsulosin",
    "theophylline": "Theophylline",
    "timolol": "Timolol",
    "tiotropium": "Tiotropium",
    "tolterodine": "Tolterodine",
    "topiramate": "Topiramate",
    "tramadol": "Tramadol",
    "trimethoprim": "Trimethoprim",
    "ursodiol": "Ursodiol",
    "valacyclovir": "Valacyclovir",
    "valproate": "Valproate",
    "valproic_acid": "Valproic Acid",
    "venlafaxine": "Venlafaxine",
    "warfarin": "Warfarin",
}
