"""
Constantes de données statiques pour le fournisseur Healthcare (fr_FR).
"""

HOSPITAL_DEPARTMENTS: tuple[str, ...] = (
    "Urgences",
    "Unité de soins intensifs",
    "Unité de soins cardiaques",
    "Salle d'opération",
    "Salle de travail et d'accouchement",
    "Pédiatrie",
    "Maternité",
    "Oncologie",
    "Radiologie",
    "Laboratoire",
    "Pharmacie",
    "Physiothérapie",
    "Ergothérapie",
    "Thérapie respiratoire",
    "Chirurgie",
    "Service d'hospitalisation",
    "Consultations externes",
    "Service de psychiatrie",
    "Unité de rééducation",
    "Salle d'endoscopie",
    "Unité de soins intensifs néonatals",
    "Unité des brûlés",
    "Unité de dialyse",
    "Laboratoire du sommeil",
    "Centre de soins des plaies",
    "Centre d'infusion",
    "Unité de cardiologie",
    "Unité de neurologie",
    "Unité d'observation médicale",
    "Salle de réveil",
)

BRAND_DRUGS: tuple[str, ...] = (
    "Lipitor",
    "Synthroid",
    "Prinivil",
    "Glucophage",
    "Norvasc",
    "Lopressor",
    "Prilosec",
    "Zocor",
    "Cozaar",
    "Neurontin",
    "Zoloft",
    "Prozac",
    "Effexor",
    "Lexapro",
    "Cymbalta",
    "Plavix",
    "Eliquis",
    "Ozempic",
    "Jardiance",
    "Farxiga",
    "Crestor",
    "Januvia",
    "Victoza",
    "Trulicity",
    "Mounjaro",
    "Zepbound",
    "Lantus",
    "Humalog",
    "NovoLog",
    "Toujeo",
    "Basaglar",
    "Levemir",
    "Tresiba",
    "Zestril",
    "Altace",
    "Vasotec",
    "Accupril",
    "Diovan",
    "Avapro",
    "Benicar",
    "Micardis",
    "Coreg",
    "Tenormin",
    "Inderal",
    "Lopressor",
    "Toprol XL",
    "Catapres",
    "Cardizem",
    "Procardia",
    "Norvasc",
    "Plendil",
    "DynaCirc",
    "Aldactone",
    "Lasix",
    "Bumex",
    "Demadex",
    "Zaroxolyn",
    "Cordarone",
    "Lanoxin",
    "Tambocor",
    "Rythmol",
    "Betapace",
    "Xarelto",
    "Pradaxa",
    "Savaysa",
    "Macrobid",
    "Cipro",
    "Levaquin",
    "Zithromax",
    "Biaxin",
    "Vibramycin",
    "Keflex",
    "Ceftin",
    "Rocephin",
    "Cleocin",
    "Flagyl",
    "Vancocin",
    "Zyvox",
    "Zovirax",
    "Valtrex",
    "Tamiflu",
    "Diflucan",
    "Vfend",
    "AmBisome",
    "Lamisil",
    "Wellbutrin",
    "Pristiq",
    "Remeron",
    "Pamelor",
    "Elavil",
    "Paxil",
    "Luvox",
    "Anafranil",
    "Eskalith",
    "Depakote",
    "Lamictal",
    "Tegretol",
    "Trileptal",
    "Topamax",
    "Keppra",
    "Dilantin",
    "Luminal",
    "Mysoline",
    "Vimpat",
    "Zonegran",
    "Aricept",
    "Exelon",
    "Razadyne",
    "Namenda",
    "Sinemet",
    "Mirapex",
    "Requip",
    "Azilect",
    "Eldepryl",
    "Lioresal",
    "Zanaflex",
    "Flexeril",
    "Soma",
    "Robaxin",
    "Xanax",
    "Ativan",
    "Valium",
    "Klonopin",
    "Restoril",
    "Ambien",
    "Lunesta",
    "Sonata",
    "Rozerem",
    "Belsomra",
    "Ritalin",
    "Concerta",
    "Focalin",
    "Vyvanse",
    "Strattera",
    "Intuniv",
    "Abilify",
    "Seroquel",
    "Zyprexa",
    "Risperdal",
    "Geodon",
    "Invega",
    "Latuda",
    "Haldol",
    "Thorazine",
    "Trilafon",
    "Flomax",
    "Proscar",
    "Avodart",
    "Viagra",
    "Cialis",
    "Levitra",
    "Ditropan",
    "Detrol",
    "Vesicare",
    "Enablex",
    "Slow-Fe",
    "Folvite",
    "Nascobal",
    "Rocaltrol",
    "Caltrate",
    "Zantac",
    "Pepcid",
    "Nexium",
    "Prevacid",
    "Aciphex",
    "Zyloprim",
    "Colcrys",
    "Benemid",
    "Uloric",
    "Krystexxa",
    "Celebrex",
    "Voltaren",
    "Indocin",
    "Toradol",
    "Feldene",
    "OxyContin",
    "Vicodin",
    "MS Contin",
    "Duragesic",
    "Tylenol #3",
    "Dilaudid",
    "Opana",
    "Dolophine",
    "Suboxone",
    "Narcan",
    "Advair",
    "Symbicort",
    "Spiriva",
    "Singulair",
    "Dulera",
    "ProAir",
    "Ventolin",
    "Xopenex",
    "Flovent",
    "Pulmicort",
    "Keytruda",
    "Opdivo",
    "Yervoy",
    "Tecentriq",
    "Imfinzi",
    "Humira",
    "Enbrel",
    "Remicade",
    "Stelara",
    "Cosentyx",
    "Dupixent",
    "Xolair",
    "Skyrizi",
    "Taltz",
    "Entyvio",
)

BLOOD_TYPES: tuple[str, ...] = ("A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-")

ALLERGIES: tuple[str, ...] = (
    "Pénicilline",
    "Arachides",
    "Noix",
    "Crustacés",
    "Poisson",
    "Lait",
    "Œufs",
    "Soja",
    "Blé",
    "Sésame",
    "Latex",
    "Piqûre d'abeille",
    "Pollen",
    "Acariens",
    "Poils d'animaux",
    "Sulfamides",
    "Aspirine",
    "Ibuprofène",
    "Codéine",
    "Morphine",
    "Produit de contraste",
    "Anesthésie",
    "Nickel",
    "Adhésif",
    "Parfum",
    "Piqûres d'insectes",
    "Moisissure",
    "Cafards",
    "Graminées",
    "Ambroisie",
    "Maïs",
    "Moutarde",
    "Céleri",
    "Lupin",
    "Sulfites",
    "Glutamate monosodique",
    "Colorant rouge",
    "Gluten",
    "Lactose",
    "Fructose",
)

MEDICAL_PROCEDURES: tuple[str, ...] = (
    "Analyse de sang",
    "IRM",
    "Tomodensitométrie",
    "Radiographie",
    "Échographie",
    "Coloscopie",
    "Endoscopie",
    "Appendicectomie",
    "Cholécystectomie",
    "Césarienne",
    "Hystérectomie",
    "Arthroplastie du genou",
    "Arthroplastie de la hanche",
    "Chirurgie de la cataracte",
    "Biopsie",
    "Séance de physiothérapie",
    "Électrocardiogramme (ECG)",
    "Échocardiogramme",
    "Vaccination",
    "Débridement de plaie",
    "Angioplastie",
    "Cathétérisme cardiaque",
    "Pontage aorto-coronarien",
    "Implantation de pacemaker",
    "Implantation de défibrillateur",
    "Ablation",
    "Amygdalectomie",
    "Adénoïdectomie",
    "Mastectomie",
    "Tumorectomie",
    "Prostatectomie",
    "Néphrectomie",
    "Splénectomie",
    "Gastrectomie",
    "Colectomie",
    "Iléostomie",
    "Colostomie",
    "Réparation de hernie",
    "Ablation de la vésicule biliaire",
    "Biopsie hépatique",
    "Biopsie rénale",
    "Biopsie de moelle osseuse",
    "Biopsie ganglionnaire",
    "Biopsie cutanée",
    "Bronchoscopie",
    "Thoracocentèse",
    "Paracentèse",
    "Ponction lombaire",
    "Ponction articulaire",
    "Injection épidurale",
    "Bloc nerveux",
    "Injection en point trigger",
    "Injection intra-articulaire",
    "Injection de Botox",
    "Injection de filler",
    "Épilation laser",
    "Peeling chimique",
    "Microdermabrasion",
    "Dermabrasion",
    "Exérèse de lésion cutanée",
    "Exérèse de grain de beauté",
    "Exérèse de verrue",
    "Cryothérapie",
    "Électrocoagulation",
    "Excision",
    "Incision et drainage",
    "Suture",
    "Agrafage",
    "Greffe de peau",
    "Lambeau cutané",
    "Chirurgie LASIK",
    "Chirurgie du glaucome",
    "Réparation de décollement de rétine",
    "Greffe de cornée",
    "Vitrectomie",
    "Tympanoplastie",
    "Stapedectomie",
    "Implant cochléaire",
    "Rhinoplastie",
    "Septoplastie",
    "Chirurgie des sinus",
    "Thyroïdectomie",
    "Parathyroïdectomie",
    "Surrénalectomie",
    "Pancréatectomie",
    "Procédure de Whipple",
    "Résection hépatique",
    "Transplantation hépatique",
    "Transplantation rénale",
    "Transplantation cardiaque",
    "Transplantation pulmonaire",
    "Transplantation pancréatique",
    "Greffe de moelle osseuse",
    "Greffe de cellules souches",
    "Dialyse",
    "Hémodialyse",
    "Dialyse péritonéale",
    "Plasmaphérèse",
    "Infusion d'IVIG",
    "Chimiothérapie",
    "Radiothérapie",
    "Immunothérapie",
    "Hormonothérapie",
    "Thérapie ciblée",
    "Thérapie CAR-T",
)

INSURANCE_PLANS: tuple[str, ...] = (
    "Assurance Maladie",
    "Mutuelle",
    "Complémentaire santé",
    "Régime général",
    "Régime agricole",
    "Régime des indépendants",
    "Complémentaire santé solidaire",
    "Assurance privée",
    "Assurance expatriés",
    "100% Santé",
    "Carte européenne d'assurance maladie",
    "Aide médicale de l'État",
    "Couverture maladie universelle",
    "Assurance santé collective",
    "Assurance santé individuelle",
)

VITAL_SIGNS: tuple[str, ...] = (
    "Tension artérielle",
    "Fréquence cardiaque",
    "Fréquence respiratoire",
    "Température corporelle",
    "Saturation en oxygène",
    "Indice de masse corporelle (IMC)",
    "Glycémie",
    "Niveau de douleur",
    "Pouls",
    "Débit expiratoire de pointe",
)
