"""
Constantes de données statiques pour le fournisseur Healthcare (fr_FR).
"""

HOSPITAL_DEPARTMENTS: tuple[str, ...] = (
    "Urgences",
    "Unité de soins intensifs",
    "Unité de soins cardiaques",
    "Salle d'opération",
    "Salle de travail et d'accouchement",
    "Pédiatrie",
    "Maternité",
    "Oncologie",
    "Radiologie",
    "Laboratoire",
    "Pharmacie",
    "Physiothérapie",
    "Ergothérapie",
    "Thérapie respiratoire",
    "Chirurgie",
    "Service d'hospitalisation",
    "Consultations externes",
    "Service de psychiatrie",
    "Unité de rééducation",
    "Salle d'endoscopie",
    "Unité de soins intensifs néonatals",
    "Unité des brûlés",
    "Unité de dialyse",
    "Laboratoire du sommeil",
    "Centre de soins des plaies",
    "Centre d'infusion",
    "Unité de cardiologie",
    "Unité de neurologie",
    "Unité d'observation médicale",
    "Salle de réveil",
)

BLOOD_TYPES: tuple[str, ...] = ("A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-")

ALLERGIES: tuple[str, ...] = (
    "Pénicilline",
    "Arachides",
    "Noix",
    "Crustacés",
    "Poisson",
    "Lait",
    "Œufs",
    "Soja",
    "Blé",
    "Sésame",
    "Latex",
    "Piqûre d'abeille",
    "Pollen",
    "Acariens",
    "Poils d'animaux",
    "Sulfamides",
    "Aspirine",
    "Ibuprofène",
    "Codéine",
    "Morphine",
    "Produit de contraste",
    "Anesthésie",
    "Nickel",
    "Adhésif",
    "Parfum",
    "Piqûres d'insectes",
    "Moisissure",
    "Cafards",
    "Graminées",
    "Ambroisie",
    "Maïs",
    "Moutarde",
    "Céleri",
    "Lupin",
    "Sulfites",
    "Colorant rouge",
)

MEDICAL_PROCEDURES: tuple[str, ...] = (
    "Analyse de sang",
    "IRM",
    "Tomodensitométrie",
    "Radiographie",
    "Échographie",
    "Coloscopie",
    "Endoscopie",
    "Appendicectomie",
    "Cholécystectomie",
    "Césarienne",
    "Hystérectomie",
    "Arthroplastie du genou",
    "Arthroplastie de la hanche",
    "Chirurgie de la cataracte",
    "Biopsie",
    "Séance de physiothérapie",
    "Électrocardiogramme (ECG)",
    "Échocardiogramme",
    "Vaccination",
    "Débridement de plaie",
    "Angioplastie",
    "Cathétérisme cardiaque",
    "Pontage aorto-coronarien",
    "Implantation de pacemaker",
    "Implantation de défibrillateur",
    "Ablation",
    "Amygdalectomie",
    "Adénoïdectomie",
    "Mastectomie",
    "Tumorectomie",
    "Prostatectomie",
    "Néphrectomie",
    "Splénectomie",
    "Gastrectomie",
    "Colectomie",
    "Iléostomie",
    "Colostomie",
    "Réparation de hernie",
    "Ablation de la vésicule biliaire",
    "Biopsie hépatique",
    "Biopsie rénale",
    "Biopsie de moelle osseuse",
    "Biopsie ganglionnaire",
    "Biopsie cutanée",
    "Bronchoscopie",
    "Thoracocentèse",
    "Paracentèse",
    "Ponction lombaire",
    "Ponction articulaire",
    "Injection épidurale",
    "Bloc nerveux",
    "Injection en point trigger",
    "Injection intra-articulaire",
    "Injection de Botox",
    "Injection de filler",
    "Épilation laser",
    "Peeling chimique",
    "Microdermabrasion",
    "Dermabrasion",
    "Exérèse de lésion cutanée",
    "Exérèse de grain de beauté",
    "Exérèse de verrue",
    "Cryothérapie",
    "Électrocoagulation",
    "Excision",
    "Incision et drainage",
    "Suture",
    "Agrafage",
    "Greffe de peau",
    "Lambeau cutané",
    "Chirurgie LASIK",
    "Chirurgie du glaucome",
    "Réparation de décollement de rétine",
    "Greffe de cornée",
    "Vitrectomie",
    "Tympanoplastie",
    "Stapedectomie",
    "Implant cochléaire",
    "Rhinoplastie",
    "Septoplastie",
    "Chirurgie des sinus",
    "Thyroïdectomie",
    "Parathyroïdectomie",
    "Surrénalectomie",
    "Pancréatectomie",
    "Procédure de Whipple",
    "Résection hépatique",
    "Transplantation hépatique",
    "Transplantation rénale",
    "Transplantation cardiaque",
    "Transplantation pulmonaire",
    "Transplantation pancréatique",
    "Greffe de moelle osseuse",
    "Greffe de cellules souches",
    "Dialyse",
    "Hémodialyse",
    "Dialyse péritonéale",
    "Plasmaphérèse",
    "Infusion d'IVIG",
    "Chimiothérapie",
    "Radiothérapie",
    "Immunothérapie",
    "Hormonothérapie",
    "Thérapie ciblée",
    "Thérapie CAR-T",
)

INSURANCE_PLANS: tuple[str, ...] = (
    "Assurance Maladie",
    "Mutuelle",
    "Complémentaire santé",
    "Régime général",
    "Régime agricole",
    "Régime des indépendants",
    "Complémentaire santé solidaire",
    "Assurance privée",
    "Assurance expatriés",
    "100% Santé",
    "Carte européenne d'assurance maladie",
    "Aide médicale de l'État",
    "Couverture maladie universelle",
    "Assurance santé collective",
    "Assurance santé individuelle",
)

VITAL_SIGNS: tuple[str, ...] = (
    "Tension artérielle",
    "Fréquence cardiaque",
    "Fréquence respiratoire",
    "Température corporelle",
    "Saturation en oxygène",
    "Indice de masse corporelle (IMC)",
    "Glycémie",
    "Niveau de douleur",
    "Pouls",
    "Débit expiratoire de pointe",
)

# Treatments that a condition's `medications` list may legitimately contain but that
# are not drugs: procedures, devices, and lifestyle measures. They are correct inside
# a condition's treatment list (see AGENTS.md), but wrong in the flat pool a consumer
# draws a medication column from, so `generic_drugs` excludes them and the provider
# exposes them separately via `interventions` / `intervention()`.
# Kept in the same order in every locale, so index i is the same intervention
# everywhere; every entry must also appear in this locale's DISEASE_CORRELATIONS
# (tests/test_locales.py enforces both).
NON_DRUG_INTERVENTIONS: tuple[str, ...] = (
    "Anti-Glare Lenses",
    "Bladder Instillations",
    "Blood Transfusions",
    "CPAP Therapy",
    "Chemotherapy",
    "Chest Tube",
    "Cochlear Implants",
    "Delivery",
    "Dialysis",
    "Diet Control",
    "Electrolyte Management",
    "Exercise",
    "Eyeglasses",
    "Gluten-Free Diet",
    "Hearing Aids",
    "Humidified Air",
    "Hydration",
    "IV Fluids",
    "Iron Infusions",
    "Laser Therapy",
    "Magnifiers",
    "No Medications",
    "Oxygen",
    "Oxygen Therapy",
    "Pelvic Floor Exercises",
    "Photodynamic Therapy",
    "Plasmapheresis",
    "Pleurodesis",
    "Pulmonary Rehab",
    "Radiation",
    "Radioactive Iodine",
    "Saline Irrigation",
    "Splenectomy",
    "Steam Inhalation",
    "Sun Exposure",
    "Supportive Care",
    "Surgery",
    "Thoracentesis",
    "Vitrectomy",
    "Voice Rest",
    "Wrist Splint",
)
