"""
Données de Corrélations des Maladies

Ce module contient le dictionnaire DISEASE_CORRELATIONS mappant les 150 maladies
à leurs symptômes, codes CIM-10, médicaments et spécialités médicales principales.

Données issues de la classification CIM-10 de l'OMS.

AVERTISSEMENT MÉDICAL : Ces données sont UNIQUEMENT À DES FINS DE TEST ET DE DÉVELOPPEMENT.
Elles NE doivent PAS être utilisées pour un diagnostic médical réel, un traitement ou des décisions en matière de soins de santé.
"""

from ..types import DiseaseData


DISEASE_CORRELATIONS: dict[str, DiseaseData] = {
    "Diabète sucré de type 2": {
        "icd10": "E11.9",
        "symptoms": ["Polyurie", "Polyphagie", "Fatigue", "Vision floue", "Perte de poids"],
        "medications": ["Metformin", "Insulin Glargine", "Empagliflozin", "Sitagliptin", "Glimepiride"],
        "medical_specialty": "Endocrinologie",
    },
    "Hypertension essentielle": {
        "icd10": "I10",
        "symptoms": ["Céphalées", "Vertiges", "Douleur thoracique", "Vision floue", "Palpitations"],
        "medications": ["Lisinopril", "Amlodipine", "Losartan", "Hydrochlorothiazide", "Metoprolol"],
        "medical_specialty": "Cardiologie",
    },
    "Hyperlipidémie": {
        "icd10": "E78.5",
        "symptoms": ["Douleur thoracique", "Fatigue", "Engourdissement", "Faiblesse"],
        "medications": ["Atorvastatin", "Simvastatin", "Rosuvastatin", "Fenofibrate", "Ezetimibe"],
        "medical_specialty": "Cardiologie",
    },
    "Cardiopathie artérioscléreuse": {
        "icd10": "I25.10",
        "symptoms": ["Douleur thoracique", "Essoufflement", "Fatigue", "Palpitations", "Vertiges"],
        "medications": ["Aspirin", "Clopidogrel", "Atorvastatin", "Metoprolol", "Nitroglycerin"],
        "medical_specialty": "Cardiologie",
    },
    "Maladie pulmonaire obstructive chronique": {
        "icd10": "J44.9",
        "symptoms": ["Essoufflement", "Toux", "Sibilants", "Douleur thoracique", "Fatigue"],
        "medications": ["Albuterol", "Tiotropium", "Fluticasone", "Prednisone", "Azithromycin"],
        "medical_specialty": "Pneumologie",
    },
    "Asthme": {
        "icd10": "J45.909",
        "symptoms": ["Sibilants", "Essoufflement", "Toux", "Douleur thoracique", "Difficulté respiratoire"],
        "medications": ["Albuterol", "Fluticasone", "Montelukast", "Prednisone", "Budesonide"],
        "medical_specialty": "Pneumologie",
    },
    "Maladie rénale chronique": {
        "icd10": "N18.9",
        "symptoms": ["Fatigue", "Œdème", "Nausées", "Perte d'appétit", "Polyurie"],
        "medications": ["Lisinopril", "Furosemide", "Erythropoietin", "Calcium Carbonate", "Sevelamer"],
        "medical_specialty": "Néphrologie",
    },
    "Arthrose": {
        "icd10": "M17.9",
        "symptoms": ["Douleur articulaire", "Œdème", "Faiblesse", "Mal de dos"],
        "medications": ["Ibuprofen", "Acetaminophen", "Naproxen", "Celecoxib", "Tramadol"],
        "medical_specialty": "Orthopédie",
    },
    "Polyarthrite rhumatoïde": {
        "icd10": "M79.1",
        "symptoms": ["Douleur articulaire", "Œdème", "Fatigue", "Faiblesse", "Douleurs musculaires"],
        "medications": ["Methotrexate", "Prednisone", "Adalimumab", "Hydroxychloroquine", "Sulfasalazine"],
        "medical_specialty": "Rhumatologie",
    },
    "Dépression": {
        "icd10": "F32.9",
        "symptoms": ["Dépression", "Fatigue", "Insomnie", "Perte d'appétit", "Anxiété"],
        "medications": ["Sertraline", "Fluoxetine", "Escitalopram", "Bupropion", "Duloxetine"],
        "medical_specialty": "Psychiatrie",
    },
    "Trouble anxieux": {
        "icd10": "F41.9",
        "symptoms": ["Anxiété", "Palpitations", "Sudation", "Tremblements", "Insomnie"],
        "medications": ["Sertraline", "Escitalopram", "Alprazolam", "Lorazepam", "Buspirone"],
        "medical_specialty": "Psychiatrie",
    },
    "Maladie du reflux gastro-œsophagien": {
        "icd10": "K21.9",
        "symptoms": ["Brûlures d'estomac", "Douleur thoracique", "Difficulté à avaler", "Mal de gorge", "Nausées"],
        "medications": ["Omeprazole", "Pantoprazole", "Esomeprazole", "Ranitidine", "Famotidine"],
        "medical_specialty": "Gastroentérologie",
    },
    "Obésité": {
        "icd10": "E66.9",
        "symptoms": ["Fatigue", "Douleur articulaire", "Essoufflement", "Sudation"],
        "medications": ["Orlistat", "Phentermine", "Liraglutide", "Semaglutide", "Naltrexone"],
        "medical_specialty": "Endocrinologie",
    },
    "Hypothyroïdie": {
        "icd10": "E03.9",
        "symptoms": ["Fatigue", "Perte de poids", "Perte de cheveux", "Peau sèche", "Constipation"],
        "medications": ["Levothyroxine", "Liothyronine", "Thyroid"],
        "medical_specialty": "Endocrinologie",
    },
    "Fibrillation auriculaire": {
        "icd10": "I48.91",
        "symptoms": ["Palpitations", "Vertiges", "Fatigue", "Essoufflement", "Douleur thoracique"],
        "medications": ["Warfarin", "Apixaban", "Rivaroxaban", "Metoprolol", "Diltiazem"],
        "medical_specialty": "Cardiologie",
    },
    "Insuffisance cardiaque congestive": {
        "icd10": "I50.9",
        "symptoms": ["Essoufflement", "Fatigue", "Œdème", "Toux", "Tachycardie"],
        "medications": ["Furosemide", "Lisinopril", "Metoprolol", "Spironolactone", "Digoxin"],
        "medical_specialty": "Cardiologie",
    },
    "Pneumonie": {
        "icd10": "J18.9",
        "symptoms": ["Fièvre", "Toux", "Essoufflement", "Douleur thoracique", "Fatigue"],
        "medications": ["Amoxicillin", "Azithromycin", "Ceftriaxone", "Levofloxacin", "Doxycycline"],
        "medical_specialty": "Pneumologie",
    },
    "Infection des voies urinaires": {
        "icd10": "N39.0",
        "symptoms": ["Dysurie", "Polyurie", "Fièvre", "Douleur abdominale", "Urinée trouble"],
        "medications": ["Nitrofurantoin", "Ciprofloxacin", "Trimethoprim", "Amoxicillin", "Cephalexin"],
        "medical_specialty": "Médecine interne",
    },
    "Bronchite aiguë": {
        "icd10": "J20.9",
        "symptoms": ["Toux", "Fièvre", "Fatigue", "Essoufflement", "Douleur thoracique"],
        "medications": ["Albuterol", "Guaifenesin", "Dextromethorphan", "Ibuprofen", "Azithromycin"],
        "medical_specialty": "Pneumologie",
    },
    "Anémie": {
        "icd10": "D64.9",
        "symptoms": ["Fatigue", "Faiblesse", "Vertiges", "Céphalées", "Essoufflement"],
        "medications": ["Ferrous Sulfate", "Vitamin B12", "Folic Acid", "Erythropoietin"],
        "medical_specialty": "Hématologie",
    },
    "Migraine": {
        "icd10": "G43.909",
        "symptoms": ["Céphalées", "Nausées", "Photophobie", "Vision floue", "Vertiges"],
        "medications": ["Sumatriptan", "Ibuprofen", "Topiramate", "Propranolol", "Amitriptyline"],
        "medical_specialty": "Neurologie",
    },
    "Accident vasculaire cérébral": {
        "icd10": "I63.9",
        "symptoms": ["Engourdissement", "Confusion", "Difficulté à avaler", "Vision floue", "Faiblesse"],
        "medications": ["Aspirin", "Clopidogrel", "Alteplase", "Warfarin", "Atorvastatin"],
        "medical_specialty": "Neurologie",
    },
    "Maladie d'Alzheimer": {
        "icd10": "G30.9",
        "symptoms": ["Perte de mémoire", "Confusion", "Anxiété", "Dépression", "Difficulté à avaler"],
        "medications": ["Donepezil", "Memantine", "Rivastigmine", "Galantamine"],
        "medical_specialty": "Neurologie",
    },
    "Cancer du sein": {
        "icd10": "C50.919",
        "symptoms": ["Masse mammaire", "Écoulement mamelonnaire", "Œdème", "Perte de poids", "Fatigue"],
        "medications": ["Tamoxifen", "Anastrozole", "Trastuzumab", "Chemotherapy", "Radiation"],
        "medical_specialty": "Oncologie",
    },
    "Cancer de la prostate": {
        "icd10": "C61",
        "symptoms": ["Dysurie", "Polyurie", "Faiblesse", "Perte de poids"],
        "medications": ["Leuprolide", "Bicalutamide", "Docetaxel", "Abiraterone", "Enzalutamide"],
        "medical_specialty": "Oncologie",
    },
    "Cancer du poumon": {
        "icd10": "C34.90",
        "symptoms": ["Toux", "Hémoptysie", "Essoufflement", "Douleur thoracique", "Perte de poids"],
        "medications": ["Carboplatin", "Paclitaxel", "Pembrolizumab", "Erlotinib", "Chemotherapy"],
        "medical_specialty": "Oncologie",
    },
    "COVID-19": {
        "icd10": "U07.1",
        "symptoms": ["Fièvre", "Toux", "Fatigue", "Perte d'odorat", "Perte de goût", "Essoufflement"],
        "medications": ["Remdesivir", "Dexamethasone", "Paxlovid", "Molnupiravir"],
        "medical_specialty": "Maladies infectieuses",
    },
    "Grippe": {
        "icd10": "J11.1",
        "symptoms": ["Fièvre", "Toux", "Mal de gorge", "Myalgies", "Fatigue", "Céphalées"],
        "medications": ["Oseltamivir", "Zanamivir", "Baloxavir", "Ibuprofen", "Acetaminophen"],
        "medical_specialty": "Médecine interne",
    },
    "Ostéoporose": {
        "icd10": "M81.0",
        "symptoms": ["Mal de dos", "Perte osseuse", "Faiblesse"],
        "medications": ["Alendronate", "Risedronate", "Denosumab", "Calcium Carbonate", "Vitamin D"],
        "medical_specialty": "Endocrinologie",
    },
    "Maladie artérielle périphérique": {
        "icd10": "I73.9",
        "symptoms": ["Douleur aux jambes", "Engourdissement", "Faiblesse", "Extrémités froides"],
        "medications": ["Cilostazol", "Aspirin", "Clopidogrel", "Atorvastatin", "Pentoxifylline"],
        "medical_specialty": "Chirurgie vasculaire",
    },
    "Angine de poitrine": {
        "icd10": "I20.9",
        "symptoms": ["Douleur thoracique", "Essoufflement", "Fatigue", "Nausées", "Sudation"],
        "medications": ["Nitroglycerin", "Aspirin", "Metoprolol", "Amlodipine", "Atorvastatin"],
        "medical_specialty": "Cardiologie",
    },
    "Hyperthyroïdie": {
        "icd10": "E05.90",
        "symptoms": ["Perte de poids", "Palpitations", "Anxiété", "Tremblements", "Intolérance à la chaleur"],
        "medications": ["Methimazole", "Propylthiouracil", "Propranolol", "Radioactive Iodine", "Levothyroxine"],
        "medical_specialty": "Endocrinologie",
    },
    "Goutte": {
        "icd10": "M10.9",
        "symptoms": ["Douleur articulaire", "Œdème", "Rougeur", "Tophus", "Mobilité limitée"],
        "medications": ["Allopurinol", "Colchicine", "Indomethacin", "Febuxostat", "Probenecid"],
        "medical_specialty": "Rhumatologie",
    },
    "Sclérose en plaques": {
        "icd10": "G35",
        "symptoms": ["Fatigue", "Engourdissement", "Problèmes de vision", "Problèmes d'équilibre", "Faiblesse musculaire"],
        "medications": ["Interferon Beta", "Glatiramer Acetate", "Fingolimod", "Natalizumab", "Ocrelizumab"],
        "medical_specialty": "Neurologie",
    },
    "Maladie de Parkinson": {
        "icd10": "G20",
        "symptoms": ["Tremblements", "Bradykinésie", "Rigidité", "Instabilité posturale", "Modifications de la parole"],
        "medications": ["Levodopa", "Carbidopa", "Pramipexole", "Selegiline", "Amantadine"],
        "medical_specialty": "Neurologie",
    },
    "Épilepsie": {
        "icd10": "G40.909",
        "symptoms": ["Crises", "Perte de conscience", "Confusion", "Regard fixe", "Convulsions"],
        "medications": ["Carbamazepine", "Valproate", "Lamotrigine", "Levetiracetam", "Phenytoin"],
        "medical_specialty": "Neurologie",
    },
    "Trouble bipolaire": {
        "icd10": "F31.9",
        "symptoms": ["Sautes d'humeur", "Manie", "Dépression", "Irritabilité", "Insomnie"],
        "medications": ["Lithium", "Valproate", "Olanzapine", "Quetiapine", "Lamotrigine"],
        "medical_specialty": "Psychiatrie",
    },
    "Schizophrénie": {
        "icd10": "F20.9",
        "symptoms": ["Hallucinations", "Délires", "Pensée désorganisée", "Symptômes négatifs", "Troubles cognitifs"],
        "medications": ["Risperidone", "Olanzapine", "Quetiapine", "Aripiprazole", "Haloperidol"],
        "medical_specialty": "Psychiatrie",
    },
    "Trouble déficitaire de l'attention avec hyperactivité": {
        "icd10": "F90.9",
        "symptoms": ["Inattention", "Hyperactivité", "Impulsivité", "Désorganisation", "Oubli"],
        "medications": ["Methylphenidate", "Amphetamine", "Atomoxetine", "Guanfacine", "Clonidine"],
        "medical_specialty": "Psychiatrie",
    },
    "Trouble du spectre autistique": {
        "icd10": "F84.0",
        "symptoms": ["Altération sociale", "Difficultés de communication", "Comportements répétitifs", "Sensibilités sensorielles", "Intérêts restreints"],
        "medications": ["Risperidone", "Aripiprazole", "SSRIs", "Stimulants", "Anticonvulsants"],
        "medical_specialty": "Psychiatrie",
    },
    "Maladie de Crohn": {
        "icd10": "K50.90",
        "symptoms": ["Douleur abdominale", "Diarrhée", "Perte de poids", "Fatigue", "Sang dans les selles"],
        "medications": ["Mesalamine", "Prednisone", "Azathioprine", "Infliximab", "Adalimumab"],
        "medical_specialty": "Gastroentérologie",
    },
    "Colite ulcéreuse": {
        "icd10": "K51.90",
        "symptoms": ["Diarrhée sanglante", "Douleur abdominale", "Urgence", "Perte de poids", "Fatigue"],
        "medications": ["Mesalamine", "Prednisone", "Azathioprine", "Infliximab", "Vedolizumab"],
        "medical_specialty": "Gastroentérologie",
    },
    "Syndrome du côlon irritable": {
        "icd10": "K58.9",
        "symptoms": ["Douleur abdominale", "Ballonnements", "Diarrhée", "Constipation", "Gaz"],
        "medications": ["Loperamide", "Lubiprostone", "Linaclotide", "Dicyclomine", "Rifaximin"],
        "medical_specialty": "Gastroentérologie",
    },
    "Maladie cœliaque": {
        "icd10": "K90.0",
        "symptoms": ["Douleur abdominale", "Diarrhée", "Ballonnements", "Fatigue", "Perte de poids"],
        "medications": ["No Medications", "Gluten-Free Diet", "Vitamin Supplements", "Iron Supplements", "Probiotics"],
        "medical_specialty": "Gastroentérologie",
    },
    "Cirrhose": {
        "icd10": "K74.60",
        "symptoms": ["Fatigue", "Ictère", "Gonflement abdominal", "Confusion", "Ecchymoses faciles"],
        "medications": ["Lactulose", "Propranolol", "Diuretics", "Vitamin Supplements", "Antibiotics"],
        "medical_specialty": "Gastroentérologie",
    },
    "Hépatite C": {
        "icd10": "B18.2",
        "symptoms": ["Fatigue", "Ictère", "Douleur abdominale", "Perte d'appétit", "Nausées"],
        "medications": ["Sofosbuvir", "Ledipasvir", "Glecaprevir", "Pibrentasvir", "Ribavirin"],
        "medical_specialty": "Gastroentérologie",
    },
    "VIH/SIDA": {
        "icd10": "B20",
        "symptoms": ["Fièvre", "Fatigue", "Perte de poids", "Ganglions lymphatiques gonflés", "Infections récurrentes"],
        "medications": ["Tenofovir", "Emtricitabine", "Dolutegravir", "Efavirenz", "Ritonavir"],
        "medical_specialty": "Maladies infectieuses",
    },
    "Tuberculose": {
        "icd10": "A15.0",
        "symptoms": ["Toux", "Fièvre", "Sudations nocturnes", "Perte de poids", "Douleur thoracique"],
        "medications": ["Isoniazid", "Rifampin", "Pyrazinamide", "Ethambutol", "Streptomycin"],
        "medical_specialty": "Pneumologie",
    },
    "Sepsie": {
        "icd10": "A41.9",
        "symptoms": ["Fièvre", "Tachycardie", "Confusion", "Essoufflement", "Hypotension"],
        "medications": ["Broad-Spectrum Antibiotics", "IV Fluids", "Vasopressors", "Corticosteroids", "Insulin"],
        "medical_specialty": "Soins intensifs",
    },
    "Thrombose veineuse profonde": {
        "icd10": "I82.409",
        "symptoms": ["Douleur à la jambe", "Œdème", "Rougeur", "Chaleur", "Crampes"],
        "medications": ["Heparin", "Warfarin", "Rivaroxaban", "Apixaban", "Enoxaparin"],
        "medical_specialty": "Médecine vasculaire",
    },
    "Embolie pulmonaire": {
        "icd10": "I26.99",
        "symptoms": ["Essoufflement", "Douleur thoracique", "Toux", "Hémoptysie", "Tachycardie"],
        "medications": ["Heparin", "Warfarin", "Rivaroxaban", "Apixaban", "Thrombolytics"],
        "medical_specialty": "Pneumologie",
    },
    "Anévrisme aortique": {
        "icd10": "I71.9",
        "symptoms": ["Douleur abdominale", "Mal de dos", "Masse pulsatile", "Hypotension", "Syncope"],
        "medications": ["Beta-Blockers", "Statins", "ACE Inhibitors", "Antihypertensives", "Pain Relievers"],
        "medical_specialty": "Chirurgie vasculaire",
    },
    "Maladie valvulaire cardiaque": {
        "icd10": "I38",
        "symptoms": ["Essoufflement", "Fatigue", "Douleur thoracique", "Palpitations", "Œdème"],
        "medications": ["Diuretics", "ACE Inhibitors", "Beta-Blockers", "Anticoagulants", "Vasodilators"],
        "medical_specialty": "Cardiologie",
    },
    "Cardiomyopathie": {
        "icd10": "I42.9",
        "symptoms": ["Fatigue", "Essoufflement", "Œdème", "Arythmie", "Douleur thoracique"],
        "medications": ["ACE Inhibitors", "Beta-Blockers", "Diuretics", "Aldosterone Antagonists", "Digoxin"],
        "medical_specialty": "Cardiologie",
    },
    "Endocardite": {
        "icd10": "I33.0",
        "symptoms": ["Fièvre", "Fatigue", "Essoufflement", "Sudations nocturnes", "Douleur articulaire"],
        "medications": ["Penicillin", "Vancomycin", "Gentamicin", "Ampicillin", "Ceftriaxone"],
        "medical_specialty": "Cardiologie",
    },
    "Péricardite": {
        "icd10": "I30.9",
        "symptoms": ["Douleur thoracique", "Fièvre", "Fatigue", "Essoufflement", "Toux"],
        "medications": ["Ibuprofen", "Colchicine", "Prednisone", "Aspirin", "Antibiotics"],
        "medical_specialty": "Cardiologie",
    },
    "Infarctus du myocarde": {
        "icd10": "I21.9",
        "symptoms": ["Douleur thoracique", "Essoufflement", "Nausées", "Sudation", "Étourdissements"],
        "medications": ["Aspirin", "Clopidogrel", "Heparin", "Beta-Blockers", "ACE Inhibitors"],
        "medical_specialty": "Cardiologie",
    },
    "Cardiopathie congénitale": {
        "icd10": "Q24.9",
        "symptoms": ["Cyanose", "Essoufflement", "Fatigue", "Croissance faible", "Souffles cardiaques"],
        "medications": ["Diuretics", "ACE Inhibitors", "Beta-Blockers", "Prostaglandin E1", "Antibiotics"],
        "medical_specialty": "Cardiologie",
    },
    "Neuropathie périphérique": {
        "icd10": "G62.9",
        "symptoms": ["Engourdissement", "Picotements", "Douleur", "Faiblesse", "Sensation de brûlure"],
        "medications": ["Gabapentin", "Pregabalin", "Duloxetine", "Amitriptyline", "Capsaicin"],
        "medical_specialty": "Neurologie",
    },
    "Apnée du sommeil": {
        "icd10": "G47.30",
        "symptoms": ["Ronflements", "Somnolence diurne", "Fatigue", "Céphalées matinales", "Irritabilité"],
        "medications": ["CPAP Therapy", "Modafinil", "Armodafinil", "Acetazolamide", "Theophylline"],
        "medical_specialty": "Pneumologie",
    },
    "Narcolepsie": {
        "icd10": "G47.419",
        "symptoms": ["Somnolence diurne excessive", "Cataplexie", "Paralysie du sommeil", "Hallucinations", "Sommeil fragmenté"],
        "medications": ["Modafinil", "Sodium Oxybate", "Pitolisant", "Methylphenidate", "Amphetamine"],
        "medical_specialty": "Neurologie",
    },
    "Syndrome des jambes sans repos": {
        "icd10": "G25.81",
        "symptoms": ["Envie de bouger les jambes", "Sensations inconfortables", "Aggravation nocturne", "Troubles du sommeil", "Soulagement par le mouvement"],
        "medications": ["Pramipexole", "Ropinirole", "Gabapentin", "Iron Supplements", "Clonazepam"],
        "medical_specialty": "Neurologie",
    },
    "Fibromyalgie": {
        "icd10": "M79.7",
        "symptoms": ["Douleur généralisée", "Fatigue", "Troubles du sommeil", "Difficultés cognitives", "Céphalées"],
        "medications": ["Duloxetine", "Pregabalin", "Milnacipran", "Amitriptyline", "Cyclobenzaprine"],
        "medical_specialty": "Rhumatologie",
    },
    "Lupus": {
        "icd10": "M32.9",
        "symptoms": ["Fatigue", "Douleur articulaire", "Éruption cutanée", "Fièvre", "Photosensibilité"],
        "medications": ["Hydroxychloroquine", "Prednisone", "Methotrexate", "Mycophenolate", "Belimumab"],
        "medical_specialty": "Rhumatologie",
    },
    "Sclérodermie": {
        "icd10": "M34.9",
        "symptoms": ["Épaississement de la peau", "Phénomène de Raynaud", "Douleur articulaire", "Essoufflement", "Problèmes gastro-intestinaux"],
        "medications": ["Methotrexate", "Mycophenolate", "Cyclophosphamide", "Nifedipine", "Proton Pump Inhibitors"],
        "medical_specialty": "Rhumatologie",
    },
    "Syndrome de Sjögren": {
        "icd10": "M35.00",
        "symptoms": ["Bouche sèche", "Yeux secs", "Fatigue", "Douleur articulaire", "Glandes salivaires gonflées"],
        "medications": ["Pilocarpine", "Cevimeline", "Hydroxychloroquine", "Cyclosporine", "Artificial Tears"],
        "medical_specialty": "Rhumatologie",
    },
    "Psoriasis": {
        "icd10": "L40.9",
        "symptoms": ["Plaques rouges", "Démangeaisons", "Desquamation", "Peau épaissie", "Douleur articulaire"],
        "medications": ["Methotrexate", "Cyclosporine", "Adalimumab", "Topical Corticosteroids", "Vitamin D Analogues"],
        "medical_specialty": "Dermatologie",
    },
    "Eczéma": {
        "icd10": "L30.9",
        "symptoms": ["Démangeaisons", "Rougeur", "Peau sèche", "Éruption", "Œdème"],
        "medications": ["Hydrocortisone", "Tacrolimus", "Pimecrolimus", "Dupilumab", "Moisturizers"],
        "medical_specialty": "Dermatologie",
    },
    "Rosacée": {
        "icd10": "L71.9",
        "symptoms": ["Rougeur faciale", "Boutons", "Vaisseaux sanguins visibles", "Irritation oculaire", "Œdème"],
        "medications": ["Metronidazole", "Azelaic Acid", "Ivermectin", "Doxycycline", "Brimonidine"],
        "medical_specialty": "Dermatologie",
    },
    "Acné vulgaire": {
        "icd10": "L70.0",
        "symptoms": ["Boutons", "Points noirs", "Points blancs", "Kystes", "Cicatrices"],
        "medications": ["Benzoyl Peroxide", "Salicylic Acid", "Retinoids", "Antibiotics", "Isotretinoin"],
        "medical_specialty": "Dermatologie",
    },
    "Mélanome": {
        "icd10": "C43.9",
        "symptoms": ["Grain de beauté changeant", "Forme asymétrique", "Bords irréguliers", "Variation de couleur", "Augmentation de diamètre"],
        "medications": ["Pembrolizumab", "Nivolumab", "Ipilimumab", "Dacarbazine", "Trametinib"],
        "medical_specialty": "Oncologie",
    },
    "Carcinome basocellulaire": {
        "icd10": "C44.91",
        "symptoms": ["Bosse perlée", "Plaie non cicatrisante", "Zone cicatricielle", "Plaque rouge", "Saignement"],
        "medications": ["Imiquimod", "Fluorouracil", "Vismodegib", "Sonidegib", "Photodynamic Therapy"],
        "medical_specialty": "Dermatologie",
    },
    "Carcinome spinocellulaire": {
        "icd10": "C44.92",
        "symptoms": ["Plaque rouge rugueuse", "Plaie ouverte", "Surface croûteuse", "Croissance avec dépression centrale", "Démangeaisons"],
        "medications": ["Fluorouracil", "Imiquimod", "Pembrolizumab", "Cemiplimab", "Chemotherapy"],
        "medical_specialty": "Dermatologie",
    },
    "Leucémie": {
        "icd10": "C95.90",
        "symptoms": ["Fatigue", "Fièvre", "Perte de poids", "Ecchymoses faciles", "Infections récurrentes"],
        "medications": ["Imatinib", "Cytarabine", "Daunorubicin", "Vincristine", "Hydroxyurea"],
        "medical_specialty": "Hématologie",
    },
    "Lymphome": {
        "icd10": "C85.90",
        "symptoms": ["Ganglions lymphatiques gonflés", "Fièvre", "Sudations nocturnes", "Perte de poids", "Fatigue"],
        "medications": ["Rituximab", "Cyclophosphamide", "Doxorubicin", "Vincristine", "Prednisone"],
        "medical_specialty": "Oncologie",
    },
    "Myélome": {
        "icd10": "C90.00",
        "symptoms": ["Douleur osseuse", "Fatigue", "Anémie", "Infections récurrentes", "Problèmes rénaux"],
        "medications": ["Bortezomib", "Lenalidomide", "Dexamethasone", "Daratumumab", "Melphalan"],
        "medical_specialty": "Hématologie",
    },
    "Cancer du côlon": {
        "icd10": "C18.9",
        "symptoms": ["Douleur abdominale", "Sang dans les selles", "Changement des habitudes intestinales", "Perte de poids", "Fatigue"],
        "medications": ["Fluorouracil", "Oxaliplatin", "Capecitabine", "Bevacizumab", "Cetuximab"],
        "medical_specialty": "Oncologie",
    },
    "Cancer du pancréas": {
        "icd10": "C25.9",
        "symptoms": ["Douleur abdominale", "Ictère", "Perte de poids", "Perte d'appétit", "Nausées"],
        "medications": ["Gemcitabine", "Paclitaxel", "Erlotinib", "FOLFIRINOX", "Capecitabine"],
        "medical_specialty": "Oncologie",
    },
    "Cancer du rein": {
        "icd10": "C64.9",
        "symptoms": ["Hématurie", "Mal de dos", "Perte de poids", "Fatigue", "Fièvre"],
        "medications": ["Sunitinib", "Pazopanib", "Axitinib", "Nivolumab", "Cabozantinib"],
        "medical_specialty": "Oncologie",
    },
    "Cancer de la vessie": {
        "icd10": "C67.9",
        "symptoms": ["Hématurie", "Polyurie", "Dysurie", "Mal de dos", "Douleur pelvienne"],
        "medications": ["BCG", "Mitomycin", "Gemcitabine", "Cisplatin", "Pembrolizumab"],
        "medical_specialty": "Urologie",
    },
    "Cancer de l'ovaire": {
        "icd10": "C56.9",
        "symptoms": ["Ballonnements abdominaux", "Douleur pelvienne", "Perte d'appétit", "Polyurie", "Fatigue"],
        "medications": ["Carboplatin", "Paclitaxel", "Bevacizumab", "Olaparib", "Doxorubicin"],
        "medical_specialty": "Oncologie",
    },
    "Cancer de l'endomètre": {
        "icd10": "C54.1",
        "symptoms": ["Saignements vaginaux anormaux", "Douleur pelvienne", "Perte de poids", "Fatigue", "Ballonnements"],
        "medications": ["Progesterone", "Tamoxifen", "Carboplatin", "Paclitaxel", "Doxorubicin"],
        "medical_specialty": "Oncologie",
    },
    "Cancer de la thyroïde": {
        "icd10": "C73",
        "symptoms": ["Masse au cou", "Enrouement", "Difficulté à avaler", "Douleur au cou", "Ganglions lymphatiques gonflés"],
        "medications": ["Levothyroxine", "Radioactive Iodine", "Sorafenib", "Lenvatinib", "Cabozantinib"],
        "medical_specialty": "Endocrinologie",
    },
    "Tumeur cérébrale": {
        "icd10": "C71.9",
        "symptoms": ["Céphalées", "Crises", "Nausées", "Changements de vision", "Troubles cognitifs"],
        "medications": ["Temozolomide", "Bevacizumab", "Carmustine", "Lomustine", "Dexamethasone"],
        "medical_specialty": "Neurologie",
    },
    "Glaucome": {
        "icd10": "H40.9",
        "symptoms": ["Perte de vision", "Douleur oculaire", "Halo autour des lumières", "Yeux rouges", "Nausées"],
        "medications": ["Timolol", "Latanoprost", "Brimonidine", "Acetazolamide", "Pilocarpine"],
        "medical_specialty": "Ophtalmologie",
    },
    "Dégénérescence maculaire": {
        "icd10": "H35.30",
        "symptoms": ["Vision floue", "Perte de vision centrale", "Vision distordue", "Taches sombres", "Décoloration des couleurs"],
        "medications": ["Ranibizumab", "Aflibercept", "Bevacizumab", "Verteporfin", "Vitamin Supplements"],
        "medical_specialty": "Ophtalmologie",
    },
    "Cataractes": {
        "icd10": "H26.9",
        "symptoms": ["Vision floue", "Sensibilité à l'éblouissement", "Vision nocturne faible", "Couleurs fanées", "Diplopie"],
        "medications": ["No Medications", "Surgery", "Eyeglasses", "Anti-Glare Lenses", "Magnifiers"],
        "medical_specialty": "Ophtalmologie",
    },
    "Rétinopathie diabétique": {
        "icd10": "E11.319",
        "symptoms": ["Vision floue", "Flotteurs", "Perte de vision", "Changements de couleur", "Zones sombres"],
        "medications": ["Ranibizumab", "Aflibercept", "Bevacizumab", "Laser Therapy", "Vitrectomy"],
        "medical_specialty": "Ophtalmologie",
    },
    "Perte auditive": {
        "icd10": "H91.90",
        "symptoms": ["Difficulté à entendre", "Sons étouffés", "Acouphènes", "Douleur à l'oreille", "Problèmes d'équilibre"],
        "medications": ["No Medications", "Hearing Aids", "Cochlear Implants", "Steroids", "Antibiotics"],
        "medical_specialty": "Oto-rhino-laryngologie",
    },
    "Maladie de Ménière": {
        "icd10": "H81.09",
        "symptoms": ["Vertiges", "Perte auditive", "Acouphènes", "Plénitude auriculaire", "Nausées"],
        "medications": ["Meclizine", "Diuretics", "Betahistine", "Steroids", "Gentamicin"],
        "medical_specialty": "Oto-rhino-laryngologie",
    },
    "Hyperplasie bénigne de la prostate": {
        "icd10": "N40.0",
        "symptoms": ["Polyurie", "Jet faible", "Urgence", "Nycturie", "Vidange incomplète"],
        "medications": ["Tamsulosin", "Finasteride", "Dutasteride", "Terazosin", "Sildenafil"],
        "medical_specialty": "Urologie",
    },
    "Dysfonction érectile": {
        "icd10": "N52.9",
        "symptoms": ["Incapacité à maintenir l'érection", "Libido réduite", "Éjaculation prématurée", "Stress", "Fatigue"],
        "medications": ["Sildenafil", "Tadalafil", "Vardenafil", "Alprostadil", "Testosterone"],
        "medical_specialty": "Urologie",
    },
    "Syndrome des ovaires polykystiques": {
        "icd10": "E28.2",
        "symptoms": ["Règles irrégulières", "Hirsutisme", "Acné", "Prise de poids", "Infertilité"],
        "medications": ["Combined Oral Contraceptives", "Metformin", "Spironolactone", "Clomiphene", "Letrozole"],
        "medical_specialty": "Endocrinologie",
    },
    "Endométriose": {
        "icd10": "N80.9",
        "symptoms": ["Douleur pelvienne", "Dysménorrhée", "Infertilité", "Dyspareunie", "Règles abondantes"],
        "medications": ["Ibuprofen", "Combined Oral Contraceptives", "Progestins", "GnRH Agonists", "Danazol"],
        "medical_specialty": "Gynécologie",
    },
    "Fibromes utérins": {
        "icd10": "D25.9",
        "symptoms": ["Saignements menstruels abondants", "Douleur pelvienne", "Polyurie", "Constipation", "Mal de dos"],
        "medications": ["GnRH Agonists", "Progestins", "Tranexamic Acid", "Ibuprofen", "Ulipristal Acetate"],
        "medical_specialty": "Gynécologie",
    },
    "Prééclampsie": {
        "icd10": "O14.90",
        "symptoms": ["Hypertension artérielle", "Protéinurie", "Œdème", "Céphalées", "Changements de vision"],
        "medications": ["Magnesium Sulfate", "Labetalol", "Hydralazine", "Nifedipine", "Delivery"],
        "medical_specialty": "Obstétrique",
    },
    "Diabète gestationnel": {
        "icd10": "O24.419",
        "symptoms": ["Soif augmentée", "Polyurie", "Fatigue", "Vision floue", "Nausées"],
        "medications": ["Insulin", "Metformin", "Glyburide", "Diet Control", "Exercise"],
        "medical_specialty": "Obstétrique",
    },
    "Carence en vitamine D": {
        "icd10": "E55.9",
        "symptoms": ["Fatigue", "Douleur osseuse", "Faiblesse musculaire", "Dépression", "Perte de cheveux"],
        "medications": ["Vitamin D Supplements", "Cholecalciferol", "Ergocalciferol", "Calcium Supplements", "Sun Exposure"],
        "medical_specialty": "Endocrinologie",
    },
    "Anémie ferriprive": {
        "icd10": "D50.9",
        "symptoms": ["Fatigue", "Pâleur", "Essoufflement", "Vertiges", "Mains froides"],
        "medications": ["Ferrous Sulfate", "Ferrous Gluconate", "Iron Infusions", "Vitamin C", "Folic Acid"],
        "medical_specialty": "Hématologie",
    },
    "Anémie pernicieuse": {
        "icd10": "D51.0",
        "symptoms": ["Fatigue", "Faiblesse", "Pâleur", "Engourdissement", "Changements cognitifs"],
        "medications": ["Vitamin B12 Injections", "Oral B12 Supplements", "Folic Acid", "Iron Supplements", "Erythropoietin"],
        "medical_specialty": "Hématologie",
    },
    "Drépanocytose": {
        "icd10": "D57.1",
        "symptoms": ["Crises douloureuses", "Anémie", "Fatigue", "Ictère", "Œdème"],
        "medications": ["Hydroxyurea", "Pain Relievers", "Antibiotics", "Blood Transfusions", "Voxelotor"],
        "medical_specialty": "Hématologie",
    },
    "Hémophilie": {
        "icd10": "D68.311",
        "symptoms": ["Saignements prolongés", "Douleur articulaire", "Ecchymoses", "Hémarthrose", "Épistaxis"],
        "medications": ["Factor VIII", "Factor IX", "Desmopressin", "Antifibrinolytics", "Emicizumab"],
        "medical_specialty": "Hématologie",
    },
    "Thrombocytopénie": {
        "icd10": "D69.6",
        "symptoms": ["Ecchymoses", "Saignements gingivaux", "Épistaxis", "Pétéchies", "Règles abondantes"],
        "medications": ["Corticosteroids", "IVIG", "Romiplostim", "Eltrombopag", "Splenectomy"],
        "medical_specialty": "Hématologie",
    },
    "Leucopénie": {
        "icd10": "D72.819",
        "symptoms": ["Infections fréquentes", "Fièvre", "Fatigue", "Ulcères buccaux", "Mal de gorge"],
        "medications": ["G-CSF", "GM-CSF", "Antibiotics", "Antivirals", "Vitamin Supplements"],
        "medical_specialty": "Hématologie",
    },
    "Diverticulite": {
        "icd10": "K57.92",
        "symptoms": ["Douleur abdominale", "Fièvre", "Nausées", "Constipation", "Diarrhée"],
        "medications": ["Ciprofloxacin", "Metronidazole", "Augmentin", "Ibuprofen", "Acetaminophen"],
        "medical_specialty": "Gastroentérologie",
    },
    "Appendicite": {
        "icd10": "K35.80",
        "symptoms": ["Douleur abdominale", "Nausées", "Vomissements", "Fièvre", "Perte d'appétit"],
        "medications": ["Antibiotics", "Pain Relievers", "IV Fluids", "Surgery", "Anti-Nausea"],
        "medical_specialty": "Chirurgie générale",
    },
    "Cholécystite": {
        "icd10": "K81.0",
        "symptoms": ["Douleur abdominale", "Nausées", "Vomissements", "Fièvre", "Ictère"],
        "medications": ["Antibiotics", "Pain Relievers", "Ursodiol", "IV Fluids", "Surgery"],
        "medical_specialty": "Chirurgie générale",
    },
    "Pancréatite": {
        "icd10": "K85.90",
        "symptoms": ["Douleur abdominale", "Nausées", "Vomissements", "Fièvre", "Pouls rapide"],
        "medications": ["IV Fluids", "Pain Relievers", "Antibiotics", "Enzyme Supplements", "Insulin"],
        "medical_specialty": "Gastroentérologie",
    },
    "Maladie ulcéreuse gastro-duodénale": {
        "icd10": "K27.9",
        "symptoms": ["Douleur abdominale", "Ballonnements", "Nausées", "Vomissements", "Brûlures d'estomac"],
        "medications": ["Omeprazole", "Ranitidine", "Amoxicillin", "Clarithromycin", "Sucralfate"],
        "medical_specialty": "Gastroentérologie",
    },
    "Gastrite": {
        "icd10": "K29.70",
        "symptoms": ["Douleur abdominale", "Nausées", "Vomissements", "Ballonnements", "Perte d'appétit"],
        "medications": ["Omeprazole", "Ranitidine", "Antacids", "Sucralfate", "Antibiotics"],
        "medical_specialty": "Gastroentérologie",
    },
    "Œsophagite": {
        "icd10": "K20.90",
        "symptoms": ["Brûlures d'estomac", "Difficulté à avaler", "Douleur thoracique", "Régurgitation", "Nausées"],
        "medications": ["Omeprazole", "Ranitidine", "Sucralfate", "Antacids", "Prokinetics"],
        "medical_specialty": "Gastroentérologie",
    },
    "Œsophage de Barrett": {
        "icd10": "K22.70",
        "symptoms": ["Brûlures d'estomac", "Régurgitation", "Difficulté à avaler", "Douleur thoracique", "Nausées"],
        "medications": ["Omeprazole", "Esomeprazole", "Antacids", "H2 Blockers", "Proton Pump Inhibitors"],
        "medical_specialty": "Gastroentérologie",
    },
    "Hernie hiatale": {
        "icd10": "K44.9",
        "symptoms": ["Brûlures d'estomac", "Douleur thoracique", "Difficulté à avaler", "Régurgitation", "Ballonnements"],
        "medications": ["Antacids", "H2 Blockers", "Proton Pump Inhibitors", "Prokinetics", "Surgery"],
        "medical_specialty": "Gastroentérologie",
    },
    "Hémorroïdes": {
        "icd10": "K64.9",
        "symptoms": ["Saignement rectal", "Démangeaisons", "Douleur", "Œdème", "Inconfort"],
        "medications": ["Hydrocortisone", "Witch Hazel", "Lidocaine", "Stool Softeners", "Fiber Supplements"],
        "medical_specialty": "Gastroentérologie",
    },
    "Fissure anale": {
        "icd10": "K60.2",
        "symptoms": ["Douleur lors des selles", "Saignement", "Démangeaisons", "Spasmes", "Constipation"],
        "medications": ["Nitroglycerin Ointment", "Diltiazem", "Botulinum Toxin", "Stool Softeners", "Pain Relievers"],
        "medical_specialty": "Gastroentérologie",
    },
    "Incontinence fécale": {
        "icd10": "R15.9",
        "symptoms": ["Selles involontaires", "Urgence", "Fuites", "Diarrhée", "Constipation"],
        "medications": ["Loperamide", "Bismuth Subsalicylate", "Fiber Supplements", "Antidiarrheals", "Cholestyramine"],
        "medical_specialty": "Gastroentérologie",
    },
    "Insuffisance rénale aiguë": {
        "icd10": "N17.9",
        "symptoms": ["Oligurie", "Œdème", "Fatigue", "Nausées", "Confusion"],
        "medications": ["Diuretics", "IV Fluids", "Dialysis", "Electrolyte Management", "Vasopressors"],
        "medical_specialty": "Néphrologie",
    },
    "Syndrome néphrotique": {
        "icd10": "N04.9",
        "symptoms": ["Œdème", "Protéinurie", "Hypoalbuminémie", "Hyperlipidémie", "Fatigue"],
        "medications": ["ACE Inhibitors", "Diuretics", "Statins", "Corticosteroids", "Immunosuppressants"],
        "medical_specialty": "Néphrologie",
    },
    "Maladie polykystique des reins": {
        "icd10": "Q61.3",
        "symptoms": ["Douleur abdominale", "Hypertension", "Hématurie", "Mal de dos", "Infections fréquentes"],
        "medications": ["ACE Inhibitors", "Diuretics", "Pain Relievers", "Antibiotics", "Tolvaptan"],
        "medical_specialty": "Néphrologie",
    },
    "Lithiase rénale": {
        "icd10": "N20.0",
        "symptoms": ["Douleur sévère", "Hématurie", "Nausées", "Vomissements", "Polyurie"],
        "medications": ["Pain Relievers", "Alpha Blockers", "Allopurinol", "Potassium Citrate", "Thiazides"],
        "medical_specialty": "Urologie",
    },
    "Cystite interstitielle": {
        "icd10": "N30.10",
        "symptoms": ["Douleur vésicale", "Urgence", "Pollakiurie", "Douleur pelvienne", "Nycturie"],
        "medications": ["Pentosan Polysulfate", "Amitriptyline", "Hydroxyzine", "Antihistamines", "Bladder Instillations"],
        "medical_specialty": "Urologie",
    },
    "Vessie hyperactive": {
        "icd10": "N32.81",
        "symptoms": ["Urgence", "Pollakiurie", "Nycturie", "Incontinence", "Spasmes vésicaux"],
        "medications": ["Oxybutynin", "Tolterodine", "Mirabegron", "Solifenacin", "Darifenacin"],
        "medical_specialty": "Urologie",
    },
    "Incontinence d'effort": {
        "icd10": "N39.3",
        "symptoms": ["Fuite urinaire à la toux", "Éternuement", "Exercice", "Levage", "Rire"],
        "medications": ["Duloxetine", "Estrogen Cream", "No Medications", "Pelvic Floor Exercises", "Surgery"],
        "medical_specialty": "Urologie",
    },
    "Incontinence par urgenturie": {
        "icd10": "N39.41",
        "symptoms": ["Envie soudaine d'uriner", "Fuite involontaire", "Pollakiurie", "Nycturie", "Spasmes vésicaux"],
        "medications": ["Oxybutynin", "Tolterodine", "Mirabegron", "Solifenacin", "Botulinum Toxin"],
        "medical_specialty": "Urologie",
    },
    "Pyélonéphrite": {
        "icd10": "N10",
        "symptoms": ["Fièvre", "Douleur lombaire", "Nausées", "Vomissements", "Polyurie"],
        "medications": ["Ciprofloxacin", "Ceftriaxone", "Amoxicillin", "Trimethoprim", "Nitrofurantoin"],
        "medical_specialty": "Néphrologie",
    },
    "Glomérulonéphrite": {
        "icd10": "N05.9",
        "symptoms": ["Hématurie", "Protéinurie", "Œdème", "Hypertension", "Fatigue"],
        "medications": ["Corticosteroids", "Immunosuppressants", "ACE Inhibitors", "Diuretics", "Plasmapheresis"],
        "medical_specialty": "Néphrologie",
    },
    "Sinusite aiguë": {
        "icd10": "J01.90",
        "symptoms": ["Douleur faciale", "Congestion nasale", "Céphalées", "Fièvre", "Toux"],
        "medications": ["Amoxicillin", "Augmentin", "Decongestants", "Nasal Steroids", "Pain Relievers"],
        "medical_specialty": "Oto-rhino-laryngologie",
    },
    "Sinusite chronique": {
        "icd10": "J32.9",
        "symptoms": ["Congestion nasale", "Pression faciale", "Écoulement post-nasal", "Céphalées", "Fatigue"],
        "medications": ["Nasal Steroids", "Antibiotics", "Saline Irrigation", "Decongestants", "Surgery"],
        "medical_specialty": "Oto-rhino-laryngologie",
    },
    "Rhinite allergique": {
        "icd10": "J30.9",
        "symptoms": ["Éternuements", "Écoulement nasal", "Démangeaisons oculaires", "Congestion", "Écoulement post-nasal"],
        "medications": ["Loratadine", "Cetirizine", "Fluticasone", "Montelukast", "Azithromycin"],
        "medical_specialty": "Allergologie",
    },
    "Otite moyenne": {
        "icd10": "H66.90",
        "symptoms": ["Douleur à l'oreille", "Fièvre", "Perte auditive", "Écoulement liquidien", "Irritabilité"],
        "medications": ["Amoxicillin", "Azithromycin", "Ibuprofen", "Acetaminophen", "Decongestants"],
        "medical_specialty": "Oto-rhino-laryngologie",
    },
    "Otite externe": {
        "icd10": "H60.90",
        "symptoms": ["Douleur à l'oreille", "Démangeaisons", "Rougeur", "Œdème", "Écoulement"],
        "medications": ["Ciprofloxacin", "Hydrocortisone", "Neomycin", "Acetic Acid", "Pain Relievers"],
        "medical_specialty": "Oto-rhino-laryngologie",
    },
    "Pharyngite": {
        "icd10": "J02.9",
        "symptoms": ["Mal de gorge", "Fièvre", "Ganglions lymphatiques gonflés", "Céphalées", "Toux"],
        "medications": ["Penicillin", "Amoxicillin", "Azithromycin", "Ibuprofen", "Acetaminophen"],
        "medical_specialty": "Oto-rhino-laryngologie",
    },
    "Amygdalite": {
        "icd10": "J03.90",
        "symptoms": ["Mal de gorge", "Fièvre", "Amygdales gonflées", "Difficulté à avaler", "Céphalées"],
        "medications": ["Penicillin", "Amoxicillin", "Azithromycin", "Ibuprofen", "Acetaminophen"],
        "medical_specialty": "Oto-rhino-laryngologie",
    },
    "Laryngite": {
        "icd10": "J04.0",
        "symptoms": ["Enrouement", "Mal de gorge", "Toux", "Difficulté à parler", "Fièvre"],
        "medications": ["Ibuprofen", "Acetaminophen", "Steam Inhalation", "Voice Rest", "Antibiotics"],
        "medical_specialty": "Oto-rhino-laryngologie",
    },
    "Laryngotrachéite": {
        "icd10": "J05.0",
        "symptoms": ["Toux aboyante", "Stridor", "Enrouement", "Fièvre", "Détresse respiratoire"],
        "medications": ["Dexamethasone", "Epinephrine", "Humidified Air", "Ibuprofen", "Acetaminophen"],
        "medical_specialty": "Pédiatrie",
    },
    "Bronchiolite": {
        "icd10": "J21.9",
        "symptoms": ["Toux", "Sibilants", "Essoufflement", "Fièvre", "Écoulement nasal"],
        "medications": ["Supportive Care", "Oxygen", "Hydration", "Albuterol", "Corticosteroids"],
        "medical_specialty": "Pédiatrie",
    },
    "Emphysème": {
        "icd10": "J43.9",
        "symptoms": ["Essoufflement", "Toux chronique", "Sibilants", "Fatigue", "Perte de poids"],
        "medications": ["Bronchodilators", "Inhaled Steroids", "Oxygen Therapy", "Antibiotics", "Pulmonary Rehab"],
        "medical_specialty": "Pneumologie",
    },
    "Mucoviscidose": {
        "icd10": "E84.9",
        "symptoms": ["Toux persistante", "Sibilants", "Infections récurrentes", "Croissance faible", "Peau salée"],
        "medications": ["Ivacaftor", "Lumacaftor", "Dornase Alfa", "Pancreatic Enzymes", "Antibiotics"],
        "medical_specialty": "Pneumologie",
    },
    "Maladie pulmonaire interstitielle": {
        "icd10": "J84.9",
        "symptoms": ["Essoufflement", "Toux sèche", "Fatigue", "Perte de poids", "Inconfort thoracique"],
        "medications": ["Prednisone", "Azathioprine", "Nintedanib", "Pirfenidone", "Oxygen Therapy"],
        "medical_specialty": "Pneumologie",
    },
    "Sarcoïdose": {
        "icd10": "D86.9",
        "symptoms": ["Fatigue", "Toux", "Essoufflement", "Éruption cutanée", "Douleur articulaire"],
        "medications": ["Prednisone", "Methotrexate", "Hydroxychloroquine", "Infliximab", "Azathioprine"],
        "medical_specialty": "Pneumologie",
    },
    "Épanchement pleural": {
        "icd10": "J90",
        "symptoms": ["Essoufflement", "Douleur thoracique", "Toux", "Fièvre", "Perte de poids"],
        "medications": ["Diuretics", "Antibiotics", "Corticosteroids", "Chemotherapy", "Thoracentesis"],
        "medical_specialty": "Pneumologie",
    },
    "Pneumothorax": {
        "icd10": "J93.9",
        "symptoms": ["Douleur thoracique", "Essoufflement", "Tachycardie", "Cyanose", "Diminution des bruits respiratoires"],
        "medications": ["Oxygen", "Pain Relievers", "Chest Tube", "Surgery", "Pleurodesis"],
        "medical_specialty": "Pneumologie",
    },
    "Hypertension pulmonaire": {
        "icd10": "I27.20",
        "symptoms": ["Essoufflement", "Fatigue", "Douleur thoracique", "Vertiges", "Œdème"],
        "medications": ["Sildenafil", "Bosentan", "Epoprostenol", "Treprostinil", "Riociguat"],
        "medical_specialty": "Pneumologie",
    },
    "Diabète sucré de type 1": {
        "icd10": "E10.9",
        "symptoms": ["Polydipsie", "Polyurie", "Faim extrême", "Perte de poids inexpliquée", "Fatigue"],
        "medications": ["Insulin", "Pramlintide", "Metformin", "Empagliflozin", "Liraglutide"],
        "medical_specialty": "Endocrinologie",
    },
    "Maladie hépatique chronique": {
        "icd10": "K76.9",
        "symptoms": ["Fatigue", "Ictère", "Douleur abdominale", "Œdème des jambes", "Démangeaisons"],
        "medications": ["Diuretics", "Beta Blockers", "Ursodiol", "Antivirals", "Immunosuppressants"],
        "medical_specialty": "Gastroentérologie",
    },
    "Cardiopathie hypertensive": {
        "icd10": "I11.9",
        "symptoms": ["Essoufflement", "Fatigue", "Douleur thoracique", "Palpitations", "Vertiges"],
        "medications": ["Lisinopril", "Metoprolol", "Hydrochlorothiazide", "Amlodipine", "Losartan"],
        "medical_specialty": "Cardiologie",
    },
    "Trouble de stress post-traumatique": {
        "icd10": "F43.1",
        "symptoms": ["Flashbacks", "Cauchemars", "Anxiété sévère", "Comportements d'évitement", "Hypervigilance"],
        "medications": ["Sertraline", "Paroxetine", "Venlafaxine", "Prazosin", "Clonidine"],
        "medical_specialty": "Psychiatrie",
    },
    "Trouble lié à l'usage de substances": {
        "icd10": "F19.9",
        "symptoms": ["Envies", "Perte de contrôle", "Tolérance", "Symptômes de sevrage", "Négligence des responsabilités"],
        "medications": ["Naltrexone", "Acamprosate", "Disulfiram", "Methadone", "Buprenorphine"],
        "medical_specialty": "Psychiatrie",
    },
    "Syndrome de douleur chronique": {
        "icd10": "G89.4",
        "symptoms": ["Douleur persistante", "Fatigue", "Troubles du sommeil", "Dépression", "Mobilité réduite"],
        "medications": ["Gabapentin", "Duloxetine", "Tramadol", "Amitriptyline", "Ibuprofen"],
        "medical_specialty": "Médecine de la douleur",
    },
    "Trouble épileptique": {
        "icd10": "G40.909",
        "symptoms": ["Crises", "Perte de conscience", "Convulsions", "Confusion", "Mouvements incontrôlés"],
        "medications": ["Levetiracetam", "Valproic Acid", "Carbamazepine", "Lamotrigine", "Topiramate"],
        "medical_specialty": "Neurologie",
    },
}
