from .. import HealthcareProvider as BaseHealthcareProvider


class Provider(BaseHealthcareProvider):
    """Proveedor de Faker para generar datos médicos/sanitarios falsos (es_ES)."""

    diseases= (
        "Diabetes tipo 2",
        "Hipertensión arterial esencial",
        "Hiperlipidemia",
        "Enfermedad arterial coronaria",
        "Enfermedad Pulmonar Obstructiva Crónica (EPOC)",
        "Asma",
        "Enfermedad renal crónica",
        "Osteoartritis",
        "Artritis reumatoide",
        "Depresión",
        "Trastorno de ansiedad",
        "Enfermedad por reflujo gastroesofágico (ERGE)",
        "Obesidad",
        "Hipotiroidismo",
        "Fibrilación auricular",
        "Insuficiencia cardíaca congestiva",
        "Neumonía",
        "Infección del tracto urinario",
        "Bronquitis aguda",
        "Anemia",
        "Migraña",
        "Accidente cerebrovascular (Ictus)",
        "Enfermedad de Alzheimer",
        "Cáncer de mama",
        "Cáncer de próstata",
        "Cáncer de pulmón",
        "COVID-19",
        "Gripe (Influenza)",
        "Osteoporosis",
        "Enfermedad arterial periférica",
        "Angina de pecho",
        "Hipertiroidismo",
        "Gota",
        "Esclerosis múltiple",
        "Enfermedad de Parkinson",
        "Epilepsia",
        "Trastorno bipolar",
        "Esquizofrenia",
        "Trastorno por déficit de atención e hiperactividad (TDAH)",
        "Trastorno del espectro autista (TEA)",
        "Enfermedad de Crohn",
        "Colitis ulcerosa",
        "Síndrome del intestino irritable",
        "Enfermedad celíaca",
        "Cirrosis",
        "Hepatitis C",
        "VIH/SIDA",
        "Tuberculosis",
        "Sepsis",
        "Trombosis venosa profunda",
        "Embolia pulmonar",
        "Aneurisma aórtico",
        "Valvulopatía cardíaca",
        "Miocardiopatía",
        "Endocarditis",
        "Pericarditis",
        "Infarto agudo de miocardio",
        "Cardiopatía congénita",
        "Neuropatía periférica",
        "Apnea del sueño",
        "Narcolepsia",
        "Síndrome de piernas inquietas",
        "Fibromialgia",
        "Lupus eritematoso sistémico",
        "Esclerodermia",
        "Síndrome de Sjögren",
        "Psoriasis",
        "Eccema (Dermatitis atópica)",
        "Rosácea",
        "Acné vulgar",
        "Melanoma",
        "Carcinoma basocelular",
        "Carcinoma de células escamosas",
        "Leucemia",
        "Linfoma",
        "Mieloma múltiple",
        "Cáncer colorrectal",
        "Cáncer de páncreas",
        "Cáncer de riñón",
        "Cáncer de vejiga",
        "Cáncer de ovario",
        "Cáncer de endometrio",
        "Cáncer de tiroides",
        "Tumor cerebral",
        "Glaucoma",
        "Degeneración macular",
        "Cataratas",
        "Retinopatía diabética",
        "Hipoacusia (Pérdida auditiva)",
        "Enfermedad de Ménière",
        "Hiperplasia benigna de próstata",
        "Disfunción eréctil",
        "Síndrome de ovario poliquístico (SOP)",
        "Endometriosis",
        "Miomas uterinos",
        "Preeclampsia",
        "Diabetes gestacional",
        "Deficiencia de vitamina D",
        "Anemia ferropénica",
        "Anemia perniciosa",
        "Anemia de células falciformes",
        "Hemofilia",
        "Trombocitopenia",
        "Leucopenia",
        "Diverticulitis",
        "Apendicitis",
        "Colecistitis",
        "Pancreatitis",
        "Úlcera péptica",
        "Gastritis",
        "Esofagitis",
        "Esófago de Barrett",
        "Hernia de hiato",
        "Hemorroides",
        "Fisura anal",
        "Incontinencia fecal",
        "Insuficiencia renal aguda",
        "Síndrome nefrótico",
        "Poliquistosis renal",
        "Cálculos renales (Litiasis renal)",
        "Cistitis intersticial",
        "Vejiga hiperactiva",
        "Incontinencia urinaria de esfuerzo",
        "Incontinencia urinaria de urgencia",
        "Pielonefritis",
        "Glomerulonefritis",
        "Sinusitis aguda",
        "Sinusitis crónica",
        "Rinitis alérgica",
        "Otitis media",
        "Otitis externa",
        "Faringitis",
        "Amigdalitis",
        "Laringitis",
        "Crup",
        "Bronquiolitis",
        "Enfisema",
        "Fibrosis quística",
        "Enfermedad pulmonar intersticial",
        "Sarcoidosis",
        "Derrame pleural",
        "Neumotórax",
        "Hipertensión pulmonar",
    )

    # Los códigos CIE-10 (ICD-10) son internacionales, se mantienen igual.
    icd10_codes= (
        "E11.9", "I10", "E78.5", "I25.10", "J44.9",
        "J45.909", "N18.9", "M17.9", "M79.1", "F32.9",
        "F41.9", "K21.9", "E66.9", "E03.9", "I48.91",
        "I50.9", "J18.9", "N39.0", "J20.9", "D64.9",
        "G43.909", "I63.9", "G30.9", "R10.9", "R50.9",
        "R06.00", "R53.81", "Z00.00", "Z79.899", "Z68.1",
        "C50.919", "C61", "C34.90", "U07.1", "J11.1",
        "M81.0", "I73.9", "K70.30", "G20", "E10.9",
        "I20.9", "E05.90", "M10.9", "G35", "G21.9",
        "G40.909", "F31.9", "F20.9", "F90.9", "F84.0",
        "K50.90", "K51.90", "K58.9", "K90.0", "K74.60",
        "B18.2", "B20", "A15.9", "A41.9", "I82.409",
        "I26.99", "I71.9", "I35.9", "I42.9", "I33.9",
        "I30.9", "I21.9", "Q24.9", "G62.9", "G47.33",
        "G47.419", "G25.81", "M79.7", "M32.9", "M34.9",
        "M35.00", "L40.9", "L20.9", "L71.9", "L70.0",
        "C43.9", "C44.91", "C44.92", "C95.90", "C85.90",
        "C90.00", "C18.9", "C25.9", "C64.9", "C67.9",
        "C56.9", "C54.1", "C73", "C71.9", "H40.9",
        "H35.30", "H25.9", "H36", "H90.3", "H81.0",
        "N40.0", "N52.9", "E28.2", "N80.9", "D25.9",
        "O14.9", "O24.919", "E55.9", "D50.9", "D51.0",
        "D57.1", "D66", "D69.6", "D70.9", "K57.90",
        "K35.80", "K81.9", "K85.90", "K27.9", "K29.70",
        "K20.9", "K22.70", "K44.9", "I84.9", "K60.2",
        "R15.9", "N17.9", "N04.9", "Q61.9", "N20.0",
        "N30.10", "N32.81", "N39.3", "N39.41", "N10",
        "N05.9", "J01.90", "J32.9", "J30.9", "H66.90",
        "H60.90", "J02.9", "J03.90", "J04.0", "J05.0",
        "J21.9", "J43.9", "E84.9", "J84.9", "D86.9",
        "J90", "J93.9", "I27.20", "Z00.01", "Z00.121",
        "Z00.129", "Z13.6", "Z13.89", "Z23", "J06.9",
        "R07.9", "M54.5", "M25.50", "M19.90", "R51.9",
        "R53.83", "E78.0", "I11.9", "I25.5", "I63.50",
        "I67.9", "I70.0", "I21.3", "I21.4", "I48.0",
        "I48.2", "I49.9", "I50.1", "I50.20", "I50.30",
        "I50.40", "I61.9", "I63.40", "I64", "I69.30",
        "I80.10", "I80.20", "I80.3", "I82.40", "I82.90",
        "I83.90", "I87.2", "I95.9", "J00", "J02.0",
        "J03.00", "J04.10", "J05.10", "J12.89", "J15.9",
        "J18.0", "J18.1", "J20.0", "J20.8", "J21.0",
        "J40", "J41.0", "J42", "J44.0", "J44.1",
        "J45.20", "J45.30", "J45.40", "J45.50", "J45.901",
        "J47.0", "J47.9", "J60", "J61", "J70.9",
        "J80", "J81.0", "J82", "J84.10", "J84.112",
        "J84.117", "J84.170", "J84.89", "J91.8", "J92.0",
        "J93.0", "J93.11", "J93.12", "J93.81", "J94.0",
        "J94.2", "J94.8", "J95.1", "J95.2", "J96.00",
        "J96.01", "J96.02", "J96.10", "J96.11", "J96.12",
        "J96.20", "J96.21", "J96.22", "J96.90", "J96.91",
        "J96.92", "J98.4", "J98.9", "K02.9", "K03.9",
        "K04.7", "K04.90", "K05.6", "K08.9", "K12.0",
        "K21.0", "K22.0", "K22.10", "K22.2", "K22.6",
        "K25.9", "K26.9", "K28.9", "K29.00", "K29.50",
        "K29.60", "K30", "K31.84", "K31.9", "K35.2",
        "K35.3", "K36", "K38.9", "K40.90", "K42.9",
        "K43.9", "K46.9", "K50.00", "K50.10", "K50.80",
        "K51.00", "K51.20", "K51.30", "K51.50", "K51.80",
        "K52.9", "K55.0", "K56.0", "K56.60", "K57.30",
        "K57.32", "K57.50", "K57.92", "K58.0", "K59.00",
        "K59.01", "K59.02", "K59.09", "K59.1", "K59.2",
        "K59.3", "K59.4", "K60.0", "K60.1", "K60.3",
        "K60.4", "K61.0", "K62.5", "K63.5", "K64.9",
        "K70.0", "K70.10", "K70.9", "K71.9", "K72.00",
        "K72.10", "K72.90", "K73.9", "K74.0", "K74.3",
        "K75.9", "K76.0", "K76.9", "K80.20", "K80.50",
        "K82.9", "K83.0", "K85.00", "K85.10", "K85.20",
        "K85.30", "K85.80", "K86.0", "K86.1", "K86.9",
        "K91.2", "K92.0", "K92.1", "K92.2", "K92.9",
    )

    medical_specialties= (
        "Cardiología",
        "Dermatología",
        "Endocrinología",
        "Gastroenterología (Aparato Digestivo)",
        "Hematología",
        "Enfermedades Infecciosas",
        "Nefrología",
        "Neurología",
        "Oncología Médica",
        "Neumología",
        "Reumatología",
        "Alergología e Inmunología Clínica",
        "Medicina de Familia y Comunitaria",
        "Medicina Interna",
        "Pediatría",
        "Psiquiatría",
        "Obstetricia y Ginecología",
        "Cirugía Ortopédica y Traumatología",
        "Urología",
        "Oftalmología",
        "Otorrinolaringología",
        "Anestesiología y Reanimación",
        "Radiodiagnóstico",
        "Anatomía Patológica",
        "Medicina de Urgencias y Emergencias",
        "Cirugía General y del Aparato Digestivo",
        "Cirugía Plástica, Estética y Reparadora",
        "Neurocirugía",
        "Medicina Física y Rehabilitación",
        "Angiología y Cirugía Vascular",
        "Cirugía Torácica",
        "Cirugía Cardiovascular",
        "Coloproctología",
        "Cirugía de Trasplantes",
        "Cirugía Pediátrica",
        "Neonatología",
        "Geriatría",
        "Unidad del Dolor",
        "Cuidados Paliativos",
        "Medicina del Deporte",
        "Medicina del Trabajo",
        "Medicina Preventiva y Salud Pública",
        "Genética Médica",
        "Medicina Nuclear",
        "Radiología Intervencionista",
    )

    hospital_departments= (
        "Urgencias",
        "Unidad de Cuidados Intensivos (UCI)",
        "Unidad Coronaria",
        "Quirófano",
        "Paritorio / Unidad de Partos",
        "Pediatría",
        "Maternidad",
        "Oncología",
        "Radiología",
        "Laboratorio de Análisis Clínicos",
        "Farmacia Hospitalaria",
        "Fisioterapia",
        "Terapia Ocupacional",
        "Terapia Respiratoria",
        "Bloque Quirúrgico",
        "Planta de Hospitalización",
        "Consultas Externas",
        "Unidad de Psiquiatría",
        "Unidad de Rehabilitación",
        "Sala de Endoscopias",
        "Unidad de Cuidados Intensivos Neonatales (UCIN)",
        "Unidad de Quemados",
        "Unidad de Diálisis",
        "Unidad del Sueño",
        "Unidad de Curas / Heridas",
        "Hospital de Día",
        "Unidad de Cardiología",
        "Unidad de Neurología",
        "Unidad de Observación",
        "Unidad de Reanimación Post-Anestésica (URPA)",
    )

    # Nombres genéricos (DCI - Denominación Común Internacional)
    generic_drugs= (
        "Atorvastatina", "Levotiroxina", "Lisinopril", "Metformina", "Amlodipino",
        "Metoprolol", "Omeprazol", "Simvastatina", "Losartán", "Gabapentina",
        "Hidroclorotiazida", "Sertralina", "Amoxicilina", "Salbutamol", "Citalopram",
        "Pantoprazol", "Trazodona", "Fluoxetina", "Tramadol", "Clopidogrel",
        "Rosuvastatina", "Escitalopram", "Montelukast", "Furosemida", "Bupropión",
        "Prednisona", "Meloxicam", "Dextroanfetamina", "Duloxetina", "Carvedilol",
        "Ibuprofeno", "Paracetamol", "Ácido acetilsalicílico", "Naproxeno", "Warfarina",
        "Apixabán", "Rivaroxabán", "Dabigatrán", "Insulina Glargina", "Insulina Aspart",
        "Insulina Lispro", "Insulina Detemir", "Empagliflozina", "Dapagliflozina", "Sitagliptina",
        "Glimepirida", "Pioglitazona", "Acarbosa", "Repaglinida", "Nateglinida",
        "Enalapril", "Quinapril", "Ramipril", "Benazepril", "Fosinopril",
        "Candesartán", "Valsartán", "Irbesartán", "Olmesartán", "Telmisartán",
        "Diltiazem", "Verapamilo", "Nifedipino", "Felodipino", "Isradipino",
        "Bisoprolol", "Atenolol", "Propranolol", "Nadolol", "Labetalol",
        "Clonidina", "Hidralazina", "Prazosina", "Doxazosina", "Terazosina",
        "Espironolactona", "Triamtereno", "Amilorida", "Clortalidona", "Indapamida",
        "Amiodarona", "Digoxina", "Flecainida", "Propafenona", "Sotalol",
        "Nitrofurantoína", "Ciprofloxacino", "Levofloxacino", "Azitromicina", "Claritromicina",
        "Doxiciclina", "Cefalexina", "Cefuroxima", "Ceftriaxona", "Clindamicina",
        "Metronidazol", "Vancomicina", "Linezolid", "Aciclovir", "Valaciclovir",
        "Oseltamivir", "Fluconazol", "Voriconazol", "Anfotericina B", "Terbinafina",
        "Venlafaxina", "Desvenlafaxina", "Mirtazapina", "Nortriptilina", "Amitriptilina",
        "Paroxetina", "Fluvoxamina", "Clomipramina", "Litio", "Valproato",
        "Lamotrigina", "Carbamazepina", "Oxcarbazepina", "Topiramato", "Levetiracetam",
        "Fenitoína", "Fenobarbital", "Primidona", "Lacosamida", "Zonisamida",
        "Donepezilo", "Rivastigmina", "Galantamina", "Memantina", "Levodopa",
        "Carbidopa", "Pramipexol", "Ropinirol", "Rasagilina", "Selegilina",
        "Baclofeno", "Tizanidina", "Ciclobenzaprina", "Carisoprodol", "Metocarbamol",
        "Alprazolam", "Lorazepam", "Diazepam", "Clonazepam", "Temazepam",
        "Zolpidem", "Eszopiclona", "Zaleplón", "Ramelteon", "Suvorexant",
        "Metilfenidato", "Dexmetilfenidato", "Lisdexanfetamina", "Atomoxetina", "Guanfacina",
        "Aripiprazol", "Quetiapina", "Olanzapina", "Risperidona", "Ziprasidona",
        "Paliperidona", "Lurasidona", "Haloperidol", "Clorpromazina", "Perfenazina",
        "Tamsulosina", "Finasterida", "Dutasterida", "Sildenafilo", "Tadalafilo",
        "Vardenafilo", "Oxibutinina", "Tolterodina", "Solifenacina", "Darifenacina",
        "Sulfato ferroso", "Ácido fólico", "Vitamina B12", "Vitamina D", "Carbonato de calcio",
        "Ranitidina", "Famotidina", "Esomeprazol", "Lansoprazol", "Rabeprazol",
        "Alopurinol", "Colchicina", "Probenecid", "Febuxostat", "Pegloticasa",
        "Celecoxib", "Diclofenaco", "Indometacina", "Ketorolaco", "Piroxicam",
        "Oxicodona", "Hidrocodona", "Morfina", "Fentanilo", "Codeína",
        "Hidromorfona", "Oximorfona", "Metadona", "Buprenorfina", "Naloxona",
    )

    brand_drugs= (
        "Lipitor", "Eutirox", "Zestril", "Dianben", "Norvasc",
        "Lopresor", "Losec", "Zocor", "Cozaar", "Neurontin",
        "Besitran", "Prozac", "Vandral", "Escitalopram", "Cymbalta",
        "Plavix", "Eliquis", "Ozempic", "Jardiance", "Forxiga",
        "Crestor", "Januvia", "Victoza", "Trulicity", "Mounjaro",
        "Zepbound", "Lantus", "Humalog", "NovoRapid", "Toujeo",
        "Abasaglar", "Levemir", "Tresiba", "Zestril", "Acovil",
        "Renitec", "Acuprel", "Diovan", "Aprovel", "Olmetec",
        "Micardis", "Coropres", "Tenormin", "Sumial", "Lopresor",
        "Beloken", "Catapresan", "Masdil", "Adalat", "Norvasc",
        "Plendil", "Dynacirc", "Aldactone", "Seguril", "Fordiuran",
        "Torasemida", "Zaroxolyn", "Trangorex", "Lanacordin", "Apocard",
        "Rythmol", "Sotapor", "Xarelto", "Pradaxa", "Lixiana",
        "Furantoina", "Ciproxina", "Tavanic", "Zitromax", "Klacid",
        "Vibramicina", "Keflex", "Zinnat", "Rocephin", "Dalacin",
        "Flagyl", "Vancomicina", "Zyvoxid", "Zovirax", "Valtrex",
        "Tamiflu", "Diflucan", "Vfend", "Ambisome", "Lamisil",
        "Elontril", "Pristiq", "Rexer", "Norfenazin", "Tryptizol",
        "Seroxat", "Dumirox", "Anafranil", "Plenur", "Depakine",
        "Lamictal", "Tegretol", "Trileptal", "Topamax", "Keppra",
        "Epanutin", "Luminal", "Mysoline", "Vimpat", "Zonegran",
        "Aricept", "Exelon", "Reminyl", "Ebixa", "Sinemet",
        "Mirapexin", "Requip", "Azilect", "Plurimen", "Lioresal",
        "Zanaflex", "Yurelax", "Robaxisal", "Trankimazin",
        "Orfidal", "Valium", "Rivotril", "Restoril", "Stilnox",
        "Limovan", "Sonata", "Ramelteon", "Belsomra", "Rubifen",
        "Concerta", "Rubicrono", "Elvanse", "Strattera", "Intuniv",
        "Abilify", "Seroquel", "Zyprexa", "Risperdal", "Zeldox",
        "Invega", "Latuda", "Haloperidol", "Largactil", "Decentan",
        "Omnic", "Proscar", "Avodart", "Viagra", "Cialis",
        "Levitra", "Ditropan", "Detrusitol", "Vesicare", "Emselex",
        "Tardyferon", "Acfol", "Optovite", "Deltius", "Calcio",
        "Zantac", "Pepcid", "Nexium", "Opren", "Pariet",
        "Zyloric", "Colchicina", "Benemid", "Adenuric", "Krystexxa",
        "Celebrex", "Voltaren", "Inacid", "Toradol", "Feldene",
        "Oxycontin", "Hidrocodona", "MST Continus", "Durogesic", "Codeisan",
        "Jurnista", "Opana", "Metasedin", "Transtec", "Naloxona",
        "Seretide", "Symbicort", "Spiriva", "Singulair", "Zenhale",
        "Ventolin", "Atrovent", "Xopenex", "Flixotide", "Pulmicort",
        "Keytruda", "Opdivo", "Yervoy", "Tecentriq", "Imfinzi",
        "Humira", "Enbrel", "Remicade", "Stelara", "Cosentyx",
        "Dupixent", "Xolair", "Skyrizi", "Entyvio",
    )

    symptoms= (
        "Fiebre", "Tos", "Disnea (Falta de aire)", "Cefalea (Dolor de cabeza)", "Fatiga",
        "Dolor abdominal", "Náuseas", "Vómitos", "Diarrea", "Dolor torácico",
        "Mareo", "Erupción cutánea (Rash)", "Dolor de garganta", "Artralgia (Dolor articular)", "Dolor de espalda",
        "Hemoptisis (Tos con sangre)", "Pérdida de peso", "Edema (Hinchazón)", "Visión borrosa", "Palpitaciones",
        "Escalofríos", "Sudoración", "Mialgia (Dolores musculares)", "Debilidad", "Entumecimiento",
        "Hormigueo", "Confusión", "Pérdida de memoria", "Ansiedad", "Depresión",
        "Insomnio", "Temblor", "Convulsiones", "Pérdida del conocimiento", "Síncope (Desmayo)",
        "Taquicardia", "Arritmia", "Bradicardia", "Hipertensión", "Hipotensión",
        "Disfagia (Dificultad para tragar)", "Pirosis (Ardor de estómago)", "Hematoquecia (Sangre roja en heces)", "Melena (Heces negras)", "Estreñimiento",
        "Distensión abdominal", "Gases (Flatulencia)", "Eructos", "Anorexia (Pérdida de apetito)", "Polifagia (Aumento de apetito)",
        "Poliuria (Micción frecuente)", "Disuria (Dolor al orinar)", "Hematuria (Sangre en orina)", "Orina turbia", "Coluria (Orina oscura)",
        "Incontinencia", "Impotencia", "Dispareunia (Dolor en relaciones sexuales)", "Menstruación irregular", "Menorragia (Sangre menstrual abundante)",
        "Flujo vaginal", "Sangrado vaginal", "Sofocos", "Sudoración nocturna", "Mastalgia (Dolor en mamas)",
        "Bulto en la mama", "Secreción por el pezón", "Dolor testicular", "Hinchazón testicular", "Masa escrotal",
        "Prurito (Picor)", "Urticaria", "Eccema", "Piel seca", "Piel grasa",
        "Alopecia (Caída del cabello)", "Uñas quebradizas", "Uñas amarillentas", "Onicomicosis (Hongos en uñas)", "Caspa",
        "Ojos rojos", "Lagrimeo", "Diplopía (Visión doble)", "Fotofobia (Sensibilidad a la luz)", "Dolor ocular",
        "Otalgia (Dolor de oído)", "Otorrea (Secreción oído)", "Tinnitus (Zumbidos en oídos)", "Hipoacusia", "Problemas de equilibrio",
        "Rinorrea (Goteo nasal)", "Congestión nasal", "Epistaxis (Sangrado nasal)", "Estornudos", "Goteo retronasal",
        "Anosmia (Pérdida de olfato)", "Ageusia (Pérdida del gusto)", "Halitosis (Mal aliento)", "Xerostomía (Boca seca)", "Aftas bucales",
        "Gingivorragia (Sangrado de encías)", "Odontalgia (Dolor de muelas)", "Dolor mandibular", "Dificultad para masticar", "Dificultad respiratoria",
        "Sibilancias (Pitos)", "Taquipnea (Respiración rápida)", "Respiración superficial", "Ronquidos", "Apnea del sueño",
    )

    blood_types= (
        "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-",
    )

    allergies= (
        "Penicilina", "Cacahuetes", "Frutos secos", "Marisco", "Pescado",
        "Leche", "Huevos", "Soja", "Trigo", "Sésamo",
        "Látex", "Picadura de abeja", "Polen", "Ácaros del polvo", "Caspa de animales",
        "Sulfamidas", "Aspirina", "Ibuprofeno", "Codeína", "Morfina",
        "Medio de contraste", "Anestesia", "Níquel", "Adhesivos", "Fragancias",
        "Picaduras de insectos", "Moho", "Cucarachas", "Gramíneas", "Ambrosía",
        "Maíz", "Mostaza", "Apio", "Altramuces", "Sulfitos",
        "Glutamato monosódico (GMS)", "Colorante rojo", "Gluten", "Lactosa", "Fructosa",
    )

    medical_procedures= (
        "Análisis de sangre", "Resonancia Magnética (RMN)", "Tomografía Computarizada (TAC)", "Radiografía (Rayos X)", "Ecografía",
        "Colonoscopia", "Endoscopia", "Apendicectomía", "Colecistectomía", "Cesárea",
        "Histerectomía", "Prótesis de rodilla", "Prótesis de cadera", "Cirugía de cataratas", "Biopsia",
        "Sesión de fisioterapia", "Electrocardiograma (ECG)", "Ecocardiograma", "Vacunación", "Desbridamiento de herida",
        "Angioplastia", "Cateterismo cardíaco", "Bypass coronario", "Implantación de marcapasos", "Implantación de desfibrilador (DAI)",
        "Ablación", "Amigdalectomía", "Adenoidectomía", "Mastectomía", "Tumorectomía",
        "Prostatectomía", "Nefrectomía", "Esplenectomía", "Gastrectomía", "Colectomía",
        "Ileostomía", "Colostomía", "Reparación de hernia", "Extirpación de vesícula", "Biopsia hepática",
        "Biopsia renal", "Biopsia de médula ósea", "Biopsia de ganglio linfático", "Biopsia de piel", "Broncoscopia",
        "Toracocentesis", "Paracentesis", "Punción lumbar", "Artrocentesis", "Inyección epidural",
        "Bloqueo nervioso", "Infiltración de puntos gatillo", "Infiltración articular", "Inyección de toxina botulínica", "Inyección de relleno",
        "Depilación láser", "Peeling químico", "Microdermoabrasión", "Dermoabrasión", "Eliminación de acrocordones",
        "Extirpación de nevus (lunares)", "Eliminación de verrugas", "Crioterapia", "Electrocauterización", "Escisión",
        "Incisión y drenaje", "Sutura", "Grapado", "Injerto de piel", "Cirugía de colgajo",
        "Cirugía LASIK", "Cirugía de glaucoma", "Reparación de desprendimiento de retina", "Trasplante de córnea", "Vitrectomía",
        "Timpanoplastia", "Estapedectomía", "Implante coclear", "Rinoplastia", "Septoplastia",
        "Cirugía de senos paranasales", "Tiroidectomía", "Paratiroidectomía", "Adrenalectomía", "Pancreatectomía",
        "Procedimiento de Whipple", "Resección hepática", "Trasplante de hígado", "Trasplante de riñón", "Trasplante de corazón",
        "Trasplante de pulmón", "Trasplante de páncreas", "Trasplante de médula ósea", "Trasplante de células madre", "Diálisis",
        "Hemodiálisis", "Diálisis peritoneal", "Plasmaféresis", "Infusión de Inmunoglobulinas (IVIG)", "Quimioterapia",
        "Radioterapia", "Inmunoterapia", "Hormonoterapia", "Terapia dirigida", "Terapia de células T con CAR",
    )

    # El sistema de seguros es diferente en España. Se han traducido los conceptos
    # y adaptado a términos comunes (Seguridad Social, Muface, Seguro Privado).
    insurance_plans= (
        "Seguro Privado (Cuadro Médico)", "Seguro Privado (Reembolso)", "Seguridad Social", "Mutualidad de Funcionarios (MUFACE/ISFAS/MUGEJU)",
        "Seguro de Salud Básico", "Seguro con Copago", "Seguro sin Copago", "Póliza Dental", "Seguro de Decesos",
        "Seguro de Accidentes", "Seguro de Baja Laboral", "Seguro de Hospitalización", "Seguro de Viaje",
        "Cobertura Internacional", "Tarjeta Sanitaria Europea", "Seguro de Dependencia",
    )

    vital_signs= (
        "Presión arterial", "Frecuencia cardíaca", "Frecuencia respiratoria", "Temperatura corporal", "Saturación de oxígeno",
        "Índice de Masa Corporal (IMC)", "Glucemia (Glucosa en sangre)", "Nivel de dolor", "Pulso", "Flujo espiratorio máximo (PEF)",
    )
