"""Display labels for the locale-neutral clinical values (es_ES).

Words only: the numbers, units and reference intervals live once in
`faker_healthcare/clinical_values.py` and are never translated. The key set must match
the base catalogue exactly (`faker_healthcare/clinical_labels.py`); see
`tests/test_locales.py::TestClinicalLabelParity`.

Dos estructuras: `CLINICAL_LABELS` (nombres de analitos y constantes, indicadores,
categorías de alcohol, vías, frecuencias, situación de la prescripción y rangos de las
escalas) y `MEDICATION_NAMES`, que asocia el identificador neutro de una sustancia con la
grafía exacta de este catálogo — es lo que permite que una sola tabla de dosis sirva para
los seis idiomas.
"""

CLINICAL_LABELS: dict[str, str] = {
    # Constantes vitales
    "systolic_bp": "Presión arterial sistólica",
    "diastolic_bp": "Presión arterial diastólica",
    "heart_rate": "Frecuencia cardíaca",
    "respiratory_rate": "Frecuencia respiratoria",
    "temperature_c": "Temperatura corporal",
    "oxygen_saturation": "Saturación de oxígeno",
    # Hematología
    "haemoglobin": "Hemoglobina",
    "wbc": "Recuento de leucocitos",
    "platelets": "Recuento de plaquetas",
    "ferritin": "Ferritina",
    "inr": "INR (razón internacional normalizada)",
    # Función renal
    "sodium": "Sodio",
    "potassium": "Potasio",
    "urea": "Urea",
    "creatinine": "Creatinina",
    "egfr": "Filtrado glomerular estimado (FGe)",
    # Función hepática
    "alt": "Alanina aminotransferasa (ALT)",
    "ast": "Aspartato aminotransferasa (AST)",
    "alkaline_phosphatase": "Fosfatasa alcalina",
    "bilirubin_total": "Bilirrubina total",
    "albumin": "Albúmina",
    # Metabolismo
    "fasting_glucose": "Glucosa en ayunas",
    "hba1c": "Hemoglobina glucosilada (HbA1c)",
    # Tiroides
    "tsh": "Hormona estimulante del tiroides (TSH)",
    "free_t4": "Tiroxina libre (T4 libre)",
    # Lípidos
    "total_cholesterol": "Colesterol total",
    "ldl": "Colesterol LDL",
    "hdl": "Colesterol HDL",
    "triglycerides": "Triglicéridos",
    # Marcadores inflamatorios
    "crp": "Proteína C reactiva (PCR)",
    # Indicadores del resultado
    "flag_low": "Bajo",
    "flag_normal": "Normal",
    "flag_high": "Alto",
    # Consumo semanal de alcohol
    "alcohol_none": "No bebedor",
    "alcohol_low_risk": "Riesgo bajo",
    "alcohol_increasing_risk": "Riesgo creciente",
    "alcohol_higher_risk": "Riesgo alto",
    # Vías de administración
    "route_oral": "Vía oral",
    "route_intravenous": "Vía intravenosa",
    "route_subcutaneous": "Vía subcutánea",
    "route_inhaled": "Vía inhalatoria",
    "route_sublingual": "Vía sublingual",
    "route_ophthalmic": "Vía oftálmica",
    # Frecuencias de administración
    "frequency_once_daily": "Una vez al día",
    "frequency_twice_daily": "Dos veces al día",
    "frequency_three_times_daily": "Tres veces al día",
    "frequency_four_times_daily": "Cuatro veces al día",
    "frequency_at_night": "Por la noche",
    "frequency_as_required": "Si precisa",
    "frequency_once_weekly": "Una vez a la semana",
    "frequency_every_three_weeks": "Cada tres semanas",
    # Situación de la prescripción
    "medication_status_past": "Tratamiento previo",
    "medication_status_current": "Tratamiento actual",
    "medication_status_future": "Tratamiento previsto",
    # Rangos de gravedad de las escalas
    "assessment_minimal": "Mínimo",
    "assessment_mild": "Leve",
    "assessment_moderate": "Moderado",
    "assessment_moderately_severe": "Moderadamente grave",
    "assessment_severe": "Grave",
    "assessment_symptoms_absent": "Síntomas ausentes",
    "assessment_normal_cognition": "Cognición normal",
    "assessment_screen_negative": "Cribado negativo",
    "assessment_screen_positive": "Cribado positivo",
    "alcohol_possible_dependence": "Posible dependencia",
}

# Las sustancias que `medication_order()` sabe dosificar, con el nombre de este catálogo.
MEDICATION_NAMES: dict[str, str] = {
    "acamprosate": "Acamprosato",
    "acetaminophen": "Paracetamol",
    "acyclovir": "Aciclovir",
    "albuterol": "Salbutamol",
    "alendronate": "Alendronato",
    "allopurinol": "Alopurinol",
    "alprazolam": "Alprazolam",
    "amitriptyline": "Amitriptilina",
    "amlodipine": "Amlodipino",
    "amoxicillin": "Amoxicilina",
    "anastrozole": "Anastrozol",
    "apixaban": "Apixabán",
    "aripiprazole": "Aripiprazol",
    "aspirin": "Ácido acetilsalicílico",
    "atomoxetine": "Atomoxetina",
    "atorvastatin": "Atorvastatina",
    "azathioprine": "Azatioprina",
    "azithromycin": "Azitromicina",
    "bicalutamide": "Bicalutamida",
    "budesonide": "Budesonida",
    "buprenorphine": "Buprenorfina",
    "bupropion": "Bupropión",
    "buspirone": "Buspirona",
    "calcium_carbonate": "Carbonato cálcico",
    "carbamazepine": "Carbamazepina",
    "ceftriaxone": "Ceftriaxona",
    "cefuroxime": "Cefuroxima",
    "cephalexin": "Cefalexina",
    "cetirizine": "Cetirizina",
    "cholecalciferol": "Colecalciferol",
    "cilostazol": "Cilostazol",
    "ciprofloxacin": "Ciprofloxacino",
    "clarithromycin": "Claritromicina",
    "clindamycin": "Clindamicina",
    "clopidogrel": "Clopidogrel",
    "colchicine": "Colchicina",
    "dexamethasone": "Dexametasona",
    "digoxin": "Digoxina",
    "diltiazem": "Diltiazem",
    "donepezil": "Donepezilo",
    "doxycycline": "Doxiciclina",
    "duloxetine": "Duloxetina",
    "dutasteride": "Dutasterida",
    "empagliflozin": "Empagliflozina",
    "enoxaparin": "Enoxaparina",
    "escitalopram": "Escitalopram",
    "esomeprazole": "Esomeprazol",
    "famotidine": "Famotidina",
    "febuxostat": "Febuxostat",
    "ferrous_sulfate": "Sulfato ferroso",
    "finasteride": "Finasterida",
    "fluoxetine": "Fluoxetina",
    "fluticasone": "Fluticasona",
    "folic_acid": "Ácido fólico",
    "furosemide": "Furosemida",
    "gabapentin": "Gabapentina",
    "galantamine": "Galantamina",
    "glimepiride": "Glimepirida",
    "glyburide": "Gliburida",
    "haloperidol": "Haloperidol",
    "hydrochlorothiazide": "Hidroclorotiazida",
    "hydrocortisone": "Hidrocortisona",
    "hydroxychloroquine": "Hidroxicloroquina",
    "ibuprofen": "Ibuprofeno",
    "insulin": "Insulina",
    "insulin_glargine": "Insulina glargina",
    "lactulose": "Lactulosa",
    "lamotrigine": "Lamotrigina",
    "latanoprost": "Latanoprost",
    "letrozole": "Letrozol",
    "levetiracetam": "Levetiracetam",
    "levofloxacin": "Levofloxacino",
    "levothyroxine": "Levotiroxina",
    "liraglutide": "Liraglutida",
    "lisinopril": "Lisinopril",
    "lithium": "Litio",
    "loperamide": "Loperamida",
    "loratadine": "Loratadina",
    "lorazepam": "Lorazepam",
    "losartan": "Losartán",
    "melatonin": "Melatonina",
    "memantine": "Memantina",
    "mesalamine": "Mesalazina",
    "metformin": "Metformina",
    "methadone": "Metadona",
    "methimazole": "Metimazol",
    "methotrexate": "Metotrexato",
    "methylphenidate": "Metilfenidato",
    "metoprolol": "Metoprolol",
    "metronidazole": "Metronidazol",
    "montelukast": "Montelukast",
    "naltrexone": "Naltrexona",
    "naproxen": "Naproxeno",
    "nitrofurantoin": "Nitrofurantoína",
    "nitroglycerin": "Nitroglicerina",
    "olanzapine": "Olanzapina",
    "omeprazole": "Omeprazol",
    "oseltamivir": "Oseltamivir",
    "oxybutynin": "Oxibutinina",
    "pantoprazole": "Pantoprazol",
    "paroxetine": "Paroxetina",
    "pembrolizumab": "Pembrolizumab",
    "phenytoin": "Fenitoína",
    "pioglitazone": "Pioglitazona",
    "prednisone": "Prednisona",
    "pregabalin": "Pregabalina",
    "propranolol": "Propranolol",
    "quetiapine": "Quetiapina",
    "risperidone": "Risperidona",
    "rivaroxaban": "Rivaroxabán",
    "rosuvastatin": "Rosuvastatina",
    "sertraline": "Sertralina",
    "sildenafil": "Sildenafilo",
    "simvastatin": "Simvastatina",
    "sitagliptin": "Sitagliptina",
    "solifenacin": "Solifenacina",
    "spironolactone": "Espironolactona",
    "sulfasalazine": "Sulfasalazina",
    "sumatriptan": "Sumatriptán",
    "tadalafil": "Tadalafilo",
    "tamoxifen": "Tamoxifeno",
    "tamsulosin": "Tamsulosina",
    "theophylline": "Teofilina",
    "timolol": "Timolol",
    "tiotropium": "Tiotropio",
    "tolterodine": "Tolterodina",
    "topiramate": "Topiramato",
    "tramadol": "Tramadol",
    "trimethoprim": "Trimetoprima",
    "ursodiol": "Ursodiol",
    "valacyclovir": "Valaciclovir",
    "valproate": "Valproato",
    "valproic_acid": "Ácido valproico",
    "venlafaxine": "Venlafaxina",
    "warfarin": "Warfarina",
}
