"""
Constantes de datos estáticos para el proveedor de atención médica (es_ES).
"""

HOSPITAL_DEPARTMENTS: tuple[str, ...] = (
    "Urgencias",
    "Unidad de Cuidados Intensivos (UCI)",
    "Unidad Coronaria",
    "Quirófano",
    "Paritorio / Unidad de Partos",
    "Pediatría",
    "Maternidad",
    "Oncología",
    "Radiología",
    "Laboratorio de Análisis Clínicos",
    "Farmacia Hospitalaria",
    "Fisioterapia",
    "Terapia Ocupacional",
    "Terapia Respiratoria",
    "Bloque Quirúrgico",
    "Planta de Hospitalización",
    "Consultas Externas",
    "Unidad de Psiquiatría",
    "Unidad de Rehabilitación",
    "Sala de Endoscopias",
    "Unidad de Cuidados Intensivos Neonatales (UCIN)",
    "Unidad de Quemados",
    "Unidad de Diálisis",
    "Unidad del Sueño",
    "Unidad de Curas / Heridas",
    "Hospital de Día",
    "Unidad de Cardiología",
    "Unidad de Neurología",
    "Unidad de Observación",
    "Unidad de Reanimación Post-Anestésica (URPA)",
)

BLOOD_TYPES: tuple[str, ...] = ("A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-")

ALLERGIES: tuple[str, ...] = (
    "Penicilina",
    "Cacahuetes",
    "Frutos secos",
    "Marisco",
    "Pescado",
    "Leche",
    "Huevos",
    "Soja",
    "Trigo",
    "Sésamo",
    "Látex",
    "Picadura de abeja",
    "Polen",
    "Ácaros del polvo",
    "Caspa de animales",
    "Sulfamidas",
    "Aspirina",
    "Ibuprofeno",
    "Codeína",
    "Morfina",
    "Medio de contraste",
    "Anestesia",
    "Níquel",
    "Adhesivos",
    "Fragancias",
    "Picaduras de insectos",
    "Moho",
    "Cucarachas",
    "Gramíneas",
    "Ambrosía",
    "Maíz",
    "Mostaza",
    "Apio",
    "Altramuces",
    "Sulfitos",
    "Colorante rojo",
)

MEDICAL_PROCEDURES: tuple[str, ...] = (
    "Análisis de sangre",
    "Resonancia Magnética (RMN)",
    "Tomografía Computarizada (TAC)",
    "Radiografía (Rayos X)",
    "Ecografía",
    "Colonoscopia",
    "Endoscopia",
    "Apendicectomía",
    "Colecistectomía",
    "Cesárea",
    "Histerectomía",
    "Prótesis de rodilla",
    "Prótesis de cadera",
    "Cirugía de cataratas",
    "Biopsia",
    "Sesión de fisioterapia",
    "Electrocardiograma (ECG)",
    "Ecocardiograma",
    "Vacunación",
    "Desbridamiento de herida",
    "Angioplastia",
    "Cateterismo cardíaco",
    "Bypass coronario",
    "Implantación de marcapasos",
    "Implantación de desfibrilador (DAI)",
    "Ablación",
    "Amigdalectomía",
    "Adenoidectomía",
    "Mastectomía",
    "Tumorectomía",
    "Prostatectomía",
    "Nefrectomía",
    "Esplenectomía",
    "Gastrectomía",
    "Colectomía",
    "Ileostomía",
    "Colostomía",
    "Reparación de hernia",
    "Extirpación de vesícula",
    "Biopsia hepática",
    "Biopsia renal",
    "Biopsia de médula ósea",
    "Biopsia de ganglio linfático",
    "Biopsia de piel",
    "Broncoscopia",
    "Toracocentesis",
    "Paracentesis",
    "Punción lumbar",
    "Artrocentesis",
    "Inyección epidural",
    "Bloqueo nervioso",
    "Infiltración de puntos gatillo",
    "Infiltración articular",
    "Inyección de toxina botulínica",
    "Inyección de relleno",
    "Depilación láser",
    "Peeling químico",
    "Microdermoabrasión",
    "Dermoabrasión",
    "Eliminación de acrocordones",
    "Extirpación de nevus (lunares)",
    "Eliminación de verrugas",
    "Crioterapia",
    "Electrocauterización",
    "Escisión",
    "Incisión y drenaje",
    "Sutura",
    "Grapado",
    "Injerto de piel",
    "Cirugía de colgajo",
    "Cirugía LASIK",
    "Cirugía de glaucoma",
    "Reparación de desprendimiento de retina",
    "Trasplante de córnea",
    "Vitrectomía",
    "Timpanoplastia",
    "Estapedectomía",
    "Implante coclear",
    "Rinoplastia",
    "Septoplastia",
    "Cirugía de senos paranasales",
    "Tiroidectomía",
    "Paratiroidectomía",
    "Adrenalectomía",
    "Pancreatectomía",
    "Procedimiento de Whipple",
    "Resección hepática",
    "Trasplante de hígado",
    "Trasplante de riñón",
    "Trasplante de corazón",
    "Trasplante de pulmón",
    "Trasplante de páncreas",
    "Trasplante de médula ósea",
    "Trasplante de células madre",
    "Diálisis",
    "Hemodiálisis",
    "Diálisis peritoneal",
    "Plasmaféresis",
    "Infusión de Inmunoglobulinas (IVIG)",
    "Quimioterapia",
    "Radioterapia",
    "Inmunoterapia",
    "Hormonoterapia",
    "Terapia dirigida",
    "Terapia de células T con CAR",
)

INSURANCE_PLANS: tuple[str, ...] = (
    "Seguro Privado (Cuadro Médico)",
    "Seguro Privado (Reembolso)",
    "Seguridad Social",
    "Mutualidad de Funcionarios (MUFACE/ISFAS/MUGEJU)",
    "Seguro de Salud Básico",
    "Seguro con Copago",
    "Seguro sin Copago",
    "Póliza Dental",
    "Seguro de Decesos",
    "Seguro de Accidentes",
    "Seguro de Baja Laboral",
    "Seguro de Hospitalización",
    "Seguro de Viaje",
    "Cobertura Internacional",
    "Tarjeta Sanitaria Europea",
    "Seguro de Dependencia",
)

VITAL_SIGNS: tuple[str, ...] = (
    "Presión arterial",
    "Frecuencia cardíaca",
    "Frecuencia respiratoria",
    "Temperatura corporal",
    "Saturación de oxígeno",
    "Índice de Masa Corporal (IMC)",
    "Glucemia (Glucosa en sangre)",
    "Nivel de dolor",
    "Pulso",
    "Flujo espiratorio máximo (PEF)",
)

# Treatments that a condition's `medications` list may legitimately contain but that
# are not drugs: procedures, devices, and lifestyle measures. They are correct inside
# a condition's treatment list (see AGENTS.md), but wrong in the flat pool a consumer
# draws a medication column from, so `generic_drugs` excludes them and the provider
# exposes them separately via `interventions` / `intervention()`.
# Kept in the same order in every locale, so index i is the same intervention
# everywhere; every entry must also appear in this locale's DISEASE_CORRELATIONS
# (tests/test_locales.py enforces both).
NON_DRUG_INTERVENTIONS: tuple[str, ...] = (
    "Lentes antideslumbrantes",
    "Instilaciones vesicales",
    "Transfusiones de sangre",
    "Terapia CPAP",
    "Quimioterapia",
    "Tubo torácico",
    "Implantes cocleares",
    "Parto",
    "Diálisis",
    "Control dietético",
    "Manejo de electrolitos",
    "Ejercicio",
    "Gafas",
    "Dieta sin gluten",
    "Audífonos",
    "Aire humidificado",
    "Hidratación",
    "Líquidos intravenosos",
    "Infusiones de hierro",
    "Terapia láser",
    "Lupas",
    "Sin medicamentos",
    "Oxígeno",
    "Oxigenoterapia",
    "Ejercicios del suelo pélvico",
    "Terapia fotodinámica",
    "Plasmaféresis",
    "Pleurodesis",
    "Rehabilitación pulmonar",
    "Radioterapia",
    "Yodo radiactivo",
    "Irrigación salina",
    "Esplenectomía",
    "Inhalación de vapor",
    "Exposición solar",
    "Cuidados de soporte",
    "Cirugía",
    "Toracocentesis",
    "Vitrectomía",
    "Reposo vocal",
    "Férula de muñeca",
)
