"""
Datos de Correlaciones de Enfermedades
Este módulo contiene el diccionario DISEASE_CORRELATIONS que mapea todas las 150 enfermedades
a sus síntomas, códigos CIE-10, medicamentos y especialidades primarias.
Datos procedentes de la clasificación CIE-10 de la OMS.
AVISO LEGAL MÉDICO: Estos datos son SOLO PARA FINES DE PRUEBAS Y DESARROLLO.
NO deben utilizarse para diagnósticos médicos reales, tratamientos o decisiones sanitarias.
"""

from ..types import DiseaseData


DISEASE_CORRELATIONS: dict[str, DiseaseData] = {
    "Diabetes mellitus tipo 2": {
        "icd10": "E11.9",
        "symptoms": ["Micción frecuente", "Aumento del apetito", "Fatiga", "Visión borrosa", "Pérdida de peso"],
        "medications": ["Metformina", "Insulina glargina", "Empagliflozina", "Sitagliptina", "Glimepirida"],
        "medical_specialty": "Endocrinología",
    },
    "Hipertensión esencial": {
        "icd10": "I10",
        "symptoms": ["Cefalea", "Mareo", "Dolor torácico", "Visión borrosa", "Palpitaciones"],
        "medications": ["Lisinopril", "Amlodipino", "Losartán", "Hidroclorotiazida", "Metoprolol"],
        "medical_specialty": "Cardiología",
    },
    "Hiperlipidemia": {
        "icd10": "E78.5",
        "symptoms": ["Dolor torácico", "Fatiga", "Entumecimiento", "Debilidad"],
        "medications": ["Atorvastatina", "Simvastatina", "Rosuvastatina", "Fenofibrato", "Ezetimiba"],
        "medical_specialty": "Cardiología",
    },
    "Enfermedad de las arterias coronarias": {
        "icd10": "I25.10",
        "symptoms": ["Dolor torácico", "Disnea", "Fatiga", "Palpitaciones", "Mareo"],
        "medications": ["Ácido acetilsalicílico", "Clopidogrel", "Atorvastatina", "Metoprolol", "Nitroglicerina"],
        "medical_specialty": "Cardiología",
    },
    "Enfermedad pulmonar obstructiva crónica": {
        "icd10": "J44.9",
        "symptoms": ["Disnea", "Tos", "Sibilancias", "Dolor torácico", "Fatiga"],
        "medications": ["Salbutamol", "Tiotropio", "Fluticasona", "Prednisona", "Azitromicina"],
        "medical_specialty": "Neumología",
    },
    "Asma": {
        "icd10": "J45.909",
        "symptoms": ["Sibilancias", "Disnea", "Tos", "Dolor torácico", "Dificultad para respirar"],
        "medications": ["Salbutamol", "Fluticasona", "Montelukast", "Prednisona", "Budesonida"],
        "medical_specialty": "Neumología",
    },
    "Enfermedad renal crónica": {
        "icd10": "N18.9",
        "symptoms": ["Fatiga", "Hinchazón", "Náuseas", "Pérdida de apetito", "Micción frecuente"],
        "medications": ["Lisinopril", "Furosemida", "Eritropoyetina", "Carbonato cálcico", "Sevelámero"],
        "medical_specialty": "Nefrología",
    },
    "Artrosis": {
        "icd10": "M17.9",
        "symptoms": ["Dolor articular", "Hinchazón", "Debilidad", "Dolor de espalda"],
        "medications": ["Ibuprofeno", "Paracetamol", "Naproxeno", "Celecoxib", "Tramadol"],
        "medical_specialty": "Ortopedia",
    },
    "Artritis reumatoide": {
        "icd10": "M79.1",
        "symptoms": ["Dolor articular", "Hinchazón", "Fatiga", "Debilidad", "Dolores musculares"],
        "medications": ["Metotrexato", "Prednisona", "Adalimumab", "Hidroxicloroquina", "Sulfasalazina"],
        "medical_specialty": "Reumatología",
    },
    "Depresión": {
        "icd10": "F32.9",
        "symptoms": ["Depresión", "Fatiga", "Insomnio", "Pérdida de apetito", "Ansiedad"],
        "medications": ["Sertralina", "Fluoxetina", "Escitalopram", "Bupropión", "Duloxetina"],
        "medical_specialty": "Psiquiatría",
    },
    "Trastorno de ansiedad": {
        "icd10": "F41.9",
        "symptoms": ["Ansiedad", "Palpitaciones", "Sudoración", "Temblor", "Insomnio"],
        "medications": ["Sertralina", "Escitalopram", "Alprazolam", "Lorazepam", "Buspirona"],
        "medical_specialty": "Psiquiatría",
    },
    "Enfermedad por reflujo gastroesofágico": {
        "icd10": "K21.9",
        "symptoms": ["Acidez", "Dolor torácico", "Dificultad para tragar", "Dolor de garganta", "Náuseas"],
        "medications": ["Omeprazol", "Pantoprazol", "Esomeprazol", "Ranitidina", "Famotidina"],
        "medical_specialty": "Gastroenterología",
    },
    "Obesidad": {
        "icd10": "E66.9",
        "symptoms": ["Fatiga", "Dolor articular", "Disnea", "Sudoración"],
        "medications": ["Orlistat", "Fentermina", "Liraglutida", "Semaglutida", "Naltrexona"],
        "medical_specialty": "Endocrinología",
    },
    "Hipotiroidismo": {
        "icd10": "E03.9",
        "symptoms": ["Fatiga", "Pérdida de peso", "Caída del cabello", "Piel seca", "Estreñimiento"],
        "medications": ["Levotiroxina", "Liotironina", "Tiroides"],
        "medical_specialty": "Endocrinología",
    },
    "Fibrilación auricular": {
        "icd10": "I48.91",
        "symptoms": ["Palpitaciones", "Mareo", "Fatiga", "Disnea", "Dolor torácico"],
        "medications": ["Warfarina", "Apixabán", "Rivaroxabán", "Metoprolol", "Diltiazem"],
        "medical_specialty": "Cardiología",
    },
    "Insuficiencia cardíaca congestiva": {
        "icd10": "I50.9",
        "symptoms": ["Disnea", "Fatiga", "Hinchazón", "Tos", "Taquicardia"],
        "medications": ["Furosemida", "Lisinopril", "Metoprolol", "Espironolactona", "Digoxina"],
        "medical_specialty": "Cardiología",
    },
    "Neumonía": {
        "icd10": "J18.9",
        "symptoms": ["Fiebre", "Tos", "Disnea", "Dolor torácico", "Fatiga"],
        "medications": ["Amoxicilina", "Azitromicina", "Ceftriaxona", "Levofloxacino", "Doxiciclina"],
        "medical_specialty": "Neumología",
    },
    "Infección del tracto urinario": {
        "icd10": "N39.0",
        "symptoms": ["Disuria", "Micción frecuente", "Fiebre", "Dolor abdominal", "Orina turbia"],
        "medications": ["Nitrofurantoína", "Ciprofloxacino", "Trimetoprima", "Amoxicilina", "Cefalexina"],
        "medical_specialty": "Medicina Interna",
    },
    "Bronquitis aguda": {
        "icd10": "J20.9",
        "symptoms": ["Tos", "Fiebre", "Fatiga", "Disnea", "Dolor torácico"],
        "medications": ["Salbutamol", "Guaifenesina", "Dextrometorfano", "Ibuprofeno", "Azitromicina"],
        "medical_specialty": "Neumología",
    },
    "Anemia": {
        "icd10": "D64.9",
        "symptoms": ["Fatiga", "Debilidad", "Mareo", "Cefalea", "Disnea"],
        "medications": ["Sulfato ferroso", "Vitamina B12", "Ácido fólico", "Eritropoyetina"],
        "medical_specialty": "Hematología",
    },
    "Migraña": {
        "icd10": "G43.909",
        "symptoms": ["Cefalea", "Náuseas", "Fotofobia", "Visión borrosa", "Mareo"],
        "medications": ["Sumatriptán", "Ibuprofeno", "Topiramato", "Propranolol", "Amitriptilina"],
        "medical_specialty": "Neurología",
    },
    "Accidente cerebrovascular": {
        "icd10": "I63.9",
        "symptoms": ["Entumecimiento", "Confusión", "Dificultad para tragar", "Visión borrosa", "Debilidad"],
        "medications": ["Ácido acetilsalicílico", "Clopidogrel", "Alteplasa", "Warfarina", "Atorvastatina"],
        "medical_specialty": "Neurología",
    },
    "Enfermedad de Alzheimer": {
        "icd10": "G30.9",
        "symptoms": ["Pérdida de memoria", "Confusión", "Ansiedad", "Depresión", "Dificultad para tragar"],
        "medications": ["Donepezilo", "Memantina", "Rivastigmina", "Galantamina"],
        "medical_specialty": "Neurología",
    },
    "Cáncer de mama": {
        "icd10": "C50.919",
        "symptoms": ["Bulto en la mama", "Secreción del pezón", "Hinchazón", "Pérdida de peso", "Fatiga"],
        "medications": ["Tamoxifeno", "Anastrozol", "Trastuzumab", "Quimioterapia", "Radioterapia"],
        "medical_specialty": "Oncología",
    },
    "Cáncer de próstata": {
        "icd10": "C61",
        "symptoms": ["Disuria", "Micción frecuente", "Debilidad", "Pérdida de peso"],
        "medications": ["Leuprolida", "Bicalutamida", "Docetaxel", "Abiraterona", "Enzalutamida"],
        "medical_specialty": "Oncología",
    },
    "Cáncer de pulmón": {
        "icd10": "C34.90",
        "symptoms": ["Tos", "Hemoptisis", "Disnea", "Dolor torácico", "Pérdida de peso"],
        "medications": ["Carboplatino", "Paclitaxel", "Pembrolizumab", "Erlotinib", "Quimioterapia"],
        "medical_specialty": "Oncología",
    },
    "COVID-19": {
        "icd10": "U07.1",
        "symptoms": ["Fiebre", "Tos", "Fatiga", "Pérdida del olfato", "Pérdida del gusto", "Disnea"],
        "medications": ["Remdesivir", "Dexametasona", "Paxlovid", "Molnupiravir"],
        "medical_specialty": "Enfermedades Infecciosas",
    },
    "Influenza": {
        "icd10": "J11.1",
        "symptoms": ["Fiebre", "Tos", "Dolor de garganta", "Dolores musculares", "Fatiga", "Cefalea"],
        "medications": ["Oseltamivir", "Zanamivir", "Baloxavir", "Ibuprofeno", "Paracetamol"],
        "medical_specialty": "Medicina Interna",
    },
    "Osteoporosis": {
        "icd10": "M81.0",
        "symptoms": ["Dolor de espalda", "Pérdida ósea", "Debilidad"],
        "medications": ["Alendronato", "Risedronato", "Denosumab", "Carbonato cálcico", "Vitamina D"],
        "medical_specialty": "Endocrinología",
    },
    "Enfermedad arterial periférica": {
        "icd10": "I73.9",
        "symptoms": ["Dolor en las piernas", "Entumecimiento", "Debilidad", "Extremidades frías"],
        "medications": ["Cilostazol", "Ácido acetilsalicílico", "Clopidogrel", "Atorvastatina", "Pentoxifilina"],
        "medical_specialty": "Cirugía Vascular",
    },
    "Angina de pecho": {
        "icd10": "I20.9",
        "symptoms": ["Dolor torácico", "Disnea", "Fatiga", "Náuseas", "Sudoración"],
        "medications": ["Nitroglicerina", "Ácido acetilsalicílico", "Metoprolol", "Amlodipino", "Atorvastatina"],
        "medical_specialty": "Cardiología",
    },
    "Hipertiroidismo": {
        "icd10": "E05.90",
        "symptoms": ["Pérdida de peso", "Palpitaciones", "Ansiedad", "Temblor", "Intolerancia al calor"],
        "medications": ["Metimazol", "Propiltiouracilo", "Propranolol", "Yodo radiactivo", "Levotiroxina"],
        "medical_specialty": "Endocrinología",
    },
    "Gota": {
        "icd10": "M10.9",
        "symptoms": ["Dolor articular", "Hinchazón", "Enrojecimiento", "Tofos", "Movilidad limitada"],
        "medications": ["Alopurinol", "Colchicina", "Indometacina", "Febuxostat", "Probenecid"],
        "medical_specialty": "Reumatología",
    },
    "Esclerosis múltiple": {
        "icd10": "G35",
        "symptoms": ["Fatiga", "Entumecimiento", "Problemas de visión", "Problemas de equilibrio", "Debilidad muscular"],
        "medications": ["Interferón beta", "Acetato de glatirámero", "Fingolimod", "Natalizumab", "Ocrelizumab"],
        "medical_specialty": "Neurología",
    },
    "Enfermedad de Parkinson": {
        "icd10": "G20",
        "symptoms": ["Temblor", "Bradicinesia", "Rigidez", "Inestabilidad postural", "Cambios en el habla"],
        "medications": ["Levodopa", "Carbidopa", "Pramipexol", "Selegilina", "Amantadina"],
        "medical_specialty": "Neurología",
    },
    "Epilepsia": {
        "icd10": "G40.909",
        "symptoms": ["Convulsiones", "Pérdida de conciencia", "Confusión", "Episodios de mirada fija", "Convulsiones"],
        "medications": ["Carbamazepina", "Valproato", "Lamotrigina", "Levetiracetam", "Fenitoína"],
        "medical_specialty": "Neurología",
    },
    "Trastorno bipolar": {
        "icd10": "F31.9",
        "symptoms": ["Cambios de humor", "Manía", "Depresión", "Irritabilidad", "Insomnio"],
        "medications": ["Litio", "Valproato", "Olanzapina", "Quetiapina", "Lamotrigina"],
        "medical_specialty": "Psiquiatría",
    },
    "Esquizofrenia": {
        "icd10": "F20.9",
        "symptoms": ["Alucinaciones", "Delirios", "Pensamiento desorganizado", "Síntomas negativos", "Deterioro cognitivo"],
        "medications": ["Risperidona", "Olanzapina", "Quetiapina", "Aripiprazol", "Haloperidol"],
        "medical_specialty": "Psiquiatría",
    },
    "Trastorno por déficit de atención con hiperactividad": {
        "icd10": "F90.9",
        "symptoms": ["Inatención", "Hiperactividad", "Impulsividad", "Desorganización", "Olvidos"],
        "medications": ["Metilfenidato", "Anfetamina", "Atomoxetina", "Guanfacina", "Clonidina"],
        "medical_specialty": "Psiquiatría",
    },
    "Trastorno del espectro autista": {
        "icd10": "F84.0",
        "symptoms": ["Alteración social", "Dificultades de comunicación", "Comportamientos repetitivos", "Sensibilidades sensoriales", "Intereses restringidos"],
        "medications": ["Risperidona", "Aripiprazol", "ISRS", "Estimulantes", "Anticonvulsivantes"],
        "medical_specialty": "Psiquiatría",
    },
    "Enfermedad de Crohn": {
        "icd10": "K50.90",
        "symptoms": ["Dolor abdominal", "Diarrea", "Pérdida de peso", "Fatiga", "Sangre en las heces"],
        "medications": ["Mesalazina", "Prednisona", "Azatioprina", "Infliximab", "Adalimumab"],
        "medical_specialty": "Gastroenterología",
    },
    "Colitis ulcerosa": {
        "icd10": "K51.90",
        "symptoms": ["Diarrea sanguinolenta", "Dolor abdominal", "Urgencia", "Pérdida de peso", "Fatiga"],
        "medications": ["Mesalazina", "Prednisona", "Azatioprina", "Infliximab", "Vedolizumab"],
        "medical_specialty": "Gastroenterología",
    },
    "Síndrome del intestino irritable": {
        "icd10": "K58.9",
        "symptoms": ["Dolor abdominal", "Hinchazón", "Diarrea", "Estreñimiento", "Gases"],
        "medications": ["Loperamida", "Lubiprostona", "Linaclotida", "Dicicloverina", "Rifaximina"],
        "medical_specialty": "Gastroenterología",
    },
    "Enfermedad celíaca": {
        "icd10": "K90.0",
        "symptoms": ["Dolor abdominal", "Diarrea", "Hinchazón", "Fatiga", "Pérdida de peso"],
        "medications": ["Sin medicamentos", "Dieta sin gluten", "Suplementos vitamínicos", "Suplementos de hierro", "Probióticos"],
        "medical_specialty": "Gastroenterología",
    },
    "Cirrosis": {
        "icd10": "K74.60",
        "symptoms": ["Fatiga", "Ictericia", "Hinchazón abdominal", "Confusión", "Fácil aparición de hematomas"],
        "medications": ["Lactulosa", "Propranolol", "Diuréticos", "Suplementos vitamínicos", "Antibióticos"],
        "medical_specialty": "Gastroenterología",
    },
    "Hepatitis C": {
        "icd10": "B18.2",
        "symptoms": ["Fatiga", "Ictericia", "Dolor abdominal", "Pérdida de apetito", "Náuseas"],
        "medications": ["Sofosbuvir", "Ledipasvir", "Glecaprevir", "Pibrentasvir", "Ribavirina"],
        "medical_specialty": "Gastroenterología",
    },
    "VIH/SIDA": {
        "icd10": "B20",
        "symptoms": ["Fiebre", "Fatiga", "Pérdida de peso", "Ganglios linfáticos inflamados", "Infecciones recurrentes"],
        "medications": ["Tenofovir", "Emtricitabina", "Dolutegravir", "Efavirenz", "Ritonavir"],
        "medical_specialty": "Enfermedades Infecciosas",
    },
    "Tuberculosis": {
        "icd10": "A15.0",
        "symptoms": ["Tos", "Fiebre", "Sudores nocturnos", "Pérdida de peso", "Dolor torácico"],
        "medications": ["Isoniazida", "Rifampicina", "Pirazinamida", "Etambutol", "Estreptomicina"],
        "medical_specialty": "Neumología",
    },
    "Sepsis": {
        "icd10": "A41.9",
        "symptoms": ["Fiebre", "Taquicardia", "Confusión", "Disnea", "Hipotensión"],
        "medications": ["Antibióticos de amplio espectro", "Líquidos intravenosos", "Vasopresores", "Corticosteroides", "Insulina"],
        "medical_specialty": "Cuidados Intensivos",
    },
    "Trombosis venosa profunda": {
        "icd10": "I82.409",
        "symptoms": ["Dolor en la pierna", "Hinchazón", "Enrojecimiento", "Calor", "Calambres"],
        "medications": ["Heparina", "Warfarina", "Rivaroxabán", "Apixabán", "Enoxaparina"],
        "medical_specialty": "Medicina Vascular",
    },
    "Embolia pulmonar": {
        "icd10": "I26.99",
        "symptoms": ["Disnea", "Dolor torácico", "Tos", "Hemoptisis", "Taquicardia"],
        "medications": ["Heparina", "Warfarina", "Rivaroxabán", "Apixabán", "Trombolíticos"],
        "medical_specialty": "Neumología",
    },
    "Aneurisma aórtico": {
        "icd10": "I71.9",
        "symptoms": ["Dolor abdominal", "Dolor de espalda", "Masa pulsátil", "Hipotensión", "Síncope"],
        "medications": ["Betabloqueantes", "Estatinas", "Inhibidores de la ECA", "Antihipertensivos", "Analgésicos"],
        "medical_specialty": "Cirugía Vascular",
    },
    "Enfermedad valvular cardíaca": {
        "icd10": "I38",
        "symptoms": ["Disnea", "Fatiga", "Dolor torácico", "Palpitaciones", "Edema"],
        "medications": ["Diuréticos", "Inhibidores de la ECA", "Betabloqueantes", "Anticoagulantes", "Vasodilatadores"],
        "medical_specialty": "Cardiología",
    },
    "Cardiomiopatía": {
        "icd10": "I42.9",
        "symptoms": ["Fatiga", "Disnea", "Hinchazón", "Latido irregular", "Dolor torácico"],
        "medications": ["Inhibidores de la ECA", "Betabloqueantes", "Diuréticos", "Antagonistas de la aldosterona", "Digoxina"],
        "medical_specialty": "Cardiología",
    },
    "Endocarditis": {
        "icd10": "I33.0",
        "symptoms": ["Fiebre", "Fatiga", "Disnea", "Sudores nocturnos", "Dolor articular"],
        "medications": ["Penicilina", "Vancomicina", "Gentamicina", "Ampicilina", "Ceftriaxona"],
        "medical_specialty": "Cardiología",
    },
    "Pericarditis": {
        "icd10": "I30.9",
        "symptoms": ["Dolor torácico", "Fiebre", "Fatiga", "Disnea", "Tos"],
        "medications": ["Ibuprofeno", "Colchicina", "Prednisona", "Ácido acetilsalicílico", "Antibióticos"],
        "medical_specialty": "Cardiología",
    },
    "Infarto de miocardio": {
        "icd10": "I21.9",
        "symptoms": ["Dolor torácico", "Disnea", "Náuseas", "Sudoración", "Mareo"],
        "medications": ["Ácido acetilsalicílico", "Clopidogrel", "Heparina", "Betabloqueantes", "Inhibidores de la ECA"],
        "medical_specialty": "Cardiología",
    },
    "Cardiopatía congénita": {
        "icd10": "Q24.9",
        "symptoms": ["Cianosis", "Disnea", "Fatiga", "Crecimiento deficiente", "Soplos cardíacos"],
        "medications": ["Diuréticos", "Inhibidores de la ECA", "Betabloqueantes", "Prostaglandina E1", "Antibióticos"],
        "medical_specialty": "Cardiología",
    },
    "Neuropatía periférica": {
        "icd10": "G62.9",
        "symptoms": ["Entumecimiento", "Hormigueo", "Dolor", "Debilidad", "Sensación de ardor"],
        "medications": ["Gabapentina", "Pregabalina", "Duloxetina", "Amitriptilina", "Capsaicina"],
        "medical_specialty": "Neurología",
    },
    "Apnea del sueño": {
        "icd10": "G47.30",
        "symptoms": ["Ronquidos", "Somnolencia diurna", "Fatiga", "Cefaleas matutinas", "Irritabilidad"],
        "medications": ["Terapia CPAP", "Modafinilo", "Armodafinilo", "Acetazolamida", "Teofilina"],
        "medical_specialty": "Neumología",
    },
    "Narcolepsia": {
        "icd10": "G47.419",
        "symptoms": ["Somnolencia diurna excesiva", "Cataplejía", "Parálisis del sueño", "Alucinaciones", "Sueño fragmentado"],
        "medications": ["Modafinilo", "Oxibato sódico", "Pitolisant", "Metilfenidato", "Anfetamina"],
        "medical_specialty": "Neurología",
    },
    "Síndrome de piernas inquietas": {
        "icd10": "G25.81",
        "symptoms": ["Urgencia de mover las piernas", "Sensaciones incómodas", "Empeora por la noche", "Alteración del sueño", "Alivio con el movimiento"],
        "medications": ["Pramipexol", "Ropinirol", "Gabapentina", "Suplementos de hierro", "Clonazepam"],
        "medical_specialty": "Neurología",
    },
    "Fibromialgia": {
        "icd10": "M79.7",
        "symptoms": ["Dolor generalizado", "Fatiga", "Alteraciones del sueño", "Dificultades cognitivas", "Cefaleas"],
        "medications": ["Duloxetina", "Pregabalina", "Milnaciprán", "Amitriptilina", "Cicobenzaprina"],
        "medical_specialty": "Reumatología",
    },
    "Lupus": {
        "icd10": "M32.9",
        "symptoms": ["Fatiga", "Dolor articular", "Erupción cutánea", "Fiebre", "Fotosensibilidad"],
        "medications": ["Hidroxicloroquina", "Prednisona", "Metotrexato", "Micofenolato", "Belimumab"],
        "medical_specialty": "Reumatología",
    },
    "Esclerodermia": {
        "icd10": "M34.9",
        "symptoms": ["Engrosamiento de la piel", "Fenómeno de Raynaud", "Dolor articular", "Disnea", "Problemas gastrointestinales"],
        "medications": ["Metotrexato", "Micofenolato", "Ciclofosfamida", "Nifedipino", "Inhibidores de la bomba de protones"],
        "medical_specialty": "Reumatología",
    },
    "Síndrome de Sjögren": {
        "icd10": "M35.00",
        "symptoms": ["Boca seca", "Ojos secos", "Fatiga", "Dolor articular", "Glándulas salivales inflamadas"],
        "medications": ["Pilocarpina", "Cevimelina", "Hidroxicloroquina", "Ciclosporina", "Lágrimas artificiales"],
        "medical_specialty": "Reumatología",
    },
    "Psoriasis": {
        "icd10": "L40.9",
        "symptoms": ["Parches rojos", "Picor", "Escamas", "Piel engrosada", "Dolor articular"],
        "medications": ["Metotrexato", "Ciclosporina", "Adalimumab", "Corticosteroides tópicos", "Análogos de la vitamina D"],
        "medical_specialty": "Dermatología",
    },
    "Eccema": {
        "icd10": "L30.9",
        "symptoms": ["Picor", "Enrojecimiento", "Piel seca", "Erupción", "Hinchazón"],
        "medications": ["Hidrocortisona", "Tacrolimús", "Pimecrolimús", "Dupilumab", "Hidratantes"],
        "medical_specialty": "Dermatología",
    },
    "Rosácea": {
        "icd10": "L71.9",
        "symptoms": ["Enrojecimiento facial", "Granos", "Vasos sanguíneos visibles", "Irritación ocular", "Hinchazón"],
        "medications": ["Metronidazol", "Ácido azelaico", "Ivermectina", "Doxiciclina", "Brimonidina"],
        "medical_specialty": "Dermatología",
    },
    "Acné vulgar": {
        "icd10": "L70.0",
        "symptoms": ["Granos", "Puntos negros", "Puntos blancos", "Quistes", "Cicatrices"],
        "medications": ["Peróxido de benzoilo", "Ácido salicílico", "Retinoides", "Antibióticos", "Isotretinoína"],
        "medical_specialty": "Dermatología",
    },
    "Melanoma": {
        "icd10": "C43.9",
        "symptoms": ["Lunar cambiante", "Forma asimétrica", "Bordes irregulares", "Variación de color", "Aumento de diámetro"],
        "medications": ["Pembrolizumab", "Nivolumab", "Ipilimumab", "Dacarbazina", "Trametinib"],
        "medical_specialty": "Oncología",
    },
    "Carcinoma de células basales": {
        "icd10": "C44.91",
        "symptoms": ["Protuberancia perlada", "Herida que no cicatriza", "Área similar a una cicatriz", "Parche rojo", "Sangrado"],
        "medications": ["Imiquimod", "Fluorouracilo", "Vismodegib", "Sonidegib", "Terapia fotodinámica"],
        "medical_specialty": "Dermatología",
    },
    "Carcinoma de células escamosas": {
        "icd10": "C44.92",
        "symptoms": ["Parche rojo áspero", "Herida abierta", "Superficie costrosa", "Crecimiento con depresión central", "Picor"],
        "medications": ["Fluorouracilo", "Imiquimod", "Pembrolizumab", "Cemiplimab", "Quimioterapia"],
        "medical_specialty": "Dermatología",
    },
    "Leucemia": {
        "icd10": "C95.90",
        "symptoms": ["Fatiga", "Fiebre", "Pérdida de peso", "Fácil aparición de hematomas", "Infecciones recurrentes"],
        "medications": ["Imatinib", "Citarabina", "Daunorrubicina", "Vincristina", "Hidroxiurea"],
        "medical_specialty": "Hematología",
    },
    "Linfoma": {
        "icd10": "C85.90",
        "symptoms": ["Ganglios linfáticos inflamados", "Fiebre", "Sudores nocturnos", "Pérdida de peso", "Fatiga"],
        "medications": ["Rituximab", "Ciclofosfamida", "Doxorrubicina", "Vincristina", "Prednisona"],
        "medical_specialty": "Oncología",
    },
    "Mieloma": {
        "icd10": "C90.00",
        "symptoms": ["Dolor óseo", "Fatiga", "Anemia", "Infecciones recurrentes", "Problemas renales"],
        "medications": ["Bortezomib", "Lenalidomida", "Dexametasona", "Daratumumab", "Melfalán"],
        "medical_specialty": "Hematología",
    },
    "Cáncer de colon": {
        "icd10": "C18.9",
        "symptoms": ["Dolor abdominal", "Sangre en las heces", "Cambio en los hábitos intestinales", "Pérdida de peso", "Fatiga"],
        "medications": ["Fluorouracilo", "Oxaliplatino", "Capecitabina", "Bevacizumab", "Cetuximab"],
        "medical_specialty": "Oncología",
    },
    "Cáncer de páncreas": {
        "icd10": "C25.9",
        "symptoms": ["Dolor abdominal", "Ictericia", "Pérdida de peso", "Pérdida de apetito", "Náuseas"],
        "medications": ["Gemcitabina", "Paclitaxel", "Erlotinib", "FOLFIRINOX", "Capecitabina"],
        "medical_specialty": "Oncología",
    },
    "Cáncer de riñón": {
        "icd10": "C64.9",
        "symptoms": ["Sangre en la orina", "Dolor de espalda", "Pérdida de peso", "Fatiga", "Fiebre"],
        "medications": ["Sunitinib", "Pazopanib", "Axitinib", "Nivolumab", "Cabozantinib"],
        "medical_specialty": "Oncología",
    },
    "Cáncer de vejiga": {
        "icd10": "C67.9",
        "symptoms": ["Sangre en la orina", "Micción frecuente", "Disuria", "Dolor de espalda", "Dolor pélvico"],
        "medications": ["BCG", "Mitomicina", "Gemcitabina", "Cisplatino", "Pembrolizumab"],
        "medical_specialty": "Urología",
    },
    "Cáncer de ovario": {
        "icd10": "C56.9",
        "symptoms": ["Hinchazón abdominal", "Dolor pélvico", "Pérdida de apetito", "Micción frecuente", "Fatiga"],
        "medications": ["Carboplatino", "Paclitaxel", "Bevacizumab", "Olaparib", "Doxorrubicina"],
        "medical_specialty": "Oncología",
    },
    "Cáncer de endometrio": {
        "icd10": "C54.1",
        "symptoms": ["Sangrado vaginal anormal", "Dolor pélvico", "Pérdida de peso", "Fatiga", "Hinchazón"],
        "medications": ["Progesterona", "Tamoxifeno", "Carboplatino", "Paclitaxel", "Doxorrubicina"],
        "medical_specialty": "Oncología",
    },
    "Cáncer de tiroides": {
        "icd10": "C73",
        "symptoms": ["Bulto en el cuello", "Ronquera", "Dificultad para tragar", "Dolor de cuello", "Ganglios linfáticos inflamados"],
        "medications": ["Levotiroxina", "Yodo radiactivo", "Sorafenib", "Lenvatinib", "Cabozantinib"],
        "medical_specialty": "Endocrinología",
    },
    "Tumor cerebral": {
        "icd10": "C71.9",
        "symptoms": ["Cefaleas", "Convulsiones", "Náuseas", "Cambios en la visión", "Deterioro cognitivo"],
        "medications": ["Temozolomida", "Bevacizumab", "Carmustina", "Lomustina", "Dexametasona"],
        "medical_specialty": "Neurología",
    },
    "Glaucoma": {
        "icd10": "H40.9",
        "symptoms": ["Pérdida de visión", "Dolor ocular", "Halos alrededor de las luces", "Ojos rojos", "Náuseas"],
        "medications": ["Timolol", "Latanoprost", "Brimonidina", "Acetazolamida", "Pilocarpina"],
        "medical_specialty": "Oftalmología",
    },
    "Degeneración macular": {
        "icd10": "H35.30",
        "symptoms": ["Visión borrosa", "Pérdida de visión central", "Visión distorsionada", "Manchas oscuras", "Decoloración"],
        "medications": ["Ranibizumab", "Aflibercept", "Bevacizumab", "Verteporfina", "Suplementos vitamínicos"],
        "medical_specialty": "Oftalmología",
    },
    "Cataratas": {
        "icd10": "H26.9",
        "symptoms": ["Visión borrosa", "Sensibilidad al deslumbramiento", "Visión nocturna deficiente", "Colores desvaídos", "Visión doble"],
        "medications": ["Sin medicamentos", "Cirugía", "Gafas", "Lentes antideslumbrantes", "Lupas"],
        "medical_specialty": "Oftalmología",
    },
    "Retinopatía diabética": {
        "icd10": "E11.319",
        "symptoms": ["Visión borrosa", "Flotadores", "Pérdida de visión", "Cambios de color", "Áreas oscuras"],
        "medications": ["Ranibizumab", "Aflibercept", "Bevacizumab", "Terapia láser", "Vitrectomía"],
        "medical_specialty": "Oftalmología",
    },
    "Pérdida auditiva": {
        "icd10": "H91.90",
        "symptoms": ["Dificultad para oír", "Sonidos amortiguados", "Tinnitus", "Dolor de oído", "Problemas de equilibrio"],
        "medications": ["Sin medicamentos", "Audífonos", "Implantes cocleares", "Esteroides", "Antibióticos"],
        "medical_specialty": "Otorrinolaringología",
    },
    "Enfermedad de Ménière": {
        "icd10": "H81.09",
        "symptoms": ["Vértigo", "Pérdida auditiva", "Tinnitus", "Sensación de plenitud en el oído", "Náuseas"],
        "medications": ["Meclizina", "Diuréticos", "Betahistina", "Esteroides", "Gentamicina"],
        "medical_specialty": "Otorrinolaringología",
    },
    "Hiperplasia prostática benigna": {
        "icd10": "N40.0",
        "symptoms": ["Micción frecuente", "Chorro débil", "Urgencia", "Nicturia", "Vaciado incompleto"],
        "medications": ["Tamsulosina", "Finasterida", "Dutasterida", "Terazosina", "Sildenafilo"],
        "medical_specialty": "Urología",
    },
    "Disfunción eréctil": {
        "icd10": "N52.9",
        "symptoms": ["Incapacidad para mantener la erección", "Libido reducida", "Eyaculación prematura", "Estrés", "Fatiga"],
        "medications": ["Sildenafilo", "Tadalafilo", "Vardenafilo", "Alprostadil", "Testosterona"],
        "medical_specialty": "Urología",
    },
    "Síndrome de ovario poliquístico": {
        "icd10": "E28.2",
        "symptoms": ["Períodos irregulares", "Exceso de vello", "Acné", "Aumento de peso", "Infertilidad"],
        "medications": ["Anticonceptivos orales combinados", "Metformina", "Espironolactona", "Clomifeno", "Letrozol"],
        "medical_specialty": "Endocrinología",
    },
    "Endometriosis": {
        "icd10": "N80.9",
        "symptoms": ["Dolor pélvico", "Dismenorrea", "Infertilidad", "Dispareunia", "Períodos abundantes"],
        "medications": ["Ibuprofeno", "Anticonceptivos orales combinados", "Progestinas", "Agonistas de GnRH", "Danazol"],
        "medical_specialty": "Ginecología",
    },
    "Fibromas uterinos": {
        "icd10": "D25.9",
        "symptoms": ["Sangrado menstrual abundante", "Dolor pélvico", "Micción frecuente", "Estreñimiento", "Dolor de espalda"],
        "medications": ["Agonistas de GnRH", "Progestinas", "Ácido tranexámico", "Ibuprofeno", "Acetato de ulipristal"],
        "medical_specialty": "Ginecología",
    },
    "Preeclampsia": {
        "icd10": "O14.90",
        "symptoms": ["Hipertensión arterial", "Proteinuria", "Hinchazón", "Cefalea", "Cambios en la visión"],
        "medications": ["Sulfato de magnesio", "Labetalol", "Hidralazina", "Nifedipino", "Parto"],
        "medical_specialty": "Obstetricia",
    },
    "Diabetes gestacional": {
        "icd10": "O24.419",
        "symptoms": ["Aumento de la sed", "Micción frecuente", "Fatiga", "Visión borrosa", "Náuseas"],
        "medications": ["Insulina", "Metformina", "Gliburida", "Control dietético", "Ejercicio"],
        "medical_specialty": "Obstetricia",
    },
    "Deficiencia de vitamina D": {
        "icd10": "E55.9",
        "symptoms": ["Fatiga", "Dolor óseo", "Debilidad muscular", "Depresión", "Caída del cabello"],
        "medications": ["Suplementos de vitamina D", "Colecalciferol", "Ergocalciferol", "Suplementos de calcio", "Exposición solar"],
        "medical_specialty": "Endocrinología",
    },
    "Anemia ferropénica": {
        "icd10": "D50.9",
        "symptoms": ["Fatiga", "Piel pálida", "Disnea", "Mareo", "Manos frías"],
        "medications": ["Sulfato ferroso", "Gluconato ferroso", "Infusiones de hierro", "Vitamina C", "Ácido fólico"],
        "medical_specialty": "Hematología",
    },
    "Anemia perniciosa": {
        "icd10": "D51.0",
        "symptoms": ["Fatiga", "Debilidad", "Piel pálida", "Entumecimiento", "Cambios cognitivos"],
        "medications": ["Inyecciones de vitamina B12", "Suplementos orales de B12", "Ácido fólico", "Suplementos de hierro", "Eritropoyetina"],
        "medical_specialty": "Hematología",
    },
    "Enfermedad de células falciformes": {
        "icd10": "D57.1",
        "symptoms": ["Crisis de dolor", "Anemia", "Fatiga", "Ictericia", "Hinchazón"],
        "medications": ["Hidroxiurea", "Analgésicos", "Antibióticos", "Transfusiones de sangre", "Voxelotor"],
        "medical_specialty": "Hematología",
    },
    "Hemofilia": {
        "icd10": "D68.311",
        "symptoms": ["Sangrado prolongado", "Dolor articular", "Hematomas", "Hemartrosis", "Epistaxis"],
        "medications": ["Factor VIII", "Factor IX", "Desmopresina", "Antifibrinolíticos", "Emicizumab"],
        "medical_specialty": "Hematología",
    },
    "Trombocitopenia": {
        "icd10": "D69.6",
        "symptoms": ["Hematomas", "Sangrado de encías", "Epistaxis", "Petequias", "Períodos abundantes"],
        "medications": ["Corticosteroides", "IVIG", "Romiplostim", "Eltrombopag", "Esplenectomía"],
        "medical_specialty": "Hematología",
    },
    "Leucopenia": {
        "icd10": "D72.819",
        "symptoms": ["Infecciones frecuentes", "Fiebre", "Fatiga", "Úlceras bucales", "Dolor de garganta"],
        "medications": ["G-CSF", "GM-CSF", "Antibióticos", "Antivirales", "Suplementos vitamínicos"],
        "medical_specialty": "Hematología",
    },
    "Diverticulitis": {
        "icd10": "K57.92",
        "symptoms": ["Dolor abdominal", "Fiebre", "Náuseas", "Estreñimiento", "Diarrea"],
        "medications": ["Ciprofloxacino", "Metronidazol", "Amoxicilina-clavulánico", "Ibuprofeno", "Paracetamol"],
        "medical_specialty": "Gastroenterología",
    },
    "Apendicitis": {
        "icd10": "K35.80",
        "symptoms": ["Dolor abdominal", "Náuseas", "Vómitos", "Fiebre", "Pérdida de apetito"],
        "medications": ["Antibióticos", "Analgésicos", "Líquidos intravenosos", "Cirugía", "Antieméticos"],
        "medical_specialty": "Cirugía General",
    },
    "Colecistitis": {
        "icd10": "K81.0",
        "symptoms": ["Dolor abdominal", "Náuseas", "Vómitos", "Fiebre", "Ictericia"],
        "medications": ["Antibióticos", "Analgésicos", "Ursodiol", "Líquidos intravenosos", "Cirugía"],
        "medical_specialty": "Cirugía General",
    },
    "Pancreatitis": {
        "icd10": "K85.90",
        "symptoms": ["Dolor abdominal", "Náuseas", "Vómitos", "Fiebre", "Pulso rápido"],
        "medications": ["Líquidos intravenosos", "Analgésicos", "Antibióticos", "Suplementos enzimáticos", "Insulina"],
        "medical_specialty": "Gastroenterología",
    },
    "Enfermedad ulcerosa péptica": {
        "icd10": "K27.9",
        "symptoms": ["Dolor abdominal", "Hinchazón", "Náuseas", "Vómitos", "Acidez"],
        "medications": ["Omeprazol", "Ranitidina", "Amoxicilina", "Claritromicina", "Sucralfato"],
        "medical_specialty": "Gastroenterología",
    },
    "Gastritis": {
        "icd10": "K29.70",
        "symptoms": ["Dolor abdominal", "Náuseas", "Vómitos", "Hinchazón", "Pérdida de apetito"],
        "medications": ["Omeprazol", "Ranitidina", "Antiácidos", "Sucralfato", "Antibióticos"],
        "medical_specialty": "Gastroenterología",
    },
    "Esofagitis": {
        "icd10": "K20.90",
        "symptoms": ["Acidez", "Dificultad para tragar", "Dolor torácico", "Regurgitación", "Náuseas"],
        "medications": ["Omeprazol", "Ranitidina", "Sucralfato", "Antiácidos", "Procinéticos"],
        "medical_specialty": "Gastroenterología",
    },
    "Esófago de Barrett": {
        "icd10": "K22.70",
        "symptoms": ["Acidez", "Regurgitación", "Dificultad para tragar", "Dolor torácico", "Náuseas"],
        "medications": ["Omeprazol", "Esomeprazol", "Antiácidos", "Bloqueadores H2", "Inhibidores de la bomba de protones"],
        "medical_specialty": "Gastroenterología",
    },
    "Hernia hiatal": {
        "icd10": "K44.9",
        "symptoms": ["Acidez", "Dolor torácico", "Dificultad para tragar", "Regurgitación", "Hinchazón"],
        "medications": ["Antiácidos", "Bloqueadores H2", "Inhibidores de la bomba de protones", "Procinéticos", "Cirugía"],
        "medical_specialty": "Gastroenterología",
    },
    "Hemorroides": {
        "icd10": "K64.9",
        "symptoms": ["Sangrado rectal", "Picor", "Dolor", "Hinchazón", "Molestia"],
        "medications": ["Hidrocortisona", "Hamamelis", "Lidocaína", "Ablandadores de heces", "Suplementos de fibra"],
        "medical_specialty": "Gastroenterología",
    },
    "Fisura anal": {
        "icd10": "K60.2",
        "symptoms": ["Dolor durante las evacuaciones", "Sangrado", "Picor", "Espasmos", "Estreñimiento"],
        "medications": ["Ungüento de nitroglicerina", "Diltiazem", "Toxina botulínica", "Ablandadores de heces", "Analgésicos"],
        "medical_specialty": "Gastroenterología",
    },
    "Incontinencia fecal": {
        "icd10": "R15.9",
        "symptoms": ["Evacuaciones involuntarias", "Urgencia", "Fugas", "Diarrea", "Estreñimiento"],
        "medications": ["Loperamida", "Subsalicilato de bismuto", "Suplementos de fibra", "Antidiarreicos", "Colestiramina"],
        "medical_specialty": "Gastroenterología",
    },
    "Lesión renal aguda": {
        "icd10": "N17.9",
        "symptoms": ["Disminución de la producción de orina", "Hinchazón", "Fatiga", "Náuseas", "Confusión"],
        "medications": ["Diuréticos", "Líquidos intravenosos", "Diálisis", "Manejo de electrolitos", "Vasopresores"],
        "medical_specialty": "Nefrología",
    },
    "Síndrome nefrótico": {
        "icd10": "N04.9",
        "symptoms": ["Edema", "Proteinuria", "Hipoalbuminemia", "Hiperlipidemia", "Fatiga"],
        "medications": ["Inhibidores de la ECA", "Diuréticos", "Estatinas", "Corticosteroides", "Inmunosupresores"],
        "medical_specialty": "Nefrología",
    },
    "Enfermedad renal poliquística": {
        "icd10": "Q61.3",
        "symptoms": ["Dolor abdominal", "Hipertensión", "Hematuria", "Dolor de espalda", "Infecciones frecuentes"],
        "medications": ["Inhibidores de la ECA", "Diuréticos", "Analgésicos", "Antibióticos", "Tolvaptán"],
        "medical_specialty": "Nefrología",
    },
    "Litiasis renal": {
        "icd10": "N20.0",
        "symptoms": ["Dolor intenso", "Hematuria", "Náuseas", "Vómitos", "Micción frecuente"],
        "medications": ["Analgésicos", "Bloqueadores alfa", "Alopurinol", "Citrato potásico", "Tiazidas"],
        "medical_specialty": "Urología",
    },
    "Cistitis intersticial": {
        "icd10": "N30.10",
        "symptoms": ["Dolor vesical", "Urgencia", "Frecuencia", "Dolor pélvico", "Nicturia"],
        "medications": ["Pentosán polisulfato", "Amitriptilina", "Hidroxizina", "Antihistamínicos", "Instilaciones vesicales"],
        "medical_specialty": "Urología",
    },
    "Vejiga hiperactiva": {
        "icd10": "N32.81",
        "symptoms": ["Urgencia", "Frecuencia", "Nicturia", "Incontinencia", "Espasmos vesicales"],
        "medications": ["Oxibutinina", "Tolterodina", "Mirabegrón", "Solifenacina", "Darifenacina"],
        "medical_specialty": "Urología",
    },
    "Incontinencia de esfuerzo": {
        "icd10": "N39.3",
        "symptoms": ["Fuga de orina al toser", "Estornudar", "Ejercicio", "Levantar", "Reír"],
        "medications": ["Duloxetina", "Crema de estrógenos", "Sin medicamentos", "Ejercicios del suelo pélvico", "Cirugía"],
        "medical_specialty": "Urología",
    },
    "Incontinencia de urgencia": {
        "icd10": "N39.41",
        "symptoms": ["Urgencia repentina para orinar", "Fuga involuntaria", "Frecuencia", "Nicturia", "Espasmos vesicales"],
        "medications": ["Oxibutinina", "Tolterodina", "Mirabegrón", "Solifenacina", "Toxina botulínica"],
        "medical_specialty": "Urología",
    },
    "Pielonefritis": {
        "icd10": "N10",
        "symptoms": ["Fiebre", "Dolor en el flanco", "Náuseas", "Vómitos", "Micción frecuente"],
        "medications": ["Ciprofloxacino", "Ceftriaxona", "Amoxicilina", "Trimetoprima", "Nitrofurantoína"],
        "medical_specialty": "Nefrología",
    },
    "Glomerulonefritis": {
        "icd10": "N05.9",
        "symptoms": ["Hematuria", "Proteinuria", "Edema", "Hipertensión", "Fatiga"],
        "medications": ["Corticosteroides", "Inmunosupresores", "Inhibidores de la ECA", "Diuréticos", "Plasmaféresis"],
        "medical_specialty": "Nefrología",
    },
    "Sinusitis aguda": {
        "icd10": "J01.90",
        "symptoms": ["Dolor facial", "Congestión nasal", "Cefalea", "Fiebre", "Tos"],
        "medications": ["Amoxicilina", "Amoxicilina-clavulánico", "Descongestionantes", "Esteroides nasales", "Analgésicos"],
        "medical_specialty": "Otorrinolaringología",
    },
    "Sinusitis crónica": {
        "icd10": "J32.9",
        "symptoms": ["Congestión nasal", "Presión facial", "Goteo posnasal", "Cefalea", "Fatiga"],
        "medications": ["Esteroides nasales", "Antibióticos", "Irrigación salina", "Descongestionantes", "Cirugía"],
        "medical_specialty": "Otorrinolaringología",
    },
    "Rinitis alérgica": {
        "icd10": "J30.9",
        "symptoms": ["Estornudos", "Nariz que moquea", "Picor en los ojos", "Congestión", "Goteo posnasal"],
        "medications": ["Loratadina", "Cetirizina", "Fluticasona", "Montelukast", "Azitromicina"],
        "medical_specialty": "Alergología",
    },
    "Otitis media": {
        "icd10": "H66.90",
        "symptoms": ["Dolor de oído", "Fiebre", "Pérdida auditiva", "Drenaje de líquido", "Irritabilidad"],
        "medications": ["Amoxicilina", "Azitromicina", "Ibuprofeno", "Paracetamol", "Descongestionantes"],
        "medical_specialty": "Otorrinolaringología",
    },
    "Otitis externa": {
        "icd10": "H60.90",
        "symptoms": ["Dolor de oído", "Picor", "Enrojecimiento", "Hinchazón", "Secreción"],
        "medications": ["Ciprofloxacino", "Hidrocortisona", "Neomicina", "Ácido acético", "Analgésicos"],
        "medical_specialty": "Otorrinolaringología",
    },
    "Faringitis": {
        "icd10": "J02.9",
        "symptoms": ["Dolor de garganta", "Fiebre", "Ganglios linfáticos inflamados", "Cefalea", "Tos"],
        "medications": ["Penicilina", "Amoxicilina", "Azitromicina", "Ibuprofeno", "Paracetamol"],
        "medical_specialty": "Otorrinolaringología",
    },
    "Amigdalitis": {
        "icd10": "J03.90",
        "symptoms": ["Dolor de garganta", "Fiebre", "Amígdalas inflamadas", "Dificultad para tragar", "Cefalea"],
        "medications": ["Penicilina", "Amoxicilina", "Azitromicina", "Ibuprofeno", "Paracetamol"],
        "medical_specialty": "Otorrinolaringología",
    },
    "Laringitis": {
        "icd10": "J04.0",
        "symptoms": ["Ronquera", "Dolor de garganta", "Tos", "Dificultad para hablar", "Fiebre"],
        "medications": ["Ibuprofeno", "Paracetamol", "Inhalación de vapor", "Reposo vocal", "Antibióticos"],
        "medical_specialty": "Otorrinolaringología",
    },
    "Crup": {
        "icd10": "J05.0",
        "symptoms": ["Tos perruna", "Estridor", "Ronquera", "Fiebre", "Dificultad respiratoria"],
        "medications": ["Dexametasona", "Epinefrina", "Aire humidificado", "Ibuprofeno", "Paracetamol"],
        "medical_specialty": "Pediatría",
    },
    "Bronquiolitis": {
        "icd10": "J21.9",
        "symptoms": ["Tos", "Sibilancias", "Disnea", "Fiebre", "Nariz que moquea"],
        "medications": ["Cuidados de soporte", "Oxígeno", "Hidratación", "Salbutamol", "Corticosteroides"],
        "medical_specialty": "Pediatría",
    },
    "Enfisema": {
        "icd10": "J43.9",
        "symptoms": ["Disnea", "Tos crónica", "Sibilancias", "Fatiga", "Pérdida de peso"],
        "medications": ["Broncodilatadores", "Esteroides inhalados", "Oxigenoterapia", "Antibióticos", "Rehabilitación pulmonar"],
        "medical_specialty": "Neumología",
    },
    "Fibrosis quística": {
        "icd10": "E84.9",
        "symptoms": ["Tos persistente", "Sibilancias", "Infecciones recurrentes", "Crecimiento deficiente", "Piel salada"],
        "medications": ["Ivacaftor", "Lumacaftor", "Dornasa alfa", "Enzimas pancreáticas", "Antibióticos"],
        "medical_specialty": "Neumología",
    },
    "Enfermedad pulmonar intersticial": {
        "icd10": "J84.9",
        "symptoms": ["Disnea", "Tos seca", "Fatiga", "Pérdida de peso", "Molestia torácica"],
        "medications": ["Prednisona", "Azatioprina", "Nintedanib", "Pirfenidona", "Oxigenoterapia"],
        "medical_specialty": "Neumología",
    },
    "Sarcoidosis": {
        "icd10": "D86.9",
        "symptoms": ["Fatiga", "Tos", "Disnea", "Erupción cutánea", "Dolor articular"],
        "medications": ["Prednisona", "Metotrexato", "Hidroxicloroquina", "Infliximab", "Azatioprina"],
        "medical_specialty": "Neumología",
    },
    "Derrame pleural": {
        "icd10": "J90",
        "symptoms": ["Disnea", "Dolor torácico", "Tos", "Fiebre", "Pérdida de peso"],
        "medications": ["Diuréticos", "Antibióticos", "Corticosteroides", "Quimioterapia", "Toracocentesis"],
        "medical_specialty": "Neumología",
    },
    "Neumotórax": {
        "icd10": "J93.9",
        "symptoms": ["Dolor torácico", "Disnea", "Taquicardia", "Cianosis", "Disminución de sonidos respiratorios"],
        "medications": ["Oxígeno", "Analgésicos", "Tubo torácico", "Cirugía", "Pleurodesis"],
        "medical_specialty": "Neumología",
    },
    "Hipertensión pulmonar": {
        "icd10": "I27.20",
        "symptoms": ["Disnea", "Fatiga", "Dolor torácico", "Mareo", "Hinchazón"],
        "medications": ["Sildenafilo", "Bosentán", "Epoprostenol", "Treprostinil", "Riociguat"],
        "medical_specialty": "Neumología",
    },
    "Diabetes mellitus tipo 1": {
        "icd10": "E10.9",
        "symptoms": ["Aumento de la sed", "Micción frecuente", "Hambre extrema", "Pérdida de peso inexplicada", "Fatiga"],
        "medications": ["Insulina", "Pramlintida", "Metformina", "Empagliflozina", "Liraglutida"],
        "medical_specialty": "Endocrinología",
    },
    "Enfermedad hepática crónica": {
        "icd10": "K76.9",
        "symptoms": ["Fatiga", "Ictericia", "Dolor abdominal", "Hinchazón en las piernas", "Picor"],
        "medications": ["Diuréticos", "Bloqueadores beta", "Ursodiol", "Antivirales", "Inmunosupresores"],
        "medical_specialty": "Gastroenterología",
    },
    "Enfermedad cardíaca hipertensiva": {
        "icd10": "I11.9",
        "symptoms": ["Disnea", "Fatiga", "Dolor torácico", "Palpitaciones", "Mareo"],
        "medications": ["Lisinopril", "Metoprolol", "Hidroclorotiazida", "Amlodipino", "Losartán"],
        "medical_specialty": "Cardiología",
    },
    "Trastorno de estrés postraumático": {
        "icd10": "F43.1",
        "symptoms": ["Flashbacks", "Pesadillas", "Ansiedad grave", "Comportamientos de evitación", "Hipervigilancia"],
        "medications": ["Sertralina", "Paroxetina", "Venlafaxina", "Prazosina", "Clonidina"],
        "medical_specialty": "Psiquiatría",
    },
    "Trastorno por uso de sustancias": {
        "icd10": "F19.9",
        "symptoms": ["Ansias", "Pérdida de control", "Tolerancia", "Síntomas de abstinencia", "Abandono de responsabilidades"],
        "medications": ["Naltrexona", "Acamprosato", "Disulfiram", "Metadona", "Buprenorfina"],
        "medical_specialty": "Psiquiatría",
    },
    "Síndrome de dolor crónico": {
        "icd10": "G89.4",
        "symptoms": ["Dolor persistente", "Fatiga", "Alteración del sueño", "Depresión", "Movilidad reducida"],
        "medications": ["Gabapentina", "Duloxetina", "Tramadol", "Amitriptilina", "Ibuprofeno"],
        "medical_specialty": "Medicina del Dolor",
    },
    "Trastorno convulsivo": {
        "icd10": "G40.909",
        "symptoms": ["Convulsiones", "Pérdida de conciencia", "Convulsiones", "Confusión", "Movimientos incontrolados"],
        "medications": ["Levetiracetam", "Ácido valproico", "Carbamazepina", "Lamotrigina", "Topiramato"],
        "medical_specialty": "Neurología",
    },
}
