from .. import HealthcareProvider as BaseHealthcareProvider


class Provider(BaseHealthcareProvider):
    """Faker provider for generating healthcare/medical fake data (de_DE)."""

    diseases= (
        "Diabetes mellitus Typ 2",
        "Arterielle Hypertonie",
        "Hyperlipidämie",
        "Koronare Herzkrankheit (KHK)",
        "Chronisch obstruktive Lungenerkrankung (COPD)",
        "Asthma bronchiale",
        "Chronische Niereninsuffizienz",
        "Arthrose",
        "Rheumatoide Arthritis",
        "Depression",
        "Angststörung",
        "Gastroösophageale Refluxkrankheit (GERD)",
        "Adipositas",
        "Hypothyreose",
        "Vorhofflimmern",
        "Herzinsuffizienz",
        "Pneumonie",
        "Harnwegsinfekt",
        "Akute Bronchitis",
        "Anämie",
        "Migräne",
        "Schlaganfall (Apoplex)",
        "Alzheimer-Krankheit",
        "Brustkrebs (Mammakarzinom)",
        "Prostatakrebs (Prostatakarzinom)",
        "Lungenkrebs (Bronchialkarzinom)",
        "COVID-19",
        "Influenza (Grippe)",
        "Osteoporose",
        "Periphere arterielle Verschlusskrankheit (pAVK)",
        "Angina Pectoris",
        "Hyperthyreose",
        "Gicht (Urikopathie)",
        "Multiple Sklerose",
        "Morbus Parkinson",
        "Epilepsie",
        "Bipolare Störung",
        "Schizophrenie",
        "Aufmerksamkeitsdefizit-/Hyperaktivitätsstörung (ADHS)",
        "Autismus-Spektrum-Störung",
        "Morbus Crohn",
        "Colitis ulcerosa",
        "Reizdarmsyndrom",
        "Zöliakie",
        "Leberzirrhose",
        "Hepatitis C",
        "HIV/AIDS",
        "Tuberkulose",
        "Sepsis",
        "Tiefe Venenthrombose (TVT)",
        "Lungenembolie",
        "Aortenaneurysma",
        "Herzklappenerkrankung",
        "Kardiomyopathie",
        "Endokarditis",
        "Perikarditis",
        "Myokardinfarkt (Herzinfarkt)",
        "Angeborener Herzfehler",
        "Polyneuropathie",
        "Schlafapnoe",
        "Narkolepsie",
        "Restless-Legs-Syndrom",
        "Fibromyalgie",
        "Systemischer Lupus Erythematodes",
        "Sklerodermie",
        "Sjögren-Syndrom",
        "Psoriasis (Schuppenflechte)",
        "Neurodermitis (Atopisches Ekzem)",
        "Rosazea",
        "Akne vulgaris",
        "Melanom",
        "Basaliom",
        "Plattenepithelkarzinom",
        "Leukämie",
        "Lymphom",
        "Multiples Myelom",
        "Darmkrebs (Kolorektales Karzinom)",
        "Pankreaskrebs",
        "Nierenkrebs",
        "Blasenkrebs",
        "Eierstockkrebs (Ovarialkarzinom)",
        "Gebärmutterkörperkrebs (Endometriumkarzinom)",
        "Schilddrüsenkrebs",
        "Hirntumor",
        "Glaukom (Grüner Star)",
        "Makuladegeneration",
        "Katarakt (Grauer Star)",
        "Diabetische Retinopathie",
        "Hörverlust",
        "Morbus Menière",
        "Benigne Prostatahyperplasie (BPH)",
        "Erektile Dysfunktion",
        "Polyzystisches Ovar-Syndrom (PCOS)",
        "Endometriose",
        "Uterus myomatosus",
        "Präeklampsie",
        "Gestationsdiabetes",
        "Vitamin-D-Mangel",
        "Eisenmangelanämie",
        "Perniziöse Anämie",
        "Sichelzellenanämie",
        "Hämophilie",
        "Thrombozytopenie",
        "Leukopenie",
        "Divertikulitis",
        "Appendizitis (Blinddarmentzündung)",
        "Cholezystitis",
        "Pankreatitis",
        "Ulcus ventriculi / duodeni",
        "Gastritis",
        "Ösophagitis",
        "Barrett-Ösophagus",
        "Hiatushernie",
        "Hämorrhoiden",
        "Analfissur",
        "Stuhlinkontinenz",
        "Akutes Nierenversagen",
        "Nephrotisches Syndrom",
        "Zystennieren",
        "Nierensteine (Nephrolithiasis)",
        "Interstitielle Zystitis",
        "Reizblase",
        "Belastungsinkontinenz",
        "Dranginkontinenz",
        "Pyelonephritis (Nierenbeckenentzündung)",
        "Glomerulonephritis",
        "Akute Sinusitis",
        "Chronische Sinusitis",
        "Allergische Rhinitis (Heuschnupfen)",
        "Otitis media (Mittelohrentzündung)",
        "Otitis externa",
        "Pharyngitis",
        "Tonsillitis (Mandelentzündung)",
        "Laryngitis",
        "Pseudokrupp",
        "Bronchiolitis",
        "Lungenemphysem",
        "Mukoviszidose",
        "Lungenfibrose",
        "Sarkoidose",
        "Pleuraerguss",
        "Pneumothorax",
        "Pulmonale Hypertonie",
    )

    # Códigos ICD-10 são mantidos, pois são padrão internacional (embora a Alemanha use ICD-10-GM, os códigos base são compatíveis)
    icd10_codes= (
        "E11.9", "I10", "E78.5", "I25.10", "J44.9",
        "J45.909", "N18.9", "M17.9", "M79.1", "F32.9",
        "F41.9", "K21.9", "E66.9", "E03.9", "I48.91",
        "I50.9", "J18.9", "N39.0", "J20.9", "D64.9",
        "G43.909", "I63.9", "G30.9", "R10.9", "R50.9",
        "R06.00", "R53.81", "Z00.00", "Z79.899", "Z68.1",
        "C50.919", "C61", "C34.90", "U07.1", "J11.1",
        "M81.0", "I73.9", "K70.30", "G20", "E10.9",
        "I20.9", "E05.90", "M10.9", "G35", "G21.9",
        "G40.909", "F31.9", "F20.9", "F90.9", "F84.0",
        "K50.90", "K51.90", "K58.9", "K90.0", "K74.60",
        "B18.2", "B20", "A15.9", "A41.9", "I82.409",
        "I26.99", "I71.9", "I35.9", "I42.9", "I33.9",
        "I30.9", "I21.9", "Q24.9", "G62.9", "G47.33",
        "G47.419", "G25.81", "M79.7", "M32.9", "M34.9",
        "M35.00", "L40.9", "L20.9", "L71.9", "L70.0",
        "C43.9", "C44.91", "C44.92", "C95.90", "C85.90",
        "C90.00", "C18.9", "C25.9", "C64.9", "C67.9",
        "C56.9", "C54.1", "C73", "C71.9", "H40.9",
        "H35.30", "H25.9", "H36", "H90.3", "H81.0",
        "N40.0", "N52.9", "E28.2", "N80.9", "D25.9",
        "O14.9", "O24.919", "E55.9", "D50.9", "D51.0",
        "D57.1", "D66", "D69.6", "D70.9", "K57.90",
        "K35.80", "K81.9", "K85.90", "K27.9", "K29.70",
        "K20.9", "K22.70", "K44.9", "I84.9", "K60.2",
        "R15.9", "N17.9", "N04.9", "Q61.9", "N20.0",
        "N30.10", "N32.81", "N39.3", "N39.41", "N10",
        "N05.9", "J01.90", "J32.9", "J30.9", "H66.90",
        "H60.90", "J02.9", "J03.90", "J04.0", "J05.0",
        "J21.9", "J43.9", "E84.9", "J84.9", "D86.9",
        "J90", "J93.9", "I27.20", "Z00.01", "Z00.121",
        "Z00.129", "Z13.6", "Z13.89", "Z23", "J06.9",
        "R07.9", "M54.5", "M25.50", "M19.90", "R51.9",
        "R53.83", "E78.0", "I11.9", "I25.5", "I63.50",
        "I67.9", "I70.0", "I21.3", "I21.4", "I48.0",
        "I48.2", "I49.9", "I50.1", "I50.20", "I50.30",
        "I50.40", "I61.9", "I63.40", "I64", "I69.30",
        "I80.10", "I80.20", "I80.3", "I82.40", "I82.90",
        "I83.90", "I87.2", "I95.9", "J00", "J02.0",
        "J03.00", "J04.10", "J05.10", "J12.89", "J15.9",
        "J18.0", "J18.1", "J20.0", "J20.8", "J21.0",
        "J40", "J41.0", "J42", "J44.0", "J44.1",
        "J45.20", "J45.30", "J45.40", "J45.50", "J45.901",
        "J47.0", "J47.9", "J60", "J61", "J70.9",
        "J80", "J81.0", "J82", "J84.10", "J84.112",
        "J84.117", "J84.170", "J84.89", "J91.8", "J92.0",
        "J93.0", "J93.11", "J93.12", "J93.81", "J94.0",
        "J94.2", "J94.8", "J95.1", "J95.2", "J96.00",
        "J96.01", "J96.02", "J96.10", "J96.11", "J96.12",
        "J96.20", "J96.21", "J96.22", "J96.90", "J96.91",
        "J96.92", "J98.4", "J98.9", "K02.9", "K03.9",
        "K04.7", "K04.90", "K05.6", "K08.9", "K12.0",
        "K21.0", "K22.0", "K22.10", "K22.2", "K22.6",
        "K25.9", "K26.9", "K28.9", "K29.00", "K29.50",
        "K29.60", "K30", "K31.84", "K31.9", "K35.2",
        "K35.3", "K36", "K38.9", "K40.90", "K42.9",
        "K43.9", "K46.9", "K50.00", "K50.10", "K50.80",
        "K51.00", "K51.20", "K51.30", "K51.50", "K51.80",
        "K52.9", "K55.0", "K56.0", "K56.60", "K57.30",
        "K57.32", "K57.50", "K57.92", "K58.0", "K59.00",
        "K59.01", "K59.02", "K59.09", "K59.1", "K59.2",
        "K59.3", "K59.4", "K60.0", "K60.1", "K60.3",
        "K60.4", "K61.0", "K62.5", "K63.5", "K64.9",
        "K70.0", "K70.10", "K70.9", "K71.9", "K72.00",
        "K72.10", "K72.90", "K73.9", "K74.0", "K74.3",
        "K75.9", "K76.0", "K76.9", "K80.20", "K80.50",
        "K82.9", "K83.0", "K85.00", "K85.10", "K85.20",
        "K85.30", "K85.80", "K86.0", "K86.1", "K86.9",
        "K91.2", "K92.0", "K92.1", "K92.2", "K92.9",
    )

    medical_specialties= (
        "Kardiologie",
        "Dermatologie",
        "Endokrinologie",
        "Gastroenterologie",
        "Hämatologie",
        "Infektiologie",
        "Nephrologie",
        "Neurologie",
        "Onkologie",
        "Pneumologie",
        "Rheumatologie",
        "Allergologie und Immunologie",
        "Allgemeinmedizin (Hausarzt)",
        "Innere Medizin",
        "Kinder- und Jugendmedizin (Pädiatrie)",
        "Psychiatrie und Psychotherapie",
        "Frauenheilkunde und Geburtshilfe (Gynäkologie)",
        "Orthopädie und Unfallchirurgie",
        "Urologie",
        "Augenheilkunde (Ophthalmologie)",
        "Hals-Nasen-Ohren-Heilkunde (HNO)",
        "Anästhesiologie",
        "Radiologie",
        "Pathologie",
        "Notfallmedizin",
        "Allgemeinchirurgie",
        "Plastische und Ästhetische Chirurgie",
        "Neurochirurgie",
        "Physikalische und Rehabilitative Medizin",
        "Gefäßchirurgie",
        "Thoraxchirurgie",
        "Herzchirurgie",
        "Viszeralchirurgie",
        "Transplantationsmedizin",
        "Kinderchirurgie",
        "Neonatologie",
        "Geriatrie",
        "Schmerztherapie",
        "Palliativmedizin",
        "Sportmedizin",
        "Arbeitsmedizin",
        "Präventivmedizin",
        "Humangenetik",
        "Nuklearmedizin",
        "Interventionelle Radiologie",
    )

    hospital_departments= (
        "Zentrale Notaufnahme (ZNA)",
        "Intensivstation (ITS/ICU)",
        "Coronary Care Unit (CCU) / Herzüberwachung",
        "Operationssaal (OP)",
        "Kreißsaal",
        "Kinderstation",
        "Wöchnerinnenstation",
        "Onkologische Station",
        "Röntgenabteilung",
        "Labor",
        "Krankenhausapotheke",
        "Physiotherapie",
        "Ergotherapie",
        "Atemtherapie",
        "Chirurgische Station",
        "Innere Abteilung",
        "Ambulanz / Poliklinik",
        "Psychiatrische Station",
        "Reha-Abteilung",
        "Endoskopie",
        "Neugeborenen-Intensivstation (NICU)",
        "Station für Schwerbrandverletzte",
        "Dialysestation",
        "Schlaflabor",
        "Wundversorgung",
        "Infusionsambulanz",
        "Kardiologische Funktionsabteilung",
        "Stroke Unit (Schlaganfallstation)",
        "Aufnahmestation",
        "Aufwachraum (AWR)",
    )

    # Nomes genéricos adaptados para a grafia alemã (INN - International Nonproprietary Name)
    generic_drugs= (
        "Atorvastatin", "Levothyroxin", "Lisinopril", "Metformin", "Amlodipin",
        "Metoprolol", "Omeprazol", "Simvastatin", "Losartan", "Gabapentin",
        "Hydrochlorothiazid (HCT)", "Sertralin", "Amoxicillin", "Salbutamol", "Citalopram",
        "Pantoprazol", "Trazodon", "Fluoxetin", "Tramadol", "Clopidogrel",
        "Rosuvastatin", "Escitalopram", "Montelukast", "Furosemid", "Bupropion",
        "Prednison", "Meloxicam", "Dexamfetamin", "Duloxetin", "Carvedilol",
        "Ibuprofen", "Paracetamol", "Acetylsalicylsäure (ASS)", "Naproxen", "Warfarin / Phenprocoumon",
        "Apixaban", "Rivaroxaban", "Dabigatran", "Insulin Glargin", "Insulin Aspart",
        "Insulin Lispro", "Insulin Detemir", "Empagliflozin", "Dapagliflozin", "Sitagliptin",
        "Glimepirid", "Pioglitazon", "Acarbose", "Repaglinid", "Nateglinid",
        "Enalapril", "Quinapril", "Ramipril", "Benazepril", "Fosinopril",
        "Candesartan", "Valsartan", "Irbesartan", "Olmesartan", "Telmisartan",
        "Diltiazem", "Verapamil", "Nifedipin", "Felodipin", "Isradipin",
        "Bisoprolol", "Atenolol", "Propranolol", "Nadolol", "Labetalol",
        "Clonidin", "Hydralazin", "Prazosin", "Doxazosin", "Terazosin",
        "Spironolacton", "Triamteren", "Amilorid", "Chlortalidon", "Indapamid",
        "Amiodaron", "Digoxin", "Flecainid", "Propafenon", "Sotalol",
        "Nitrofurantoin", "Ciprofloxacin", "Levofloxacin", "Azithromycin", "Clarithromycin",
        "Doxycyclin", "Cefalexin", "Cefuroxim", "Ceftriaxon", "Clindamycin",
        "Metronidazol", "Vancomycin", "Linezolid", "Aciclovir", "Valaciclovir",
        "Oseltamivir", "Fluconazol", "Voriconazol", "Amphotericin B", "Terbinafin",
        "Venlafaxin", "Desvenlafaxin", "Mirtazapin", "Nortriptylin", "Amitriptylin",
        "Paroxetin", "Fluvoxamin", "Clomipramin", "Lithium", "Valproat",
        "Lamotrigin", "Carbamazepin", "Oxcarbazepin", "Topiramat", "Levetiracetam",
        "Phenytoin", "Phenobarbital", "Primidon", "Lacosamid", "Zonisamid",
        "Donepezil", "Rivastigmin", "Galantamin", "Memantin", "Levodopa",
        "Carbidopa", "Pramipexol", "Ropinirol", "Rasagilin", "Selegilin",
        "Baclofen", "Tizanidin", "Cyclobenzaprin", "Carisoprodol", "Methocarbamol",
        "Alprazolam", "Lorazepam", "Diazepam", "Clonazepam", "Temazepam",
        "Zolpidem", "Zopiclon", "Zaleplon", "Ramelteon", "Suvorexant",
        "Methylphenidat", "Dexmethylphenidat", "Lisdexamfetamin", "Atomoxetin", "Guanfacin",
        "Aripiprazol", "Quetiapin", "Olanzapin", "Risperidon", "Ziprasidon",
        "Paliperidon", "Lurasidon", "Haloperidol", "Chlorpromazin", "Perphenazin",
        "Tamsulosin", "Finasterid", "Dutasterid", "Sildenafil", "Tadalafil",
        "Vardenafil", "Oxybutynin", "Tolterodin", "Solifenacin", "Darifenacin",
        "Eisensulfat", "Folsäure", "Vitamin B12", "Vitamin D", "Calciumcarbonat",
        "Ranitidin", "Famotidin", "Esomeprazol", "Lansoprazol", "Rabeprazol",
        "Allopurinol", "Colchicin", "Probenecid", "Febuxostat", "Pegloticase",
        "Celecoxib", "Diclofenac", "Indometacin", "Ketorolac", "Piroxicam",
        "Oxycodon", "Tilidin", "Morphin", "Fentanyl", "Codein",
        "Hydromorphon", "Oxymorphon", "Methadon", "Buprenorphin", "Naloxon",
        "Metamizol (Novalgin)",
    )

    # Marcas comerciais comuns na Alemanha (DE)
    brand_drugs= (
        "Sortis", "L-Thyroxin Henning", "Lisinopril-ratiopharm", "Glucophage", "Norvasc",
        "Beloc-Zok", "Antra MUPS", "Zocor", "Lorzaar", "Gabapentin-neuraxpharm",
        "Zoloft", "Fluctin", "Trevilor", "Cipralex", "Cymbalta",
        "Iscover", "Eliquis", "Ozempic", "Jardiance", "Forxiga",
        "Crestor", "Januvia", "Victoza", "Trulicity", "Mounjaro",
        "Wegovy", "Lantus", "Humalog", "NovoRapid", "Toujeo",
        "Abasaglar", "Levemir", "Tresiba", "Delix", "Ramilich",
        "Xanef", "Accuzide", "Diovan", "Karvea", "Votum",
        "Micardis", "Dilatrend", "Tenormin", "Dociton", "Beloc",
        "Catapresan", "Dilzem", "Adalat", "Carmen",
        "Plendil", "Aldactone", "Lasix", "Moduretik",
        "Torasemid", "Hygroton", "Cordarex", "Lanicor", "Tambocor",
        "Rytmonorm", "Sotalex", "Xarelto", "Pradaxa", "Lixiana",
        "Nifuretten", "Cipro", "Tavanic", "Zithromax", "Klacid",
        "Doxy-Wolff", "Keflex", "Elobact", "Rocephin", "Sobelin",
        "Clont", "Vancomycin CP", "Zyvoxid", "Zovirax", "Valtrex",
        "Tamiflu", "Diflucan", "Vfend", "Ambisome", "Lamisil",
        "Elontril", "Desiq", "Remergil", "Nortrilen", "Saroten",
        "Seroxat", "Fevarin", "Anafranil", "Quilonum", "Ergenyl",
        "Lamictal", "Tegretal", "Trileptal", "Topamax", "Keppra",
        "Phenhydan", "Luminal", "Mylepsinum", "Vimpat", "Zonegran",
        "Aricept", "Exelon", "Reminyl", "Axura", "Restex",
        "Sifrol", "Requip", "Azilect", "Movergan", "Lioresal",
        "Sirdalud", "Ambril", "Musaril", "Ortoton", "Tavor",
        "Tafil", "Valium", "Rivotril", "Remestan", "Stilnox",
        "Ximovan", "Sonata", "Circadin", "Ritalin",
        "Concerta", "Medikinet", "Elvanse", "Strattera", "Intuniv",
        "Abilify", "Seroquel", "Zyprexa", "Risperdal", "Zeldox",
        "Xeplion", "Latuda", "Haldol", "Megaphen", "Decentan",
        "Alna", "Proscar", "Avodart", "Viagra", "Cialis",
        "Levitra", "Dridase", "Detrusitol", "Vesikur", "Emselex",
        "Ferro sanol", "Folsan", "Vigantol", "Calcium Sandoz",
        "Zantic", "Pepdul", "Nexium", "Agopton", "Pariet",
        "Zyloric", "Colchysat", "Adenuric",
        "Celebrex", "Voltaren", "Amuno", "Felden",
        "Oxygesic", "Valoron", "MST Continus", "Durogesic", "Tussamag",
        "Palladon", "Polamidon", "Subutex", "Narcanti", "Novalgin",
        "Viani", "Symbicort", "Spiriva", "Singulair",
        "Salbuhexal", "Berodual", "Flutide", "Pulmicort",
        "Keytruda", "Opdivo", "Yervoy", "Tecentriq", "Imfinzi",
        "Humira", "Enbrel", "Remicade", "Stelara", "Cosentyx",
        "Dupixent", "Xolair", "Skyrizi", "Entyvio",
    )

    symptoms= (
        "Fieber", "Husten", "Atemnot (Dyspnoe)", "Kopfschmerzen", "Müdigkeit / Fatigue",
        "Bauchschmerzen", "Übelkeit", "Erbrechen", "Durchfall (Diarrhö)", "Brustschmerzen (Thoraxschmerz)",
        "Schwindel", "Hautausschlag (Exanthem)", "Halsschmerzen", "Gelenkschmerzen (Arthralgie)", "Rückenschmerzen",
        "Bluthusten (Hämoptyse)", "Gewichtsverlust", "Schwellung (Ödem)", "Verschwommenes Sehen", "Herzklopfen (Palpitationen)",
        "Schüttelfrost", "Schwitzen (Hyperhidrose)", "Muskelschmerzen (Myalgie)", "Schwäche", "Taubheitsgefühl",
        "Kribbeln (Parästhesie)", "Verwirrtheit", "Gedächtnisverlust", "Angstzustände", "Niedergeschlagenheit",
        "Schlaflosigkeit (Insomnie)", "Zittern (Tremor)", "Krampfanfälle", "Bewusstlosigkeit", "Ohnmacht (Synkope)",
        "Herzrasen (Tachykardie)", "Herzrhythmusstörungen", "Verlangsamter Herzschlag (Bradykardie)", "Bluthochdruck", "Niedriger Blutdruck (Hypotonie)",
        "Schluckbeschwerden (Dysphagie)", "Sodbrennen", "Blut im Stuhl", "Teerstuhl (Meläna)", "Verstopfung (Obstipation)",
        "Blähbauch", "Blähungen (Flatulenz)", "Aufstoßen", "Appetitlosigkeit", "Heißhunger",
        "Häufiges Wasserlassen (Pollakisurie)", "Schmerzen beim Wasserlassen (Dysurie)", "Blut im Urin (Hämaturie)", "Trüber Urin", "Dunkler Urin",
        "Inkontinenz", "Impotenz", "Schmerzen beim Geschlechtsverkehr (Dyspareunie)", "Unregelmäßige Periode", "Starke Regelblutung (Hypermenorrhoe)",
        "Vaginaler Ausfluss", "Zwischenblutungen", "Hitzewallungen", "Nachtschweiß", "Brustspannen",
        "Knoten in der Brust", "Flüssigkeitsaustritt aus der Brustwarze", "Hodenschmerzen", "Hodenschwellung", "Raumforderung im Skrotum",
        "Juckreiz (Pruritus)", "Nesselsucht (Urtikaria)", "Ekzem", "Trockene Haut", "Fettige Haut",
        "Haarausfall (Alopezie)", "Brüchige Nägel", "Verfärbte Nägel", "Nagelpilz", "Schuppen",
        "Rote Augen", "Tränende Augen", "Doppeltsehen (Diplopie)", "Lichtempfindlichkeit", "Augenschmerzen",
        "Ohrenschmerzen", "Ohrenausfluss", "Ohrgeräusche (Tinnitus)", "Hörverlust", "Gleichgewichtsstörungen",
        "Laufende Nase (Rhinorrhoe)", "Verstopfte Nase", "Nasenbluten (Epistaxis)", "Niesen", "Verschleimung",
        "Geruchsverlust (Anosmie)", "Geschmacksverlust (Ageusie)", "Mundgeruch (Foetor ex ore)", "Mundtrockenheit (Xerostomie)", "Aphthen",
        "Zahnfleischbluten", "Zahnschmerzen", "Kieferschmerzen", "Kauprobleme", "Atembeschwerden",
        "Pfeifende Atmung (Giemen)", "Schnelle Atmung (Tachypnoe)", "Flache Atmung", "Schnarchen", "Atemaussetzer",
    )

    blood_types= (
        "A+", "A-", "B+", "B-", "AB+", "AB-", "0+", "0-", # 0 em vez de O na Alemanha
    )

    allergies= (
        "Penicillin", "Erdnüsse", "Schalenfrüchte (Nüsse)", "Krebstiere", "Fisch",
        "Kuhmilch", "Hühnerei", "Soja", "Weizen", "Sesam",
        "Latex", "Bienengift", "Pollen (Gräser, Bäume)", "Hausstaubmilben", "Tierhaare",
        "Sulfonamide", "Aspirin (ASS)", "Ibuprofen", "Codein", "Morphin",
        "Kontrastmittel", "Lokalanästhetika", "Nickel", "Pflasterklebstoff", "Duftstoffe",
        "Insektenstiche", "Schimmelpilze", "Kakerlaken", "Gräser", "Ambrosia",
        "Mais", "Senf", "Sellerie", "Lupinen", "Sulfite",
        "Glutamat", "Farbstoffe", "Gluten", "Laktose", "Fruktose",
    )

    medical_procedures= (
        "Blutuntersuchung", "Magnetresonanztomographie (MRT)", "Computertomographie (CT)", "Röntgen", "Ultraschall (Sonographie)",
        "Darmspiegelung (Koloskopie)", "Magenspiegelung (Gastroskopie)", "Blinddarmentfernung (Appendektomie)", "Gallenblasenentfernung (Cholezystektomie)", "Kaiserschnitt (Sectio)",
        "Gebärmutterentfernung (Hysterektomie)", "Knieprothese (Knie-TEP)", "Hüftprothese (Hüft-TEP)", "Katarakt-OP", "Biopsie",
        "Physiotherapie", "Elektrokardiogramm (EKG)", "Echokardiographie", "Impfung", "Wundversorgung",
        "Herzkatheteruntersuchung", "Angioplastie (PTCA)", "Bypass-Operation (CABG)", "Herzschrittmacher-Implantation", "Defibrillator-Implantation (ICD)",
        "Ablation", "Mandelentfernung (Tonsillektomie)", "Polypenentfernung (Adenotomie)", "Brustamputation (Mastektomie)", "Brusterhaltende Operation",
        "Prostataentfernung", "Nierenentfernung", "Milzentfernung", "Magenentfernung", "Dickdarmentfernung",
        "Ileostoma-Anlage", "Colostoma-Anlage", "Leistenbruch-OP", "Leberbiopsie", "Nierenbiopsie",
        "Knochenmarkpunktion", "Lymphknotenbiopsie", "Hautbiopsie", "Bronchoskopie", "Pleurapunktion",
        "Aszitespunktion", "Lumbalpunktion", "Gelenkpunktion", "Periduralanästhesie (PDA)", "Nervenblockade",
        "Triggerpunkt-Injektion", "Gelenkinjektion", "Botox-Injektion", "Hyaluronsäure-Unterspritzung", "Laserhaarentfernung",
        "Chemisches Peeling", "Mikrodermabrasion", "Hautanhängsel-Entfernung", "Muttermal-Entfernung", "Warzen-Vereisung (Kryotherapie)",
        "Elektrokauterisation", "Exzision", "Inzision und Drainage", "Wundnaht", "Klammerung",
        "Hauttransplantation", "Lappenplastik", "Augenlasern (LASIK)", "Glaukom-OP", "Netzhaut-OP",
        "Hornhauttransplantation", "Vitrektomie", "Trommelfellplastik", "Stapesplastik", "Cochlea-Implantat",
        "Nasenkorrektur (Rhinoplastik)", "Nasenscheidewand-OP (Septoplastik)", "Nasennebenhöhlen-OP", "Schilddrüsen-OP", "Nebenschilddrüsen-OP",
        "Nebennieren-OP", "Pankreas-OP", "Whipple-OP", "Leberresektion", "Lebertransplantation",
        "Nierentransplantation", "Herztransplantation", "Lungentransplantation", "Pankreastransplantation", "Stammzelltransplantation",
        "Dialyse (Blutwäsche)", "Peritonealdialyse", "Plasmapherese", "Immunglobulin-Gabe", "Chemotherapie",
        "Strahlentherapie", "Immuntherapie", "Antihormontherapie", "Zielgerichtete Therapie", "CAR-T-Zell-Therapie",
    )

    # Adaptação para o sistema GKV (Público) e PKV (Privado) da Alemanha
    insurance_plans= (
        "Gesetzliche Krankenversicherung (GKV) - AOK",
        "Gesetzliche Krankenversicherung (GKV) - Barmer",
        "Gesetzliche Krankenversicherung (GKV) - TK (Techniker)",
        "Gesetzliche Krankenversicherung (GKV) - DAK",
        "Gesetzliche Krankenversicherung (GKV) - IKK",
        "Gesetzliche Krankenversicherung (GKV) - BKK",
        "Private Krankenversicherung (PKV) - Vollversicherung",
        "Private Krankenversicherung (PKV) - Beihilfe (Beamte)",
        "Private Krankenversicherung (PKV) - Basistarif",
        "Zusatzversicherung (Zahn)",
        "Zusatzversicherung (Krankenhaus/Chefarzt)",
        "Pflegeversicherung",
        "Auslandskrankenversicherung",
        "Berufsgenossenschaft (Unfallversicherung)",
        "Familienversicherung",
    )

    vital_signs= (
        "Blutdruck", "Herzfrequenz", "Atemfrequenz", "Körpertemperatur", "Sauerstoffsättigung",
        "Body-Mass-Index (BMI)", "Blutzucker", "Schmerzskala", "Puls", "Peak-Flow",
    )
