"""Display labels for the locale-neutral clinical values (de_DE).

Words only: the numbers, units and reference intervals live once in
`faker_healthcare/clinical_values.py` and are never translated. The key set must match
the base catalogue exactly (`faker_healthcare/clinical_labels.py`); see
`tests/test_locales.py::TestClinicalLabelParity`.

Zwei Dictionaries: `CLINICAL_LABELS` (Namen der Analyte und Vitalzeichen,
Befundkennzeichnung, Alkoholkategorien, Applikationswege, Einnahmefrequenzen, Status der
Verordnung, Schweregrade der Skalen) und `MEDICATION_NAMES`, das die neutrale Wirkstoff-ID
auf die genaue Schreibweise dieses Katalogs abbildet — dadurch genügt eine einzige
Dosistabelle für alle sechs Sprachen.
"""

CLINICAL_LABELS: dict[str, str] = {
    # Vitalzeichen
    "systolic_bp": "Systolischer Blutdruck",
    "diastolic_bp": "Diastolischer Blutdruck",
    "heart_rate": "Herzfrequenz",
    "respiratory_rate": "Atemfrequenz",
    "temperature_c": "Körpertemperatur",
    "oxygen_saturation": "Sauerstoffsättigung",
    # Hämatologie
    "haemoglobin": "Hämoglobin",
    "wbc": "Leukozytenzahl",
    "platelets": "Thrombozytenzahl",
    "ferritin": "Ferritin",
    "inr": "INR (International Normalized Ratio)",
    # Nierenwerte
    "sodium": "Natrium",
    "potassium": "Kalium",
    "urea": "Harnstoff",
    "creatinine": "Kreatinin",
    "egfr": "Geschätzte glomeruläre Filtrationsrate (eGFR)",
    # Leberwerte
    "alt": "Alanin-Aminotransferase (ALT/GPT)",
    "ast": "Aspartat-Aminotransferase (AST/GOT)",
    "alkaline_phosphatase": "Alkalische Phosphatase",
    "bilirubin_total": "Gesamtbilirubin",
    "albumin": "Albumin",
    # Stoffwechsel
    "fasting_glucose": "Nüchternblutzucker",
    "hba1c": "Hämoglobin A1c (HbA1c)",
    # Schilddrüse
    "tsh": "Thyreoidea-stimulierendes Hormon (TSH)",
    "free_t4": "Freies Thyroxin (fT4)",
    # Blutfette
    "total_cholesterol": "Gesamtcholesterin",
    "ldl": "LDL-Cholesterin",
    "hdl": "HDL-Cholesterin",
    "triglycerides": "Triglyzeride",
    # Entzündungsmarker
    "crp": "C-reaktives Protein (CRP)",
    # Befundkennzeichnung
    "flag_low": "Niedrig",
    "flag_normal": "Normal",
    "flag_high": "Hoch",
    # Wöchentlicher Alkoholkonsum
    "alcohol_none": "Kein Alkoholkonsum",
    "alcohol_low_risk": "Geringes Risiko",
    "alcohol_increasing_risk": "Erhöhtes Risiko",
    "alcohol_higher_risk": "Hohes Risiko",
    # Applikationswege
    "route_oral": "Orale Gabe",
    "route_intravenous": "Intravenöse Gabe",
    "route_subcutaneous": "Subkutane Gabe",
    "route_inhaled": "Inhalative Gabe",
    "route_sublingual": "Sublinguale Gabe",
    "route_ophthalmic": "Ophthalmische Gabe",
    # Einnahmefrequenzen
    "frequency_once_daily": "Einmal täglich",
    "frequency_twice_daily": "Zweimal täglich",
    "frequency_three_times_daily": "Dreimal täglich",
    "frequency_four_times_daily": "Viermal täglich",
    "frequency_at_night": "Zur Nacht",
    "frequency_as_required": "Bei Bedarf",
    "frequency_once_weekly": "Einmal wöchentlich",
    "frequency_every_three_weeks": "Alle drei Wochen",
    # Status der Verordnung
    "medication_status_past": "Frühere Medikation",
    "medication_status_current": "Aktuelle Medikation",
    "medication_status_future": "Geplante Medikation",
    # Schweregrade der Skalen
    "assessment_minimal": "Minimal",
    "assessment_mild": "Leicht",
    "assessment_moderate": "Mittelgradig",
    "assessment_moderately_severe": "Mittelschwer",
    "assessment_severe": "Schwer",
    "assessment_symptoms_absent": "Keine Symptome",
    "assessment_normal_cognition": "Normale Kognition",
    "assessment_screen_negative": "Screening negativ",
    "assessment_screen_positive": "Screening positiv",
    "alcohol_possible_dependence": "Mögliche Abhängigkeit",
}

# Die Wirkstoffe, die `medication_order()` dosieren kann, benannt wie in diesem Katalog.
MEDICATION_NAMES: dict[str, str] = {
    "acamprosate": "Acamprosat",
    "acetaminophen": "Paracetamol",
    "acyclovir": "Aciclovir",
    "albuterol": "Albuterol",
    "alendronate": "Alendronat",
    "allopurinol": "Allopurinol",
    "alprazolam": "Alprazolam",
    "amitriptyline": "Amitriptylin",
    "amlodipine": "Amlodipin",
    "amoxicillin": "Amoxicillin",
    "anastrozole": "Anastrozol",
    "apixaban": "Apixaban",
    "aripiprazole": "Aripiprazol",
    "aspirin": "Aspirin",
    "atomoxetine": "Atomoxetin",
    "atorvastatin": "Atorvastatin",
    "azathioprine": "Azathioprin",
    "azithromycin": "Azithromycin",
    "bicalutamide": "Bicalutamid",
    "budesonide": "Budesonid",
    "buprenorphine": "Buprenorphin",
    "bupropion": "Bupropion",
    "buspirone": "Buspiron",
    "calcium_carbonate": "Calciumcarbonat",
    "carbamazepine": "Carbamazepin",
    "ceftriaxone": "Ceftriaxon",
    "cefuroxime": "Cefuroxim",
    "cephalexin": "Cephalexin",
    "cetirizine": "Cetirizin",
    "cholecalciferol": "Cholecalciferol",
    "cilostazol": "Cilostazol",
    "ciprofloxacin": "Ciprofloxacin",
    "clarithromycin": "Clarithromycin",
    "clindamycin": "Clindamycin",
    "clopidogrel": "Clopidogrel",
    "colchicine": "Colchicin",
    "dexamethasone": "Dexamethason",
    "digoxin": "Digoxin",
    "diltiazem": "Diltiazem",
    "donepezil": "Donepezil",
    "doxycycline": "Doxycyclin",
    "duloxetine": "Duloxetin",
    "dutasteride": "Dutasterid",
    "empagliflozin": "Empagliflozin",
    "enoxaparin": "Enoxaparin",
    "escitalopram": "Escitalopram",
    "esomeprazole": "Esomeprazol",
    "famotidine": "Famotidin",
    "febuxostat": "Febuxostat",
    "ferrous_sulfate": "Eisensulfat",
    "finasteride": "Finasterid",
    "fluoxetine": "Fluoxetin",
    "fluticasone": "Fluticason",
    "folic_acid": "Folsäure",
    "furosemide": "Furosemid",
    "gabapentin": "Gabapentin",
    "galantamine": "Galantamin",
    "glimepiride": "Glimepiride",
    "glyburide": "Glyburid",
    "haloperidol": "Haloperidol",
    "hydrochlorothiazide": "Hydrochlorothiazid",
    "hydrocortisone": "Hydrocortison",
    "hydroxychloroquine": "Hydroxychloroquin",
    "ibuprofen": "Ibuprofen",
    "insulin": "Insulin",
    "insulin_glargine": "Insulin Glargine",
    "lactulose": "Lactulose",
    "lamotrigine": "Lamotrigin",
    "latanoprost": "Latanoprost",
    "letrozole": "Letrozol",
    "levetiracetam": "Levetiracetam",
    "levofloxacin": "Levofloxacin",
    "levothyroxine": "Levothyroxin",
    "liraglutide": "Liraglutid",
    "lisinopril": "Lisinopril",
    "lithium": "Lithium",
    "loperamide": "Loperamid",
    "loratadine": "Loratadin",
    "lorazepam": "Lorazepam",
    "losartan": "Losartan",
    "melatonin": "Melatonin",
    "memantine": "Memantin",
    "mesalamine": "Mesalamin",
    "metformin": "Metformin",
    "methadone": "Methadon",
    "methimazole": "Methimazol",
    "methotrexate": "Methotrexat",
    "methylphenidate": "Methylphenidat",
    "metoprolol": "Metoprolol",
    "metronidazole": "Metronidazol",
    "montelukast": "Montelukast",
    "naltrexone": "Naltrexon",
    "naproxen": "Naproxen",
    "nitrofurantoin": "Nitrofurantoin",
    "nitroglycerin": "Nitroglycerin",
    "olanzapine": "Olanzapin",
    "omeprazole": "Omeprazol",
    "oseltamivir": "Oseltamivir",
    "oxybutynin": "Oxybutynin",
    "pantoprazole": "Pantoprazol",
    "paroxetine": "Paroxetin",
    "pembrolizumab": "Pembrolizumab",
    "phenytoin": "Phenytoin",
    "pioglitazone": "Pioglitazon",
    "prednisone": "Prednison",
    "pregabalin": "Pregabalin",
    "propranolol": "Propranolol",
    "quetiapine": "Quetiapin",
    "risperidone": "Risperidon",
    "rivaroxaban": "Rivaroxaban",
    "rosuvastatin": "Rosuvastatin",
    "sertraline": "Sertralin",
    "sildenafil": "Sildenafil",
    "simvastatin": "Simvastatin",
    "sitagliptin": "Sitagliptin",
    "solifenacin": "Solifenacin",
    "spironolactone": "Spironolacton",
    "sulfasalazine": "Sulfasalazin",
    "sumatriptan": "Sumatriptan",
    "tadalafil": "Tadalafil",
    "tamoxifen": "Tamoxifen",
    "tamsulosin": "Tamsulosin",
    "theophylline": "Theophyllin",
    "timolol": "Timolol",
    "tiotropium": "Tiotropium",
    "tolterodine": "Tolterodin",
    "topiramate": "Topiramat",
    "tramadol": "Tramadol",
    "trimethoprim": "Trimethoprim",
    "ursodiol": "Ursodiol",
    "valacyclovir": "Valaciclovir",
    "valproate": "Valproat",
    "valproic_acid": "Valproinsäure",
    "venlafaxine": "Venlafaxin",
    "warfarin": "Warfarin",
}
