"""
Statische Datenkonstanten für den Healthcare Provider (de_DE).
"""

HOSPITAL_DEPARTMENTS: tuple[str, ...] = (
    "Zentrale Notaufnahme (ZNA)",
    "Intensivstation (ITS/ICU)",
    "Coronary Care Unit (CCU) / Herzüberwachung",
    "Operationssaal (OP)",
    "Kreißsaal",
    "Kinderstation",
    "Wöchnerinnenstation",
    "Onkologische Station",
    "Röntgenabteilung",
    "Labor",
    "Krankenhausapotheke",
    "Physiotherapie",
    "Ergotherapie",
    "Atemtherapie",
    "Chirurgische Station",
    "Innere Abteilung",
    "Ambulanz / Poliklinik",
    "Psychiatrische Station",
    "Reha-Abteilung",
    "Endoskopie",
    "Neugeborenen-Intensivstation (NICU)",
    "Station für Schwerbrandverletzte",
    "Dialysestation",
    "Schlaflabor",
    "Wundversorgung",
    "Infusionsambulanz",
    "Kardiologische Funktionsabteilung",
    "Stroke Unit (Schlaganfallstation)",
    "Aufnahmestation",
    "Aufwachraum (AWR)",
)

BRAND_DRUGS: tuple[str, ...] = (
    "Sortis",
    "L-Thyroxin Henning",
    "Lisinopril-ratiopharm",
    "Glucophage",
    "Norvasc",
    "Beloc-Zok",
    "Antra MUPS",
    "Zocor",
    "Lorzaar",
    "Gabapentin-neuraxpharm",
    "Zoloft",
    "Fluctin",
    "Trevilor",
    "Cipralex",
    "Cymbalta",
    "Iscover",
    "Eliquis",
    "Ozempic",
    "Jardiance",
    "Forxiga",
    "Crestor",
    "Januvia",
    "Victoza",
    "Trulicity",
    "Mounjaro",
    "Wegovy",
    "Lantus",
    "Humalog",
    "NovoRapid",
    "Toujeo",
    "Abasaglar",
    "Levemir",
    "Tresiba",
    "Delix",
    "Ramilich",
    "Xanef",
    "Accuzide",
    "Diovan",
    "Karvea",
    "Votum",
    "Micardis",
    "Dilatrend",
    "Tenormin",
    "Dociton",
    "Beloc",
    "Catapresan",
    "Dilzem",
    "Adalat",
    "Carmen",
    "Plendil",
    "Aldactone",
    "Lasix",
    "Moduretik",
    "Torasemid",
    "Hygroton",
    "Cordarex",
    "Lanicor",
    "Tambocor",
    "Rytmonorm",
    "Sotalex",
    "Xarelto",
    "Pradaxa",
    "Lixiana",
    "Nifuretten",
    "Cipro",
    "Tavanic",
    "Zithromax",
    "Klacid",
    "Doxy-Wolff",
    "Keflex",
    "Elobact",
    "Rocephin",
    "Sobelin",
    "Clont",
    "Vancomycin CP",
    "Zyvoxid",
    "Zovirax",
    "Valtrex",
    "Tamiflu",
    "Diflucan",
    "Vfend",
    "Ambisome",
    "Lamisil",
    "Elontril",
    "Desiq",
    "Remergil",
    "Nortrilen",
    "Saroten",
    "Seroxat",
    "Fevarin",
    "Anafranil",
    "Quilonum",
    "Ergenyl",
    "Lamictal",
    "Tegretal",
    "Trileptal",
    "Topamax",
    "Keppra",
    "Phenhydan",
    "Luminal",
    "Mylepsinum",
    "Vimpat",
    "Zonegran",
    "Aricept",
    "Exelon",
    "Reminyl",
    "Axura",
    "Restex",
    "Sifrol",
    "Requip",
    "Azilect",
    "Movergan",
    "Lioresal",
    "Sirdalud",
    "Ambril",
    "Musaril",
    "Ortoton",
    "Tavor",
    "Tafil",
    "Valium",
    "Rivotril",
    "Remestan",
    "Stilnox",
    "Ximovan",
    "Sonata",
    "Circadin",
    "Ritalin",
    "Concerta",
    "Medikinet",
    "Elvanse",
    "Strattera",
    "Intuniv",
    "Abilify",
    "Seroquel",
    "Zyprexa",
    "Risperdal",
    "Zeldox",
    "Xeplion",
    "Latuda",
    "Haldol",
    "Megaphen",
    "Decentan",
    "Alna",
    "Proscar",
    "Avodart",
    "Viagra",
    "Cialis",
    "Levitra",
    "Dridase",
    "Detrusitol",
    "Vesikur",
    "Emselex",
    "Ferro sanol",
    "Folsan",
    "Vigantol",
    "Calcium Sandoz",
    "Zantic",
    "Pepdul",
    "Nexium",
    "Agopton",
    "Pariet",
    "Zyloric",
    "Colchysat",
    "Adenuric",
    "Celebrex",
    "Voltaren",
    "Amuno",
    "Felden",
    "Oxygesic",
    "Valoron",
    "MST Continus",
    "Durogesic",
    "Tussamag",
    "Palladon",
    "Polamidon",
    "Subutex",
    "Narcanti",
    "Novalgin",
    "Viani",
    "Symbicort",
    "Spiriva",
    "Singulair",
    "Salbuhexal",
    "Berodual",
    "Flutide",
    "Pulmicort",
    "Keytruda",
    "Opdivo",
    "Yervoy",
    "Tecentriq",
    "Imfinzi",
    "Humira",
    "Enbrel",
    "Remicade",
    "Stelara",
    "Cosentyx",
    "Dupixent",
    "Xolair",
    "Skyrizi",
    "Entyvio",
)

BLOOD_TYPES: tuple[str, ...] = ("A+", "A-", "B+", "B-", "AB+", "AB-", "0+", "0-")

ALLERGIES: tuple[str, ...] = (
    "Penicillin",
    "Erdnüsse",
    "Schalenfrüchte (Nüsse)",
    "Krebstiere",
    "Fisch",
    "Kuhmilch",
    "Hühnerei",
    "Soja",
    "Weizen",
    "Sesam",
    "Latex",
    "Bienengift",
    "Pollen (Gräser, Bäume)",
    "Hausstaubmilben",
    "Tierhaare",
    "Sulfonamide",
    "Aspirin (ASS)",
    "Ibuprofen",
    "Codein",
    "Morphin",
    "Kontrastmittel",
    "Lokalanästhetika",
    "Nickel",
    "Pflasterklebstoff",
    "Duftstoffe",
    "Insektenstiche",
    "Schimmelpilze",
    "Kakerlaken",
    "Gräser",
    "Ambrosia",
    "Mais",
    "Senf",
    "Sellerie",
    "Lupinen",
    "Sulfite",
    "Glutamat",
    "Farbstoffe",
    "Gluten",
    "Laktose",
    "Fruktose",
)

MEDICAL_PROCEDURES: tuple[str, ...] = (
    "Blutuntersuchung",
    "Magnetresonanztomographie (MRT)",
    "Computertomographie (CT)",
    "Röntgen",
    "Ultraschall (Sonographie)",
    "Darmspiegelung (Koloskopie)",
    "Magenspiegelung (Gastroskopie)",
    "Blinddarmentfernung (Appendektomie)",
    "Gallenblasenentfernung (Cholezystektomie)",
    "Kaiserschnitt (Sectio)",
    "Gebärmutterentfernung (Hysterektomie)",
    "Knieprothese (Knie-TEP)",
    "Hüftprothese (Hüft-TEP)",
    "Katarakt-OP",
    "Biopsie",
    "Physiotherapie",
    "Elektrokardiogramm (EKG)",
    "Echokardiographie",
    "Impfung",
    "Wundversorgung",
    "Herzkatheteruntersuchung",
    "Angioplastie (PTCA)",
    "Bypass-Operation (CABG)",
    "Herzschrittmacher-Implantation",
    "Defibrillator-Implantation (ICD)",
    "Ablation",
    "Mandelentfernung (Tonsillektomie)",
    "Polypenentfernung (Adenotomie)",
    "Brustamputation (Mastektomie)",
    "Brusterhaltende Operation",
    "Prostataentfernung",
    "Nierenentfernung",
    "Milzentfernung",
    "Magenentfernung",
    "Dickdarmentfernung",
    "Ileostoma-Anlage",
    "Colostoma-Anlage",
    "Leistenbruch-OP",
    "Leberbiopsie",
    "Nierenbiopsie",
    "Knochenmarkpunktion",
    "Lymphknotenbiopsie",
    "Hautbiopsie",
    "Bronchoskopie",
    "Pleurapunktion",
    "Aszitespunktion",
    "Lumbalpunktion",
    "Gelenkpunktion",
    "Periduralanästhesie (PDA)",
    "Nervenblockade",
    "Triggerpunkt-Injektion",
    "Gelenkinjektion",
    "Botox-Injektion",
    "Hyaluronsäure-Unterspritzung",
    "Laserhaarentfernung",
    "Chemisches Peeling",
    "Mikrodermabrasion",
    "Hautanhängsel-Entfernung",
    "Muttermal-Entfernung",
    "Warzen-Vereisung (Kryotherapie)",
    "Elektrokauterisation",
    "Exzision",
    "Inzision und Drainage",
    "Wundnaht",
    "Klammerung",
    "Hauttransplantation",
    "Lappenplastik",
    "Augenlasern (LASIK)",
    "Glaukom-OP",
    "Netzhaut-OP",
    "Hornhauttransplantation",
    "Vitrektomie",
    "Trommelfellplastik",
    "Stapesplastik",
    "Cochlea-Implantat",
    "Nasenkorrektur (Rhinoplastik)",
    "Nasenscheidewand-OP (Septoplastik)",
    "Nasennebenhöhlen-OP",
    "Schilddrüsen-OP",
    "Nebenschilddrüsen-OP",
    "Nebennieren-OP",
    "Pankreas-OP",
    "Whipple-OP",
    "Leberresektion",
    "Lebertransplantation",
    "Nierentransplantation",
    "Herztransplantation",
    "Lungentransplantation",
    "Pankreastransplantation",
    "Stammzelltransplantation",
    "Dialyse (Blutwäsche)",
    "Peritonealdialyse",
    "Plasmapherese",
    "Immunglobulin-Gabe",
    "Chemotherapie",
    "Strahlentherapie",
    "Immuntherapie",
    "Antihormontherapie",
    "Zielgerichtete Therapie",
    "CAR-T-Zell-Therapie",
)

INSURANCE_PLANS: tuple[str, ...] = (
    "Gesetzliche Krankenversicherung (GKV) - AOK",
    "Gesetzliche Krankenversicherung (GKV) - Barmer",
    "Gesetzliche Krankenversicherung (GKV) - TK (Techniker)",
    "Gesetzliche Krankenversicherung (GKV) - DAK",
    "Gesetzliche Krankenversicherung (GKV) - IKK",
    "Gesetzliche Krankenversicherung (GKV) - BKK",
    "Private Krankenversicherung (PKV) - Vollversicherung",
    "Private Krankenversicherung (PKV) - Beihilfe (Beamte)",
    "Private Krankenversicherung (PKV) - Basistarif",
    "Zusatzversicherung (Zahn)",
    "Zusatzversicherung (Krankenhaus/Chefarzt)",
    "Pflegeversicherung",
    "Auslandskrankenversicherung",
    "Berufsgenossenschaft (Unfallversicherung)",
    "Familienversicherung",
)

VITAL_SIGNS: tuple[str, ...] = (
    "Blutdruck",
    "Herzfrequenz",
    "Atemfrequenz",
    "Körpertemperatur",
    "Sauerstoffsättigung",
    "Body-Mass-Index (BMI)",
    "Blutzucker",
    "Schmerzskala",
    "Puls",
    "Peak-Flow",
)
