"""
Daten zu Krankheitskorrelationen

Dieses Modul enthält das Wörterbuch KRANKHEITS_KORRELATIONEN, das alle 150 Krankheiten
zu ihren Symptomen, ICD-10-Codes, Medikamenten und primären Fachgebieten zuordnet.

Daten stammen aus der WHO-ICD-10-Klassifikation.

MEDIZINISCHER HAFTUNGSAUSSCHLUSS: Diese Daten sind NUR ZU TEST- UND ENTWICKLUNGSZWECKEN.
Sie sollten NICHT für tatsächliche medizinische Diagnose, Behandlung oder Gesundheitsentscheidungen verwendet werden.
"""

from ..types import DiseaseData


DISEASE_CORRELATIONS: dict[str, DiseaseData] = {
    "Diabetes mellitus Typ 2": {
        "icd10": "E11.9",
        "symptoms": ["Häufiges Harnlassen", "Erhöhter Appetit", "Müdigkeit", "Verschwommenes Sehen", "Gewichtsverlust"],
        "medications": ["Metformin", "Insulin Glargine", "Empagliflozin", "Sitagliptin", "Glimepiride"],
        "medical_specialty": "Endokrinologie",
    },
    "Essentielle Hypertonie": {
        "icd10": "I10",
        "symptoms": ["Kopfschmerzen", "Schwindel", "Brustschmerz", "Verschwommenes Sehen", "Herzklopfen"],
        "medications": ["Lisinopril", "Amlodipin", "Losartan", "Hydrochlorothiazid", "Metoprolol"],
        "medical_specialty": "Kardiologie",
    },
    "Hyperlipidämie": {
        "icd10": "E78.5",
        "symptoms": ["Brustschmerz", "Müdigkeit", "Taubheitsgefühl", "Schwäche"],
        "medications": ["Atorvastatin", "Simvastatin", "Rosuvastatin", "Fenofibrat", "Ezetimib"],
        "medical_specialty": "Kardiologie",
    },
    "Koronare Herzkrankheit": {
        "icd10": "I25.10",
        "symptoms": ["Brustschmerz", "Kurzatmigkeit", "Müdigkeit", "Herzklopfen", "Schwindel"],
        "medications": ["Aspirin", "Clopidogrel", "Atorvastatin", "Metoprolol", "Nitroglycerin"],
        "medical_specialty": "Kardiologie",
    },
    "Chronisch obstruktive Lungenkrankheit": {
        "icd10": "J44.9",
        "symptoms": ["Kurzatmigkeit", "Husten", "Keuchen", "Brustschmerz", "Müdigkeit"],
        "medications": ["Albuterol", "Tiotropium", "Fluticason", "Prednison", "Azithromycin"],
        "medical_specialty": "Pulmonologie",
    },
    "Asthma": {
        "icd10": "J45.909",
        "symptoms": ["Keuchen", "Kurzatmigkeit", "Husten", "Brustschmerz", "Atembeschwerden"],
        "medications": ["Albuterol", "Fluticason", "Montelukast", "Prednison", "Budesonid"],
        "medical_specialty": "Pulmonologie",
    },
    "Chronische Nierenerkrankung": {
        "icd10": "N18.9",
        "symptoms": ["Müdigkeit", "Schwellungen", "Übelkeit", "Appetitlosigkeit", "Häufiges Harnlassen"],
        "medications": ["Lisinopril", "Furosemid", "Erythropoietin", "Calciumcarbonat", "Sevelamer"],
        "medical_specialty": "Nephrologie",
    },
    "Arthrose": {
        "icd10": "M17.9",
        "symptoms": ["Gelenkschmerzen", "Schwellungen", "Schwäche", "Rückenschmerzen"],
        "medications": ["Ibuprofen", "Paracetamol", "Naproxen", "Celecoxib", "Tramadol"],
        "medical_specialty": "Orthopädie",
    },
    "Rheumatoide Arthritis": {
        "icd10": "M79.1",
        "symptoms": ["Gelenkschmerzen", "Schwellungen", "Müdigkeit", "Schwäche", "Muskelschmerzen"],
        "medications": ["Methotrexat", "Prednison", "Adalimumab", "Hydroxychloroquin", "Sulfasalazin"],
        "medical_specialty": "Rheumatologie",
    },
    "Depression": {
        "icd10": "F32.9",
        "symptoms": ["Depression", "Müdigkeit", "Schlaflosigkeit", "Appetitlosigkeit", "Ängste"],
        "medications": ["Sertralin", "Fluoxetin", "Escitalopram", "Bupropion", "Duloxetin"],
        "medical_specialty": "Psychiatrie",
    },
    "Angststörung": {
        "icd10": "F41.9",
        "symptoms": ["Ängste", "Herzklopfen", "Schwitzen", "Zittern", "Schlaflosigkeit"],
        "medications": ["Sertralin", "Escitalopram", "Alprazolam", "Lorazepam", "Buspiron"],
        "medical_specialty": "Psychiatrie",
    },
    "Gastroösophageale Refluxkrankheit": {
        "icd10": "K21.9",
        "symptoms": ["Sodbrennen", "Brustschmerz", "Schluckbeschwerden", "Halsschmerzen", "Übelkeit"],
        "medications": ["Omeprazol", "Pantoprazol", "Esomeprazol", "Ranitidin", "Famotidin"],
        "medical_specialty": "Gastroenterologie",
    },
    "Adipositas": {
        "icd10": "E66.9",
        "symptoms": ["Müdigkeit", "Gelenkschmerzen", "Kurzatmigkeit", "Schwitzen"],
        "medications": ["Orlistat", "Phentermin", "Liraglutid", "Semaglutid", "Naltrexon"],
        "medical_specialty": "Endokrinologie",
    },
    "Hypothyreose": {
        "icd10": "E03.9",
        "symptoms": ["Müdigkeit", "Gewichtsverlust", "Haarausfall", "Trockene Haut", "Verstopfung"],
        "medications": ["Levothyroxin", "Liothyronin", "Thyroid"],
        "medical_specialty": "Endokrinologie",
    },
    "Vorhofflimmern": {
        "icd10": "I48.91",
        "symptoms": ["Herzklopfen", "Schwindel", "Müdigkeit", "Kurzatmigkeit", "Brustschmerz"],
        "medications": ["Warfarin", "Apixaban", "Rivaroxaban", "Metoprolol", "Diltiazem"],
        "medical_specialty": "Kardiologie",
    },
    "Kongestive Herzinsuffizienz": {
        "icd10": "I50.9",
        "symptoms": ["Kurzatmigkeit", "Müdigkeit", "Schwellungen", "Husten", "Schneller Herzschlag"],
        "medications": ["Furosemid", "Lisinopril", "Metoprolol", "Spironolacton", "Digoxin"],
        "medical_specialty": "Kardiologie",
    },
    "Pneumonie": {
        "icd10": "J18.9",
        "symptoms": ["Fieber", "Husten", "Kurzatmigkeit", "Brustschmerz", "Müdigkeit"],
        "medications": ["Amoxicillin", "Azithromycin", "Ceftriaxon", "Levofloxacin", "Doxycyclin"],
        "medical_specialty": "Pulmonologie",
    },
    "Harnwegsinfektion": {
        "icd10": "N39.0",
        "symptoms": ["Schmerzhaftes Harnlassen", "Häufiges Harnlassen", "Fieber", "Bauchschmerzen", "Trüber Urin"],
        "medications": ["Nitrofurantoin", "Ciprofloxacin", "Trimethoprim", "Amoxicillin", "Cephalexin"],
        "medical_specialty": "Innere Medizin",
    },
    "Akute Bronchitis": {
        "icd10": "J20.9",
        "symptoms": ["Husten", "Fieber", "Müdigkeit", "Kurzatmigkeit", "Brustschmerz"],
        "medications": ["Albuterol", "Guaifenesin", "Dextromethorphan", "Ibuprofen", "Azithromycin"],
        "medical_specialty": "Pulmonologie",
    },
    "Anämie": {
        "icd10": "D64.9",
        "symptoms": ["Müdigkeit", "Schwäche", "Schwindel", "Kopfschmerzen", "Kurzatmigkeit"],
        "medications": ["Eisensulfat", "Vitamin B12", "Folsäure", "Erythropoietin"],
        "medical_specialty": "Hämatologie",
    },
    "Migräne": {
        "icd10": "G43.909",
        "symptoms": ["Kopfschmerzen", "Übelkeit", "Lichtempfindlichkeit", "Verschwommenes Sehen", "Schwindel"],
        "medications": ["Sumatriptan", "Ibuprofen", "Topiramat", "Propranolol", "Amitriptylin"],
        "medical_specialty": "Neurologie",
    },
    "Schlaganfall": {
        "icd10": "I63.9",
        "symptoms": ["Taubheitsgefühl", "Verwirrtheit", "Schluckbeschwerden", "Verschwommenes Sehen", "Schwäche"],
        "medications": ["Aspirin", "Clopidogrel", "Alteplase", "Warfarin", "Atorvastatin"],
        "medical_specialty": "Neurologie",
    },
    "Alzheimer-Krankheit": {
        "icd10": "G30.9",
        "symptoms": ["Gedächtnisverlust", "Verwirrtheit", "Ängste", "Depression", "Schluckbeschwerden"],
        "medications": ["Donepezil", "Memantin", "Rivastigmin", "Galantamin"],
        "medical_specialty": "Neurologie",
    },
    "Brustkrebs": {
        "icd10": "C50.919",
        "symptoms": ["Brustknötchen", "Nippelausfluss", "Schwellungen", "Gewichtsverlust", "Müdigkeit"],
        "medications": ["Tamoxifen", "Anastrozol", "Trastuzumab", "Chemotherapie", "Strahlentherapie"],
        "medical_specialty": "Onkologie",
    },
    "Prostatakrebs": {
        "icd10": "C61",
        "symptoms": ["Schmerzhaftes Harnlassen", "Häufiges Harnlassen", "Schwäche", "Gewichtsverlust"],
        "medications": ["Leuprolid", "Bicalutamid", "Docetaxel", "Abirateron", "Enzalutamid"],
        "medical_specialty": "Onkologie",
    },
    "Lungenkrebs": {
        "icd10": "C34.90",
        "symptoms": ["Husten", "Bluthusten", "Kurzatmigkeit", "Brustschmerz", "Gewichtsverlust"],
        "medications": ["Carboplatin", "Paclitaxel", "Pembrolizumab", "Erlotinib", "Chemotherapie"],
        "medical_specialty": "Onkologie",
    },
    "COVID-19": {
        "icd10": "U07.1",
        "symptoms": ["Fieber", "Husten", "Müdigkeit", "Geruchsverlust", "Geschmacksverlust", "Kurzatmigkeit"],
        "medications": ["Remdesivir", "Dexamethason", "Paxlovid", "Molnupiravir"],
        "medical_specialty": "Infektiologie",
    },
    "Influenza": {
        "icd10": "J11.1",
        "symptoms": ["Fieber", "Husten", "Halsschmerzen", "Muskelschmerzen", "Müdigkeit", "Kopfschmerzen"],
        "medications": ["Oseltamivir", "Zanamivir", "Baloxavir", "Ibuprofen", "Paracetamol"],
        "medical_specialty": "Innere Medizin",
    },
    "Osteoporose": {
        "icd10": "M81.0",
        "symptoms": ["Rückenschmerzen", "Knochenschwund", "Schwäche"],
        "medications": ["Alendronat", "Risedronat", "Denosumab", "Calciumcarbonat", "Vitamin D"],
        "medical_specialty": "Endokrinologie",
    },
    "Periphere Arterienkrankheit": {
        "icd10": "I73.9",
        "symptoms": ["Beinschmerzen", "Taubheitsgefühl", "Schwäche", "Kalte Extremitäten"],
        "medications": ["Cilostazol", "Aspirin", "Clopidogrel", "Atorvastatin", "Pentoxifyllin"],
        "medical_specialty": "Gefäßchirurgie",
    },
    "Angina Pectoris": {
        "icd10": "I20.9",
        "symptoms": ["Brustschmerz", "Kurzatmigkeit", "Müdigkeit", "Übelkeit", "Schwitzen"],
        "medications": ["Nitroglycerin", "Aspirin", "Metoprolol", "Amlodipin", "Atorvastatin"],
        "medical_specialty": "Kardiologie",
    },
    "Hyperthyreose": {
        "icd10": "E05.90",
        "symptoms": ["Gewichtsverlust", "Herzklopfen", "Ängste", "Zittern", "Hitzeintoleranz"],
        "medications": ["Methimazol", "Propylthiouracil", "Propranolol", "Radioaktives Iod", "Levothyroxin"],
        "medical_specialty": "Endokrinologie",
    },
    "Gicht": {
        "icd10": "M10.9",
        "symptoms": ["Gelenkschmerzen", "Schwellungen", "Rötung", "Tophi", "Eingeschränkte Beweglichkeit"],
        "medications": ["Allopurinol", "Colchicin", "Indometacin", "Febuxostat", "Probenecid"],
        "medical_specialty": "Rheumatologie",
    },
    "Multiple Sklerose": {
        "icd10": "G35",
        "symptoms": ["Müdigkeit", "Taubheitsgefühl", "Sehprobleme", "Gleichgewichtsprobleme", "Muskelschwäche"],
        "medications": ["Interferon Beta", "Glatirameracetat", "Fingolimod", "Natalizumab", "Ocrelizumab"],
        "medical_specialty": "Neurologie",
    },
    "Parkinson-Krankheit": {
        "icd10": "G20",
        "symptoms": ["Zittern", "Bradykinesie", "Rigidität", "Haltungsstabilität", "Sprachveränderungen"],
        "medications": ["Levodopa", "Carbidopa", "Pramipexol", "Selegilin", "Amantadin"],
        "medical_specialty": "Neurologie",
    },
    "Epilepsie": {
        "icd10": "G40.909",
        "symptoms": ["Anfälle", "Bewusstseinsverlust", "Verwirrtheit", "Starrende Blicke", "Krämpfe"],
        "medications": ["Carbamazepin", "Valproat", "Lamotrigin", "Levetiracetam", "Phenytoin"],
        "medical_specialty": "Neurologie",
    },
    "Bipolare Störung": {
        "icd10": "F31.9",
        "symptoms": ["Stimmungsschwankungen", "Manie", "Depression", "Reizbarkeit", "Schlaflosigkeit"],
        "medications": ["Lithium", "Valproat", "Olanzapin", "Quetiapin", "Lamotrigin"],
        "medical_specialty": "Psychiatrie",
    },
    "Schizophrenie": {
        "icd10": "F20.9",
        "symptoms": ["Halluzinationen", "Wahnvorstellungen", "Desorganisiertes Denken", "Negative Symptome", "Kognitive Beeinträchtigung"],
        "medications": ["Risperidon", "Olanzapin", "Quetiapin", "Aripiprazol", "Haloperidol"],
        "medical_specialty": "Psychiatrie",
    },
    "Aufmerksamkeitsdefizit-Hyperaktivitätsstörung": {
        "icd10": "F90.9",
        "symptoms": ["Unaufmerksamkeit", "Hyperaktivität", "Impulsivität", "Desorganisation", "Vergesslichkeit"],
        "medications": ["Methylphenidat", "Amphetamin", "Atomoxetin", "Guanfacin", "Clonidin"],
        "medical_specialty": "Psychiatrie",
    },
    "Autismus-Spektrum-Störung": {
        "icd10": "F84.0",
        "symptoms": ["Soziale Beeinträchtigung", "Kommunikationsschwierigkeiten", "Repetitive Verhaltensweisen", "Sensorische Empfindlichkeiten", "Eingeschränkte Interessen"],
        "medications": ["Risperidon", "Aripiprazol", "SSRIs", "Stimulanzien", "Antikonvulsiva"],
        "medical_specialty": "Psychiatrie",
    },
    "Morbus Crohn": {
        "icd10": "K50.90",
        "symptoms": ["Bauchschmerzen", "Durchfall", "Gewichtsverlust", "Müdigkeit", "Blut im Stuhl"],
        "medications": ["Mesalamin", "Prednison", "Azathioprin", "Infliximab", "Adalimumab"],
        "medical_specialty": "Gastroenterologie",
    },
    "Colitis ulcerosa": {
        "icd10": "K51.90",
        "symptoms": ["Blutiger Durchfall", "Bauchschmerzen", "Dringlichkeit", "Gewichtsverlust", "Müdigkeit"],
        "medications": ["Mesalamin", "Prednison", "Azathioprin", "Infliximab", "Vedolizumab"],
        "medical_specialty": "Gastroenterologie",
    },
    "Reizdarmsyndrom": {
        "icd10": "K58.9",
        "symptoms": ["Bauchschmerzen", "Blähungen", "Durchfall", "Verstopfung", "Gase"],
        "medications": ["Loperamid", "Lubiproston", "Linaclotid", "Dicyclomin", "Rifaximin"],
        "medical_specialty": "Gastroenterologie",
    },
    "Zöliakie": {
        "icd10": "K90.0",
        "symptoms": ["Bauchschmerzen", "Durchfall", "Blähungen", "Müdigkeit", "Gewichtsverlust"],
        "medications": ["Keine Medikamente", "Glutenfreie Diät", "Vitaminergänzungen", "Eisenergänzungen", "Probiotika"],
        "medical_specialty": "Gastroenterologie",
    },
    "Leberzirrhose": {
        "icd10": "K74.60",
        "symptoms": ["Müdigkeit", "Gelbsucht", "Bauchschwellung", "Verwirrtheit", "Leichte Blutergüsse"],
        "medications": ["Lactulose", "Propranolol", "Diuretika", "Vitaminergänzungen", "Antibiotika"],
        "medical_specialty": "Gastroenterologie",
    },
    "Hepatitis C": {
        "icd10": "B18.2",
        "symptoms": ["Müdigkeit", "Gelbsucht", "Bauchschmerzen", "Appetitlosigkeit", "Übelkeit"],
        "medications": ["Sofosbuvir", "Ledipasvir", "Glecaprevir", "Pibrentasvir", "Ribavirin"],
        "medical_specialty": "Gastroenterologie",
    },
    "HIV/AIDS": {
        "icd10": "B20",
        "symptoms": ["Fieber", "Müdigkeit", "Gewichtsverlust", "Geschwollene Lymphknoten", "Wiederkehrende Infektionen"],
        "medications": ["Tenofovir", "Emtricitabin", "Dolutegravir", "Efavirenz", "Ritonavir"],
        "medical_specialty": "Infektiologie",
    },
    "Tuberkulose": {
        "icd10": "A15.0",
        "symptoms": ["Husten", "Fieber", "Nachtschweiß", "Gewichtsverlust", "Brustschmerz"],
        "medications": ["Isoniazid", "Rifampin", "Pyrazinamid", "Ethambutol", "Streptomycin"],
        "medical_specialty": "Pulmonologie",
    },
    "Sepsis": {
        "icd10": "A41.9",
        "symptoms": ["Fieber", "Schneller Herzschlag", "Verwirrtheit", "Kurzatmigkeit", "Niedriger Blutdruck"],
        "medications": ["Breitspektrum-Antibiotika", "IV-Flüssigkeiten", "Vasopressoren", "Kortikosteroide", "Insulin"],
        "medical_specialty": "Intensivmedizin",
    },
    "Tiefe Venenthrombose": {
        "icd10": "I82.409",
        "symptoms": ["Beinschmerzen", "Schwellungen", "Rötung", "Wärme", "Krämpfe"],
        "medications": ["Heparin", "Warfarin", "Rivaroxaban", "Apixaban", "Enoxaparin"],
        "medical_specialty": "Vaskuläre Medizin",
    },
    "Lungenembolie": {
        "icd10": "I26.99",
        "symptoms": ["Kurzatmigkeit", "Brustschmerz", "Husten", "Bluthusten", "Schneller Herzschlag"],
        "medications": ["Heparin", "Warfarin", "Rivaroxaban", "Apixaban", "Thrombolytika"],
        "medical_specialty": "Pulmonologie",
    },
    "Aortenaneurysma": {
        "icd10": "I71.9",
        "symptoms": ["Bauchschmerzen", "Rückenschmerzen", "Pulsierende Masse", "Hypotonie", "Synkope"],
        "medications": ["Beta-Blocker", "Statine", "ACE-Hemmer", "Antihypertensiva", "Schmerzmittel"],
        "medical_specialty": "Gefäßchirurgie",
    },
    "Klappenerkrankung des Herzens": {
        "icd10": "I38",
        "symptoms": ["Kurzatmigkeit", "Müdigkeit", "Brustschmerz", "Herzklopfen", "Ödem"],
        "medications": ["Diuretika", "ACE-Hemmer", "Beta-Blocker", "Antikoagulanzien", "Vasodilatatoren"],
        "medical_specialty": "Kardiologie",
    },
    "Kardiomyopathie": {
        "icd10": "I42.9",
        "symptoms": ["Müdigkeit", "Kurzatmigkeit", "Schwellungen", "Unregelmäßiger Herzschlag", "Brustschmerz"],
        "medications": ["ACE-Hemmer", "Beta-Blocker", "Diuretika", "Aldosteron-Antagonisten", "Digoxin"],
        "medical_specialty": "Kardiologie",
    },
    "Endokarditis": {
        "icd10": "I33.0",
        "symptoms": ["Fieber", "Müdigkeit", "Kurzatmigkeit", "Nachtschweiß", "Gelenkschmerzen"],
        "medications": ["Penicillin", "Vancomycin", "Gentamicin", "Ampicillin", "Ceftriaxon"],
        "medical_specialty": "Kardiologie",
    },
    "Perikarditis": {
        "icd10": "I30.9",
        "symptoms": ["Brustschmerz", "Fieber", "Müdigkeit", "Kurzatmigkeit", "Husten"],
        "medications": ["Ibuprofen", "Colchicin", "Prednison", "Aspirin", "Antibiotika"],
        "medical_specialty": "Kardiologie",
    },
    "Myokardinfarkt": {
        "icd10": "I21.9",
        "symptoms": ["Brustschmerz", "Kurzatmigkeit", "Übelkeit", "Schwitzen", "Benommenheit"],
        "medications": ["Aspirin", "Clopidogrel", "Heparin", "Beta-Blocker", "ACE-Hemmer"],
        "medical_specialty": "Kardiologie",
    },
    "Angeborene Herzkrankheit": {
        "icd10": "Q24.9",
        "symptoms": ["Zyanose", "Kurzatmigkeit", "Müdigkeit", "Schlechtes Wachstum", "Herzgeräusche"],
        "medications": ["Diuretika", "ACE-Hemmer", "Beta-Blocker", "Prostaglandin E1", "Antibiotika"],
        "medical_specialty": "Kardiologie",
    },
    "Periphere Neuropathie": {
        "icd10": "G62.9",
        "symptoms": ["Taubheitsgefühl", "Kribbeln", "Schmerzen", "Schwäche", "Brennendes Gefühl"],
        "medications": ["Gabapentin", "Pregabalin", "Duloxetin", "Amitriptylin", "Capsaicin"],
        "medical_specialty": "Neurologie",
    },
    "Schlafapnoe": {
        "icd10": "G47.30",
        "symptoms": ["Schnarchen", "Tagesmüdigkeit", "Müdigkeit", "Morgenkopfschmerzen", "Reizbarkeit"],
        "medications": ["CPAP-Therapie", "Modafinil", "Armodafinil", "Acetazolamid", "Theophyllin"],
        "medical_specialty": "Pulmonologie",
    },
    "Narkolepsie": {
        "icd10": "G47.419",
        "symptoms": ["Übermäßige Tagesmüdigkeit", "Kataplexie", "Schlafparalyse", "Halluzinationen", "Fragmentierter Schlaf"],
        "medications": ["Modafinil", "Natriumoxybat", "Pitolisant", "Methylphenidat", "Amphetamin"],
        "medical_specialty": "Neurologie",
    },
    "Restless-Legs-Syndrom": {
        "icd10": "G25.81",
        "symptoms": ["Drang, die Beine zu bewegen", "Unangenehme Empfindungen", "Verschlechterung in der Nacht", "Schlafstörungen", "Linderung durch Bewegung"],
        "medications": ["Pramipexol", "Ropinirol", "Gabapentin", "Eisenergänzungen", "Clonazepam"],
        "medical_specialty": "Neurologie",
    },
    "Fibromyalgie": {
        "icd10": "M79.7",
        "symptoms": ["Ausgedehnte Schmerzen", "Müdigkeit", "Schlafstörungen", "Kognitive Schwierigkeiten", "Kopfschmerzen"],
        "medications": ["Duloxetin", "Pregabalin", "Milnacipran", "Amitriptylin", "Cyclobenzaprin"],
        "medical_specialty": "Rheumatologie",
    },
    "Lupus": {
        "icd10": "M32.9",
        "symptoms": ["Müdigkeit", "Gelenkschmerzen", "Ausschlag", "Fieber", "Photosensitivität"],
        "medications": ["Hydroxychloroquin", "Prednison", "Methotrexat", "Mycophenolat", "Belimumab"],
        "medical_specialty": "Rheumatologie",
    },
    "Sklerodermie": {
        "icd10": "M34.9",
        "symptoms": ["Hautverdickung", "Raynaud-Phänomen", "Gelenkschmerzen", "Kurzatmigkeit", "Gastrointestinale Probleme"],
        "medications": ["Methotrexat", "Mycophenolat", "Cyclophosphamid", "Nifedipin", "Protonenpumpenhemmer"],
        "medical_specialty": "Rheumatologie",
    },
    "Sjögren-Syndrom": {
        "icd10": "M35.00",
        "symptoms": ["Trockener Mund", "Trockene Augen", "Müdigkeit", "Gelenkschmerzen", "Geschwollene Speicheldrüsen"],
        "medications": ["Pilocarpin", "Cevimelin", "Hydroxychloroquin", "Ciclosporin", "Künstliche Tränen"],
        "medical_specialty": "Rheumatologie",
    },
    "Psoriasis": {
        "icd10": "L40.9",
        "symptoms": ["Rote Flecken", "Jucken", "Schuppung", "Verdickte Haut", "Gelenkschmerzen"],
        "medications": ["Methotrexat", "Ciclosporin", "Adalimumab", "Topische Kortikosteroide", "Vitamin-D-Analoga"],
        "medical_specialty": "Dermatologie",
    },
    "Ekzem": {
        "icd10": "L30.9",
        "symptoms": ["Jucken", "Rötung", "Trockene Haut", "Ausschlag", "Schwellungen"],
        "medications": ["Hydrocortison", "Tacrolimus", "Pimecrolimus", "Dupilumab", "Feuchtigkeitsspender"],
        "medical_specialty": "Dermatologie",
    },
    "Rosazea": {
        "icd10": "L71.9",
        "symptoms": ["Gesichtsrötung", "Pickel", "Sichtbare Blutgefäße", "Augenreizung", "Schwellungen"],
        "medications": ["Metronidazol", "Azelaicsäure", "Ivermectin", "Doxycyclin", "Brimonidin"],
        "medical_specialty": "Dermatologie",
    },
    "Akne vulgaris": {
        "icd10": "L70.0",
        "symptoms": ["Pickel", "Mitesser", "Weißköpfe", "Zysten", "Narben"],
        "medications": ["Benzoylperoxid", "Salicylsäure", "Retinoide", "Antibiotika", "Isotretinoin"],
        "medical_specialty": "Dermatologie",
    },
    "Melanom": {
        "icd10": "C43.9",
        "symptoms": ["Veränderter Leberfleck", "Asymmetrische Form", "Unregelmäßige Ränder", "Farbvariation", "Durchmesserzunahme"],
        "medications": ["Pembrolizumab", "Nivolumab", "Ipilimumab", "Dacarbazin", "Trametinib"],
        "medical_specialty": "Onkologie",
    },
    "Basalzellkarzinom": {
        "icd10": "C44.91",
        "symptoms": ["Perlenartiger Knoten", "Wunde, die nicht heilt", "Narbenähnlicher Bereich", "Roter Fleck", "Blutung"],
        "medications": ["Imiquimod", "Fluorouracil", "Vismodegib", "Sonidegib", "Photodynamische Therapie"],
        "medical_specialty": "Dermatologie",
    },
    "Plattenepithelkarzinom": {
        "icd10": "C44.92",
        "symptoms": ["Raue rote Stelle", "Offene Wunde", "Verkrustete Oberfläche", "Wachstum mit zentraler Vertiefung", "Jucken"],
        "medications": ["Fluorouracil", "Imiquimod", "Pembrolizumab", "Cemiplimab", "Chemotherapie"],
        "medical_specialty": "Dermatologie",
    },
    "Leukämie": {
        "icd10": "C95.90",
        "symptoms": ["Müdigkeit", "Fieber", "Gewichtsverlust", "Leichte Blutergüsse", "Wiederkehrende Infektionen"],
        "medications": ["Imatinib", "Cytarabin", "Daunorubicin", "Vincristin", "Hydroxyharnstoff"],
        "medical_specialty": "Hämatologie",
    },
    "Lymphom": {
        "icd10": "C85.90",
        "symptoms": ["Geschwollene Lymphknoten", "Fieber", "Nachtschweiß", "Gewichtsverlust", "Müdigkeit"],
        "medications": ["Rituximab", "Cyclophosphamid", "Doxorubicin", "Vincristin", "Prednison"],
        "medical_specialty": "Onkologie",
    },
    "Myelom": {
        "icd10": "C90.00",
        "symptoms": ["Knochenschmerzen", "Müdigkeit", "Anämie", "Wiederkehrende Infektionen", "Nierenprobleme"],
        "medications": ["Bortezomib", "Lenalidomid", "Dexamethason", "Daratumumab", "Melphalan"],
        "medical_specialty": "Hämatologie",
    },
    "Darmkrebs": {
        "icd10": "C18.9",
        "symptoms": ["Bauchschmerzen", "Blut im Stuhl", "Veränderung der Stuhlgewohnheiten", "Gewichtsverlust", "Müdigkeit"],
        "medications": ["Fluorouracil", "Oxaliplatin", "Capecitabin", "Bevacizumab", "Cetuximab"],
        "medical_specialty": "Onkologie",
    },
    "Pankreaskrebs": {
        "icd10": "C25.9",
        "symptoms": ["Bauchschmerzen", "Gelbsucht", "Gewichtsverlust", "Appetitlosigkeit", "Übelkeit"],
        "medications": ["Gemcitabin", "Paclitaxel", "Erlotinib", "FOLFIRINOX", "Capecitabin"],
        "medical_specialty": "Onkologie",
    },
    "Nierenkrebs": {
        "icd10": "C64.9",
        "symptoms": ["Blut im Urin", "Rückenschmerzen", "Gewichtsverlust", "Müdigkeit", "Fieber"],
        "medications": ["Sunitinib", "Pazopanib", "Axitinib", "Nivolumab", "Cabozantinib"],
        "medical_specialty": "Onkologie",
    },
    "Blasenkrebs": {
        "icd10": "C67.9",
        "symptoms": ["Blut im Urin", "Häufiges Harnlassen", "Schmerzhaftes Harnlassen", "Rückenschmerzen", "Beckenschmerzen"],
        "medications": ["BCG", "Mitomycin", "Gemcitabin", "Cisplatin", "Pembrolizumab"],
        "medical_specialty": "Urologie",
    },
    "Eierstockkrebs": {
        "icd10": "C56.9",
        "symptoms": ["Bauchaufblähung", "Beckenschmerzen", "Appetitlosigkeit", "Häufiges Harnlassen", "Müdigkeit"],
        "medications": ["Carboplatin", "Paclitaxel", "Bevacizumab", "Olaparib", "Doxorubicin"],
        "medical_specialty": "Onkologie",
    },
    "Endometriumkarzinom": {
        "icd10": "C54.1",
        "symptoms": ["Abnormale vaginale Blutung", "Beckenschmerzen", "Gewichtsverlust", "Müdigkeit", "Blähungen"],
        "medications": ["Progesteron", "Tamoxifen", "Carboplatin", "Paclitaxel", "Doxorubicin"],
        "medical_specialty": "Onkologie",
    },
    "Schilddrüsenkrebs": {
        "icd10": "C73",
        "symptoms": ["Halsknötchen", "Heiserkeit", "Schluckbeschwerden", "Halsschmerzen", "Geschwollene Lymphknoten"],
        "medications": ["Levothyroxin", "Radioaktives Iod", "Sorafenib", "Lenvatinib", "Cabozantinib"],
        "medical_specialty": "Endokrinologie",
    },
    "Hirntumor": {
        "icd10": "C71.9",
        "symptoms": ["Kopfschmerzen", "Anfälle", "Übelkeit", "Sehveränderungen", "Kognitive Beeinträchtigung"],
        "medications": ["Temozolomid", "Bevacizumab", "Carmustin", "Lomustin", "Dexamethason"],
        "medical_specialty": "Neurologie",
    },
    "Glaukom": {
        "icd10": "H40.9",
        "symptoms": ["Sehverlust", "Augenschmerzen", "Höfe um Lichter", "Rote Augen", "Übelkeit"],
        "medications": ["Timolol", "Latanoprost", "Brimonidin", "Acetazolamid", "Pilocarpin"],
        "medical_specialty": "Ophthalmologie",
    },
    "Makuladegeneration": {
        "icd10": "H35.30",
        "symptoms": ["Verschwommenes Sehen", "Zentraler Sehverlust", "Verzerrtes Sehen", "Dunkle Flecken", "Farbverblasung"],
        "medications": ["Ranibizumab", "Aflibercept", "Bevacizumab", "Verteporfin", "Vitaminergänzungen"],
        "medical_specialty": "Ophthalmologie",
    },
    "Grauer Star": {
        "icd10": "H26.9",
        "symptoms": ["Verschwommenes Sehen", "Blendempfindlichkeit", "Schlechtes Nachtsehen", "Verblasste Farben", "Doppeltsehen"],
        "medications": ["Keine Medikamente", "Chirurgie", "Brillen", "Blendfreie Linsen", "Vergrößerungen"],
        "medical_specialty": "Ophthalmologie",
    },
    "Diabetische Retinopathie": {
        "icd10": "E11.319",
        "symptoms": ["Verschwommenes Sehen", "Floater", "Sehverlust", "Farbveränderungen", "Dunkle Bereiche"],
        "medications": ["Ranibizumab", "Aflibercept", "Bevacizumab", "Lasertherapie", "Vitrektomie"],
        "medical_specialty": "Ophthalmologie",
    },
    "Hörverlust": {
        "icd10": "H91.90",
        "symptoms": ["Schwierigkeiten beim Hören", "Gedämpfte Geräusche", "Tinnitus", "Ohrschmerzen", "Gleichgewichtsprobleme"],
        "medications": ["Keine Medikamente", "Hörgeräte", "Cochlea-Implantate", "Steroide", "Antibiotika"],
        "medical_specialty": "HNO-Medizin",
    },
    "Ménière-Krankheit": {
        "icd10": "H81.09",
        "symptoms": ["Schwindel", "Hörverlust", "Tinnitus", "Ohrenfülle", "Übelkeit"],
        "medications": ["Meclizin", "Diuretika", "Betahistin", "Steroide", "Gentamicin"],
        "medical_specialty": "HNO-Medizin",
    },
    "Benigne Prostatahyperplasie": {
        "icd10": "N40.0",
        "symptoms": ["Häufiges Harnlassen", "Schwacher Strahl", "Dringlichkeit", "Nächtliches Harnlassen", "Unvollständige Entleerung"],
        "medications": ["Tamsulosin", "Finasterid", "Dutasterid", "Terazosin", "Sildenafil"],
        "medical_specialty": "Urologie",
    },
    "Erektile Dysfunktion": {
        "icd10": "N52.9",
        "symptoms": ["Unfähigkeit, Erektion aufrechtzuerhalten", "Reduzierte Libido", "Vorzeitige Ejakulation", "Stress", "Müdigkeit"],
        "medications": ["Sildenafil", "Tadalafil", "Vardenafil", "Alprostadil", "Testosteron"],
        "medical_specialty": "Urologie",
    },
    "Polyzystisches Ovarsyndrom": {
        "icd10": "E28.2",
        "symptoms": ["Unregelmäßige Perioden", "Übermäßiger Haarwuchs", "Akne", "Gewichtszunahme", "Unfruchtbarkeit"],
        "medications": ["Kombinierte orale Kontrazeptiva", "Metformin", "Spironolacton", "Clomifen", "Letrozol"],
        "medical_specialty": "Endokrinologie",
    },
    "Endometriose": {
        "icd10": "N80.9",
        "symptoms": ["Beckenschmerzen", "Dysmenorrhoe", "Unfruchtbarkeit", "Schmerzhafter Geschlechtsverkehr", "Starke Perioden"],
        "medications": ["Ibuprofen", "Kombinierte orale Kontrazeptiva", "Progestine", "GnRH-Agonisten", "Danazol"],
        "medical_specialty": "Gynäkologie",
    },
    "Uterusmyome": {
        "icd10": "D25.9",
        "symptoms": ["Starke Menstruationsblutung", "Beckenschmerzen", "Häufiges Harnlassen", "Verstopfung", "Rückenschmerzen"],
        "medications": ["GnRH-Agonisten", "Progestine", "Tranexamsäure", "Ibuprofen", "Ulipristalacetat"],
        "medical_specialty": "Gynäkologie",
    },
    "Präeklampsie": {
        "icd10": "O14.90",
        "symptoms": ["Hoher Blutdruck", "Proteinurie", "Schwellungen", "Kopfschmerzen", "Sehveränderungen"],
        "medications": ["Magnesiumsulfat", "Labetalol", "Hydralazin", "Nifedipin", "Entbindung"],
        "medical_specialty": "Geburtshilfe",
    },
    "Gestationsdiabetes": {
        "icd10": "O24.419",
        "symptoms": ["Erhöhter Durst", "Häufiges Harnlassen", "Müdigkeit", "Verschwommenes Sehen", "Übelkeit"],
        "medications": ["Insulin", "Metformin", "Glyburid", "Diätkontrolle", "Bewegung"],
        "medical_specialty": "Geburtshilfe",
    },
    "Vitamin-D-Mangel": {
        "icd10": "E55.9",
        "symptoms": ["Müdigkeit", "Knochenschmerzen", "Muskelschwäche", "Depression", "Haarausfall"],
        "medications": ["Vitamin-D-Ergänzungen", "Cholecalciferol", "Ergocalciferol", "Calciumergänzungen", "Sonneneinstrahlung"],
        "medical_specialty": "Endokrinologie",
    },
    "Eisenmangelanämie": {
        "icd10": "D50.9",
        "symptoms": ["Müdigkeit", "Blasse Haut", "Kurzatmigkeit", "Schwindel", "Kalte Hände"],
        "medications": ["Eisensulfat", "Eisengluconat", "Eiseninfusionen", "Vitamin C", "Folsäure"],
        "medical_specialty": "Hämatologie",
    },
    "Perniziöse Anämie": {
        "icd10": "D51.0",
        "symptoms": ["Müdigkeit", "Schwäche", "Blasse Haut", "Taubheitsgefühl", "Kognitive Veränderungen"],
        "medications": ["Vitamin-B12-Injektionen", "Orale B12-Ergänzungen", "Folsäure", "Eisenergänzungen", "Erythropoietin"],
        "medical_specialty": "Hämatologie",
    },
    "Sichelzellanämie": {
        "icd10": "D57.1",
        "symptoms": ["Schmerzanfälle", "Anämie", "Müdigkeit", "Gelbsucht", "Schwellungen"],
        "medications": ["Hydroxyharnstoff", "Schmerzmittel", "Antibiotika", "Bluttransfusionen", "Voxelotor"],
        "medical_specialty": "Hämatologie",
    },
    "Hämophilie": {
        "icd10": "D68.311",
        "symptoms": ["Verlängerte Blutung", "Gelenkschmerzen", "Blutergüsse", "Hämarthrose", "Nasenbluten"],
        "medications": ["Faktor VIII", "Faktor IX", "Desmopressin", "Antifibrinolytika", "Emicizumab"],
        "medical_specialty": "Hämatologie",
    },
    "Thrombozytopenie": {
        "icd10": "D69.6",
        "symptoms": ["Blutergüsse", "Zahnfleischbluten", "Nasenbluten", "Petechien", "Starke Perioden"],
        "medications": ["Kortikosteroide", "IVIG", "Romiplostim", "Eltrombopag", "Splenektomie"],
        "medical_specialty": "Hämatologie",
    },
    "Leukopenie": {
        "icd10": "D72.819",
        "symptoms": ["Häufige Infektionen", "Fieber", "Müdigkeit", "Mundgeschwüre", "Halsschmerzen"],
        "medications": ["G-CSF", "GM-CSF", "Antibiotika", "Antivirale Mittel", "Vitaminergänzungen"],
        "medical_specialty": "Hämatologie",
    },
    "Divertikulitis": {
        "icd10": "K57.92",
        "symptoms": ["Bauchschmerzen", "Fieber", "Übelkeit", "Verstopfung", "Durchfall"],
        "medications": ["Ciprofloxacin", "Metronidazol", "Amoxicillin-Clavulanat", "Ibuprofen", "Paracetamol"],
        "medical_specialty": "Gastroenterologie",
    },
    "Appendizitis": {
        "icd10": "K35.80",
        "symptoms": ["Bauchschmerzen", "Übelkeit", "Erbrechen", "Fieber", "Appetitlosigkeit"],
        "medications": ["Antibiotika", "Schmerzmittel", "IV-Flüssigkeiten", "Chirurgie", "Anti-Übelkeit"],
        "medical_specialty": "Allgemeinchirurgie",
    },
    "Cholezystitis": {
        "icd10": "K81.0",
        "symptoms": ["Bauchschmerzen", "Übelkeit", "Erbrechen", "Fieber", "Gelbsucht"],
        "medications": ["Antibiotika", "Schmerzmittel", "Ursodiol", "IV-Flüssigkeiten", "Chirurgie"],
        "medical_specialty": "Allgemeinchirurgie",
    },
    "Pankreatitis": {
        "icd10": "K85.90",
        "symptoms": ["Bauchschmerzen", "Übelkeit", "Erbrechen", "Fieber", "Schneller Puls"],
        "medications": ["IV-Flüssigkeiten", "Schmerzmittel", "Antibiotika", "Enzymergänzungen", "Insulin"],
        "medical_specialty": "Gastroenterologie",
    },
    "Peptische Ulkuskrankheit": {
        "icd10": "K27.9",
        "symptoms": ["Bauchschmerzen", "Blähungen", "Übelkeit", "Erbrechen", "Sodbrennen"],
        "medications": ["Omeprazol", "Ranitidin", "Amoxicillin", "Clarithromycin", "Sucralfat"],
        "medical_specialty": "Gastroenterologie",
    },
    "Gastritis": {
        "icd10": "K29.70",
        "symptoms": ["Bauchschmerzen", "Übelkeit", "Erbrechen", "Blähungen", "Appetitlosigkeit"],
        "medications": ["Omeprazol", "Ranitidin", "Antazida", "Sucralfat", "Antibiotika"],
        "medical_specialty": "Gastroenterologie",
    },
    "Ösophagitis": {
        "icd10": "K20.90",
        "symptoms": ["Sodbrennen", "Schluckbeschwerden", "Brustschmerz", "Rückfluss", "Übelkeit"],
        "medications": ["Omeprazol", "Ranitidin", "Sucralfat", "Antazida", "Prokinetika"],
        "medical_specialty": "Gastroenterologie",
    },
    "Barrett-Ösophagus": {
        "icd10": "K22.70",
        "symptoms": ["Sodbrennen", "Rückfluss", "Schluckbeschwerden", "Brustschmerz", "Übelkeit"],
        "medications": ["Omeprazol", "Esomeprazol", "Antazida", "H2-Blocker", "Protonenpumpenhemmer"],
        "medical_specialty": "Gastroenterologie",
    },
    "Hiatushernie": {
        "icd10": "K44.9",
        "symptoms": ["Sodbrennen", "Brustschmerz", "Schluckbeschwerden", "Rückfluss", "Blähungen"],
        "medications": ["Antazida", "H2-Blocker", "Protonenpumpenhemmer", "Prokinetika", "Chirurgie"],
        "medical_specialty": "Gastroenterologie",
    },
    "Hämorrhoiden": {
        "icd10": "K64.9",
        "symptoms": ["Rektale Blutung", "Jucken", "Schmerzen", "Schwellungen", "Unbehagen"],
        "medications": ["Hydrocortison", "Hamamelis", "Lidocain", "Stuhlweichmacher", "Ballaststoffergänzungen"],
        "medical_specialty": "Gastroenterologie",
    },
    "Analfissur": {
        "icd10": "K60.2",
        "symptoms": ["Schmerzen bei Stuhlgang", "Blutung", "Jucken", "Spasmen", "Verstopfung"],
        "medications": ["Nitroglycerinsalbe", "Diltiazem", "Botulinumtoxin", "Stuhlweichmacher", "Schmerzmittel"],
        "medical_specialty": "Gastroenterologie",
    },
    "Fäkale Inkontinenz": {
        "icd10": "R15.9",
        "symptoms": ["Unwillkürlicher Stuhlgang", "Dringlichkeit", "Leckage", "Durchfall", "Verstopfung"],
        "medications": ["Loperamid", "Bismutsubsalicylat", "Ballaststoffergänzungen", "Antidiarrhoika", "Cholestyramin"],
        "medical_specialty": "Gastroenterologie",
    },
    "Akute Nierenschädigung": {
        "icd10": "N17.9",
        "symptoms": ["Verminderte Urinausscheidung", "Schwellungen", "Müdigkeit", "Übelkeit", "Verwirrtheit"],
        "medications": ["Diuretika", "IV-Flüssigkeiten", "Dialyse", "Elektrolytmanagement", "Vasopressoren"],
        "medical_specialty": "Nephrologie",
    },
    "Nephrotisches Syndrom": {
        "icd10": "N04.9",
        "symptoms": ["Ödem", "Proteinurie", "Hypoalbuminämie", "Hyperlipidämie", "Müdigkeit"],
        "medications": ["ACE-Hemmer", "Diuretika", "Statine", "Kortikosteroide", "Immunsuppressiva"],
        "medical_specialty": "Nephrologie",
    },
    "Polyzystische Nierenerkrankung": {
        "icd10": "Q61.3",
        "symptoms": ["Bauchschmerzen", "Hypertonie", "Hämaturie", "Rückenschmerzen", "Häufige Infektionen"],
        "medications": ["ACE-Hemmer", "Diuretika", "Schmerzmittel", "Antibiotika", "Tolvaptan"],
        "medical_specialty": "Nephrologie",
    },
    "Nierensteine": {
        "icd10": "N20.0",
        "symptoms": ["Starke Schmerzen", "Hämaturie", "Übelkeit", "Erbrechen", "Häufiges Harnlassen"],
        "medications": ["Schmerzmittel", "Alpha-Blocker", "Allopurinol", "Kaliumcitrat", "Thiazide"],
        "medical_specialty": "Urologie",
    },
    "Interstitielle Zystitis": {
        "icd10": "N30.10",
        "symptoms": ["Blasenschmerzen", "Dringlichkeit", "Häufigkeit", "Beckenschmerzen", "Nächtliches Harnlassen"],
        "medications": ["Pentosanpolysulfat", "Amitriptylin", "Hydroxyzin", "Antihistaminika", "Blaseninstillationen"],
        "medical_specialty": "Urologie",
    },
    "Überaktive Blase": {
        "icd10": "N32.81",
        "symptoms": ["Dringlichkeit", "Häufigkeit", "Nächtliches Harnlassen", "Inkontinenz", "Blasenkrämpfe"],
        "medications": ["Oxybutynin", "Tolterodin", "Mirabegron", "Solifenacin", "Darifenacin"],
        "medical_specialty": "Urologie",
    },
    "Stressinkontinenz": {
        "icd10": "N39.3",
        "symptoms": ["Urinleckage beim Husten", "Niesen", "Sport", "Heben", "Lachen"],
        "medications": ["Duloxetin", "Östrogencreme", "Keine Medikamente", "Beckenbodentraining", "Chirurgie"],
        "medical_specialty": "Urologie",
    },
    "Dranginkontinenz": {
        "icd10": "N39.41",
        "symptoms": ["Plötzlicher Harndrang", "Unwillkürliche Leckage", "Häufigkeit", "Nächtliches Harnlassen", "Blasenkrämpfe"],
        "medications": ["Oxybutynin", "Tolterodin", "Mirabegron", "Solifenacin", "Botulinumtoxin"],
        "medical_specialty": "Urologie",
    },
    "Pyelonephritis": {
        "icd10": "N10",
        "symptoms": ["Fieber", "Flankenschmerzen", "Übelkeit", "Erbrechen", "Häufiges Harnlassen"],
        "medications": ["Ciprofloxacin", "Ceftriaxon", "Amoxicillin", "Trimethoprim", "Nitrofurantoin"],
        "medical_specialty": "Nephrologie",
    },
    "Glomerulonephritis": {
        "icd10": "N05.9",
        "symptoms": ["Hämaturie", "Proteinurie", "Ödem", "Hypertonie", "Müdigkeit"],
        "medications": ["Kortikosteroide", "Immunsuppressiva", "ACE-Hemmer", "Diuretika", "Plasmapherese"],
        "medical_specialty": "Nephrologie",
    },
    "Akute Sinusitis": {
        "icd10": "J01.90",
        "symptoms": ["Gesichtsschmerzen", "Nasenverstopfung", "Kopfschmerzen", "Fieber", "Husten"],
        "medications": ["Amoxicillin", "Amoxicillin-Clavulanat", "Dekongestiva", "Nasale Steroide", "Schmerzmittel"],
        "medical_specialty": "HNO-Medizin",
    },
    "Chronische Sinusitis": {
        "icd10": "J32.9",
        "symptoms": ["Nasenverstopfung", "Gesichtsdruck", "Postnasaler Tropf", "Kopfschmerzen", "Müdigkeit"],
        "medications": ["Nasale Steroide", "Antibiotika", "Salzspülung", "Dekongestiva", "Chirurgie"],
        "medical_specialty": "HNO-Medizin",
    },
    "Allergische Rhinitis": {
        "icd10": "J30.9",
        "symptoms": ["Niesen", "Laufende Nase", "Juckende Augen", "Verstopfung", "Postnasaler Tropf"],
        "medications": ["Loratadin", "Cetirizin", "Fluticason", "Montelukast", "Azithromycin"],
        "medical_specialty": "Allergologie",
    },
    "Otitis media": {
        "icd10": "H66.90",
        "symptoms": ["Ohrschmerzen", "Fieber", "Hörverlust", "Flüssigkeitsausfluss", "Reizbarkeit"],
        "medications": ["Amoxicillin", "Azithromycin", "Ibuprofen", "Paracetamol", "Dekongestiva"],
        "medical_specialty": "HNO-Medizin",
    },
    "Otitis externa": {
        "icd10": "H60.90",
        "symptoms": ["Ohrschmerzen", "Jucken", "Rötung", "Schwellungen", "Ausfluss"],
        "medications": ["Ciprofloxacin", "Hydrocortison", "Neomycin", "Essigsäure", "Schmerzmittel"],
        "medical_specialty": "HNO-Medizin",
    },
    "Pharyngitis": {
        "icd10": "J02.9",
        "symptoms": ["Halsschmerzen", "Fieber", "Geschwollene Lymphknoten", "Kopfschmerzen", "Husten"],
        "medications": ["Penicillin", "Amoxicillin", "Azithromycin", "Ibuprofen", "Paracetamol"],
        "medical_specialty": "HNO-Medizin",
    },
    "Tonsillitis": {
        "icd10": "J03.90",
        "symptoms": ["Halsschmerzen", "Fieber", "Geschwollene Mandeln", "Schluckbeschwerden", "Kopfschmerzen"],
        "medications": ["Penicillin", "Amoxicillin", "Azithromycin", "Ibuprofen", "Paracetamol"],
        "medical_specialty": "HNO-Medizin",
    },
    "Laryngitis": {
        "icd10": "J04.0",
        "symptoms": ["Heiserkeit", "Halsschmerzen", "Husten", "Schwierigkeiten beim Sprechen", "Fieber"],
        "medications": ["Ibuprofen", "Paracetamol", "Dampfinhalation", "Stimmruhe", "Antibiotika"],
        "medical_specialty": "HNO-Medizin",
    },
    "Krupp": {
        "icd10": "J05.0",
        "symptoms": ["Bellender Husten", "Stridor", "Heiserkeit", "Fieber", "Atemnot"],
        "medications": ["Dexamethason", "Epinephrin", "Befeuchtete Luft", "Ibuprofen", "Paracetamol"],
        "medical_specialty": "Pädiatrie",
    },
    "Bronchiolitis": {
        "icd10": "J21.9",
        "symptoms": ["Husten", "Keuchen", "Kurzatmigkeit", "Fieber", "Laufende Nase"],
        "medications": ["Supportive Pflege", "Sauerstoff", "Hydration", "Albuterol", "Kortikosteroide"],
        "medical_specialty": "Pädiatrie",
    },
    "Emphysem": {
        "icd10": "J43.9",
        "symptoms": ["Kurzatmigkeit", "Chronischer Husten", "Keuchen", "Müdigkeit", "Gewichtsverlust"],
        "medications": ["Bronchodilatatoren", "Inhalierte Steroide", "Sauerstofftherapie", "Antibiotika", "Lungenrehabilitation"],
        "medical_specialty": "Pulmonologie",
    },
    "Zystische Fibrose": {
        "icd10": "E84.9",
        "symptoms": ["Anhältender Husten", "Keuchen", "Wiederkehrende Infektionen", "Schlechtes Wachstum", "Salzige Haut"],
        "medications": ["Ivacaftor", "Lumacaftor", "Dornase Alfa", "Pankreasenzyme", "Antibiotika"],
        "medical_specialty": "Pulmonologie",
    },
    "Interstitielle Lungenkrankheit": {
        "icd10": "J84.9",
        "symptoms": ["Kurzatmigkeit", "Trockener Husten", "Müdigkeit", "Gewichtsverlust", "Brustunbehagen"],
        "medications": ["Prednison", "Azathioprin", "Nintedanib", "Pirfenidon", "Sauerstofftherapie"],
        "medical_specialty": "Pulmonologie",
    },
    "Sarkoidose": {
        "icd10": "D86.9",
        "symptoms": ["Müdigkeit", "Husten", "Kurzatmigkeit", "Hautausschlag", "Gelenkschmerzen"],
        "medications": ["Prednison", "Methotrexat", "Hydroxychloroquin", "Infliximab", "Azathioprin"],
        "medical_specialty": "Pulmonologie",
    },
    "Pleurale Erguss": {
        "icd10": "J90",
        "symptoms": ["Kurzatmigkeit", "Brustschmerz", "Husten", "Fieber", "Gewichtsverlust"],
        "medications": ["Diuretika", "Antibiotika", "Kortikosteroide", "Chemotherapie", "Thorakozentese"],
        "medical_specialty": "Pulmonologie",
    },
    "Pneumothorax": {
        "icd10": "J93.9",
        "symptoms": ["Brustschmerz", "Kurzatmigkeit", "Schneller Herzschlag", "Zyanose", "Verminderte Atemgeräusche"],
        "medications": ["Sauerstoff", "Schmerzmittel", "Brustdrainage", "Chirurgie", "Pleurodese"],
        "medical_specialty": "Pulmonologie",
    },
    "Pulmonale Hypertonie": {
        "icd10": "I27.20",
        "symptoms": ["Kurzatmigkeit", "Müdigkeit", "Brustschmerz", "Schwindel", "Schwellungen"],
        "medications": ["Sildenafil", "Bosentan", "Epoprostenol", "Treprostinil", "Riociguat"],
        "medical_specialty": "Pulmonologie",
    },
    "Diabetes mellitus Typ 1": {
        "icd10": "E10.9",
        "symptoms": ["Erhöhter Durst", "Häufiges Harnlassen", "Extremer Hunger", "Unerklärter Gewichtsverlust", "Müdigkeit"],
        "medications": ["Insulin", "Pramlintid", "Metformin", "Empagliflozin", "Liraglutid"],
        "medical_specialty": "Endokrinologie",
    },
    "Chronische Lebererkrankung": {
        "icd10": "K76.9",
        "symptoms": ["Müdigkeit", "Gelbsucht", "Bauchschmerzen", "Schwellungen in den Beinen", "Jucken"],
        "medications": ["Diuretika", "Beta-Blocker", "Ursodiol", "Antivirale Mittel", "Immunsuppressiva"],
        "medical_specialty": "Gastroenterologie",
    },
    "Hypertensive Herzkrankheit": {
        "icd10": "I11.9",
        "symptoms": ["Kurzatmigkeit", "Müdigkeit", "Brustschmerz", "Herzklopfen", "Schwindel"],
        "medications": ["Lisinopril", "Metoprolol", "Hydrochlorothiazid", "Amlodipin", "Losartan"],
        "medical_specialty": "Kardiologie",
    },
    "Posttraumatische Belastungsstörung": {
        "icd10": "F43.1",
        "symptoms": ["Flashbacks", "Albträume", "Schwere Ängste", "Vermeidungsverhalten", "Hypervigilanz"],
        "medications": ["Sertralin", "Paroxetin", "Venlafaxin", "Prazosin", "Clonidin"],
        "medical_specialty": "Psychiatrie",
    },
    "Stoffmissbrauchsstörung": {
        "icd10": "F19.9",
        "symptoms": ["Heißhunger", "Verlust der Kontrolle", "Toleranz", "Entzugserscheinungen", "Vernachlässigung von Verpflichtungen"],
        "medications": ["Naltrexon", "Acamprosat", "Disulfiram", "Methadon", "Buprenorphin"],
        "medical_specialty": "Psychiatrie",
    },
    "Chronisches Schmerzsyndrom": {
        "icd10": "G89.4",
        "symptoms": ["Anhältender Schmerz", "Müdigkeit", "Schlafstörungen", "Depression", "Reduzierte Mobilität"],
        "medications": ["Gabapentin", "Duloxetin", "Tramadol", "Amitriptylin", "Ibuprofen"],
        "medical_specialty": "Schmerzmedizin",
    },
    "Anfallsleiden": {
        "icd10": "G40.909",
        "symptoms": ["Anfälle", "Bewusstseinsverlust", "Krämpfe", "Verwirrtheit", "Unkontrollierte Bewegungen"],
        "medications": ["Levetiracetam", "Valproinsäure", "Carbamazepin", "Lamotrigin", "Topiramat"],
        "medical_specialty": "Neurologie",
    },
}
